### ISSUE TITLE
"Packets out of order" PHP error

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#1044]
**Describe the bug**
A PHP Error was encountered
Severity: Warning

Message: Packets out of order. Expected 1 received 0. Packet size=145

Filename: mysqli/mysqli_driver.php

Line Number: 201

**To Reproduce**
Unfortunately, it happens randomly... but when it does, I seem to be doing anything involving a lookup of QSOs in the database. It could be as simple as loading the log view, or clicking on a callsign for more detail on a particular QSO.

**Server environment
 - PHP: 7.4.18
 - MySQL: 8.0.25
 - Cloudlog: Latest build

**Comment by magicbug** [comment]
this won't be a Cloudlog issue but rather a MySQL configuration one, I'd suggest looking at max_connections settings and making sure things are setup correctly. Googles got quite a bit of info on the subject

**Comment by magicbug** [comment]
Also ATTR_EMULATE_PREPARES in the database.php config might help but I think its not possible to set that but could be wrong
