### ISSUE TITLE
Feature Request: QSL Menu

### ISSUE THREAD

**Issue by myzinsky** [magicbug/Cloudlog#1049]
<img width="328" alt="image" src="https://user-images.githubusercontent.com/1970554/120118577-93441d00-c193-11eb-998b-8e1e1b8cf906.png">

Here it would be very helpful to have:

1) The possibility to set "QSL requested" and "Ignore", in order to generate later the QSL excel file for printing the cards. The clicking trough the menu is very time consuming. 

2) A Link to QRZ.com using the url https://www.qrz.com/db/DL9MJ

**Comment by magicbug** [comment]
Done.
