### ISSUE TITLE
Custom Maps - Date/Time selection not working correctly.

### ISSUE THREAD

**Issue by magicbug** [magicbug/Cloudlog#1055]
I'm trying to plot a map of the stations I worked during the CQWW WPX CW contest this past weekend.
In Custom Maps I pull down the calendars to enter the start and finish dates and times.  My settings have time set up as UTC so I am entering the times in UTC.

The resulting map shows only a small fraction of the stations I worked.  It's as if I enter the time in UTC but it assumes another time zone.  When I first start the Custom Maps app (for lack of a better description) I can see that it's pulling the time from my computer, which is set to UTC, but it's still not displaying all of the QSOs made in that period.

73,
Ken, VE3HLS

_Originally posted by @ve3hls in https://github.com/magicbug/Cloudlog/discussions/1054_

**Comment by ve3hls** [comment]
Thanks Peter!

I'll give it a try tomorrow

73,
.
Ken
