### ISSUE TITLE
US county does not populate from Callbook

### ISSUE THREAD

**Issue by tarantir** [magicbug/Cloudlog#1066]
When logging a US callsign the US county does not populate.

1. Ensure Cloudlog callbook is setup (I'm a QRZ Logbook XML subscriber)
2. Enter a us callsign (e.g. N8AUU) on the live QSO screen 
3. Tab to let callbook retrieve the callsign details

**Expected behaviour**
US County will populate on the QSO general tab.

I've attempted to debug this without luck.

**Desktop (please complete the following information):**
 - OS: Mint Linux 20.04 and Windows 10
 - Browser Chrome (latest)
 - Version Latest cloudlog from Repo

**Comment by phl0** [comment]
Thought I'll make a quick fix here due to latest experiences with auto-filling German DOKs. This should be fixed by PR https://github.com/magicbug/Cloudlog/pull/1460

**Comment by phl0** [comment]
Its now in station_logbooks.
