### ISSUE TITLE
Dark mode makes QSO info header on map invisible

### ISSUE THREAD

**Issue by mpentler** [magicbug/Cloudlog#1067]
**Describe the bug**
When using Cyborg (dark) theme the tool tips that display when you click on a red dot on the map don’t show the callsign at the top of the bubble. The text is in white, but the background is also white: 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to your display settings and select the Cyborg dark mode theme
2. Select any red dot from the map and click to open the QSO info
3. See the invisible header. The text can be selected to reveal its presence.

I do have an image of this if required, but not where I’m posting this from.

**Expected behaviour**
I assume black text instead? Like the rest of the QSO info box.

**Screenshots**
Can post later this evening.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91.0.4472.106

**Additional context**
N/A

Edit: same on iOS Safari.

Edit 2: the same does NOT happen with the other dark themes too, I’ve been able to confirm.

Thanks!
Mark MM3IIG

**Comment by mpentler** [comment]
Seems it's this that's doing it: 
https://github.com/magicbug/Cloudlog/blob/8ed1141e36fb91e36b3259763afd88dabadb1061/assets/css/cyborg/bootstrap.min.css#L371

There's no corresponding setting of white in, for example, the superhero theme when you inspect the element in developer mode. I think the line can possibly come out?

**Comment by AndreasK79** [comment]
You should really put the CSS in overrides.css instead. The problem is that if you comment out that line, the header in gridsquares will disappear. Try putting this in overrides.css in the cyborg-folder instead:
`.leaflet-popup-content h3 {
	color: #000;
}`

**Comment by AndreasK79** [comment]
Pushed #1072
