### ISSUE TITLE
Awards->DXCC/WAS: 60 meter band isn't eligible

### ISSUE THREAD

**Issue by rtucker** [magicbug/Cloudlog#1073]
Per the award rules at arrl.org, contacts on the 60-meter band are not eligible for the DXCC or WAS awards (due to the FCC rules surrounding the 60-meter band).  So, they should probably not be "counted" on the DXCC/WAS award pages.

This may apply to other awards as well... I haven't checked though.

Thanks :)

**Comment by magicbug** [comment]
While its not accepted as part of the awards lots of hams like to track it hence it included.
