### ISSUE TITLE
Maritime mobile QSOs

### ISSUE THREAD

**Issue by prstoetzer** [magicbug/Cloudlog#1090]
QSOs with maritime mobile stations are not handled properly by Cloudlog. I recommend adding a "NONE" option for DXCC (DXCC ID of 0) and perhaps automatically selecting the NONE DXCC if the suffix entered after the call is "/MM"

**Comment by magicbug** [comment]
I've added "None" as an option in the DXCC dropdowns I need to adjust the callsign lookup bits when you type a callsign in to set that correctly but that's overdue an overhaul.

I'm guessing we arent handling DXCC ID 0 in the awards parts ? @AndreasK79

**Comment by AndreasK79** [comment]
@magicbug some places the sql checks for dxcc > 0, and it's also joining on dxcc_entitites. Since dxcc_entities doesn't have an adif = 0, it shouldn't be a problem.

It needs testing to be 100% sure, but it seems that it should work as is.

**Comment by AndreasK79** [comment]
@magicbug the summary didn't check for col_dxcc > 0. Fixed that now with a PR.
