### ISSUE TITLE
Some PHP problem after installation 

### ISSUE THREAD

**Issue by scalpya** [magicbug/Cloudlog#1103]
Hi
I try install it on my server (now run PHP 7.3 and MarinaDB) 
install success but i can used, some PHP error message, iven i cant login . Its any chance to review link i post hire and give me some idea what is the problem ? 
Thanks 
PS
I try chcnge PHP version from 7.1 to 8.0

www.deekeynet.nazwa.pl/cloudlog/index.php

**Comment by magicbug** [comment]
Looks like you need to make some adjustments to the database settings to go `/application/config/database.php` and find `'pconnect' => TRUE` change TRUE to FALSE and save the file hopefully will resolve it.

**Comment by scalpya** [comment]
Working, Thank You

**Comment by magicbug** [comment]
Perfect.
