### ISSUE TITLE
Security bugs

### ISSUE THREAD

**Issue by amammad** [magicbug/Cloudlog#1106]
Hi dear Cloudlog team.
Can I report vulnerabilities that exist in your nice application?
are you care about security issues ?

**Comment by dg9vh** [comment]
Please report it as issue I think that would be the best way... Or Peter
@2m0sql should tell a better way (direct email to him?)



amammad ***@***.***> schrieb am Di., 27. Juli 2021, 09:44:

**Comment by amammad** [comment]
Oh man, Thanks for your quick response, your the best !!!
In this week I report several vulnerabilities (10 until now!!) in Huntr.dev platform and they send to you a authorization link. OK ?
I and my friend on this platform do bug bounty for open source community. this bug bounty platform also give bounty for fix the vulnerabilities to maintainers !!! 
If  you and your nice team have no problem with these kind of procedure in such good platform, then just tell me to report vulnerabilities there.

**Comment by magicbug** [comment]
> Please report it as issue I think that would be the best way... Or Peter @2m0sql should tell a better way (direct email to him?) amammad

Exactly this, this is a small project, any issues will be fixed that are reported.

**Comment by amammad** [comment]
I dont understand what you mean my friend.
can i report them to huntr?

**Comment by magicbug** [comment]
If you have a security bug contact me the repo owner directly peter@2m0sql.com 

Please note we don't use bounty programmes or pay any money .

**Comment by amammad** [comment]
huntr.dev is a good interactive platform and give very good reputation to each repository as they do it for us absolutely free.

**Comment by amammad** [comment]
i don't mean i want to ger feom you money man!!
i'm sorry for my bad

**Comment by amammad** [comment]
hutr support all repository in github for free nad give 250$ until 500$ monthly budget for each of ones for making open source world more secure

**Comment by amammad** [comment]
Also without any registration🤣
they send you a link that juat for you  and then you can interact with huntr tram or the bug hunter and when you fix your own qpplication they give both of us free bounty.

**Comment by amammad** [comment]
just give me some feedback to start working more and more and making good secure application with huntr team and their bug bounty hunters like me :))

**Comment by magicbug** [comment]
I've already told you how to report
