### ISSUE TITLE
Bearing calculation wrong

### ISSUE THREAD

**Issue by dg9vh** [magicbug/Cloudlog#1117]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
Some bearings are calculated wrong, example see screenshot

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter "JN39KF" as locator for station profile
2. Go to New QSO and Enter A61QQ as callsign, also happens with brasilian callsigns or other south-americans or Australian callsigns. 
3. See error

**Expected behaviour**
The right bearing should be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/13950650/127713888-b4acf791-91b4-4b2c-a879-28ee2575c7e2.png)

![image](https://user-images.githubusercontent.com/13950650/127713985-6a873faf-4725-47b5-a7c2-90458f0ac0e8.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome 64 Bit
 - Version 92.0.4515.107

**Comment by AndreasK79** [comment]
Nice catch @dg9vh. Strange that this hasn't been reported before.
The bug is in the qra-library.

I found another bug while looking at it. Try to enter a locator directly to the south or north of you. The distance will not be calculated.

I'm not sure how to fix the bug in the existing code, but I have some code that I can use to replace the existing code.
@magicbug will you take a look, or should I replace the existing code and make a PR?

**Comment by magicbug** [comment]
@AndreasK79 I was wondering myself how its not been reported before! its old code but still.. I'm out most of the day so if you fancy correcting it with a PR I'll accept it! else will fix later this afternoon

**Comment by magicbug** [comment]
A good example can be found here https://www.dougv.com/2009/07/calculating-the-bearing-and-compass-rose-direction-between-two-latitude-longitude-coordinates-in-php/ with the Great Circle calculation :)

**Comment by AndreasK79** [comment]
@magicbug thanks. This was much simpler than the code I had. PR coming up.

**Comment by magicbug** [comment]
Merged shall close once I've checked when home but guessing its fine now :)

**Comment by AndreasK79** [comment]
@magicbug it should be ok. The tests I did, came up with the same result as another program,

**Comment by magicbug** [comment]
Still surprised no one noticed! oh well better late than never

**Comment by dg9vh** [comment]
Yesterday was my first time I used a beam :-) all the time before I simply used an endfed wire on shortwave and therefore never been interested in bearings :-) With the beam it was suprising me, why I should beam northward to get to A61 :-)

**Comment by AndreasK79** [comment]
I see. Well, thanks to you, two bugs were fixed @dg9vh.
