### ISSUE TITLE
Trying to delete yourself results in an error

### ISSUE THREAD

**Issue by DC7IA** [magicbug/Cloudlog#1128]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**

I know this is a bad idea, but since the web interface allows it, I had to try deleting the demo user using the demo user.

It produced an error, unsuprisingly.

**To Reproduce**
Steps to reproduce the behaviour:
1. Try to delete an account using that account
2. get an error

**Expected behaviour**

The button should not be visible or the user should confirm and get logged out.

**Comment by magicbug** [comment]
Agreed bug
