### ISSUE TITLE
8-character gridsquare breaks the maps

### ISSUE THREAD

**Issue by AndreasK79** [magicbug/Cloudlog#1177]
If a QSO has an 8-character gridsquare entered, nothing is displayed on the map on the dashboard, logbook or in the qsodata.

In the QSO data i get this error, and no map is displayed:
![image](https://user-images.githubusercontent.com/6977712/133661859-323eff8d-95c2-4d9f-ba71-61e14fd07e59.png)

I see that an issue regarding this has been reported before:
https://github.com/magicbug/Cloudlog/issues/934
The fix doesn't seem to avoid all problems here.

@magicbug perhaps fixing this by using only the first 6 is a solution?

**Comment by AndreasK79** [comment]
@magicbug I edited the qra-library to check if gridsquare is longer than 6 chars. If it is, I run a substring to fetch only the 6 first. It seems to fix the maps. If this is an ok solution, I'll submit a PR.

**Comment by magicbug** [comment]
Seems best fix for now, ultimate solution is make it handle more chars but yep!

**Comment by AndreasK79** [comment]
Fixed in #1179
