### ISSUE TITLE
Editing a QSO with a USA state and county set, duplicates state in county column

### ISSUE THREAD

**Issue by AndreasK79** [magicbug/Cloudlog#1178]
**To Reproduce**
1. Log a QSO with state and county set. 
2. Edit the qso and save.

You can't edit and correct this either, as selectize on county will not allow me to.
Need to look into the code for saving edit.

**Screenshots**
![image](https://user-images.githubusercontent.com/6977712/133658084-bf12309d-6b23-4a2c-97e6-1b658bf60676.png)
![image](https://user-images.githubusercontent.com/6977712/133658124-ce7734f7-e82a-418c-8536-8de98c585023.png)

**Comment by magicbug** [comment]
Oh that needs sorted
