### ISSUE TITLE
While editing a QSO from the live QSO page, you cannot select the county dropdown.

### ISSUE THREAD

**Issue by T012m3n7oR** [magicbug/Cloudlog#1184]
**Describe the bug**
The County Dropdown on Edit QSO is not selectable if you access it from the Live QSO page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Live QSO (QSO -> Live QSO).
2. Click Edit QSO.
3. Go to the Awards tab.
4. Click the County dropdown.
5. Unable to type/select a County.

**Expected behaviour**
The county dropdown should be selectable, like it would be from following the same steps from the logbook.
If you go to the logbook page, then click on any previous contact -> Edit QSO -> Awards, the county dropdown is selectable.

**Screenshots**
Live QSO:
![2021-09-18_13h52_07](https://user-images.githubusercontent.com/48076977/133898026-00677eef-b68c-4443-9fc7-cb09656a5509.gif)

Logbook:
![2021-09-18_14h05_05](https://user-images.githubusercontent.com/48076977/133898290-47d4b727-7d90-4709-9a75-724725a48ce4.gif)

**Desktop (please complete the following information):**
 - OS: Win10 Home, 21H1
 - Browser: Chrome
 - Version: 93.0.4577.82 (Official Build) (64-bit)

**Additional context**
This is duplicatable on another device as well, so I do not believe it is my machine.

**Comment by AndreasK79** [comment]
@T012m3n7oR thanks for reporting. The problem was that the id-tag was the same in Live/Post QSO as in edit. Changed the tags. It is now fixed in the latest codebase.
