### ISSUE TITLE
LOTW Add LOC from LOTW record when is missing in QSO record

### ISSUE THREAD

**Issue by ok1cdj** [magicbug/Cloudlog#1204]
Will be nice to get LOCATOR from LOTW when is missing in QSO record when syncing LOTW QSL's.

**Comment by magicbug** [comment]
Theres already a PR but it isn't/wasnt handling VUCC so hasn't been merged yet.

**Comment by AndreasK79** [comment]
@magicbug It's merged into station_logbooks. It doesn't update if COL_VUCC is set, but it handles gridsquares. @T012m3n7oR said he could make another PR to handle VUCC as well.

**Comment by magicbug** [comment]
@AndreasK79 Perfect :)
