### ISSUE TITLE
Unable to upload MFSK QSO to LOTW

### ISSUE THREAD

**Issue by imlonghao** [magicbug/Cloudlog#1248]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**

Failed to upload MFSK related QSO (for example, JS8) to LOTW, there is an error on LOTW Activity Record:

```
LOTW_QSO: Error in record 3: MODE: Invalid value in field (MFSK)
```

I believed that LOTW doesn't support MFSK, they only support MFSK8 and MFSK16.

JS8 may be need to be map to `DATA` mode instead of `MFSK`

**To Reproduce**
Steps to reproduce the behaviour:
1. Make a JS8 QSO
2. Sync to LOTW

**Expected behaviour**

I can upload the JS8 QSO to LOTW

**Additional context**

[What emission modes are supported by LoTW?](https://lotw.arrl.org/lotw-help/frequently-asked-questions/#modes)

**Comment by magicbug** [comment]
Thanks does indeed need added to the remap code, will be next week been away from coding due to contesting.
