### ISSUE TITLE
Callsign info not autofilling on contest QSO page

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#1254]
When on the contest logging screen, entering a callsign doesn't autofill the name as it does on the live QSO screen. I'm using the latest dev of Cloudlog on Apache/2.4.51 (Ubuntu) and PHP 7.4.24.

**Comment by magicbug** [comment]
If it's added to the contest page might want an option to turn off as it can be classed as assisted if doing an entry.

**Comment by AndreasK79** [comment]
It was never designed to do that. Not sure if that is something we should implement or not.

**Comment by magicbug** [comment]
Personally dont think so.

**Comment by AndreasK79** [comment]
I agree @magicbug, but if more people request this, it might get added. Though it would not be high up in the wish list.
