### ISSUE TITLE
install dir

### ISSUE THREAD

**Issue by iddq** [magicbug/Cloudlog#1257]
https://github.com/magicbug/Cloudlog/blob/2bf589474495205e03229466921d3695f9a578e0/install/includes/core_class.php#L29

Hello

Can I ask what kind of check this? I cannot proceed the install because of it
Thank you.

**Comment by AndreasK79** [comment]
Hi.

I've just added a fix to master that hopefully will fix your issue.
Can you download master again and try?

Andreas.

**Comment by iddq** [comment]
ok, thanks.
