### ISSUE TITLE
[question] differences for the user roles?

### ISSUE THREAD

**Issue by DC7IA** [magicbug/Cloudlog#1273]
Couldn't find it in the wiki.

What are the differences for the user roles?

**Comment by magicbug** [comment]
Better suited to discussions https://github.com/magicbug/Cloudlog/discussions

However, at the moment the roles don't do much, that being said, in the next release v2 that's being worked on it will be the following

- Administrator: can access the admin dropdown and their own qsos and deal with user accs
- Operator: Can access their QSOs and their account related details.
