### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by DC7IA** [magicbug/Cloudlog#1274]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**

Updated Cloudlog from a version which was a few weeks old, now I get "500 Internal Server Error".

Old version: 6a42641
New version: cd63704

**To Reproduce**
Steps to reproduce the behaviour:
1. Install an old version of cloudlog
2. update (git pull)
3. 500

**Expected behaviour**

200 OK

**Screenshots**

**Desktop (please complete the following information):**

not applicable

**Smartphone (please complete the following information):**

not applicable

**Additional context**

I don't know anything about PHP, so if you could tell me what to look for I could elaborate. :)

**Comment by iddq** [comment]
check your web server logs access.log error.log

**Comment by DC7IA** [comment]
Error log contains no error and access log just says "500".

**Comment by magicbug** [comment]
500 is internal server error so bit beyond the scope of Github Issues for Cloudlog, as already pointed out suggest checking server logs but that's the limit of my suggestions, you can use Discussions for further discussion on this.
