### ISSUE TITLE
[Maps] set assets/js/leaflet/leafembed.js hardcoded maps tile server to use the options map_tile_server address

### ISSUE THREAD

**Issue by magicbug** [magicbug/Cloudlog#1276]
The js file `assets/js/leaflet/leafembed.js` uses a hardcoded map tile URL, this needs to be changed to use the options database map_tile_server field instead so it can be changed on the fly.

Thanks to @samhjn for pointing this out.

**Comment by phl0** [comment]
Fix proposed with https://github.com/magicbug/Cloudlog/pull/1617.
