### ISSUE TITLE
Create station location fails after clean install

### ISSUE THREAD

**Issue by WW2DX** [magicbug/Cloudlog#1314]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
Performed a clean install on Ubuntu 20.04-LTS + PHP7.4. After creating the new admin user account and removing m0abc the next step to "create station location". This step fails with error in attached screenshot.

**Screenshots**

Attached.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04-LTS running in EC2 AWS
 - Browser [safari]

![CleanShot%202021-11-18%20at%2018 28 28](https://user-images.githubusercontent.com/1928833/142713544-a7693b01-1a2d-476f-9c0a-9629d71d8459.jpeg)
![CleanShot%202021-11-18%20at%2018 28 15](https://user-images.githubusercontent.com/1928833/142713548-b82ce2ed-c4dc-40e3-b0ce-971d879edda6.jpeg)

**Comment by AndreasK79** [comment]
@WW2DX the dxcc list doesn't come with the installation. Go to Admin -> Update Country Files. When that is done, you can create a station location.

Andreas.
