### ISSUE TITLE
Is QSO API changed in v2?

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#1332]
When using V2 Cloudlog with Gridtracker, I'm unable to get QSOs to log correctly. My initial thought is that it's because a station location isn't being specified in Gridtracker despite it being part of the API documentation... but maybe it's something else amiss?

**Comment by AndreasK79** [comment]
Take a look here: https://github.com/magicbug/Cloudlog/discussions/1131#discussioncomment-1727927

**Comment by magicbug** [comment]
Currently under development and subject to change at any moment it will be documented fully once its ready for a decent stable beta test period.

**Comment by ofadam** [comment]
Understood and thank you for all the work on V2! I'm happy to help test (despite my limited skills, sadly.)

**Comment by AndreasK79** [comment]
@ofadam we need testers. So any help is welcome. Report whatever you find.
