### ISSUE TITLE
Station County list truncated for state of Missouri

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#1336]
I noticed when editing a station location in Cloudlog that the county list for the U.S. state of Missouri ends with "Scott"... when others should come after that in A-Z order (I was looking for Shelby.) Perhaps it's being truncated somehow?

**Comment by AndreasK79** [comment]
I think the number of counties are limited in the lookup. I think I fixed this a while back in the QSO edit. I have no trouble finding Shelby there. I'll dig further.

**Comment by AndreasK79** [comment]
The limit was set to 100. In QSO edit it was changed to 300. I'll push a fix:
![image](https://user-images.githubusercontent.com/6977712/147500992-ee35a32d-b3a1-4af0-974b-5ba3c5e38bbc.png)

**Comment by AndreasK79** [comment]
This is fixed now in master and station_logbooks.
