### ISSUE TITLE
WAS overlay map doesn't scale on smaller screens

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#1346]
When viewing the WAS map in the Awards section, it doesn't auto-scale to keep the whole United States in view on smaller screens. You can scroll, but it might be helpful to see the entire country at a glance (even if smaller.)

<img width="725" alt="Screen Shot 2022-01-02 at 11 21 51 PM" src="https://user-images.githubusercontent.com/5504940/147901603-d8da0aa8-eb5b-49db-8ce1-d0496bd1ab4d.png">

**Comment by AndreasK79** [comment]
@ofadam pushed a fix for this now: 
![image](https://user-images.githubusercontent.com/6977712/147961600-184f3ec8-234b-4d15-9cd2-6ab074add69e.png)

**Comment by ofadam** [comment]
It doesn't look like anything changed on my iPhone with this commit, unfortunately.

**Comment by AndreasK79** [comment]
Only tested on pc while changing size of browser. Phone doesn't work I see. Will take another look.

**Comment by AndreasK79** [comment]
Needed to add some more html tags:
![image](https://user-images.githubusercontent.com/6977712/148249709-626c20a3-1493-4510-b161-a8fdb0b7e9ad.jpeg) 
Will push fix later.

**Comment by AndreasK79** [comment]
@ofadam Pushed a fix to master now.
