### ISSUE TITLE
DB error: Incorrect integer value

### ISSUE THREAD

**Issue by peterus** [magicbug/Cloudlog#1358]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
An error is coming up on a new installed cloudlog (in docker) when creating a station.

**To Reproduce**
Steps to reproduce the behaviour:
1. create a new station and save it

** screenshot **

![image](https://user-images.githubusercontent.com/1764325/148613161-3d1e6cd4-e26b-4692-86ae-5c3dde05330a.png)

looks like the field was not rendered.

**Desktop (please complete the following information):**
 - OS: linux, docker
 - Browser chrome
 - Version ?

**Additional context**
```
A Database Error Occurred
Error Number: 1366

Incorrect integer value: '' for column `cloudlog`.`station_profile`.`station_dxcc` at row 1

INSERT INTO `station_profile` (`station_profile_name`, `station_gridsquare`, `station_city`, `station_iota`, `station_sota`, `station_sig`, `station_sig_info`, `station_callsign`, `station_dxcc`, `station_country`, `station_cnty`, `station_cq`, `station_itu`, `state`, `eqslqthnickname`, `qrzapikey`, `qrzrealtime`) VALUES ('Home QTH', 'JN78DH', 'Linz', '', '', '', '', 'OE5BPA', '', '', '', '15', '28', '', '', '', '0')

Filename: models/Stations.php

Line Number: 71
```

**Comment by magicbug** [comment]
Please remember to follow the Wiki you need to go to "Admin -> Update Country Files" and download the latest files.

**Comment by peterus** [comment]
this was the "issue" - thanks!

**Comment by petrkr** [comment]
I just got this error in latest version too..

Maybe there could be some info about download country files instead crash ?
