### ISSUE TITLE
Radio connection timed-out

### ISSUE THREAD

**Issue by on4dgt** [magicbug/Cloudlog#1368]
I don't know if it's a bug or a misconfiguration somewhere. 

My CloudlogCAT shows: localtime -1
Radio interface shows: localtime -1
datebase entry shows: localtime -1

live QSO shows: Radio connection timed-out: OmniRig 1 data is 60 minutes old.

catcontrol works but the "Radio connection" message won't disapear

pc set to localtime
Linux server set to localtime

**Comment by magicbug** [comment]
Can you confirm your running the very latest codebase?

**Comment by on4dgt** [comment]
I am Peter.
the cloudlog.sh returns "Already up-to-date"

**Comment by m0urs** [comment]
I updated today to the most current version and I now have that message as well. Did not appear before the update.

**Comment by KE8AKW** [comment]
I believe this might be a issue with CloudLogCAT. In the bottom part of CloudLogCAT it says something like "Successfully synced with CloudLog @( current time). For whatever reason, it is showing for me 3 hours ahead hence forth why we are getting this data is old error in Cloudlog. Im not sure where CloudLogCAT gets its time from so don't know how to fix. @magicbug
