### ISSUE TITLE
[Version 2] API Import of ADIF doesn't work in station_logbooks branch

### ISSUE THREAD

**Issue by phl0** [magicbug/Cloudlog#1381]
**Describe the bug**
Using the python script sending WSJT-X log data to Cloudlog doesn't work in V2 / station_logbooks any more.

**To Reproduce**
Steps to reproduce the behaviour:
Send a ADIF QSO data via API to Cloudlog

**Expected behaviour**
The ADIF data should get imported

**Additional context**

Reason for this fail is that Stations->check_station_is_accessible fails because no user session exists. But for API requests there will be no valid user session. So this needs to be skipped on API imports.

**Comment by AndreasK79** [comment]
Briefly discussed here: https://github.com/magicbug/Cloudlog/discussions/1131#discussioncomment-1727927

**Comment by phl0** [comment]
Jupp, I already talked to @magicbug about this directly. :-)

**Comment by magicbug** [comment]
@phl0 with any luck this is now resolved

**Comment by magicbug** [comment]
Confirmed fix 👍🏻
