### ISSUE TITLE
A PHP Error was encountered on Filling in the locator with something other then a locator

### ISSUE THREAD

**Issue by PD0RZH** [magicbug/Cloudlog#1385]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
A more descriptive errormessage would be useful, even this mistake was user initiated.....( I know the name of a city is not a locator....)

**To Reproduce**
Steps to reproduce the behaviour:
- Log a QSO in Live QSO
- Enter the name of a city in the Locator field

**Expected behaviour**
A more descriptive errormessage would be useful.

**Screenshots**
![PHP Error](https://user-images.githubusercontent.com/60810525/151327595-56f3801a-720b-4186-bb17-bd043c5c2ba2.png)

**Comment by magicbug** [comment]
I have a feeling this was already addressed within the codebase but might be wrong or perhaps only in v2 codebase shall have a look later :)
