### ISSUE TITLE
Not displayed Link distance

### ISSUE THREAD

**Issue by MikleBas** [magicbug/Cloudlog#1394]
I go to Analytics, Distances Worked
I am generating a report (there are links in the log)
But the log gives No QSOs found to plot.
What am I doing wrong?

**Comment by magicbug** [comment]
Can you say which branch this is I'm guessing the station_logbooks one as it seems fine in master?

**Comment by magicbug** [comment]
Indeed this seems to be a bug in both branches, I don't think we have changed any code but will see what @AndreasK79 thinks

**Comment by AndreasK79** [comment]
As it works in both branches for me, it's very difficult to guess what the problem is.

@MikleBas do you get this on every band you select?
