### ISSUE TITLE
[Cloudlog V2] Compute QRB and QTF distance isn't using location gridsquare

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#1408]
It looks like the new QRB/QTF calculations are based off of your default gridsquare and not the gridsquare for your location when making the QSO.

**Comment by AndreasK79** [comment]
Ah, you are right. An oversight there. Need to send in the gridsquare for the QSO as well.

When you launch it with ALT-Q, it fetches from the active location, but that will not work when launched from QSOs.

I'll look into it. Hopefully it is an easy fix.

**Comment by AndreasK79** [comment]
@magicbug check out #1409. It works in my tests, but please test it out before merge.

**Comment by AndreasK79** [comment]
@ofadam I merged the fix into station_logbooks now.
