### ISSUE TITLE
Post-QSO won't submit because of a locator issue, but it looks fine

### ISSUE THREAD

**Issue by mpentler** [magicbug/Cloudlog#1410]
I am entering a locator square string into a post-QSO entry, but I am getting the red box around a perfectly ok locator string. Indeed, the map dot looks ok and the distance is calculated ok underneath the locator box entry. It won't let me leave it blank, so I can't submit a QSO right now.

Additionally there seems to be rather a lot of javascript errors. Not really sure which of those you may need.

Just wondering if anyone else had seen something similar.

**Comment by mpentler** [comment]
When I click Save QSO, I get this: 

qso:1 An invalid form control with name='cqz' is not focusable.
qso:1 An invalid form control with name='dxcc_id' is not focusable.

**Comment by magicbug** [comment]
Is this a new install? is the country files intact? "admin -> update country files", I'm guessing that a Station Locations been created

**Comment by magicbug** [comment]
Some screenshots of whats being entered might also be helpful

**Comment by mpentler** [comment]
I ran the update country files and got:
Updating...
Dxcc Entities: 0
Dxcc Exceptions: 0
Dxcc Prefixes: 0

Unsure if that is the final output or if the Updating... means it is still running.

**Comment by mpentler** [comment]
Image: https://media.discordapp.net/attachments/935938190634778674/946707610927767583/unknown.png

Not a new install, part of the OARC cluster of CloudLogs, so I have been asking the Admin people there about it too and we figured the errors were worth reporting.

**Comment by magicbug** [comment]
Unless those numbers go beyond zero and updating changes to done then that will be the issue likely with permissions of the file system

**Comment by mpentler** [comment]
Thanks Peter, If it is the permissions will it let me know?

**Comment by magicbug** [comment]
I cannot remember without checking the code, if you go to Admin -> Debug there's quite a bit of info there

**Comment by mpentler** [comment]
Just to say I eventually got my instance reset, updating country files worked, and this is all okay now.
