### ISSUE TITLE
Validate Grid Locator Entry Field

### ISSUE THREAD

**Issue by ve1cwj** [magicbug/Cloudlog#1414]
Recently noticed that I had incorrectly entered several locators as "multigrids" without repeating the letters (i.e. DM33,43 vs DM33,DM43). This showed up in the VUCC awards summary table, but took a bit of searching to find the offending QSO. Totally operator error on my part, but perhaps Cloudlog could validate the values entered in this field to ensure they are in the correct format (i.e. XX##, XX##xx, XX##,XX## etc)?

**Comment by magicbug** [comment]
This looks like it comes under Pull Request #1445 so hopefully once this is checked and merged it will be resolved

**Comment by phl0** [comment]
Yes this would result in an error message being displayed and the QSO not saved. See screenshots of the code:

![Screenshot from 2022-03-29 08-15-12](https://user-images.githubusercontent.com/7112907/160545724-e093d989-a077-47da-bd58-7a373fd3a052.png)

![Screenshot from 2022-03-29 08-15-49](https://user-images.githubusercontent.com/7112907/160545743-91ebab16-8bd2-4b8b-813a-f77bdf757fee.png)

**Comment by magicbug** [comment]
Perfect, busy with work this afternoon but will check it later and see if its ok for merge :)
