### ISSUE TITLE
A Database Error Occurred

### ISSUE THREAD

**Issue by formateando** [magicbug/Cloudlog#1420]
Hello
After more than a year of using cloudlog, today I can not access.
I get the following message.

A Database Error Occurred
Error Number: 1061

Duplicate key name 'HRD_IDX_COL_CQZ'

ALTER TABLE TABLE_HRD_CONTACTS_V01 ADD INDEX `HRD_IDX_COL_CQZ` (`COL_CQZ`);

Filename: migrations/067_add_index_cqz_prop.php

Line Number: 15

Any idea how to fix it?

Thanks

**Comment by AndreasK79** [comment]
Hi.

Did you change anything? That should not happen, unless something changed.

Are you able to run sql commands on your installation? If so, you can run this update: 

`update migrations set version = 67;`

This will then skip migration file 67. 

If not, you could edit the file migrations/067_add_index_cqz_prop.php, and comment out  line 15 and 17.

Andreas.
