### ISSUE TITLE
Ability to automatically look up the contact information from QRZ

### ISSUE THREAD

**Issue by MikeWills** [magicbug/Cloudlog#1423]
It would be really great if, when entering in a QSO, that the contact information came in fro QRZ or another lookup service.

**Comment by phl0** [comment]
This is implemented. See: https://github.com/magicbug/Cloudlog/wiki/Callsign-Lookup

**Comment by MikeWills** [comment]
Ah, I see, I thought I had it configured properly, but missed one step. Thanks.
