### ISSUE TITLE
Show which Callsing/Log QSO made from

### ISSUE THREAD

**Issue by m1bxf** [magicbug/Cloudlog#143]
I import my logs from various activations; OY/M1BXF, FP/M1BXF, MM1BXF etc but when looking at a QSO in my M1BXF Cloudlog it is not clear which callsign a QSO was made under.  The Station Callsign is part of the ADIF file header so could it be tagged to each QSO during Import?

Or could imports be tagged with a manually entered Station Callsign so QSOs can be grouped per activation?

Gav.

**Comment by magicbug** [comment]
Its worth noting that the current version doesn't officially support multi callsign (logbooks) its a rehash closing this however multilogs will be in v2.
