### ISSUE TITLE
eQSL upload 

### ISSUE THREAD

**Issue by m0urs** [magicbug/Cloudlog#1447]
I have setup a second station location in Cloudlog for a portable QTH with callsign "DG3NAB/P" and eQSL nickname "JO40JE (Hochstadt)".

In eQSL I have setup a second attached account with the nickname "JO40JE (Hochstadt)" and the callsign "DG3NAB/P"

If I now enter a QSO to the station location "JO40JE (Hochstadt)" in Cloudlog and try to upload the QSO to eQSL it says "The following QSOs were sent to eQSL ..." but the next time I try to upload the QSOs the same QSO is displayed again.

I can also not find the QSO in eQSL so I guess it has NOT been uploaded.

Did I miss something?

Uploading from my main station location "Home" in Cloudlog, does work as expected.

**UPDATE:**

If I try to download from eQSL while having the new station profile as active profile, I do get the following error:

"No such Username/Password found This could mean the wrong callsign or the wrong password, or the user does not exist."

Maybe this relates to the upload problem?

**Comment by magicbug** [comment]
Yes eQSL badly handles multi location and creates a new account for each, this will be resolved in V2 with the option to create profiles that hold login details that can be assigned against station locations

**Comment by Vic152** [comment]
Same here added /P and no luck uploading to eQSL

**Comment by Meganitrospeed** [comment]
It appears also that the "comments" made in the logbook arent forwarded to eQSL's comment field

**Comment by phl0** [comment]
> It appears also that the "comments" made in the logbook arent forwarded to eQSL's comment field

This works as designed. The comments are not supposed to be transferred to eQSL.cc. To accomplish this a separate field has been added to the QSL section with https://github.com/magicbug/Cloudlog/pull/1435 in station_logbooks branch. The ADIF field used here is called "QSLMSG".

![Screenshot from 2022-05-23 10-36-38](https://user-images.githubusercontent.com/7112907/169779322-57d6bf32-1026-4513-8e13-136f677402c9.png)

**Comment by Meganitrospeed** [comment]
> > It appears also that the "comments" made in the logbook arent forwarded to eQSL's comment field
> 
> This works as designed. The comments are not supposed to be transferred to eQSL.cc. To accomplish this a separate field has been added to the QSL section with #1435 in station_logbooks branch. The ADIF field used here is called "QSLMSG".
> 
> ![Screenshot from 2022-05-23 10-36-38](https://user-images.githubusercontent.com/7112907/169779322-57d6bf32-1026-4513-8e13-136f677402c9.png)

Perfect, didnt check the current dev repo, my fault, I guess eQSL is also going to get an option to automate upload through Cron?

**Comment by m0urs** [comment]
Yes, and I think CLoudlog is using the username defined in the user account for eQSL.cc. Instead I would say it should use the call sign defined in the active station location (or the eQSL username needs to be set for every station location explicitly).

**Comment by nolith** [comment]
> Yes, and I think CLoudlog is using the username defined in the user account for eQSL.cc. Instead I would say it should use the call sign defined in the active station location (or the eQSL username needs to be set for every station location explicitly).

https://github.com/magicbug/Cloudlog/pull/1576 implements uploading for linked account with different callsigns (i.e. /P /M and so on)


Downloading confirmations suffers from the same problem as well (not fixed yet)

**Comment by m0urs** [comment]
I did play some more with eQSL in the last weeks. It seems that you need to add different accounts in eQSL for every portable activity you have done in order to get the right QSL information like QTH, locator and a different picture etc.

So you end up with many accounts within eQSL which all have the same call sign like "DG3NAB/P". So I guess it is not sufficient to use the "/P" callsign during upload but somehow you need to specify the correct eQSL nickname? I have named my station location profile name in Cloudlog with the same name as the nickname in eQSL so maybe this could be used to link the two together?

**Comment by nolith** [comment]
The nickname management is already implemented in cloudlog. 

If you have more QTH for your callsign it will just work. 

However if you have linked account with different callsings (/P or similar) not only you need to provide the right nickname, but you also must login with the callsign assigned to that location  (this is the fix I implemented).

**Comment by m0urs** [comment]
Ah ok, great. So that should then work for my setup. So I will either wait until the pull request is approved or try it in my local fork  if I find some time. Thanks!

**Comment by nolith** [comment]
https://github.com/magicbug/Cloudlog/pull/1579 implements downloading from all the linked accounts defined in each station location.
