### ISSUE TITLE
Advanced Search: Not able to search for "DISTANCE"

### ISSUE THREAD

**Issue by m0urs** [magicbug/Cloudlog#1452]
If I try to search for "DISTANCE" in Advanced Search, it is not working. I can search for "equal or greater than 0" but all values above "0" will not be found. It seems that the DISTANCE field is always "0" although the total distance is correctly displayed if I open the detailed view of a QSO.

**Comment by magicbug** [comment]
I suspect its because the fields empty

**Comment by m0urs** [comment]
So where does the distance information in the QSO detailed view comes from?

**Comment by magicbug** [comment]
Calculated on the fly

**Comment by m0urs** [comment]
Ok. So this could be a feature request :-). Thanks.
