### ISSUE TITLE
[FEATURE] Add a distance & bearing readout on the Add QSO screen

### ISSUE THREAD

**Issue by m1geo** [magicbug/Cloudlog#1459]
It would be nice to have a distance and bearing readout on the Add QSO screen.
--George, M1GEO.

**Comment by phl0** [comment]
Well there is? At least in v2 aka station_logbooks branch. See info text below gridsquare.

![Screenshot from 2022-04-16 21-19-29](https://user-images.githubusercontent.com/7112907/163688577-9f87a6f1-d9e2-451b-82a9-36537ff4edd6.png)

**Comment by magicbug** [comment]
Its there on V1 as well

![chrome_Cyiu4S7pRc](https://user-images.githubusercontent.com/84308/163690116-77617249-40a9-4360-aa5e-39e5087cf3aa.png)

**Comment by m1geo** [comment]
Yeah. No idea how I missed this! Sorry. I'll crawl back under my rock.
