### ISSUE TITLE
No pins showing on custom map

### ISSUE THREAD

**Issue by pa8s** [magicbug/Cloudlog#1473]
**Describe the bug**
When selecting a time frame with logged QSO's (e.g. one week) and band to whatever suitable, no pins are showing on the custom map.

**To Reproduce**
1. Create Custom Map with valid time frame.
2. Select whatever band suitable (including 'Every band')
3. 'Load Map'
4. Bottom of screen shows: 'Showing QSOs for Custom Date for Active Station Profile - _name of profile_'
5. No pins visible on map (complete world map visible)

**Expected behaviour**
Pins for applicable QSO's visible on map.

**Screenshots**
N/A

**Server**

    OS: FreeBSD 12
    HTTP Server: Apache 2.4.53
    Cloudlog version: 073
    Git Pull performed on 2022/05/06 19:45Z

**Desktop**

    OS: Linux Ubuntu 20.04
    Browser: Firefox 99

**Additional context**
Rechecked this and the custom map seems to work only if the number of qso's in selected time frame is below a (yet undetermined) value. Is this observation correct?
When creating a custom map of one day (e.g. 01/05/2022 12:00AM - 01/05/2022 11:59PM) for every band, the maps shows more (about 30) logged qso's than is exported in ADIF for the same timespan (19 qso's in this example).

**Comment by magicbug** [comment]
I suspect its because your selecting too many QSOs and servers timing out I just tried on a few copies here without much issue, Leaflet can handle about 2000 points becoming too slow and buggy.

**Comment by Meganitrospeed** [comment]
Hello,

Im suffering from the same issue, with about 48 QSO´s.

Chrome dev log shows an issue with the changeState() function in leaflet

index.php:1 Uncaught SyntaxError: Unexpected token '<'
    at XMLHttpRequest.stateChanged (leafembed.js:64:58)

Running currently
	'char_set' => 'utf8mb4',
	'dbcollat' => 'utf8mb4_general_ci',

Im guesing its related to something in the database being in a wrong format. I have taken a look at it but not yet found a culprit.

**Comment by Meganitrospeed** [comment]
This does however, not only affect custom maps. also the normal map* I will raise a new issue since the scope has changed
