### ISSUE TITLE
Install errors no users

### ISSUE THREAD

**Issue by NA7KR** [magicbug/Cloudlog#1496]
The new install has no users

INSERT INTO `users` VALUES ('4', 'm0abc', '$2a$08$r9UF3YhipAY6htSQoZRjeOFDx3Yuh7Zjuh45vKyUN4gO8g5l.saES', 'demo@demo.com', '99', 'M0ABC', 'io91js', 'Demo', 'Account', '0', null, null, null, null, null);

MySQL said: Documentation

#1136 - Column count doesn't match value count at row 1

**Comment by magicbug** [comment]
If a new install has no users that means you didn't finish setup, based on the other error sounds like you have issues with mysql
