### ISSUE TITLE
MYsql error

### ISSUE THREAD

**Issue by NA7KR** [magicbug/Cloudlog#1497]
A PHP Error was encountered
Severity: Warning

Message: mysqli::real_connect(): MySQL server has gone away

Filename: mysqli/mysqli_driver.php

Line Number: 201

**Comment by magicbug** [comment]
This is a setup issue suggesting that mysql is crashing

**Comment by NA7KR** [comment]
Mysql is working fine only problem with your app, I have lots of other PHP running in the same MYSQL cluster.
