### ISSUE TITLE
eQSL QSO Upload is not uploading all QSOs

### ISSUE THREAD

**Issue by do4bmw** [magicbug/Cloudlog#1502]
Hy

I have a problem that the eQSL upload dont upload all my "old" QSOs

and when i click in Tools on "Mark all QSOs as Send"

these list from the OLD QSOs are still there

maybe someone can help me

mny thanks
![Screenshot_40](https://user-images.githubusercontent.com/76187206/175872925-9941c77d-25d8-4cd1-b8c5-4c448bebcb06.jpg)
![Screenshot_42](https://user-images.githubusercontent.com/76187206/175872928-304b6dc2-9249-4515-b00f-da7cc2b4d55c.jpg)
![Screenshot_41](https://user-images.githubusercontent.com/76187206/175872933-7268236c-ae9d-482b-9a8f-964da5494892.jpg)

**Comment by magicbug** [comment]
Interesting, are they a part of the same active location that you're using?

**Comment by do4bmw** [comment]
i think so ... 

![image](https://user-images.githubusercontent.com/76187206/175924261-67d210d0-22d5-46a6-971c-5bc08a1c63dc.png)

**Comment by do4bmw** [comment]
one more thing

when i click on these QSOs and EDIT them ...

in ALL of them the mode ist set to AM 

see screenshots, is there a way to modify them all at once ? or do i need to edit all of them (around 900 QSOs)

![image](https://user-images.githubusercontent.com/76187206/175928215-773d0b3e-7c8d-469e-916b-610217521871.png)
![image](https://user-images.githubusercontent.com/76187206/175928247-e972aaea-ec57-452e-a807-45a2bac0b4d0.png)
![image](https://user-images.githubusercontent.com/76187206/175928401-add13811-b1ef-4804-a527-dcf842d36dcb.png)
![image](https://user-images.githubusercontent.com/76187206/175928373-2fb4be86-7e31-4fc0-ace9-9de4cd8071e8.png)

**Comment by do4bmw** [comment]
and FUN FACT all these QSOs are Confirmed from eQSL and LOTW ! 
but still in my upload list ... is there a ERROR LOG for the upload that i can look at ?

**Comment by magicbug** [comment]
If you go to QSL and check the eQSL tab in the edit qso are they marked as sent?

**Comment by do4bmw** [comment]
that works ... but it will be a pain in the ass todo this for nearly  ~900 QSOs

**Comment by do4bmw** [comment]
i dont need them all uploaded to eQSL ... i just want that list clear ... is there maybe a work around to mark them all as send , because the "Mark all as Send" Button is not working with these QSOs

**Comment by do4bmw** [comment]
no help ? no infos :-( 

do i realy need to change all of these QSO by Hand ? :-(

**Comment by AndreasK79** [comment]
@do4bmw are you using the master branch or the station_logbooks branch?

**Comment by AndreasK79** [comment]
@do4bmw pull the latest code and try to mark all QSOs now.

**Comment by AndreasK79** [comment]
@do4bmw now you can pull the latest code. I've refined it, so only those QSOs that are not marked with Y as sent will be updated to sent.

**Comment by do4bmw** [comment]
doing update now ... and try to upload and after that , try to mark the QSO as send

will return in a few minutes

**Comment by do4bmw** [comment]
YAY !!! the list is empty

Many Many Thanks !

![image](https://user-images.githubusercontent.com/76187206/177274070-4f7b3968-1a63-450d-bd91-e5945c3920e7.png)
