### ISSUE TITLE
Date on the Logbook page is incorrect

### ISSUE THREAD

**Issue by g4klx** [magicbug/Cloudlog#1504]
I'm using the hosted beta version of Cloudlog.

On the Logbook page, the Date column is correct for at least the first QSO on the page but that date is used for all of the QSOs on that page, and ones further back in time. If I go into "Edit QSO" the date is correct.

The image shows the date not changing even though the time shows that a day ended and a new one started.

This was produced just by going into the Log
![Cloudlog_date_bug](https://user-images.githubusercontent.com/11149768/176257177-ece73625-9cbb-4195-9e13-8cb891ced77b.png)
book page.

**Comment by phl0** [comment]
I see different dates on that picture?!

**Comment by g4klx** [comment]
I feel like a fool! You are absolutely correct. I'll close the issue.

**Comment by phl0** [comment]
No worries. I know the feeling. The answer usually drops from sky after I asked in a forum or the like :)
