### ISSUE TITLE
[station_logbooks] Search bar not displayed on public page

### ISSUE THREAD

**Issue by m0urs** [magicbug/Cloudlog#1505]
I have set "Public Search Bar" to "enabled" in the Global Options and I would expect that the search bar is now visible on the public page. Unfortunately it does not seem to be the case. Is this a bug or did I get it wrong for what this option is good for?

[https://cloudlog.urspringer.de/index.php/visitor/dg3nab](https://cloudlog.urspringer.de/index.php/visitor/dg3nab)

I am also missing the possibility to scroll through the QSOs list on the public page. I think think was possible in the old version? Currently only a fixed numbers of QSOs are listed on the public page.

**Comment by phl0** [comment]
@magicbug Should there be a public search bar in station_logbooks? I did dig through the code but could not find a hint that it was implemented or removed in station_logbooks. Or is that just that it has not yet been (re-)implemented for station_logbooks?

**Comment by magicbug** [comment]
The answer is yes, reason its not is because I hadn't written the search function for the new public dashboard code :)

**Comment by phl0** [comment]
We have a solution for that in https://github.com/magicbug/Cloudlog/pull/2282.

**Comment by m0urs** [comment]
Does work for me.
However, I would suggest, that we can search for parts of a call e.g. to find "DG3NAB/P" also if we search for "DG3NAB". What  do you think?

**Comment by phl0** [comment]
> Does work for me. However, I would suggest, that we can search for parts of a call e.g. to find "DG3NAB/P" also if we search for "DG3NAB". What do you think?

Good idea. Implemented with https://github.com/magicbug/Cloudlog/pull/2285.

**Comment by m0urs** [comment]
> Good idea. Implemented with #2285.

This does not work for me? Could it be that a "%" as wildcard is needed after a LIKE statement in your SQL where clause?

**Comment by phl0** [comment]
> This does not work for me? Could it be that a "%" as wildcard is needed after a LIKE statement in your SQL where clause?

It is the same search statement as in the "internal" search. Does it work there for you? On my machine:

![Screenshot from 2023-07-14 08-59-53](https://github.com/magicbug/Cloudlog/assets/7112907/f5a65c0c-d7c4-421f-90c3-3951a8f792ec)

The executed SQL statement is:

```
SELECT *                                                            
FROM `TABLE_HRD_CONTACTS_V01`                                                                            
JOIN `station_profile` ON `station_profile`.`station_id` = `TABLE_HRD_CONTACTS_V01`.`station_id`
LEFT OUTER JOIN `lotw_users` ON `lotw_users`.`callsign` = `TABLE_HRD_CONTACTS_V01`.`col_call`
WHERE `COL_CALL` LIKE '%DG3YJB%' ESCAPE '!'                                                              
AND `station_profile`.`user_id` = '4'                                                                    
ORDER BY `COL_TIME_ON` DESC
```

So no %% needed here. Sure you are on the right branch?

**Comment by m0urs** [comment]
Yeah, right branch. But if you do not make a pull after a merge it cannot work ;-) Sorry. It does work now ..
