### ISSUE TITLE
Unable to use hamqth callbook in latest station_logbooks branch

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#1511]
Despite having credentials set properly, I'm unable to use the hamqth callbook in the latest station_logbooks branch. QRZ.com still works as expected, though.

No error is displayed, but using the Live or Post QSO form results in nothing being looked up (not even older QSOs already logged in Cloudlog.)

**Comment by AndreasK79** [comment]
The problem is related to the QRZ lookup. Edit your account and turn off this:
![image](https://user-images.githubusercontent.com/6977712/177000834-9c6bca4f-821b-4a51-a84b-0287e342a09c.png)

This need to be fixed so that it is ignored if HamQTH is chosen.

**Comment by phl0** [comment]
Oopps. That is probably my fault. I will take a look.

**Comment by phl0** [comment]
Found a way to fix this by implementing the picture lookup functions also for hamqth profiles. Tests and reports welcome.
