### ISSUE TITLE
Map pins not loading

### ISSUE THREAD

**Issue by Meganitrospeed** [magicbug/Cloudlog#1512]
**Describe the bug**
Map pins not loading in any map (custom or normal public map), a JS error is thrown in the console. Likely related to a database record not being handled correctly or the collation/charset not being what is expected by the system

**To Reproduce**
Enter a Cloudlog which is suffering from this issue

**Expected behaviour**
Have the map pins load. Not having an empty map

**Screenshots**
https://i.imgur.com/Qxy4qGO.png
https://i.imgur.com/LtC1eiF.png

Chrome dev log shows an issue with the changeState() function in leaflet

index.php:1 Uncaught SyntaxError: Unexpected token '<'
at XMLHttpRequest.stateChanged (leafembed.js:64:58)

Running currently
'char_set' => 'utf8mb4',
'dbcollat' => 'utf8mb4_general_ci',

Im guesing its related to something in the database being in a wrong format. I have taken a look at it but not yet found a culprit.

Happened right after trying FT8 and uploading the logs straight up in adif format.

**Comment by Meganitrospeed** [comment]
Im guessing also user in https://github.com/magicbug/Cloudlog/issues/1473 had suffered from the same issue

**Comment by magicbug** [comment]
If your happy to supply an ADIF file then it might speed up things getting sorted so we can take a peak.

**Comment by magicbug** [comment]
I'm also going to guess this is station_logbooks branch?

**Comment by Meganitrospeed** [comment]
This is actually from the masters branch. Here you have an ADIF export https://drive.google.com/file/d/155fbSsFtKuyrAHPNc2kQs4FDl7L_920Z/view?usp=sharing

**Comment by AndreasK79** [comment]
I had a go with your provided ADIF file. I created a new station location, imported the file and pins were plotted here. Custom map also works.

If you load the front page and go to devtools -> network -> map -> response and look there. Does it contain an error?
It should look something like this:

![image](https://user-images.githubusercontent.com/6977712/177000614-05880456-b6f6-47bc-9d21-27af9ed90d9d.png)

**Comment by Meganitrospeed** [comment]
There appear to be a lot of correct logs, but also some php errors

Here you have a complete pastebin of the map

https://pastebin.com/JL2xRqvS

**Comment by Meganitrospeed** [comment]
The faulty record appears to be MQ0HVU which has for some reason no lat and no long 
https://i.imgur.com/1rmdNsT.png

I have deleted this QSO from my cloud log and now it's working again!

Any idea why it was lat0 long 0?

**Comment by phl0** [comment]
Probably because the special Q prefixes like MQ are not considered (valid) DXCC?

**Comment by AndreasK79** [comment]
@Meganitrospeed I located the bug. MQ0HVU exists in the dxcc_exceptions table. When dxcc_lookup checks, it doesn't fetch longitude and latitude from the table:

![image](https://user-images.githubusercontent.com/6977712/177039164-ae924e0a-3bfe-45cd-973d-9d55d0078c07.png)

If you change the line in logbook_model like the picture above, it will work. I'll push a fix shortly.

**Comment by AndreasK79** [comment]
@Meganitrospeed master has been updated with fix.

**Comment by AndreasK79** [comment]
Reopening this, since it also exists in V2, but since dxcc_lookup has been changed, it doesn't give an error, as the code is not encountered in this case.

This part has been changed, and doesn't work:

> $dxcc_exceptions = $this->db->select('`entity`, `adif`, `cqz`')
	->where('call', $call)
	->where('(start <= CURDATE()')
	->or_where('start is null)', NULL, false)
	->where('(end >= CURDATE()')
	->or_where('end is null)', NULL, false)
	->get('dxcc_exceptions');

**Comment by AndreasK79** [comment]
@magicbug my head is spinning while trying to figure this one out.
We have several flaws in the implementation here for using dxcc_exceptions with dates.

Logbook_model:
1. Function dxcc_lookup: select('entity, adif, cqz') - if this part is triggered, we don't have lat/long (easy to fix with a *).
2. Function dxcc_lookup: curdate() is used in the same query, which leads to every lookup with older dates than today might be wrong. Probably fixable by using the $date parameter in the function, which leeds to the next problem.
3. Function dxcc_lookup is called with col_time_on some places, but this will not work correctly when checking for date in query.
4. When doing post qso, the date is never sent in when doing lookups for dxcc, but is set as todays date, which again might trigger incorrect dxcc info.

These are the things found so far, while trying to figure out a fix. I'm not sure about the best approach for fixing this. Any input is welcome.

**Comment by magicbug** [comment]
I'd suggest we look at it from the instance of loading the pin on the map.

**How I think it should work**

- When a callsign is entered it's checked against exceptions (This would need updating from clublog regularly by the user) for match and then DXCC for the date of right now
- The DXCC field in the QSO input area is shown or if nothing is found its None then user would have to select the DXCC
- Saved should hold this information into the database table for the QSO.

Map display

- Reads the QSO
- Probably needs todo a check against exceptions/dxcc again
- Map based on the lat/long or the gridsquare

**Comment by AndreasK79** [comment]
> * When a callsign is entered it's checked against exceptions (This would need updating from clublog regularly by the user) for match and then DXCC for the date of right now

This works for live logging, but not from post logging, since the date from the QSO input is never sent to the lookup. If we get a hit on the exception, we don't need to determine the DXCC for the date of right now. That is what exceptions are for.

> Map display
> 
> * Reads the QSO
> * Just grab the DXCC from the QSO and check it against the prefix table
> * If DXCC is "none" then just silently not display it.
> * Map based on the lat/long or the gridsquare

I agree. Since logged QSOs have the DXCC set, we don't need to determine this again. I'll take a look at this part and see if I can figure something out.

I was trying to fix the original problem, but I kept stumbling into more and more problems connected to dxcc_lookup.

**Comment by magicbug** [comment]
Might be that we need to create a new function for returning the data correctly. agree for Post we need to send the date across!
