### ISSUE TITLE
First letter of county name being dropped

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#1513]
In v2, the first letter of the county name is now being dropped on all states with the latest commit. 

Example: "SC,eaufort" instead of "SC,Beaufort"

**Comment by ofadam** [comment]
I forgot to mention that this is with the QRZ callbook integration.

**Comment by phl0** [comment]
Which branch are you using? And where exactly is the error occuring?

**Comment by ofadam** [comment]
station_logbooks branch – you can see the problem when on the Logbooks page and popping up a QSO lightbox to see the county entry that was sourced from QRZ.com.

**Comment by phl0** [comment]
Hmm not happening on my installation.

![Screenshot from 2022-07-02 12-08-36](https://user-images.githubusercontent.com/7112907/176996086-97120f8d-71c5-4bfb-b614-e431eea243dd.png)

How can I reproduce this pls?

**Comment by AndreasK79** [comment]
Can' reproduce this here either. Are you using the latest codebase from station_logbooks?

**Comment by ofadam** [comment]
I am indeed. My US_counties.csv file is intact, yet this is what I see when accessing various screens in Cloudlog.

<img width="917" alt="Screen Shot 2022-07-02 at 6 10 55 PM" src="https://user-images.githubusercontent.com/5504940/177018625-461c90f3-5a2f-45d5-a4b7-052ed892602e.png">

Strangely, in Live QSO, this is what I see for the county field after entering a callsign and having it pull from the callbook service – it's unavailable.

<img width="470" alt="Screen Shot 2022-07-02 at 6 11 49 PM" src="https://user-images.githubusercontent.com/5504940/177018643-e282e4d2-a552-4cc8-bfa4-c67ce56cd7e6.png">

**Comment by phl0** [comment]
I entered KE8PZN and get:

![Screenshot from 2022-07-03 08-49-19](https://user-images.githubusercontent.com/7112907/177028520-5952782b-801d-4712-a187-3ed4c5697e0c.png)

And if I lookup the QSO after that:

![Screenshot from 2022-07-03 08-49-32](https://user-images.githubusercontent.com/7112907/177028532-fdd075d9-05e8-4203-a0d9-92f5067d6139.png)

I have enabled the qrz.com API and it pulls the info from there. Is yours enabled or disabled?

**Comment by ofadam** [comment]
With QRZ callbook enabled, went through the same exact steps as you – I currently only have a non-paid QRZ.com account. Could that be the difference?

**Comment by magicbug** [comment]
As this is nearly a year old I'm closing
