### ISSUE TITLE
'Visit Public Page:' link does not include '/visitor/'

### ISSUE THREAD

**Issue by PotatoesMakeChips** [magicbug/Cloudlog#1515]
file: /application/views/logbooks/edit.php
line: 64
![image](https://user-images.githubusercontent.com/29355368/177027530-cd1a96a1-247a-44cb-ad57-f6dbb8474d35.png)
![image](https://user-images.githubusercontent.com/29355368/177027619-a93d4858-9700-46af-aa80-1fb9a391e826.png)

Clicking the link results in the following error:
![image](https://user-images.githubusercontent.com/29355368/177027657-5961312b-0917-4ad9-ba78-e1f81f317fa8.png)

Adding /visitor/ resolves the issue:
![image](https://user-images.githubusercontent.com/29355368/177027553-b23cf0f9-bb6d-4f79-94b9-0ddaf6a4a348.png)

I'll make a pull request when I can set up a dev environment if no one beats me to it. Unless there's a different way you want to solve the issue

**Comment by phl0** [comment]
Tnx for finding this bug. In the sense of the rest of the code the fix should be like here: 545e7765a08c20b1afc6cb9f8c28be14d673ad5d.

**Comment by magicbug** [comment]
Looks a perfect fix @phl0 PR away

**Comment by phl0** [comment]
There you go: https://github.com/magicbug/Cloudlog/pull/1518

**Comment by PotatoesMakeChips** [comment]
That fix works on my end
