### ISSUE TITLE
Feature Request: Dockerized App

### ISSUE THREAD

**Issue by cjtheham** [magicbug/Cloudlog#1529]
By setting up a Docker Compose file and the ability to run all of Cloudlog (everything from the actual PHP app to the db), it will make running the application on other platforms than Linux a breeze. It will also make it easier to spin up a development environment for testing.

https://www.cloudways.com/blog/docker-php-application/

**Comment by magicbug** [comment]
Theres quite a few docker Cloudlog files already on Github not something I'm planning to offer at this stage
