### ISSUE TITLE
[Station Locations] Make City field optional

### ISSUE THREAD

**Issue by magicbug** [magicbug/Cloudlog#1539]
### Discussed in https://github.com/magicbug/Cloudlog/discussions/1538

<div type='discussions-op-text'>

<sup>Originally posted by **KB2YSI** July 18, 2022</sup>
Is there a reason that the CITY field in a station location is required?

I frequently operate from many locations, satellite rover, and hardly know what county I am in much less than the town/city.  Having to enter that for each location is going to be either completely incorrect or a PITA to obtain the correct name.</div>

**Comment by phl0** [comment]
PR https://github.com/magicbug/Cloudlog/pull/1572 is merged. Please test and report.
