### ISSUE TITLE
Problem with upload to Clublog from cron

### ISSUE THREAD

**Issue by ok1cdj** [magicbug/Cloudlog#1541]
I have installed V2 Station logbooks branch. I have problem with upload to Clublog from cron. When i am logged in cloudlog and trying the URL for upload all is working. From the command line the result is 200 OK but empty response and no upload same from browser when i am not logged in to the cloudlog.

**Comment by magicbug** [comment]
If your using V2 branch its a known issue and will be resolved soon

**Comment by dg9vh** [comment]
See https://github.com/magicbug/Cloudlog/issues/1517, so you could close this issue :-)
