### ISSUE TITLE
Analytics could usefully use a page of statistics

### ISSUE THREAD

**Issue by g4klx** [magicbug/Cloudlog#1549]
It would be great to have a page in the analytics section that gave the raw statistics of activity across all of the bands. For example the list of bands in the left most column, followed by columns for the number of countries, grid squares, zones, etc. that have been confirmed (and maybe unconfirmed also). Only showing those bands where the numbers are greater than zero.

That way it would be easy to see progress towards awards, and general status of the confirmations. It wouldn't need any special graphics so would presumably be pretty efficient too.

**Comment by kb-light** [comment]
I would be interested in number of unique stations (maybe also by band/mode).

**Comment by kb-light** [comment]
I am fine with the new statistics from #1621
