### ISSUE TITLE
Add Aircraft Scatter (AS) as Propagation Mode

### ISSUE THREAD

**Issue by magicbug** [magicbug/Cloudlog#1565]
### Discussed in https://github.com/magicbug/Cloudlog/discussions/1563

<div type='discussions-op-text'>

<sup>Originally posted by **LAwmand** August 16, 2022</sup>

1. In propagation modes add "Aircraft Scatter".

David G0LBK</div>

**Comment by phl0** [comment]
Created a PR for this. See https://github.com/magicbug/Cloudlog/pull/1573

**Comment by magicbug** [comment]
and now merged into the dev branch
