### ISSUE TITLE
Custom Map - Allow filtering by mode / propagation

### ISSUE THREAD

**Issue by magicbug** [magicbug/Cloudlog#1566]
### Discussed in https://github.com/magicbug/Cloudlog/discussions/1563

<div type='discussions-op-text'>

<sup>Originally posted by **LAwmand** August 16, 2022</sup>
2. On a custom map dates search could other search criteria be added such as mode to narrow down qso's such as "mode" or "propagation type"? So, for example I could just see my meteor scatter contacts in August rather than seeing everything.
</div>

**Comment by AndreasK79** [comment]
Something like this:
![image](https://user-images.githubusercontent.com/6977712/187040494-1ee311e7-09a8-4240-aeea-e33ecfc46892.png)

**Comment by AndreasK79** [comment]
#1583 created for testing.

**Comment by AndreasK79** [comment]
And with some tweaking, I made the date selection the same size as the others:
![image](https://user-images.githubusercontent.com/6977712/187042911-51e50169-9f43-48bc-891a-c4dd2f7593be.png)

**Comment by AndreasK79** [comment]
It now keeps the datetimes too :)

**Comment by phl0** [comment]
Cool. I will test and report.

**Comment by phl0** [comment]
Forgot to report here. Works for me. Go for merge :)
