### ISSUE TITLE
Google Bot / Bing Bot seems to cause a PHP error when indexing Cloudlog instances

### ISSUE THREAD

**Issue by dm5tt** [magicbug/Cloudlog#1587]
**Describe the bug**
Google Bot / Bing Bot seems to cause an PHP error when trying to index a Cloudlog Instance.

CloudLog sites are getting indexed with following error message

`A PHP Error was encountered. Severity: 8192. Message: Return type of CI_Session_files_driver::open($save_path, $name) should either be compatible with ...`

I'm not able to get the full message.

**To Reproduce**
1. Install CloudLog
2. Allow Google Bot / Bing Bot to index your Cloudlog Instace
3. Use Google/Bing and search for your Cloudlog instance

**Expected behaviour**
Not throwing any error message when getting hit by an internet crawler

**Screenshots**
 
![image](https://user-images.githubusercontent.com/87605596/188097547-7670993e-51fc-404a-a076-fa9764f18472.png)

**Comment by magicbug** [comment]
Strange, can you tell us a bit about your install windows/linux/apache/php as I don't see this across all the ones I host but would be nice to fix it.

**Comment by dm5tt** [comment]
Closing this as "Can't Repro".
