### ISSUE TITLE
LoTW sync appears to be broken after adding secondary certificates

### ISSUE THREAD

**Issue by ryandzink** [magicbug/Cloudlog#1597]
**Describe the bug**
LoTW sync appears to be broken after adding certificates for Canadian provinces (.tq8 files get generated but never get uploaded)

**To Reproduce**
This may be a specific USA issue but I recently added two new certificates for KI7QEK/VE6 and KI7QEK/VE7 for operation there while on vacation. After adding those certificates, no QSOs using the LoTW manual sync operation ever appear in Logbook of the World, even in my default station location using my normal certificate without a /VE appended.

Steps to reproduce the behaviour:
1. Go to 'Logbook of the World'
2. Add a certificate for a callsign with a /VE appendix
3. Add a QSO (for any station location/certificate combination)
4. Attempt a manual sync and confirm .tq8 file is generated in the station locations with new QSOs
> Upload Successful - ./uploads/lotw/ki7qek-2022-09-10-01-11-17-cloudlog.tq8
6. Wait (forever) for those QSOs to appear in LOTW

**Expected behaviour**
On manual sync, I would expect to see the .tq8 file generated for any station location with new QSOs and then after they are processed see those QSOs in LoTW. However, they never appear. This is still the case even after removing the certificates I added with /VE6 and /VE7, and now means to sync with LoTW I must manually export ADIF files and upload via TQSL again.

**Additional context**
I'm using commit `ed33967472b12e9ed2ae224984a5299f552b3cd0` on the master branch.

**Comment by phl0** [comment]
Could it be this https://github.com/magicbug/Cloudlog/pull/1580? This was fixed by PR but only in station_logbooks branch as of now.

**Comment by ryandzink** [comment]
I think that actually fixes a related issue I had when setting up those other certificates but I'm not sure that it would cover this situation. I had been hoping to avoid moving over to station_logbooks as I wasn't sure what kind of schema migrations etc it might take to move over from master... is the process fairly straightforward?

**Comment by magicbug** [comment]
I believe we have fixed this in the dev branch, but not 100% sure.

Move is fairly straightforward but it is the dev branch so bits can break just a matter of switching branch and then creating a Logbook and a few other chages

**Comment by ryandzink** [comment]
@magicbug When you say creating a logbook does that mean basically starting from scratch in a new logbook after switching to the branch and pulling in the latest commit or do previous QSOs survive the switch? 😨

**Comment by AndreasK79** [comment]
Previous QSOs survive the switch. They are contacted to a station location.
A logbook is needed to group station locations.

Switching should not be a problem, but as always, make a database backup, just in case.

**Comment by ryandzink** [comment]
Alright, I successfully migrated to the dev branch 🎉  I've claimed ownership of many of my station locations and created a logbook for them for my VUCC circle etc but even on creating a dummy QSO in one of those sttations and uploading, I see the file get generated but it never makes it to LoTW. Is there any kind of debugging mode or logging on where that file goes? It gets removed from the filesystem faster than I can inspect it.

![image](https://user-images.githubusercontent.com/13768946/191166585-57794d92-1e8a-4e19-aaec-4e25b78fd2cc.png)

**Comment by phl0** [comment]
You can temporarily comment line 349 in `application/controllers/Lotw.php`:

```
diff --git a/application/controllers/Lotw.php b/application/controllers/Lotw.php
index 5505a045..f5b8b626 100644
--- a/application/controllers/Lotw.php
+++ b/application/controllers/Lotw.php
@@ -346,7 +346,7 @@ class Lotw extends CI_Controller {
                                        }

                                        // Delete TQ8 File - This is done regardless of whether upload was succcessful
-                                       unlink(realpath($filename_for_saving));
+                                       #unlink(realpath($filename_for_saving));
                                }
                        } else {
                                echo "No Station Profiles found to upload to LOTW";
````

Which disables the deletion of the tq8 file after upload. The file uploaded can then be found in `uploads/lotw/`. Should have a name similar to `df2et-2022-07-04-15-14-03-cloudlog.tq8`. This is basically a gzip file that you can extract and view. For example using:

```
$ zcat df2et-2022-07-04-15-14-03-cloudlog.tq8 | less
````

Maybe this reveals some hints?

**Comment by ryandzink** [comment]
OK, I was able to inspect the .tq8 file that was generated but don't see any evidence it made it into lotw after a few minutes. Here are two SOTA chases from today that I am trying to do a manual sync on.

A couple of things seemed off... but based only on my knowledge of ADIF file format. I marked them with asterisks...

```txt
<TQSL_IDENT:54>TQSL V2.5.4 Lib: V2.5 Config: V11.12 AllowDupes: false
<Rec_Type:5>tCERT
<CERT_UID:1>1
**<CERTIFICATE:1650>{1624 characters redacted... is this a certificate mismatch somehow?}**
<EOR>
<Rec_Type:8>tSTATION
<STATION_UID:1>1
<CERT_UID:1>1
<CALL:6>KI7QEK
<DXCC:3>291
<GRIDSQUARE:6>DM33XJ
<ITUZ:1>6
<CQZ:1>3
<IOTA:0>
<US_STATE:2>AZ
<EOR>
<Rec_Type:8>tCONTACT
<STATION_UID:1>1
<CALL:5>W7JET
<BAND:3>40M
<MODE:2>CW
<FREQ:5>7.032
<FREQ_RX:1>0
<QSO_DATE:10>2022-09-22
<QSO_TIME:9>21:02:00Z
<**SIGN_LOTW_V2.0:173:6**>{173 characters redacted}
<SIGNDATA:45>3DM33XJ6AZ40MW7JET7.0320CW2022-09-2221:02:00Z
<EOR>
<Rec_Type:8>tCONTACT
<STATION_UID:1>1
<CALL:5>W7JET
<BAND:3>40M
<MODE:2>CW
<FREQ:5>7.032
<FREQ_RX:1>0
<QSO_DATE:10>2022-09-22
<QSO_TIME:9>18:08:00Z
<**SIGN_LOTW_V2.0:173:6**>{172 characters redacted}
<SIGNDATA:45>3DM33XJ6AZ40MW7JET7.0320CW2022-09-2218:08:00Z
<EOR>
```

**Comment by ryandzink** [comment]
Disregard that, I looked in lotw_certs and the certificate length for my only remaining certificate (after I removed the /VE6 and /VE7) matches the certificate generated in the .tq8 file.

**Comment by phl0** [comment]
This looks exactly like the stuff I get for a QSO that I just created on my test system:

```
<TQSL_IDENT:54>TQSL V2.5.4 Lib: V2.5 Config: V11.12 AllowDupes: false

<Rec_Type:5>tCERT
<CERT_UID:1>1
<CERTIFICATE:1877>***removed***
<EOR>

<Rec_Type:8>tSTATION
<STATION_UID:1>1
<CERT_UID:1>1
<CALL:5>DF2ET
<DXCC:3>230
<GRIDSQUARE:6>JO31OL
<ITUZ:2>28
<CQZ:2>14
<IOTA:0>



<EOR>

<Rec_Type:8>tCONTACT
<STATION_UID:1>1
<CALL:6>KI7QEK
<BAND:3>80M
<MODE:2>AM
<FREQ:5>3.583
<FREQ_RX:1>0



<QSO_DATE:10>2022-09-23
<QSO_TIME:9>07:28:00Z
<SIGN_LOTW_V2.0:173:6>***removed***
<SIGNDATA:46>14JO31OL2880MKI7QEK3.5830AM2022-09-2307:28:00Z
<EOR>
```

I cannot see any (relevant) difference here....

**Comment by phl0** [comment]
Another idea just came to mind. Log into LotW and go to `Your Accoun` -> `Your Activity`. That should show all activity regarding uploads. You can see the filename processed and there is also a link to `Result`. First I hope that your uploaded file (filename from the sync LotW output in Cloudlog) appears in the list. And what is the result?

This is what it looks like on my end:

![Screenshot from 2022-09-23 10-18-31](https://user-images.githubusercontent.com/7112907/191919413-a60409e5-99a6-4d1c-bb62-ed7c85f9b7e6.png)


![Screenshot from 2022-09-23 10-18-38](https://user-images.githubusercontent.com/7112907/191919387-aab3cad9-113f-480e-8e0e-a6d92b57e930.png)

**Comment by ryandzink** [comment]
Ah! Now we're getting somewhere. 

```
2022-09-10 22:49:05 LOTW_QSO: Processing file: 20220910224806.13131
2022-09-10 22:49:05 LOTW_QSO: User file: /opt/bitnami/apache2/htdocs/uploads/lotw/ki7qek-2022-09-10-22-48-06-cloudlog.tq8
2022-09-10 22:49:05 LOTW_QSO: Processing ABORTED: INVALID CERTIFICATE - Certificate may not be used. Certificate status = Superceded
```

**Comment by ryandzink** [comment]
I think this is all user error... I initially uploaded my certificate from a computer that ultimately got lost and never had to use TQSL until recently, when I had to generate a new certificate on a different computer. I don't think I was aware that immediately made my old certificate (for `KI7QEK`) invalid. Going to try importing my new certificate into Cloudlog and see if that fixes things.

**Comment by ryandzink** [comment]
And there it is... updated certificate fixed the whole thing.

```
2022-09-23 22:44:15 LOTW_QSO: Processing file: 20220923224330.6738
2022-09-23 22:44:15 LOTW_QSO: User file: /opt/bitnami/apache2/htdocs/uploads/lotw/ki7qek-2022-09-23-22-43-30-cloudlog.tq8
2022-09-23 22:44:15 LOTW_QSO: Certificate found for KI7QEK - UNITED STATES OF AMERICA (291)
2022-09-23 22:44:15 LOTW_QSO: Successfully processed 1 QSO record in 0.088617 seconds
2022-09-23 22:44:15 LOTW_QSO: No errors encountered
```

Thanks @phl0 ! I'm going to revert my changes so the .tq8 files get auto cleaned and close this out as resolved.
