### ISSUE TITLE
[Version 2] Upgrade Checklist for users coming from V1

### ISSUE THREAD

**Issue by magicbug** [magicbug/Cloudlog#1614]
Thought I better write some notes down on what I was thinking for this as there are some functional changes.

- I'd suggest we use the config table to store whether the user has seen the V2 Checklist
- Need to suggest to user to take ownership of ALL Station Locations perhaps a button they can press
- API this needs similar treatment to Locations, or revoke ALL API keys and tell them to make new ones.
- Teach them about Logbooks and the importance and how to use them.
- Perhaps a little reminder to update the Country files
- In the config perhaps rename the user auth roles as you can now have standard users and admins with their own logbooks etc.

Theres probably some other bits, I'm doing Railways on the Air this weekend so times a bit thin but wanted to dump my brain!

**Comment by magicbug** [comment]
### Changes to config.php

```php
$config['auth_level'][3] = "Operator";
$config['auth_level'][99] = "Administrator";
```

**Comment by magicbug** [comment]
### Changes to index.php

Remind users that they might want to set the _ENVIRONMENT_ to production rather than development to hide errors and debugging data.

```php
define('ENVIRONMENT', 'production');
```

**Comment by AndreasK79** [comment]
@phl0 pointed out that PHP 8.1 gives errors with Cloudlog. I think Codeigniter has been updated to fix this, but I need to test it out with an upgrade here. Is PHP 8.1 compatibility wanted for V2, or is 8.0 good enough for the time being?

**Comment by magicbug** [comment]
8.1 would be nice but if we can scrape 8.0 that wouldn't be a bad thing :)

**Comment by AndreasK79** [comment]
8.0 works. That was upgraded last year. I think the latest dev-version for Codeigniter is ok with 8.1, but need to test.

**Comment by AndreasK79** [comment]
Just had a quick test with the latest dev version of CI. It does not fix the errors being thrown. That means 8.1 compatibility will have to wait.

**Comment by magicbug** [comment]
> Just had a quick test with the latest dev version of CI. It does not fix the errors being thrown. That means 8.1 compatibility will have to wait.

Agreed

**Comment by phl0** [comment]
> Just had a quick test with the latest dev version of CI. It does not fix the errors being thrown. That means 8.1 compatibility will have to wait.

Roger that.

**Comment by magicbug** [comment]
OK @AndreasK79 @phl0 I believe this is now done, if you chaps can have a look

**Comment by AndreasK79** [comment]
I'm stuck at welcome :)

**Comment by AndreasK79** [comment]
Lovely colors too :)
![image](https://user-images.githubusercontent.com/6977712/195133177-fe2a0a72-3295-43ac-9232-0d9bcdbd1988.png)

Seems to be the code tag. Need to look into that as well.

**Comment by AndreasK79** [comment]
Fixed a typo in the view, but it didn't fix my issue. Need to dig more later.

**Comment by magicbug** [comment]
Probably my shockingly bad IF statements.. it will be a lesson of "don't code when feeling terrible" I'm sure of it :p

**Comment by magicbug** [comment]
Poked a few more things and perhaps fixed, certainly isn't an issue with V1 to V2

**Comment by ofadam** [comment]
Unfortunately, still seem to be stuck. Same issue with cron prompt not being able to be cleared in welcome message, but also with addition of API keys. After clicking on "Claim APIs" button and have it change to "All API Keys Claimed," clicking on "check if migration complete" button then protests with same API message.

**Comment by AndreasK79** [comment]
That last commit solved it for me. I was having the exact same issue as @ofadam described above.

**Comment by magicbug** [comment]
Perfect

**Comment by ofadam** [comment]
Yep, I'm good now as well! Thanks for all your incredible work in getting to V2, all!

**Comment by magicbug** [comment]
> Yep, I'm good now as well! Thanks for all your incredible work in getting to V2, all!

I'll be very happy once its live, can get back to fixing bugs and building new features ;-)

**Comment by magicbug** [comment]
Right, sooo at some point I need to take the plunge and make this live once everyone thinks we are good to go

**Comment by phl0** [comment]
> OK @AndreasK79 @phl0 I believe this is now done, if you chaps can have a look

I just set up another V1 instance, added some log data and then switch branches to `station_logbooks`. What shall I say? All migrations ran smoothly and the upgrade worked out of the box.

**Comment by magicbug** [comment]
I'll let it sit for a night, see if anything appears, then do a quick run through everything to look for issues then perhaps its release time.
