### ISSUE TITLE
[Bug][station_logbooks] PHP Error when claiming ownership after migration

### ISSUE THREAD

**Issue by kb-light** [magicbug/Cloudlog#1627]
**Describe the bug**
When switching to branch station_logbooks and trying to claim ownership of a location a PHP error is displayed. The ownership is successfully claimed.

**To Reproduce**
Steps to reproduce the behaviour: 
1. Go to 'Station Location'
2. Click on 'Claim Ownership'
3. See error

**Expected behaviour**
No error is displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/14014119/193408036-2174be4e-ca1c-4cbb-bd4e-0dc910dd4741.png)

**Server:**
 - Docker
 - Apache2
 - PHP 7.4
 - MariaDB 10

**Comment by magicbug** [comment]
should be resolved now some left over code

**Comment by kb-light** [comment]
Can confirm that it is resolved.
