### ISSUE TITLE
Incorrect QSO totals for new statistics grid

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#1631]
In the latest version on the station_logbooks branch, both the X and Y axis QSO totals don't equal what's present in the table.

<img width="1151" alt="Screen Shot 2022-10-02 at 3 19 17 PM" src="https://user-images.githubusercontent.com/5504940/193474602-f59ea81f-3b1e-4a94-bef0-58cdab0e1118.png">

**Comment by magicbug** [comment]
Believe this is a known issue with the dev branch but @AndreasK79 will be able to say for sure

**Comment by AndreasK79** [comment]
Currently there are 2 issues with the code. It has to do with the data in the database.

1. Different casing on bands. 160m and 160M are treated as different bands.
2. COL_SUBMODE can be either null or blank. The code checks for null values.

If the database had been more strict, this wouldn't be an issue.

My bet is issue 2 is causing this.

It's on my list, just haven't gotten around to it.

**Comment by AndreasK79** [comment]
@ofadam I've pushed a fix now. Could you pull the latest code and report back?

**Comment by ofadam** [comment]
Works beautifully! Thanks!
