### ISSUE TITLE
Reproduceable crash

### ISSUE THREAD

**Issue by LAwmand** [magicbug/Cloudlog#1633]
I know nothing about code.

The whole app crashes when I fully zoom out when displaying locator squares. I know it,s a stupid thing to do but ive twiddled my mousewheel the wrong way a few times. Once crashed it just freezes and is unresponsive until I hit the back button a couple of times
Windows 10 on Magicbug server, same error on my desktops and laptop

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to "Analytics" then "Gridsquares"
2. Zoom out until it will zoom no more using mouse wheel
3. Once zoomed out nothing works, you can't zoom back or click anything or click headings
4. Back button gets you out of it after pressing it a few times

**Expected behaviour**
To zoom in and out flawlessly

**Desktop (please complete the following information):**
 - OS: Win 10
 - Microsoft Edge
 - Version

**Comment by AndreasK79** [comment]
Hi. I've seen this issue myself. I think we need to specify max zoom levels to avoid this.

**Comment by magicbug** [comment]
Quite likely, Leaflet gets a little upset if lots of markers are being displayed

**Comment by phl0** [comment]
I think its not the markers but zoom level being 0 that causes the issue here. Up to zoom = 1 everything works fine on my end.

**Comment by magicbug** [comment]
That narrows it down for a quick fix!

**Comment by phl0** [comment]
This fixes it. Can someone test?

https://github.com/magicbug/Cloudlog/compare/station_logbooks...phl0:Cloudlog:minZoom?expand=1

**Comment by phl0** [comment]
Fixed it by setting minZoom to 1. So you cannot zoom out more. See https://github.com/magicbug/Cloudlog/pull/1634.

**Comment by phl0** [comment]
Custom map is not affected by the way. PR fixes it for gridsquares and activated gridsquares.

**Comment by LAwmand** [comment]
Thanks for the prompt and effective response phl0.
Magicbug, will this be reflected on my site?
Regards all, David

**Comment by LAwmand** [comment]
Thanks Peter,
Best Regards
David
