### ISSUE TITLE
[Feature][Bands] Disable columns function for awards

### ISSUE THREAD

**Issue by phl0** [magicbug/Cloudlog#1640]
During coding for POTA support I discovered that it might be useful to have a checkbox per column to disable all bands per award. E.g. all bands for POTA etc. @AndreasK79 What do you think?

So like this roughly?

![Screenshot from 2022-10-05 22-11-37](https://user-images.githubusercontent.com/7112907/194157408-c0ba6484-300f-408e-82f8-f81f4d7fff2a.png)

**Comment by AndreasK79** [comment]
I like the idea. One "master" checkbox to disable all checkboxes for the award?

**Comment by phl0** [comment]
> I like the idea. One "master" checkbox to disable all checkboxes for the award?

Exactly that.

**Comment by AndreasK79** [comment]
Want me to look into it, or do you want to give it a go?

**Comment by phl0** [comment]
Feel free to do it. I am just digging around trying to hide SAT pages and data if SAT is disabled in bands. See https://github.com/magicbug/Cloudlog/discussions/1637

**Comment by AndreasK79** [comment]
Frontend is done and working:
![image](https://user-images.githubusercontent.com/6977712/194244086-d3cd431b-ea18-4728-984f-6966533a088b.png)
Just need the backend to save the changes.

**Comment by AndreasK79** [comment]
@phl0 here #1642 is your wish.

**Comment by phl0** [comment]
> @phl0 here #1642 is your wish.

As you command my king. I will test as soon as possible an report.
