### ISSUE TITLE
Installation problem: database.php not writable

### ISSUE THREAD

**Issue by ct2iww** [magicbug/Cloudlog#165]
Hello.

I'm trying to install Cloudlog on my local Xubuntu 14.04 PC and followed all steps but keep getting an error message that asks to make the database.php in /aplication/config/ writable, which I've done (chmod 777), but to no avail.

I've noticed that the file in that directory is named database.sample.php and renamed it. Copying the database.php file in /install/config and making it writable won't do it either.

Also looked into the install index.html file and tried to change the index.php file to point to the file but also is a no go, even when adding the full pat (var/www/html.. etc.).

What else could I try?

Thank you.

Paulo, CT2IWW

**Comment by magicbug** [comment]
As this is an old issue i'm closing it.
