### ISSUE TITLE
[Feature] Interactive map for CQ Award

### ISSUE THREAD

**Issue by kb-light** [magicbug/Cloudlog#1650]
I like the map which is shown at the Worked All States award page and I would like to have a similar map for the CQ Award. Also for DXCC and so on, but that seems a bit much to me.

Additionally the "Map" subpage at CQ Award can then be removed.

**Comment by AndreasK79** [comment]
I wouldn't mind implementing it, if you could find an interactive javascript map for CQ zones or DXCC, like the one made for the US States.

**Comment by AndreasK79** [comment]
Perhaps something like this could work:

![image](https://user-images.githubusercontent.com/6977712/194718240-fba51fdc-3bd7-4a6d-9879-171f8be9d0d3.png)
I need to solve a problem with zone 1, 19, 31 and 32. They will not draw correctly in Leaflet.

**Comment by magicbug** [comment]
That would work.. @g7vjr did have some KML files for CQ and ITU zones but seems blogs down

**Comment by AndreasK79** [comment]
Yep, that was my first idea (IV3TMM links them on his QRZ profile).
![image](https://user-images.githubusercontent.com/6977712/194740675-0e63c20b-735a-4ed3-bf6b-9b3de489aecf.png)
Same problem with the zones.

The problem is Leaflet:
https://github.com/leaflet/leaflet/issues/82

**Comment by AndreasK79** [comment]
Tried to solve it with the antimeridian plugin, but the result wasn't exactly what I wanted.
![image](https://user-images.githubusercontent.com/6977712/194746220-c1dc975e-4568-4260-ac5c-73553db2575e.png)
Not sure if I can manage to solve this one, but haven't given up quite yet.

**Comment by phl0** [comment]
Well at least it looks ... "interesting" ... :)

**Comment by AndreasK79** [comment]
Haha. Yes, that is one way of describing it :)

**Comment by AndreasK79** [comment]
Now we're getting somewhere:

![image](https://user-images.githubusercontent.com/6977712/194749931-4dc71727-83c1-47e5-bd31-e9f1abced07a.png)

**Comment by AndreasK79** [comment]
The worst part is done:
![image](https://user-images.githubusercontent.com/6977712/194769385-f13f0b3c-36c6-4a3f-a2ce-607aa6e337eb.png)

**Comment by magicbug** [comment]
What's the best part

**Comment by AndreasK79** [comment]
Integrating it into Cloudlog. That should just be a matter of doing now that the zones are drawn correctly :)

**Comment by phl0** [comment]
Great job @AndreasK79 👍

**Comment by g7vjr** [comment]
Fantastic work on this! 🙌On 9 Oct 2022, at 10:48, Andreas Kristiansen ***@***.***> wrote:﻿
Now we're getting somewhere:

**Comment by AndreasK79** [comment]
> Great job @AndreasK79 👍

Thanks

**Comment by AndreasK79** [comment]
> Fantastic work on this! 🙌

Thanks Michael.

A few things left to do, but shouldn't be that hard:
![image](https://user-images.githubusercontent.com/6977712/195039395-d0bb176f-5015-4f60-ac26-6769bdf7d69d.png)

Perhaps you are interested in the map for Club Log as well?

**Comment by AndreasK79** [comment]
Another teaser:
![image](https://user-images.githubusercontent.com/6977712/195188139-164519c9-aa51-46ff-aa5d-f7d6ee4f6dc1.png)
Some polishing and tweaking, but getting there.

Also need to add popup with QSOs when clicking on map.

**Comment by magicbug** [comment]
This is looking swish!

**Comment by phl0** [comment]
Want++. Nice work @AndreasK79

**Comment by magicbug** [comment]
Should I hold out to put it in V2 launch ;-)

**Comment by AndreasK79** [comment]
It depends on how eager you are to release. 

Hopefully I can make a PR tomorrow afternoon for testing.

**Comment by magicbug** [comment]
Its taken this long to get it ready.. another day wont hurt

**Comment by AndreasK79** [comment]
Test away :)

**Comment by kb-light** [comment]
![image](https://user-images.githubusercontent.com/14014119/195377677-cd4a2fd7-6410-4859-9fbe-05ef55321e06.png)
Thanks, that was faster than expected and it looks great.

Bug:
- Old maps seems to stay in the background. You can see that when generating multiple maps and than zoom out or try to move the map.

Some small improvements:
- Add a small space between the map and the Bottom of the screen (similar to the tables)
- Shift the map a bit to the right as there are small parts missing from zone 31 and 32

**Comment by AndreasK79** [comment]
The map is responsive, so there will always be space between the map and the bottom.
We can shift the map a bit to the right, but the whole map will not fit. If you use a widescreen monitor, take a look at these custom wide themes I made: https://github.com/AndreasK79/cloudlog_wide_custom_themes

As for the old maps, I need to see if I can figure out what's going on.

**Comment by phl0** [comment]
Confirmed. Seems like pushing the button again just creates a new map overlay (which is hidden below the first one)

![Screenshot from 2022-10-12 21-42-08](https://user-images.githubusercontent.com/7112907/195433510-46c94250-958c-41dc-a7d9-9ef7de46c3c2.png)
