### ISSUE TITLE
Stuck on "welcome" message in v2

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#1656]
On the verrry latest station_logbooks edition, I'm unable to move past the cronjob adjustments message. I've set mine up with everything suggested, but there's no way to move ahead.

**Comment by magicbug** [comment]
Small chance this is fixed, seems to be an issue with those already using v2.

**Comment by magicbug** [comment]
This issue is already being discussed at https://github.com/magicbug/Cloudlog/issues/1614
