### ISSUE TITLE
All users station profiles appear when editing existing QSO

### ISSUE THREAD

**Issue by Hubok** [magicbug/Cloudlog#1664]
![image](https://user-images.githubusercontent.com/1284419/195547380-330e1cd6-8496-49f0-80e8-40517a2f55be.png)

On commit 465fa4256f9a61a7395aea7142a08abcca2fcb1f, I'm able to view every other station profile in this screen as an operator, though attempting to save silently fails and the QSO remains in the existing profile.

**Comment by phl0** [comment]
I cannot confirm on my installation. Could you please elaborate on your accounts? 
I logged in as an Operator and cannot see the station locations for another admin account ...

**Comment by phl0** [comment]
A fix has been proposed in PR https://github.com/magicbug/Cloudlog/pull/1689.
