### ISSUE TITLE
Band Textboxes are showing a lot of bands

### ISSUE THREAD

**Issue by ea5wa** [magicbug/Cloudlog#1671]
When I open whatever band textbox, it shows a lot of bands....
![cloudlog bug](https://user-images.githubusercontent.com/54686689/195890526-6f7cb0c1-9276-4146-aa5d-dc1ee2e91242.jpg)
![cloudlog bug 2](https://user-images.githubusercontent.com/54686689/195890833-18bb0e43-e268-47e3-bf32-be4807e54bc2.jpg)

**Comment by magicbug** [comment]
I'd suggest deleting the duplicate bands seems they are listed twice.

**Comment by ea5wa** [comment]
Yes, it works... But why has it happened?

**Comment by AndreasK79** [comment]
Can't say I understand why. Migration checks if tables exists or not.

**Comment by magicbug** [comment]
I'm going to close this as an unknown random bug and hope it doesn't reappear

**Comment by AndreasK79** [comment]
We can hope. Impossible to know what happened without having the database before migration.

**Comment by ea5wa** [comment]
Ok. Thanks

**Comment by tonyc** [comment]
Just wanted to note, this is currently happening in my cloudlog-hosted instance.
