### ISSUE TITLE
Remove slug from logbook not possible

### ISSUE THREAD

**Issue by PD0RZH** [magicbug/Cloudlog#1680]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
Unable to remove a slug completely.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Station Logbooks
2. Edit a logbook
3. Set a public slug and Save
4. Try to remove the slug (textfield empty)
5. System responds with "Looks good! is available"
6. Try to Save
7. Nothing happens, no error is shown

**Expected behaviour**
I expect the system can handle a default  (read empty) slug. 

**Desktop (please complete the following information):**
 - MAC OS Monterey
 - Safari
 - Version 16.0

**Comment by dg9vh** [comment]
Use this link:
![image](https://user-images.githubusercontent.com/13950650/195978733-cecb71fa-d3e0-4842-9939-a7565bea5643.png)

**Comment by PD0RZH** [comment]
Isn't that the place to remove the logbook? I just want the slug to be removed.

**Comment by magicbug** [comment]
Thats a bug.. I'll add an option later :)

**Comment by phl0** [comment]
I have some basically working code for this:

![Screenshot from 2022-10-15 18-45-04](https://user-images.githubusercontent.com/7112907/195998215-037b3746-f877-4668-8248-46a007797103.png)

Needs some CSS align on the buttons and some magic to make the input field empty as soon as the slug is removed.

**Comment by magicbug** [comment]
If you want me todo the CSS magic put it as a PR and I'll do my thing later on it ?)

**Comment by phl0** [comment]
Just had to take a break. Let me look into it once again. If I fail I will give a shout.

**Comment by phl0** [comment]
I made a proposal: https://github.com/magicbug/Cloudlog/pull/1688

![Screenshot from 2022-10-15 20-51-26](https://user-images.githubusercontent.com/7112907/196003338-199b1b4b-9ec2-4776-8044-771079e97f76.png)
