### ISSUE TITLE
Gridline qsos not properly showing up in gridsquare map for 6 meters

### ISSUE THREAD

**Issue by N9EAT** [magicbug/Cloudlog#1687]
I have multiple qsos that do not properly populate on the grid square map on 6 meters that are grid line qsos. This is an issue I do not have for satellite qsos. Grids are properly inputted into the vucc gridsquare field. The grids are still counted in the vucc total, and where the square is is still clickable and shows the qso in question. 

![image](https://user-images.githubusercontent.com/111320900/195990474-0817cadd-d714-4ca6-aafe-98b4b1d0c75f.png)

**Comment by magicbug** [comment]
Thanks for reporting @N9EAT this is a bug, seems vucc squares for band isn't checked hence ignored.

**Comment by AndreasK79** [comment]
#1714 fixed this problem.

**Comment by AndreasK79** [comment]
This has been fixed in dev.
