### ISSUE TITLE
Installation O3S

### ISSUE THREAD

**Issue by Platforme** [magicbug/Cloudlog#169]
![image](https://cloud.githubusercontent.com/assets/11796787/6992626/eaf9b06a-dad0-11e4-9702-fcb21674e3d4.png)

I have this issues when  I try to have O3S in my localhost via wampserver.
Please any one can help me . I follow this link : https://github.com/drakkr/QSOS/blob/master/Docs/en/qsos-o3s-install_en.md
 And I still have a problem.

Thank you very much

**Comment by magicbug** [comment]
Please refer to https://github.com/magicbug/Cloudlog/wiki/Installation to make sure you've installed it correctly. the "installation" system is broken.
