### ISSUE TITLE
Cloudlog Developer Mode

### ISSUE THREAD

**Issue by do4bmw** [magicbug/Cloudlog#1715]
Hy

after Update to 2.0 i have "Developer Mode" on ?!
and i get a lot of debug outputs below my logbook

how can i disable this "feature" ?

![Screenshot_49](https://user-images.githubusercontent.com/76187206/197462539-1e82bfe1-624d-4be9-a2ef-97855b35c0e5.jpg)
![Screenshot_48](https://user-images.githubusercontent.com/76187206/197462542-a7492ca0-e3fa-4b2a-8b5f-13d5b55f14c6.jpg)

**Comment by phl0** [comment]
edit index.php and set:

`define('ENVIRONMENT', 'production'`

**Comment by petrkr** [comment]
This should be set from Apache/Nginx environment (vhost) configuration, editing git based files will lead to their overwrite in next clone/deploy/update.
