### ISSUE TITLE
Pagination in public view

### ISSUE THREAD

**Issue by PD0RZH** [magicbug/Cloudlog#1720]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
No pagination in Public View

**To Reproduce**
Steps to reproduce the behaviour:
1. Make sure you've got enough QSO's  for pagination
2. Go to Public view 
3. Scroll down to  bottom
4. No pagination

**Expected behaviour**
Pagination to go through all QSO's

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser  Edge
 - Version 106.0.1370.52 (Officiële build) (64-bits)

And if it's not a bug then maybe a feature request

**Comment by magicbug** [comment]
scratch that its a bug! seems public has no logbook.. I'll create a request

**Comment by PD0RZH** [comment]
Serioously i was not sure whether this isa bug or not. Glad you created a request.

**Comment by patrickrb** [comment]
I think public logbooks are working again.  Should this one be closed? Or is there more work to be done?

**Comment by patrickrb** [comment]
Also, i was talking to my club about this today.  We think itd be nice if we could share our entire log publicly.  Would it be ok if we added an option in the logbook options to 'allow full access'? Or something to that affect, that would allow paging/search etc through the entire log publicly?

**Comment by PD0RZH** [comment]
Are you sure pagination is working in public view? 
![pagination](https://github.com/magicbug/Cloudlog/assets/60810525/717375b8-fb51-4f81-be3e-fcdcda96519b)

cloudlog/index.php/visitor/logbook
