### ISSUE TITLE
Callsign with slash in the search, searches for the text before the slash, and gives too many results.

### ISSUE THREAD

**Issue by AndreasK79** [magicbug/Cloudlog#1721]
I haven't looked too much into this issue, but noticed it while testing out another PR.

I searched for LA/SP7VC, and got that callsign and several thousand other entries. The search was searching for calls and gridsquares with LA in it:
![image](https://user-images.githubusercontent.com/6977712/197991981-427c1918-1880-46c1-a2b7-d971d08ca87c.png)

@magicbug is this by design, or a bug?

**Comment by magicbug** [comment]
Currently by design, think I used a like query

**Comment by AndreasK79** [comment]
I see. Should it be changed to search for the whole call, not just the text before the slash?

**Comment by magicbug** [comment]
Could do it that if nothings found doing a whole search that it trys a LIKE query

**Comment by AndreasK79** [comment]
I agree. I'll see if I can figure out how this works. I did have a look, but couldn't quite get the hang of it.

**Comment by magicbug** [comment]
Its some original code that i havent touched in years :D

**Comment by phl0** [comment]
cnfm here. Seems to only happen with prefixed callsigns:

![Screenshot from 2022-10-26 13-26-48](https://user-images.githubusercontent.com/7112907/198014978-5ad18f77-0178-4c7f-838a-f217ef081c35.png)

**Comment by phl0** [comment]
No happening with only suffixed callsigns.

![Screenshot from 2022-10-26 13-36-43](https://user-images.githubusercontent.com/7112907/198016617-25319458-4f6f-4515-9f63-c64f7a49601c.png)

**Comment by AndreasK79** [comment]
Technically it is happening, but since DF2ET is unique, it will not happen. LA is not unique enough. If you had logged a locator with DF2ET, you would get that as a result as well.

**Comment by AndreasK79** [comment]
Pushed #1726 now that searches correctly when callsign contains /. Since the function was called with url/callsign, only the part before the / was searched. Now we search with the / and the string after that. If no result, we do as before.

**Comment by AndreasK79** [comment]
Merged fix into dev.
