### ISSUE TITLE
Feature request: "Confirmed" option for Timeline page

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#1722]
Currently, I'm able to see which new countries I've contacted via the Timeline page – but I'm not able to necessarily tell which new countries I've confirmed via LoTW. Maybe a new checkbox or drop-down menu would do the trick?

<img width="1155" alt="Screen Shot 2022-10-26 at 10 59 08 AM" src="https://user-images.githubusercontent.com/5504940/198076192-a23cbfa0-cd1b-47a4-9628-1da5b831a59d.png">

**Comment by AndreasK79** [comment]
Added #1727 with checkboxes for QSL/LoTW/eQSL

**Comment by AndreasK79** [comment]
This is merged into latest dev.
