### ISSUE TITLE
Public Search not visible

### ISSUE THREAD

**Issue by PD0RZH** [magicbug/Cloudlog#1728]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
In Public View the search bar is not visible anymore.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Public View
2. Verify that the Public Search bar is visible.
3. If visible 
    a. Login and go to Admin page. 
    b. Toggle the search bar visibility under Appearance 
    c. Log out and verify that search bar is not visible 
4. If not visible    
    d. Log in (again) and toggle visibility back to enabled
    e. Log out again. And verify that Search bar is not enabled 

**Expected behaviour**
Searchbar to be enabled when toggled to enabled in Admin area

**Screenshots**
<img width="1364" alt="Scherm­afbeelding 2022-10-29 om 08 47 16" src="https://user-images.githubusercontent.com/60810525/198818151-b6aa5b3f-38c3-44f3-bf22-201fac61fa9c.png">

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser Safari and Chrome

**Comment by AndreasK79** [comment]
Duplicate #1505. It's not implemented yet.
