### ISSUE TITLE
Error when attempting to edit user in admin

### ISSUE THREAD

**Issue by bakoontz** [magicbug/Cloudlog#173]
There are two fields missing in the users table that prevents user edits from being saved correctly:

```
A Database Error Occurred

Error Number: 1054

Unknown column 'user_lotw_name' in 'field list'

<update statement deleted>

Filename: C:\wamp\www\cloudlog\system\database\DB_driver.php

Line Number: 330
```

**Comment by magicbug** [comment]
Please make sure you're running the latest version and have created all the tables earlier versions had some fields missing.
