### ISSUE TITLE
Error when using same email address on different user accounts

### ISSUE THREAD

**Issue by bakoontz** [magicbug/Cloudlog#174]
If I'm working with 3 different callsigns, I really don't want to go through the hassle of entering a different email for each.  Probably not a good idea to use the email as a primary key in the table.  Callsign should be sufficient.

**Comment by magicbug** [comment]
Email address isn't the primary key of the table? its an indexed field, the primary key is USER_ID.

**Comment by magicbug** [comment]
Cloudlog doesn't support multi user logbooks as it states all QSOs are placed in one table and shown on all logins

**Comment by magicbug** [comment]
The email was set to unique based on a feature I was going to add but decided not too, you can easily remove the index if that doesn't fit to your use case.

**Comment by bakoontz** [comment]
> Cloudlog doesn't support multi user logbooks as it states all QSOs are placed in one table and shown on all logins 

OK I must have missed that in the docs.  Doesn't do me much good then...
