### ISSUE TITLE
QSO records not associated with user call?

### ISSUE THREAD

**Issue by bakoontz** [magicbug/Cloudlog#175]
Maybe I'm not understanding the design here, but I'm running cloudlog locally...I am entering QSOs from a previous callsign I once had.  But what I'm seeing are QSOs that were entered under a different callsign.  Am I missing something here?

**Comment by magicbug** [comment]
Thats working as per design.

**Comment by bakoontz** [comment]
How so?  Why would I want all my QSOs from different callsigns lumped together?
