### ISSUE TITLE
Can't create a location 

### ISSUE THREAD

**Issue by ruilvo** [magicbug/Cloudlog#1767]
On master branch as of today, when I try to create a station location, I can't select a DXCC entity:
![imagem](https://user-images.githubusercontent.com/8402646/201144356-36968dc3-840b-49ba-9768-780eac8338a9.png)

On `production` mode, nothing happens. On `developer` mode, this error pops up:
![imagem](https://user-images.githubusercontent.com/8402646/201144582-3b7f5056-c923-45b6-b511-aece747f7e24.png)

Confirming it is indeed due to the inability to select the DXCC entity.

This is how I setup the server, it's reproduceable for anybody with docker: https://github.com/ruilvo/cloudlog-docker-compose

**Comment by phl0** [comment]
Did you update the DXCC information?

**Comment by ruilvo** [comment]
That was it, thanks.
