### ISSUE TITLE
PHP 7 compatability

### ISSUE THREAD

**Issue by core-dd** [magicbug/Cloudlog#177]
Hej hej,
updated to PHP 7 and running into issues now. Start page returns:
'''
A PHP Error was encountered
Severity: Notice
Message: Only variables should be assigned by reference
Filename: core/Controller.php
Line Number: 51
'''
Looks like CodeIgniter is using some depricated statements. Any suggestions besides downgrading PHP?

Cheers,
Jens

**Comment by magicbug** [comment]
Current version of codeigniter that cloudlog uses isn't php7 ready, so
sadly the only option is to downgrade for now.

I've not checked how badly the latest codeigniter update breaks the system
yet.

Peter

**Comment by core-dd** [comment]
I'm on my way in merging the latest CodeIgniter updates up to 2.2.6. Have to add a database migration file for the minor changes in CIs databases. Migration up to 3.x series is a more advanced endeavour...

**Comment by magicbug** [comment]
Yeah I have a sneaky feeling 3x might require some large rewrites in places
but 2.x should in theory merge up ok

On 16 January 2016 at 13:41, Jens Abraham <notifications@github.com> wrote:

> I'm on my way in merging the latest CodeIgniter updates up to 2.2.6. Have
> to add a database migration file for the minor changes in CIs databases.
> Migration up to 3.x series is a more advanced endeavour...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magicbug/Cloudlog/issues/177#issuecomment-172207913>.
>



-- 
Peter Goodhall

**Comment by core-dd** [comment]
I've updated my local instance to CI 2.2.6. It's working so far under PHP 5.X without any noticible change. Unfortunatly CI seems to support PHP 7 only in the 3.X branch.

**Comment by magicbug** [comment]
Yeah, switching to 3x would require near on rewrite i think, and by then might as well start considering my plans for cloudlog v2 :)

**Comment by wvolz** [comment]
I have a working new install of Cloudlog running on CI 3.1.6 and PHP7. I haven't tested the code to upgrade older databases yet, but will try to do that soon. Pull request will come shortly unless you would like me to post a link to my fork.

**Comment by magicbug** [comment]
Pull would be fantastic @wvolz sadly development halted my end due to health issues and moving.

**Comment by wvolz** [comment]
Pull request #206 created.

**Comment by magicbug** [comment]
Thanks @wvolz soon as I get time to test i'll merge

**Comment by magicbug** [comment]
Thanks @wvolz Cloudlog is now PHP7 ready.
