### ISSUE TITLE
New proposed option for customizable logbook fields

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#1777]
As someone who regularly activates Parks On The Air sites, I'd love to be able to customize one of the 5 logbook columns to show Station Location.

One potential issue is that the name could be rather long... which would. Two possible solutions could be just using ellipses after a certain number of characters (with the user expected to keep names short, with distinguishable info at the front) or maybe a "short name" field in the Station Location setup?

**Comment by phl0** [comment]
This could be possible as soon as ADIF supports separate fields for POTA. This has been proposed and will be added with 3.1.4. But thats not been released yet. I have a Cloudlog patch ready for the day it comes. 😇

https://github.com/phl0/Cloudlog/tree/POTA

**Comment by magicbug** [comment]
@phl0 did POTA field get added to the field selection cant honestly remember since we committed the code

**Comment by phl0** [comment]
> @phl0 did POTA field get added to the field selection cant honestly remember since we committed the code

I think I misunderstood the request here. The op wants to show his own POTA location as user definable column I guess. I didn't add that.

**Comment by phl0** [comment]
@ofadam Should this show your POTA location or the one of the DX station?
