### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by teabreakninja** [magicbug/Cloudlog#178]
Your requirements say "PHP5 & MySQL", but they need to say "PHP5.4 or higher, and MySQL".

I tried to run it on an old install with PHP5.3 (yes, I know, v5.3!) and your array declaration syntax is is v5.4 or higher (application/controllers/qso.php line 50).

**Comment by magicbug** [comment]
Thanks for reporting this will update to 5.4 just to make it clear :)

**Comment by magicbug** [comment]
@teabreakninja based on your pull request can I mark this as fixed and close the issue?

**Comment by teabreakninja** [comment]
@magicbug yup, fine by me!
