### ISSUE TITLE
Ancillary suffixes are ignored

### ISSUE THREAD

**Issue by kconkas** [magicbug/Cloudlog#1798]
**Describe the bug**
Ancillary suffixes, for station operating outside its home country using a suffix to identify such operation, are ignored and the country is logged incorrectly as the home country. Example: `VE1CWJ/VP9` is logged as "Canada" instead of "Bermuda".

**To Reproduce**
Steps to reproduce the behaviour:
1. In "QSO" menu click "Post QSO"
2. In "Callsign" textbox enter affected call sign (for example "VE1CWJ/VP9")

**Expected behaviour**
Country is derived from ancillary suffix.

**Screenshots**
<img width="424" alt="Screenshot 2022-11-19 at 23 24 35" src="https://user-images.githubusercontent.com/8178837/202875889-c9b788a6-728d-457b-992f-e2c2052d2e4d.png">

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.6
 - Browser: Firefox 104.0.1

**Comment by magicbug** [comment]
Aware fix in progress, temp solution is just select the correct dxcc for now

**Comment by dg9vh** [comment]
Should that not be logged as VP9/VE1CWJ?

73 de Kim
DG9VH

Kristijan Conkas ***@***.***> schrieb am So., 20. Nov. 2022,
00:44:

**Comment by magicbug** [comment]
North America put it on the end rather than front.

**Comment by dg9vh** [comment]
Ah, ok.

Peter Goodhall ***@***.***> schrieb am So., 20. Nov. 2022,
11:48:

**Comment by kconkas** [comment]
> Should that not be logged as VP9/VE1CWJ? 73 de Kim DG9VH Kristijan Conkas ***@***.***> schrieb am So., 20. Nov. 2022, 00:44:
Both forms are valid. Also, I can only log the call sign as it is given on air or else I may have problems when trying to confirm the QSO.

**Comment by AndreasK79** [comment]
This has been fixed in the dev branch.
