### ISSUE TITLE
API not updating frequency and mode

### ISSUE THREAD

**Issue by TriBallscom** [magicbug/Cloudlog#1800]
After upgrading to Cloudlog 2.1 (comming from 1.x) the API call does not update the frequency and mode.
The name of the radio is registered so the api call does work

Tested with:

curl --silent --insecure \
         --header "Content-Type: application/json" \
         --request POST \
         --data "{
           \"key\":\"xxxxxxxxxxxxx\",
           \"radio\":\"TestRadio\",
           \"frequency\":\"1838999\",
           \"mode\":\"ssb\",
           \"timestamp\":\"$(date -u +"%Y/%m/%d %H:%M")\"
         }" https://<url to cloudlog>/index.php/api/radio

It updates correct on the "hardware interfaces" page but not in the QSO > Live QSO page

**Comment by phl0** [comment]
Tested ok here with some escapes:

```
curl --insecure --header "Content-Type: application/json" --request POST --data "{ \"key\":\"xxxxxxxxxxx\", \"radio\":\"TestRadio\", \"frequency\":\"1838999\", \"mode\":\"ssb\", \"timestamp\":\"$(date -u +"%Y/%m/%d %H:%M")\" }" https://host.name/cloudlog/index.php/api/radio
```

![Screenshot from 2022-11-21 10-08-42](https://user-images.githubusercontent.com/7112907/203010238-0fb0595d-b8fa-404c-92c5-7bdd5a6f466b.png)

![Screenshot from 2022-11-21 10-08-47](https://user-images.githubusercontent.com/7112907/203010249-8847edca-8731-4588-b41e-f2bc842b9744.png)

**Comment by TriBallscom** [comment]
> Any hints in the API response on the console if you omit "--silent"?

No just a 
{"status":"success"}

**Comment by TriBallscom** [comment]
> Tested ok here with some escapes:

tested the same but same result.
![image](https://user-images.githubusercontent.com/44622203/203011869-f81dfbdb-b851-4df3-8f15-afe3e4912a0a.png)
![image](https://user-images.githubusercontent.com/44622203/203011946-dc448685-093a-41c1-ae33-9945ef45ca5f.png)

**Comment by phl0** [comment]
> ![image](https://user-images.githubusercontent.com/44622203/203011946-dc448685-093a-41c1-ae33-9945ef45ca5f.png)

So frequency is set here. Cannot see an error?!

**Comment by phl0** [comment]
> ![image](https://user-images.githubusercontent.com/44622203/203011946-dc448685-093a-41c1-ae33-9945ef45ca5f.png)

Frequency is set. Cannot see an error here?!

**Comment by TriBallscom** [comment]
> Frequency is set. Cannot see an error here?!

It's not the frequency I parsed to the api

**Comment by phl0** [comment]
> It's not the frequency I parsed to the api

Oh right. I overlooked the decimals... Will have a look.

**Comment by phl0** [comment]
It sets the freqency here correctly up to the single Hz. 

![Screenshot from 2022-11-21 11-43-34](https://user-images.githubusercontent.com/7112907/203030747-55965667-876e-40d9-8065-61bacbd4af10.png)

The JSON response also contains the exact frequency as above.

So only possible thing I can think of currently is the browser. Which one are you using?

**Comment by TriBallscom** [comment]
> So only possible thing I can think of currently is the browser. Which one are you using?

I checked with Chrome and Edge on Windows 11.
It's weird that the variable is set in the "hardware interfaces" but not in the Live QSO screen.

**Comment by TriBallscom** [comment]
![image](https://user-images.githubusercontent.com/44622203/203061115-6df90204-721c-4737-bfee-5c2c26e11d82.png)

**Comment by magicbug** [comment]
I think this is a simple case of Cloudlogs expecting the freq in Hz via the API

**Comment by phl0** [comment]
> ![image](https://user-images.githubusercontent.com/44622203/203061115-6df90204-721c-4737-bfee-5c2c26e11d82.png)

Can you check the API JSON response for the value the API gives back?

**Comment by TriBallscom** [comment]
> Can you check the API JSON response for the value the API gives back?

The API works, in the "hardware interfaces" it gives the correct frequency just not on the Live QSO page

**Comment by WaarlandIT** [comment]
@phl0 What browser are you using? 
I try to replicate the screenshots you made but my views are different and to make sure we look at the same thing I like to use the same browser you are using.

**Comment by phl0** [comment]
I am using Firefox on Linux (Ubuntu) as default.

**Comment by WaarlandIT** [comment]
Interesting.. You get a json response and I don't .. 
I send a SSB Mode to the API and in the hardware interfaces page that is shown but in the Live QSO page I only get an AM and SAT mode but no SSB. The AM mode shows the frequency shown on the page as default 

![image](https://user-images.githubusercontent.com/53364386/204131989-5e6e58c3-0314-4f76-a684-fc3130dcfb2d.png)

**Comment by TriBallscom** [comment]
I just realized I commented with the wrong account ;) WaarlandIT, is another account of mine..

**Comment by phl0** [comment]
> I send a SSB Mode to the API and in the hardware interfaces page that is shown but in the Live QSO page I only get an AM and SAT mode but no SSB. The AM mode shows the frequency shown on the page as default

Can you show the curl request? I will try to reproduce here.

**Comment by TriBallscom** [comment]
Sure.. just removed the hostname.domain and the api key.. 

curl --insecure --header "Content-Type: application/json" --request POST --data  "{\"key\":\"XXXXXXXXXXXX\", \
\"radio\":\"QO-100 Station\",
\"frequency\":\"24001700\",
\"mode\": \"SSB\",
\"timestamp\":\"2022/11/26 10:47\"}" https://XXXXXXXXXXXXXXXXXX/index.php/api/radio

**Comment by TriBallscom** [comment]
extra info I use Ubuntu 20.04 with PHP7.4

**Comment by TriBallscom** [comment]
Ok some new development in my research. 
I installed Cloudlog on a Ubuntu 18.04 with PHP 7.2 and now it works. 
Not sure what the difference is but it is interesting

**Comment by TriBallscom** [comment]
If I look at the hardware interfaces page I see that the notation of the frequency is also different when running on Ubuntu 18.04 with php7.2
![image](https://user-images.githubusercontent.com/44622203/204134877-80fb09ba-14f5-4d97-8738-e33aac8e1839.png)

**Comment by phl0** [comment]
> If I look at the hardware interfaces page I see that the notation of the frequency is also different when running on Ubuntu 18.04 with php7.2 ![image](https://user-images.githubusercontent.com/44622203/204134877-80fb09ba-14f5-4d97-8738-e33aac8e1839.png)

Seems you missed to pass the frequency in Hz on the API request?

**Comment by TriBallscom** [comment]
> Seems you missed to pass the frequency in Hz on the API request?

No same request from my workstation just updated the timestamp

**Comment by phl0** [comment]
> No same request from my workstation just updated the timestamp

Roger. I will try to debug ...

**Comment by TriBallscom** [comment]
Just to be sure.. What are the specs of your server? Is that Ubuntu 18.04?

**Comment by phl0** [comment]
> Just to be sure.. What are the specs of your server? Is that Ubuntu 18.04?

Sri delay. Its Ubuntu 20.04. Apache 2.4.41. PHP 7.4.3.

**Comment by TriBallscom** [comment]
That was my setup when it failed.. weird.
