### ISSUE TITLE
Date format on previous contacts not the same as anywhere else in the system

### ISSUE THREAD

**Issue by PD0RZH** [magicbug/Cloudlog#1816]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
Date format on previous contacts not the same as anywhere else in the system

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to QSO > Live QSO
2. Click on fill in a callsign which you've worked before
3. See dicsrepancy between date on live QSO page and date format on previous contact
Note: In cloudlog.php the dateformat is set as d/m/y

**Expected behaviour**
Same dateformat throughout the system

**Screenshots**
![prev cont](https://user-images.githubusercontent.com/60810525/204802945-f9c065c3-8db6-494d-962f-fcfcf98b7127.png)

![date format](https://user-images.githubusercontent.com/60810525/204802895-ea2f462a-9a05-4f96-9645-d0af85c59506.png)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Edge
 - Version 107.0.1418.62

**Comment by PD0RZH** [comment]
Same goes for EQSL upload and download
![eqsl upload](https://user-images.githubusercontent.com/60810525/204807970-193c73f3-36f4-4539-90bb-03cc40d9502d.png)

**Comment by phl0** [comment]
> Same goes for EQSL upload and download ![eqsl upload](https://user-images.githubusercontent.com/60810525/204807970-193c73f3-36f4-4539-90bb-03cc40d9502d.png)

This can be fixed with https://github.com/magicbug/Cloudlog/pull/1817.
