### ISSUE TITLE
Menu overlaped in screen

### ISSUE THREAD

**Issue by TriBallscom** [magicbug/Cloudlog#1818]
I was looking in 'Awards' > 'CQ' clicked on the (W)orked on 2m. The overlay shows the details but when I clicked on the Settings "wheel"
the settings menu came behind the details overlay.
![image](https://user-images.githubusercontent.com/44622203/204893822-09f42ef5-8264-447f-a8a5-e80ca2030f08.png)

**Comment by magicbug** [comment]
![image](https://user-images.githubusercontent.com/84308/204916462-51574625-5bcb-48fa-9f4d-1114d0dd120f.png)

I'm aware of this in the master branch, but it has been fixed in the dev branch and will be released this week.

**Comment by TriBallscom** [comment]
Great, thanks
