### ISSUE TITLE
Awards - DXCC

### ISSUE THREAD

**Issue by teabreakninja** [magicbug/Cloudlog#182]
I've started writing the DXCC status page and am trying to link the callsigns to countries. I notice that in the log entry screen you perform a lookup against clublog.org, but don't store any DXCC info - Just the country name. Should you perhaps also store the entity_code?

I also have a small script which matches all existing log entries against the dxcc table and returns the correct country, but the table doesn't have the dxcc entity_code. Is it worth adding this column to the table and using it as part of the Awards->DXCC page?

Thoughts, comments?

**Comment by magicbug** [comment]
Could the entity code be stored in the field COL_DXCC? Agreed I should really be storing it not sure why I wasn't (laziness likely) 

The DXCC table is built using Clublog's cty xml file http://clublog.freshdesk.com/support/solutions/articles/54902-downloading-the-prefixes-and-exceptions-as-xml I'm a feeling it didnt include the code hence why I never added it (iffy memory on this one)
