### ISSUE TITLE
Calendar date picker unavailable on "Mark QSOs" page for QRZ logbook

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#1821]
**Describe the bug**
I'm unable to use the calendar date picker option to mark QSOs as exported to QRZ logbook.

**To Reproduce**
1. Go to /qrz/export
2. Click on "Mark QSOs" tab
3. Try to click on calendar icon

**Expected behaviour**
Calendar should appear when clicking on calendar icon.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser: Firefox
 - Version: 106

**Comment by AndreasK79** [comment]
@ofadam thanks for reporting. I've fixed this in the dev branch now. It was probably forgotten when it was moved to it's own place a while back.
