### ISSUE TITLE
QSL Upload - filetype not allowed (JPG/jpg)

### ISSUE THREAD

**Issue by dg9vh** [magicbug/Cloudlog#1822]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
dev-branch: upload JPG or jpg-file as qsl-card to contact ends in "filetype not allowed"

**Expected behaviour**
JPG or jpg-files should be accepted.

**Screenshots**
![image](https://user-images.githubusercontent.com/13950650/205460448-b13f6300-06e6-4ee7-b80a-8d758df02b9c.png)

**Desktop (please complete the following information):**
 - Linux (Debian)
 - Chrome Version 108.0.5359.71 (Offizieller Build) (64-Bit)

**Comment by phl0** [comment]
Strange. Works flawlessly here ....

![Screenshot from 2022-12-03 21-31-01](https://user-images.githubusercontent.com/7112907/205460912-ccd38320-98f2-4eca-b1c7-658ea2c146eb.png)

**Comment by dg9vh** [comment]
hm...
kimhu@DG9VH-LinuxNB:~/Downloads$ file SP6TP.JPG 
SP6TP.JPG: PNG image data, 800 x 523, 8-bit/color RGBA, non-interlaced

**Comment by dg9vh** [comment]
OK, there is the problem... it is a PNG in costume of a JPG :-)

**Comment by phl0** [comment]
Aaaaahhhh QSL by PA4R QSL tools?

**Comment by dg9vh** [comment]
Fixed after rename...
nope... Log4eQSL by https://qrztr.com/ as I can see in the generated email.

**Comment by dg9vh** [comment]
Do we still need the issue or should I close it? Problem is not originated by cloudlog, so I think, I would close it :-)
