### ISSUE TITLE
Backup logbook.adi header incorrect

### ISSUE THREAD

**Issue by pa8s** [magicbug/Cloudlog#1837]
**Describe the bug**
Backup logbook.adi header has an incorrect PROGRAMVERSION tag.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on 'Admin'
2. Scroll down to 'Backup'
3. Click on 'Backup ADIF data'
4. Click on generated link.
5. Open in text editor.
6. See error at line 4:` <PROGRAMVERSION:3>Version 1.7`

**Expected behaviour**
`<PROGRAMVERSION:11>Version 1.7`

**Comment by AndreasK79** [comment]
Fixed in latest dev.

**Comment by pa8s** [comment]
Quick fix. Thank you. :)
