### ISSUE TITLE
[PHP 8.1] "Passing null to parameter #1 ($datetime) of type string is deprecated" errors while searching in logbook

### ISSUE THREAD

**Issue by pa8s** [magicbug/Cloudlog#1848]
**Describe the bug**
When I search for log entries I often get this PHP error where the 'Uploaded to LoTW' arrow is seen:
```
A PHP Error was encountered

Severity: 8192

Message: strtotime(): Passing null to parameter #1 ($datetime) of type string is deprecated

Filename: partial/log_ajax.php

Line Number: 200
data-original-title="LoTW Sent " data-toggle="tooltip" class="lotw-green">
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Search for (part of) callsign.
2. Scroll down until error is seen.
3. White "Uploaded to LoTW" arrow is seen with PHP error above.

**Expected behaviour**
No error and green up arrow. 
Looking into QSO data, the COL_LOTW_QSLRDATE has a valid date and COL_LOTW_QSL_RCVD is 'Y'.

**Screenshots**
![errorOrBug](https://user-images.githubusercontent.com/77061865/208654798-2d391322-071c-44a8-be8e-53b061d2a5ea.png)

**Server**
OS: FreeBSD 13.1
Server: nginx/1.22.1
PHP: 8.1.13
Git branch: dev
Git commit: 04e99607
Git Tag: 2.1-94-g04e99607

**Comment by phl0** [comment]
Can you please show the QSO details for that specific QSO? I am looking for values of COL_LOTW_QSL_SENT and COL_LOTW_QSLSDATE. 
The COL_LOTW_QSLRDATE and COL_LOTW_QSL_RCVD obviously work fine as the green arrow shows.

**Comment by pa8s** [comment]
COL_LOTW_QSL_SENT = 'Y'
COL_LOTW_QSLSDATE = NULL

**Comment by phl0** [comment]
> My mistake, the fields mentioned in the report are not that relevant, the fields below are obviously for the up arrow.
> 
> COL_LOTW_QSL_SENT = 'Y' COL_LOTW_QSLSDATE = NULL

Yes they are. But why is the COL_LOTW_QSLSDATE NULL?!

**Comment by phl0** [comment]
I mean I could fix the code to not run into an error here. But it seems that your LotW uploads do not set the upload date here. Maybe an issue of PHP 8.1.

**Comment by pa8s** [comment]
> Yes they are. But why is the COL_LOTW_QSLSDATE NULL?!

I don't know, I see the mentioned error on multiple QSOs. Maybe those QSOs where uploaded to LoTW with another tool, I can't recall exactly.

**Comment by phl0** [comment]
Ok, let me check how to circumvent this error.

**Comment by phl0** [comment]
Fix PRred with https://github.com/magicbug/Cloudlog/pull/1849.

**Comment by pa8s** [comment]
Thank you this quick fix. :D

**Comment by phl0** [comment]
> Thank you this quick fix. :D

uw.

**Comment by pa8s** [comment]
Same error is visible in the QSO list when clicking on the 'Check log Call' or 'Check log Date/Time' button on the OQRS Requests list. 

Filename: oqrs/qsolist.php Line Number: 143

**Comment by AndreasK79** [comment]
@pa8s You're finding all the PHP8.1 issues :) Will look into them.

**Comment by pa8s** [comment]
> @pa8s You're finding all the PHP8.1 issues :) Will look into them.

I can't imagine I'm the only Cloudlog user with PHP8.1 ;)

**Comment by dg9vh** [comment]
Indeed you are not. I am running PHP Version 8.1.11
and have non of your problems here...

curious.

73 de Kim
DG9VH

**Comment by phl0** [comment]
Possible reason: @pa8s is running ENVIRONMENT set to development and @dg9vh production. The latter hides PHP warnings.

**Comment by phl0** [comment]
@pa8s Could you please test the code in https://github.com/magicbug/Cloudlog/pull/1893?

**Comment by phl0** [comment]
> Although this issue is closed, I just saw the same thing when doing an advanced search. This time the problem is in search/search_result_ajax.php line number 322.

Fixed with https://github.com/magicbug/Cloudlog/pull/1893/commits/41d6da8d4def75bee4acd1e1fb741f26bc9a9f48 in https://github.com/magicbug/Cloudlog/pull/1893

**Comment by pa8s** [comment]
> @pa8s Could you please test the code in #1893?

Just tested the code in pr 1893. Problem fixed.

**Comment by phl0** [comment]
> Just tested the code in pr 1893. Problem fixed.

Tnx report.

**Comment by pa8s** [comment]
> Possible reason: @pa8s is running ENVIRONMENT set to development and @dg9vh production. The latter hides PHP warnings.

Yes, I'm running in development mode.

**Comment by AndreasK79** [comment]
Fixed in dev.
