### ISSUE TITLE
OQRS Multi-Logbook Enhancement

### ISSUE THREAD

**Issue by myzinsky** [magicbug/Cloudlog#1856]
The new OQRS-Feature is awesome, however it is not perfect yet with respect to multiple logs. For example for each COTA/SOTA Activation I create a new logbook in cloud log. However, the requester cannot really distinguish this:

![image](https://user-images.githubusercontent.com/1970554/209156101-13ce0ce9-a700-4bf8-b8b6-3f88d0f917e9.png)

It would be nice to merge all logs for OQRS, or at least show the logbook name also in the dropdown.

**Comment by magicbug** [comment]
Yep just mentioned that in https://github.com/magicbug/Cloudlog/discussions/1855 i think the best solution is to group the callsigns not sure if that would cause a bigger problem down the line. @AndreasK79 better placed for that :)

**Comment by AndreasK79** [comment]
It's not built for grouping. Can't remember exactly, but think it needs several changes. 

But I am against grouping. They are not the same, so I would rather include more info in the dropdown.

**Comment by AndreasK79** [comment]
By grouping, the other station wouldn't really know which activation they request the QSL for. On the other hand, as long as it's the same call, it wouldn't matter. 

What if one of the activations were to have another QSL manager?

I guess there are plenty of reasons both way. Perhaps it doesn't matter, as it will not be anything like M0URX/M0OXO/Clublog regarding OQRS and expeditions.

**Comment by AndreasK79** [comment]
So far 2 issues:

1. SAT is not displayed correctly
2. Add more info about callsign to the dropdown.

Grouping is not an easy fix, as it was built around each station location.

**Comment by magicbug** [comment]
Perhaps show grid or the location name

**Comment by AndreasK79** [comment]
Yep. That is a possibility. Perhaps add iota/sota/pota if those exists.

**Comment by myzinsky** [comment]
I think the Logbook's name would be the most reasonable....

**Comment by AndreasK79** [comment]
I fixed callsign dropdown, and hopefully all SAT issues in the dev branch.

**Comment by AndreasK79** [comment]
Still a little issue with QSO matching on SAT. Will look into it.

**Comment by phl0** [comment]
Cool. I will go ahead and test asap.

**Comment by AndreasK79** [comment]
SAT QSO OQRS identifying is fixed.

**Comment by dg9vh** [comment]
> I fixed callsign dropdown, and hopefully all SAT issues in the dev branch.

![image](https://user-images.githubusercontent.com/13950650/209227228-ca42274d-65ae-472f-b39c-11709d0f8837.png)
looks good here :-)

**Comment by magicbug** [comment]
Much better thanks!
