### ISSUE TITLE
OQRS - requests not shown

### ISSUE THREAD

**Issue by dg9vh** [magicbug/Cloudlog#1857]
**Describe the bug**
After requesting a QSO for QSL, the Request is not shown in the requests-view.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to /oqrs as not logged in user
2. Request QSL for QSO
![image](https://user-images.githubusercontent.com/13950650/209194444-b7d47374-8e43-4d2e-b516-8fef1277d264.png)
3. Open requests-page
![image](https://user-images.githubusercontent.com/13950650/209194522-f129b629-b73e-4450-b144-a722db0e3469.png)
5. See error

The QSO is correctly marked in the database-table:
![image](https://user-images.githubusercontent.com/13950650/209194637-425a05ac-796f-4dbe-abbd-79e8a58272b3.png)

**Expected behaviour**
Find the QSO as requested in the requests-view.

**Comment by AndreasK79** [comment]
Since it's a match, you'll fknd it in qslprint.

**Comment by dg9vh** [comment]
But it would be printed as bureau-card, there is no thing saying it is direct:
![image](https://user-images.githubusercontent.com/13950650/209202439-71fd9e20-6a00-45a7-b2f4-c1fe42a31a68.png)

**Comment by AndreasK79** [comment]
You are right. Another issue to look into. I bet there are more, but the only way to get feedback here, was to release it.

**Comment by AndreasK79** [comment]
Bureau or direct is never set on the QSO, only on the OQRS I see. Thanks for reporting. Will hopefully fix it tomorrow. Just pushed several SAT fixes to dev.

**Comment by dg9vh** [comment]
> You are right. Another issue to look into. I bet there are more, but the only way to get feedback here, was to release it.

Yes, but it was very short in /dev so I had no chance to report this earlier :-)
I am running dev-branch in production and would find this issues there vy soon :-)

**Comment by AndreasK79** [comment]
Yes, the release was a bit quick, but we'll fix the stuff :) Just keep testing and reporting. More to find!

**Comment by magicbug** [comment]
> , but the only way to get feedback here, was to release it.

Exactly why I did it

**Comment by AndreasK79** [comment]
@dg9vh pushed fix to DEV now. Turns out the QSO class which logbookadvanced uses, is case sensitive.

Besides, I think Print Requested QSLs should be updated to show col_qsl_sent_via as well.

**Comment by dg9vh** [comment]
Ok, will test it tomorrow, if time available.

**Comment by dg9vh** [comment]
Requested new QSL as direct, but it is now shown as requested direct in QSO-View:
![image](https://user-images.githubusercontent.com/13950650/209437332-b4f9f997-db80-4c74-b2d7-6661569d072e.png)

Working :-)




> Besides, I think Print Requested QSLs should be updated to show col_qsl_sent_via as well.

Would you fix this within this issue or should I file another one?

**Comment by AndreasK79** [comment]
No need for another issue. Just need some time:)

**Comment by AndreasK79** [comment]
Updated dev now so that QSLPrint shows sent method.
