### ISSUE TITLE
OQRS: Only one QSO found even if there ere more QSOs in log

### ISSUE THREAD

**Issue by m0urs** [magicbug/Cloudlog#1876]
If you search for a call sign in the OQRS page for which there are more than one QSO in the log, only one QSO per band is found:

![image](https://user-images.githubusercontent.com/2588362/209797890-ba9d57a4-a69d-4b5c-9e18-42d899e5d9c5.png)

![image](https://user-images.githubusercontent.com/2588362/209798008-112d9be5-851f-43b4-9600-1cd9786fe9b3.png)

I would have expected that all QSOs on all bands are found.

**Comment by AndreasK79** [comment]
No, it should not. Only the distinct should show here.
What if you click on Request QSL?

**Comment by AndreasK79** [comment]
But I see that the text is wrong. Should list band 2, and 6 QSOs in log.

**Comment by m0urs** [comment]
I get one line per band. so I cannot request a QSL for more than one QSO on the same band?

**Comment by AndreasK79** [comment]
I see. Need to check out the code then. Table should show distinct, but the QSO list should list them all. Thanks for the report.

**Comment by AndreasK79** [comment]
I found the issue. It is fixed in #1883.

**Comment by m0urs** [comment]
Can confirm that this solves the issue.
