### ISSUE TITLE
wants to keep running the install

### ISSUE THREAD

**Issue by anwoke8204** [magicbug/Cloudlog#1904]
Hi, I uploaded this to my webhost, ran through the install, but it keeps wanting to run the install, even though I did the install and it said the install succeeded and then told me to delete the install folder.  how can I get past this?

**Comment by AndreasK79** [comment]
Hi. If the config.php file is not found, it will redirect you to run install again.
It's impossible to say what might be wrong without knowing more about your setup.
Config.php should exist in application/config/ after install is done. If not, some permissions might not be set correctly.

**Comment by magicbug** [comment]
I'm guessing permissions issue on application/config folder so the installer isn't creating the config files thus install loop
