### ISSUE TITLE
Station Lookup not working

### ISSUE THREAD

**Issue by do4bmw** [magicbug/Cloudlog#1907]
Hy

i have a problem that my QRZ.com Lookup does not work.

If i enter a callsign in the LiveQSO Window , in the past it makes a fetch of the name , locator , etc

but since update to 2.x it does not work.

Auto look up and image fetch option are enabled

the QSO upload to QRZ.com works fine. and i have a QRZ.com subscription

maybe the 2FA on QRZ.com is a problem ? or something else ?

![Screenshot_60](https://user-images.githubusercontent.com/76187206/211299447-30fa6b54-ee2b-4f9e-9279-a6cf78176a06.jpg)
![Screenshot_61](https://user-images.githubusercontent.com/76187206/211299827-378d9990-5ac5-4c2a-aecd-4d4ec44d0a96.jpg)
![Screenshot_59](https://user-images.githubusercontent.com/76187206/211299452-a0df1ddb-5dad-4aa9-b170-f8a9ec93fc0c.jpg)

**Comment by do4bmw** [comment]
![Screenshot_61](https://user-images.githubusercontent.com/76187206/211299827-378d9990-5ac5-4c2a-aecd-4d4ec44d0a96.jpg)

**Comment by do4bmw** [comment]
here as example with the clubstation callsign DL0GH

there are no infos , or picture ... but if you look at [qrz.com/db/dl0gh](url) there is

**Comment by phl0** [comment]
No issues known in 2.0. Anything useful in the log or browser console?

**Comment by do4bmw** [comment]
what logfile ? apache ?

here a screenshot from the browser console
![Screenshot_62](https://user-images.githubusercontent.com/76187206/211303532-f22c82d1-7276-4408-9d6e-e4fe19f5c6fe.jpg)

**Comment by magicbug** [comment]
I'd make sure that /application/config/config.php is correctly setup for QRZ.

**Comment by do4bmw** [comment]
> I'd make sure that /application/config/config.php is correctly setup for QRZ.
> 
> You could also check application/logs to see if anything is getting reported
> 
> But certainly not aware of any bugs in this code.

that was the problem ! many thanks , problem solved !

i had 

$config['callbook'] = "hamqth"; // Options are hamqth or qrz

and now changed to 

$config['callbook'] = "qrz"; // Options are hamqth or qrz


because i dont use hamqth ... my failure

many thanks for help !
