### ISSUE TITLE
Feature request: Pull county data for LoTW confirmations

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#1910]
When syncing with Logbook of the World, certain fields are automatically added to the Cloudlog database, like state and gridsquare. But would be great to add "CNTY" as an updated field for those of us in the United States so that the Awards/US Counties page can become more accurate.

Reference docs for LoTW: https://lotw.arrl.org/lotw-help/developer-query-qsos-qsls/

**Comment by phl0** [comment]
Made a patch with https://github.com/magicbug/Cloudlog/pull/1913. Would you be able to test this and report?
