### ISSUE TITLE
QSO Widget Provide Broken Log Links

### ISSUE THREAD

**Issue by StrangeWill** [magicbug/Cloudlog#1915]
**Describe the bug**
The permissions required to access the Logbook links on the widget QSO are not met by public users, making the links broken, they will take you to a completely blank page (no body) with a 200 response code.

**Expected behavior**
Either the QSOs shouldn't link to the logbook, or we should have public logbook access.

**Comment by magicbug** [comment]
They shouldn't be linked needs fixing
