### ISSUE TITLE
No Station Location after Upgrade

### ISSUE THREAD

**Issue by DL3EL** [magicbug/Cloudlog#1920]
We did an upgrade today to the latest version (comming from a version from mid this year). After that, all station locations were gone. Fortunatley, we had a backup and could reload the old version. Everything is good now.

Any idea where we can look, to solve the problem?

Cloudlog runs on a PI with bullseye and we have the latest PHP 7.4.33

DL3EL & DL5ZR

**Comment by magicbug** [comment]
Hi,

I suspect the issue is the upgrade script assigning all Locations to the first user, only real method is to manually assign the location via the table in the database this is the `station_profile` table and you want to edit the user_id column 

Peter
