### ISSUE TITLE
Feature-Request: (Pre-)populate Callsign via API

### ISSUE THREAD

**Issue by int2001** [magicbug/Cloudlog#1922]
i wrote a small Tool to sync the TRX-VFO with a choosen Spot on the Cluster (f.ex. dxheat).
Would be very nice, if one can call the Cloudlog-API to populate the Callsign-field in the QSO-Field with that.

Actually you can prepopulate QRG/Mode via the Radio-API or
log a qso via the qso-API.

I'm looking for one step before logging the QSO. Due to the fact, that the live-QSO-Page already refreshes itself (for QRG/Mode given by radio-API), it's perhaps possible to implement sth. like a "pre-qso-API".

vy 73, Jörg, DJ7NT

**Comment by magicbug** [comment]
Currently, no plan to add this, QSOs can be sent via the API but the Radio API is just for interfacing with hardware.
