### ISSUE TITLE
Feature Request: Use "Sent Method" for "Mark requested QSLs as sent"

### ISSUE THREAD

**Issue by m0urs** [magicbug/Cloudlog#1923]
If you mark a QSO for "QSL requested", you can also set the method, e.g. "Electronic":

![image](https://user-images.githubusercontent.com/2588362/212141486-6a20b8f8-0e23-4ce2-bd4a-1788fe076c85.png)

If you later, in the "Print requested QSLs" view, press the button "Mark requested QSLs as sent", the QSO will always be marked as "QSL sent via bureau":

![image](https://user-images.githubusercontent.com/2588362/212141808-ecd9cd25-6eb2-4384-86ff-5c0f7d0760bc.png)

It would be very helpful, if the "Sent method" is not changed to bureau, but would be left with its original value.

If there is no sent method choosen before, then "Bureau" as default would be ok.

What do you think?

**Comment by AndreasK79** [comment]
@m0urs I agree. Done and pushed to dev.

**Comment by m0urs** [comment]
Thanks very much. This does work for me and is very helpful!
