### ISSUE TITLE
[PHP 8.1] 'strftime() is deprecated' while re-checking DXCC info in logbook

### ISSUE THREAD

**Issue by pa8s** [magicbug/Cloudlog#1926]
**Describe the bug**
While re-checking DXCC info in logbook, all logbook entries needing update are throwing an error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Admin -> Update Country Files -> Re-check all QSOs in logbook.
2. See error in screenshot.

**Expected behaviour**
No error.

**Screenshots**
![strftimedep](https://user-images.githubusercontent.com/77061865/212565180-e3bc59f8-7a55-4549-af43-e2482e04c0aa.png)

**Logfile**
```
ERROR - 2023-01-15 20:24:34 --> Severity: 8192 --> Function strftime() is deprecated /mnt/www/application/models/Logbook_model.php 3130
```

**Server**
OS: FreeBSD 13.1
Server: nginx/1.22.1
PHP: 8.1.13
Codeigniter: 3.2.0-dev
Git branch: dev
Git commit: 178c5ec9
Git Tag: 2.1-224-g178c5ec9

**Comment by AndreasK79** [comment]
Pushed a fix to dev now.
