### ISSUE TITLE
Missing field "Mark QSL Card Requested" after select "Mark QSL Card Received (Bureau)"

### ISSUE THREAD

**Issue by HB9WDF** [magicbug/Cloudlog#1930]
In the Logbook overview, I press the dropdown menu and select "Mark QSL Card Received (Bureau)" 
After that, I press the dropdown again. Then the entry "Mark QSL Card Requested" is gone.
![Screenshot_20230115_231354](https://user-images.githubusercontent.com/53918535/212570446-5d0669fc-2321-4461-b880-545baa287588.png)
![Screenshot_20230115_231539](https://user-images.githubusercontent.com/53918535/212570448-7667f37e-d1bb-4624-b125-ed8726e56287.png)

**Comment by AndreasK79** [comment]
Thanks for reporting. Fixed this in the dev-branch.

**Comment by AndreasK79** [comment]
This is merged into master now.
