### ISSUE TITLE
DXCC identification fails for Anguilla and Montserrat

### ISSUE THREAD

**Issue by dk2ro** [magicbug/Cloudlog#1933]
How to reproduce:

- Update Country Files
- In QSO tab enter a callsign from Anguilla or Montserrat (VP2MDG, VP2EGR, VP2MOM, ...)
- After hitting TAB, no DXCC and no previous QSOs are returned

DXCC identification also fails with imported ADIF qsos.
![grafik](https://user-images.githubusercontent.com/460969/212749735-e7e11598-9b33-4999-83d3-90b1c6c26bf1.png)

Testing here running the latest master branch. 
![grafik](https://user-images.githubusercontent.com/460969/212750223-c806bc4b-b60e-46ec-add3-3b2c0d0a5ca9.png)

**Comment by AndreasK79** [comment]
That's strange. I'll take a look and see if I can figure out what is going on here.

**Comment by AndreasK79** [comment]
Some logic flaw in the latest code. Pushed a fix to the dev branch now.

**Comment by dk2ro** [comment]
That fixed it for me.
