### ISSUE TITLE
No logbooks were found

### ISSUE THREAD

**Issue by teabreakninja** [magicbug/Cloudlog#1944]
**Describe the bug**
A new logbook doesn't seem to be associated with the user.

**To Reproduce**
Fresh Install of Cloudlog from Git, populate DXCC, create Station info and location. Create new log. Import ADIF backup.
Logbook not associated with user. 

**Expected behaviour**
Backup logs imported into new logbook.

**Desktop (please complete the following information):**
Linux Server, Docker using https://hub.docker.com/r/mattrayner/lamp

**Additional context**
No entry in station_logbooks_relationship table, all imported log entries visible in TABLE_HRD_CONTACTS_V01.

**Comment by teabreakninja** [comment]
ok, seems it's missing an entry in station_logbooks_relationship

**Comment by magicbug** [comment]
Not a bug, read the error, to go Station Logbooks create one, then link it to any of the Station Locations.

**Comment by teabreakninja** [comment]
No Link option is/was availble

![image](https://user-images.githubusercontent.com/9462722/213919357-34d41169-94ef-4b50-ac01-555a60b75836.png)
