### ISSUE TITLE
[PHP 8.1] mb_substr(): Passing null to parameter #2 ($start) of type int is deprecated

### ISSUE THREAD

**Issue by pa8s** [magicbug/Cloudlog#1945]
**Describe the bug**
While importing an ADIF file, mb_substr() deprecated error shown.

**To Reproduce**
Steps to reproduce the behaviour:
1. <Your Call>  -> ADIF Import/Export -> ADIF Import -> <select local file> -> <select station location> -> Mark LoTW -> Upload 
2. See error in screenshot.

**Expected behaviour**
No error.

**Logfile**
```
ERROR - 2023-01-21 21:16:17 --> Severity: 8192 --> mb_substr(): Passing null to parameter #2 ($start) of type int is deprecated /mnt/www/application/libraries/Adif_parser.php 118
```

**Server**
OS: FreeBSD 13.1
Server: nginx/1.22.1
PHP: 8.1.13
Codeigniter: 3.2.0-dev
Git branch: dev
Git commit: b03870e1
Git Tag:  2.1-239-gb03870e1

**Comment by AndreasK79** [comment]
Can't reproduce that here. Any way you were willing to share the ADIF-file so I could test?

**Comment by pa8s** [comment]
Problematic ADIF record added to issue #1946

**Comment by AndreasK79** [comment]
Fix pushed to dev. Variable was never set if EOH didn't exist in the file. And as a result, null was passed to mb_substr.

**Comment by pa8s** [comment]
Checked with 'problematic' ADIF file. I had split a large ADIF file into smaller files hence some imports had no header present.

**Comment by AndreasK79** [comment]
And that uncovered a bug that needed fixing :)

**Comment by pa8s** [comment]
Apparently, the transition from PHP 7 to 8 is giving you guys a lot of work with all those deprecated functions. Exploratory testing is in my nature, so discovering those bugs is to be expected. :)

**Comment by AndreasK79** [comment]
Nothing is better than getting people to test. Most of the bugs are easy to fix. I swapped to PHP8.1 myself on my dev machine, so I've fixed a few that suddenly appeared.
