### ISSUE TITLE
Make gridsquare maps separatable for LEO/GEO/MEO

### ISSUE THREAD

**Issue by phl0** [magicbug/Cloudlog#1949]
I would like to make the gridsquare maps a little more detailed so that you could filter for LEO/GEO/MEO satellites as well as QSL type paper, LotW and eQSL maybe. 
Now the core question is to where to keep the info about sat type (LEO/GEO/MEO) best. There are various options:

1. Hard code that stuff based on satellite name (as we have in "Gridsquare Activators" for example)
2. Put the SAT characteristics into satellite.json
3. Put SATs into a separate table and enrich with SAT type (like we added for bands for example)

@magicbug I would like to know your opinion on this before I start implementing. Oh and @AndreasK79 as well of course :)
-

**Comment by AndreasK79** [comment]
Option 1 is a no go from me. I'm against hardcoding anything.

Option 2 would be the easiest, with minimal changes, but requires updating Cloudlog for each change (I'm not thinking about those users that are capable of doing this themselves).

Option 3 would be the most user friendly, as users themselves could edit information, but is the one that requires most changes. 

My vote is for option 3, unless there are good reasons for keeping option 2.
