### ISSUE TITLE
blank screen after upgrading cloudlog

### ISSUE THREAD

**Issue by on4dgt** [magicbug/Cloudlog#1950]
Upgrading my Cloudlog broke something. I got only a blank screen.
In development environment I noticed it came from line 2895 in logbook_model.php
I think  _$c = substr($c, 1,);_ should be _$c = substr($c, 1);_

**Comment by phl0** [comment]
Thanks for reporting. This has been addressed and fixed already in the dev branch with https://github.com/magicbug/Cloudlog/pull/1942. Just needs transfer to master branch / release.

**Comment by magicbug** [comment]
Released this morning into master branch
