### ISSUE TITLE
Feature request: Set ADIF import/export default to "active" location

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#1956]
For users with only one location set in Cloudlog, it would be handy to show that one by default on the ADIF import/export page instead of forcing them to use the pull-down menu to select it. A minor quibble, but one that would save a click with each import/export!

![image000000](https://user-images.githubusercontent.com/5504940/214943113-5a53692e-344d-4de7-a0f2-e8886330e445.jpg)

**Comment by magicbug** [comment]
I think default should be the "active" location of the user even if there's more than one.

**Comment by ofadam** [comment]
That makes a lot more sense – will adjust issue title to reflect.

**Comment by phl0** [comment]
Proposed a patch for this in https://github.com/magicbug/Cloudlog/pull/1958.

**Comment by magicbug** [comment]
@phl0 your on it faster than me these days! merged into dev branch will make it into master next week

**Comment by phl0** [comment]
Oh sorry for that. I saw the issue last night but as it wasn't solved this morning I thought I'd contribute some code :)
