### ISSUE TITLE
Feature request: Match style of advanced logbook with overview logbook

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#1957]
The new advanced logbook view is an incredibly powerful page for filtering QSOs, but the overall look borrows heavily from an average spreadsheet with a very large grid.

On the classic overview logbook view, the results have a bit more polish with striped rows and no vertical rules at all.

Obviously, this may come down to personal style preference – but there may be benefits toward standardizing style between the two?

**Comment by magicbug** [comment]
@ofadam Fear not, its on my radar as well, needs a bit more polish to fit in with the rest of the system

**Comment by ofadam** [comment]
No fear here! Thanks for all you do.

**Comment by magicbug** [comment]
It bugged me the other day, got to get the small things right :)

**Comment by AndreasK79** [comment]
The main reason not adding this in the first place, was that marking lines would not show correctly.
I've fixed striped table and marking now. I have pushed this to the dev branch.

@magicbug didn't bug you enough to fix? ;)
