### ISSUE TITLE
ADIF Export Frequency

### ISSUE THREAD

**Issue by core-dd** [magicbug/Cloudlog#196]
Hej hej,
according to ADIF 3.0.4 (http://www.adif.org/304/ADIF_304.htm) the FREQ field contains the frequency in MHz. Right now export seems to be in Hertz. We might need to change the export for compatibility reasons (e.g. TQSL).

73s de Jens, M0INN

**Comment by magicbug** [comment]
Correct Jens the ADIF export needs a tweak to be MHz.

**Comment by magicbug** [comment]
Tagged wrong code commit, but now doing hertz / 1000000 to generate correct MHz for ADIF.

**Comment by magicbug** [comment]
Closer inspection its for things like 14081011 aka 14.081011 LoTW doesn't like that so throws an error

**Comment by core-dd** [comment]
I'll have a look the next time I'm exporting for LOTW. Last time I've manually fixed the exported files via search and replace. ;)

**Comment by magicbug** [comment]
It might actually be semi working in the latest codebase, I really need to sit down and start thinking about Version 2 and finding a suitable system to support PHP7 and beyond :)

**Comment by core-dd** [comment]
Are you around for the upcoming Camb-Hams trip? We could do a small session on Cloudlog NG ideas. :)

**Comment by magicbug** [comment]
I will be 😀

Peter
