### ISSUE TITLE
LotW not able to sync or up/download

### ISSUE THREAD

**Issue by mreasy2023** [magicbug/Cloudlog#1960]
I am running cloudlog on an ubuntu 22.04.1 LTS server with php 8.1.

I uploaded the LotW certificate and it is valid. I double checked my user and password for lotw (I use it for cloudlog as well).

Cloudlog is not able to sync or up/download. I got this message:

_Upload Successful - ./uploads/lotw/df2ca-2023-01-27-19-49-12-cloudlog.tq8
LoTW Matches
LoTW Downloading failed either due to it being down or incorrect logins._

I stored my password in my cloudlog profile.

Any hints or sugestions for the issues?

Thanks for your help.
Patrick

**Comment by mreasy2023** [comment]
Now it works. I don't know why. I tried it for several days.

**Comment by Vic152** [comment]
Same here. Just setup new password and I get the same error.
