### ISSUE TITLE
Feature suggestion: OAuth/SAML integration for SSO

### ISSUE THREAD

**Issue by simonszu** [magicbug/Cloudlog#1970]
In my infrastructure i have a SSO provider running (Authentik) from which i login to my various selfhosted services. It would be great if Cloudlog supports logging in via OAuth or SAML mechanism as well, to have it integrated into the SSO setup.

**Comment by magicbug** [comment]
Cant see this being added anytime soon but noted.

**Comment by ChristianSwift** [comment]
Totally agree with that
