### ISSUE TITLE
R2 prefix with /P is seen as European Russia

### ISSUE THREAD

**Issue by pa8s** [magicbug/Cloudlog#1971]
**Describe the bug**
R2 prefix with /P is seen as European Russia (DXCC CQ Zone 16,17,21) while this should be Kaliningrad (CQ Zone 15)

**Server**
OS: FreeBSD 13.1
Server: nginx/1.22.1
PHP: 8.1.13
Codeigniter: 3.2.0-dev
Git branch: [dev](https://github.com/magicbug/Cloudlog/tree/dev)
Git commit: [5e5136fa](https://github.com/magicbug/Cloudlog/commit/5e5136fa4432911b5b6e1fd56d2add077454e89e)
Git Tag: [2.3.1-56-g5e5136fa4](https://github.com/magicbug/Cloudlog/releases/tag/2.3.1)

**Comment by AndreasK79** [comment]
Seems the algorithm needs more tweaking. I'll debug and see what happens. Thanks for reporting.

**Comment by AndreasK79** [comment]
This one is harder to fix without breaking identification of other DXCC's.

I wrote a call tester (being tired of testing my list manually), so that it's easier to identify cases that should be identified.

We will never get to 100%, but it can probably be improved upon.

**Comment by magicbug** [comment]
Even so, /P should be able to not affect the main dxcc lookup as we didn't have these issues before hand although it largely ignored anything after the /

**Comment by AndreasK79** [comment]
Ignoring everything after / is not the solution either.

**Comment by AndreasK79** [comment]
Added #1977. It fixes issue with Kaliningrad and other issues I found. 

It includes the calltester as well.

**Comment by AndreasK79** [comment]
Merged into dev. Closing.
