### ISSUE TITLE
Contest Exchange don't save in upper case

### ISSUE THREAD

**Issue by Stiles96** [magicbug/Cloudlog#1980]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
At contest logging the Exchange is every time in upper case, in the log it saves the lower case exchange and will be shown.

**To Reproduce**
Steps to reproduce the behaviour:
1. Make an Contestlog with Exchange and write it in lower case.

**Expected behaviour**
In the textbox you write automatically in upper case.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/51234422/216811140-af8f990c-3a4a-4518-80fb-7f37e821f1f4.png)

**Desktop (please complete the following information):**
 - OS: Win10 22H2
 - Browser Firefox
 - Version latest

**Comment by phl0** [comment]
Created a fix for this in https://github.com/magicbug/Cloudlog/pull/1982.
