### ISSUE TITLE
Not able to log non-existing WWFF reference

### ISSUE THREAD

**Issue by m0urs** [magicbug/Cloudlog#1984]
I had the problem that I needed to log a very new WWFF reference which had been existing on the WWFF website but seems not to be included in the CSV file (even I updated it manually).

Because of that, I was not able to enter this reference as the field will be wiped out if there is no match found.

I would like to be able to enter a reference, even if it is not found in the CSV file (for sure there is no no update of QTH and locator in this case, but at least I can log the reference number).

**Comment by phl0** [comment]
There is this in the DOK field:

![Screenshot from 2023-02-06 08-15-52](https://user-images.githubusercontent.com/7112907/216907814-aa1abb87-af91-4a6c-84e8-d1fc31190bc8.png)

So just need to find the difference here ...

**Comment by phl0** [comment]
Solution proposed in https://github.com/magicbug/Cloudlog/pull/1985.
Looks like this then:

![Screenshot from 2023-02-06 08-32-00](https://user-images.githubusercontent.com/7112907/216911792-bd33d91e-9d24-4c93-87d4-cae233c85dd3.png)

**Comment by m0urs** [comment]
Thanks a lot, this does work for me. I created a similar pull request also for POTA and SOTA references (https://github.com/magicbug/Cloudlog/pull/1987)
