### ISSUE TITLE
after installation i got the a few Api problems. the NoApiKey and the MissingKeyMapError 

### ISSUE THREAD

**Issue by jkoolschijn** [magicbug/Cloudlog#199]
Hi, 

after is installed the software on an linux based unit i am getting these two error's

util.js:211 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
js:32 Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error

i can log in and make logs so far so good. but at the dashboard i see the world popping up and then i get these errors ? is there an sollution to this?

**Comment by magicbug** [comment]
I'm aware of this Maps API code in the html layouts need updating to reflect change in Google Maps API since it was implemented.

**Comment by b4sh** [comment]
This is not a bug. I have gmaps on different domains. On some domains I need to add my API key. I think that soon the key will be required on all domains.

**Comment by magicbug** [comment]
Indeed, its not a bug, however code needs updating its just the best way to label it.

**Comment by lnitram** [comment]
Found the following places where the key needs to be added:
```
application/views/layout/header.php
application/views/layout/mini_header.php
application/views/view_log/qso.log
```

Would be nice to have a config-entry for this that is used everywhere
