### ISSUE TITLE
SSB doesn't include USB/LSB on new Continents analytics page

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#1998]
On the new Continents analytics page, selecting SSB as mode omits the submodes of LSB and USB.

This differs from how the Advanced Logbook filters, where a search of SSB also includes LSB and USB results.

**Comment by AndreasK79** [comment]
The query for mode is basically the same, so I find that a bit strange.

I logged two QSO's now (USB and LSB) on a band I don't have those continents. Both are included in continental stats.

**Comment by magicbug** [comment]
Yeah think theres something weird, I have SSB & LSB but no USB listed and the numbers vary between the two
