### ISSUE TITLE
Add QSO DXCC Summary Slow and data out of columns

### ISSUE THREAD

**Issue by magicbug** [magicbug/Cloudlog#2005]
This might just be affecting me but I'm finding that with the DXCC Summary on the Add QSO page, not only is it slowing down the population of the QSO fields that I'm also getting data outside of the table.

![dxcc](https://user-images.githubusercontent.com/84308/219417907-834f4618-2fc1-40bc-bee0-7da1e6319ea0.PNG)

**Comment by AndreasK79** [comment]
Not seeing that problem with the table here. 

I guess everything comes with a cost when doing business with the database, but perhaps we can change it a little bit so you need to click a button or something for it to load?

**Comment by magicbug** [comment]
Maybe if we can delay it to run last, not sure where in the chain, its happening need to check

I'm wondering if unknowns is due to me turning off some bands?

**Comment by AndreasK79** [comment]
The call is here: qso.js:411 getDxccResult(result.dxcc.adif, convert_case(result.dxcc.entity));

As for deactivated bands, it seems you nailed that one. I deactivated one band with QSOs and I got a similar result to the one you posted.

**Comment by AndreasK79** [comment]
Pushed fix for the table.

**Comment by magicbug** [comment]
Push fixed the table issue thanks! will look at the js call
