### ISSUE TITLE
Mode flips back to last used mode when CloudlogCat has been used but currently is stopped

### ISSUE THREAD

**Issue by PD0RZH** [magicbug/Cloudlog#2011]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
Mode flips back to last used mode when CloudlogCat has been used prior to this QSO but currently is stopped

**To Reproduce**
1. Start CloudlogCat and Cloudlog (verify that connection is made)
2. Click QSO > Live QSO
3. Log a QSO remembering the mode your radio and the add qso widget is currently set to
4. Stop CloudlogCat and stop Cloudlog
5. Start ONLY Cloudlog
6. Add a QSO > Live QSO using a different mode. On changing of the texboxes verify that the mode is flipping back to the mode u used in step 3

**Expected behaviour**
I CloudlogCat is NOT running I expect the mode to stay at what I manually have chosen

**Desktop (please complete the following information):**
 - OS: Windows !!
 - Browser Edge
 - Version Versie 110.0.1587.50 (Officiële build) (64-bits)

**Comment by magicbug** [comment]
If you unselect the radio and then save a QSO, cloudlog should remember this and it will then populate based on whatever is saved for the QSO going forward.
