### ISSUE TITLE
Analytics > Timeline > Award DXCC > Show > Show QSO's doesn't show pop up with QSO's

### ISSUE THREAD

**Issue by PD0RZH** [magicbug/Cloudlog#2012]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
Analytics > Timeline > Award DXCC > Show > Show QSO's doesn't show pop up with QSO's

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Analytics > Timeline > Award DXCC > Show > Show QSO's 
2. Verify that pop up doesn't show up

**Expected behaviour**
Like with the other choices a pop up showing QSO's should be there

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MAC Ventura 13.1
 - Browser Safari
 - Version 16.2

**Comment by AndreasK79** [comment]
It seems I broke something when I updated it for VUCC timeline. I'll take a look.

**Comment by AndreasK79** [comment]
Pushed fix to dev branch.
