### ISSUE TITLE
Countries breakdown shows clickable link to confirmed but does not lead to anything

### ISSUE THREAD

**Issue by PD0RZH** [magicbug/Cloudlog#2013]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
Countries breakdown shows clickable link to confirmed but does not lead to anything

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to cloudlog/index.php
2. Take a look half way on the right side
3. Click Confirmed (in blue)
4. Nothing happens

**Expected behaviour**
A link to a view where Confirmed QSO will be showed

**Screenshots**

<img width="380" alt="Confirmed" src="https://user-images.githubusercontent.com/60810525/220584279-370bbe3d-5df0-4726-8435-32b417bb5001.png">

**Desktop (please complete the following information):**
 - OS: Ventura
 - Browser Safari

**Smartphone (please complete the following information):**

**Additional context**

**Comment by magicbug** [comment]
Because its a roll over tooltip.

**Comment by PD0RZH** [comment]
Hi Peter,

Ah for me it’s confusing since the word gets underlined when hovering thus
suggesting a link ( well in my view anyway)

But thanks for explanation.

Keep up the good work.

( oh by the way in your 2.4 announcement you referred to Awards > Timeline
and Awards > Continents. Awards should have been Analytics. )

Greetings from the Netherlands

Rob PD0RZH

Op wo 22 feb. 2023 om 10:51 schreef Peter Goodhall ***@***.***

**Comment by soakland5** [comment]
Hi Rob, I know this is off topic, but I have been trying to get your ADIFPUSH to work. I installed DOT.net but don't know where to go from here. I also copied the .dll you created and put it in a directory but couldn't point to it. Can you give me an idea on how to do it? I am running Windows 11.
