### ISSUE TITLE
Use different map icons to indicate QSO mode or band

### ISSUE THREAD

**Issue by m1bxf** [magicbug/Cloudlog#202]
On the map, all icons used to represent QSOs are red drop pins, could this be enhanced to have different colours or types to signify different QSO data. 

For example different colours for mode; voice, data, SAT, & CW would likely suffice on modes.
And perhaps different types of icon, drop pin, circle or? indicating HF, VHF, UHF?

So a red drop pin could be voice on HF, a blue drop pin could be SAT on UHF (uplink) etc?

**Comment by magicbug** [comment]
This is actually possible now with the latest release switching to OSM and LeafetJS, although not personally high on my todo list.

**Comment by magicbug** [comment]
Closed this thread as we have two regarding map icons
