### ISSUE TITLE
Save last Exchange also in other modes

### ISSUE THREAD

**Issue by Stiles96** [magicbug/Cloudlog#2022]
**Describe the bug**
In the contest mode, the last entered exchange (last contest) will also be saved, if the contest don't contain an exchange.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Contest Log
2. Add Log with Exchange
3. Set Contest to other mode (in my case: Serial + Grid)
4. Log
5. See also the exchange in the log.

**Expected behaviour**
Exchange will not be saved, if not selected in the drobdown.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/51234422/222914163-c18afabb-c488-4a2f-b981-8fdd88735db6.png)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Firefox
 - Version 110

**Comment by AndreasK79** [comment]
Nice catch. This was something I never thought about when this was written. I need to add a check for exchangetype and set columns accordingly. Now it just checks if exchangetype exists and sets all columns.

**Comment by AndreasK79** [comment]
@Stiles96 I pushed a fix to the dev branch now. Should fix the issue with logging according to exchangetype.
