### ISSUE TITLE
Google maps not loading when I open de webpage 

### ISSUE THREAD

**Issue by datakrom** [magicbug/Cloudlog#204]
If I startup the homepage I don't get google maps loaded message received is:
Sorry! Something went wrong.
This page didn't load Google Maps correctly. See the JavaScript console for technical details.
In the java console I get error message 
MissingKeyMapError – An API key is not being used
I have made a new key following this link 
https://churchthemes.com/page-didnt-load-google-maps-correctly/#MissingKeyMapError
The question is how do I get the key loaded into the cloudlog software?
Brgds Rob

**Comment by R4D4R** [comment]
I'm having the same issue.  Searching through all of the PHP files, I don't see anywhere to put the API key for Google.

**Comment by magicbug** [comment]
Closing due to duplicate issue #199
