### ISSUE TITLE
504 gateway 

### ISSUE THREAD

**Issue by iplayradionetworks** [magicbug/Cloudlog#2047]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by magicbug** [comment]
As this is an issue with server config i'd suggest opening a discussion.

**Comment by iplayradionetworks** [comment]
Hi .

How is that a server issue ?

I have checked everything on my side but nothing wrong . 

I have even increased the timeout length in php . 

Can you suggest me where to check ?

Best 73s
Jimmy

**Comment by phl0** [comment]
I guess it is using a kind of proxy in front of the Cloudlog instance? Then the timeouts apply to the proxy ...

**Comment by iplayradionetworks** [comment]
No there is no proxy. 

Just plain apache . 

Should I be checking for apache timeout sessions In case to increase that parameter too ?

**Comment by phl0** [comment]
Strange that it does output a 504 gateway timeout then. This is normally happening if a reverse proxy cannot access the backend. Is apache used as reverse proxy?

**Comment by iplayradionetworks** [comment]
> Strange that it does output a 504 gateway timeout then. This is normally happening if a reverse proxy cannot access the backend. Is apache used as reverse proxy?

No . No reverse proxy with apache.

So I guess I must discover what it can be

**Comment by phl0** [comment]
Answered in https://github.com/magicbug/Cloudlog/discussions/2049#discussioncomment-5451607.

**Comment by iplayradionetworks** [comment]
Here is what I get after uploading.....
![20230404_122320.jpg](https://user-images.githubusercontent.com/40426604/229748276-14a91b0c-6064-41e6-a943-1e4a409f9ec8.jpg)
