### ISSUE TITLE
[Feature] Config Variable to Remove QSO Notification

### ISSUE THREAD

**Issue by jrwoodman** [magicbug/Cloudlog#2053]
Would love to have a variable in the config file to be able to disable the QSO notification at the top of the log screen.

**Comment by magicbug** [comment]
Which the saved or number of qsos today?

**Comment by jrwoodman** [comment]
Number of QSOs today. The 'banner' message at the top of the display.

**Comment by phl0** [comment]
I would rather skip implementing this. But here is a patch you could apply to remove the pop-up completely:

https://gist.github.com/phl0/93b47292227047c451c946549ccdad6c
