### ISSUE TITLE
[Feature Request] eQSL Card Auto-Import

### ISSUE THREAD

**Issue by techfixpros** [magicbug/Cloudlog#2059]
Please provide a function to automatically import and attach QSL cards downloaded from eQSL via DXKeeper.

DXKeeper from DXLabs can automatically download eQSL cards, and stores them in the format `<callsign>_<band>_<mode>_<yyyy>_<mm>_<dd>_<hh>_<mm>_<ss>.png`

The files can be dropped in a folder accessible from cloudLog and matched to the confirmed QSO, and automatically added for viewing.

![image](https://user-images.githubusercontent.com/7028086/230707661-fdfcaa5a-d964-4fbf-8530-21b3c6f4ce6a.png)

**Comment by magicbug** [comment]
Cloudlog already will download the eQSL card click the down arrow in the logbook next to eQSL and its saved locally so this would just need a script that would read the file name and assign it correctly into the database table.

**Comment by phl0** [comment]
> so this would just need a script that would read the file name and assign it correctly into the database table.

Something like this?

![Screenshot from 2023-05-09 22-04-01](https://github.com/magicbug/Cloudlog/assets/7112907/eb49eba4-5563-4721-8f11-eda7c5d14b41)

**Comment by techfixpros** [comment]
Yes, that and the backend to automatically download it and link the stored file to the qso for local storage.

**Comment by techfixpros** [comment]
This is resolved. Thank you for the new feature.
