### ISSUE TITLE
Blank page after installation wizard

### ISSUE THREAD

**Issue by ALJAZHERO** [magicbug/Cloudlog#2071]
Hi.
I got the installation working up to the installation wizard page. when I fill out all of the required information and click Install, I get a blank page loaded up. Do you have any sugestios on fixing this up? 
Thanks in advanced.

**Comment by ALJAZHERO** [comment]
![Posnetek zaslona (709)](https://user-images.githubusercontent.com/109150822/234057014-3d71e31e-c984-4cd9-a5ce-2e294ebf9d29.png)
![Posnetek zaslona (710)](https://user-images.githubusercontent.com/109150822/234057053-517faa9b-7011-449a-9e04-60179db98fa2.png)
![Posnetek zaslona (711)](https://user-images.githubusercontent.com/109150822/234057074-bf4fda4c-31c6-4d1a-9b2b-c83fa7fcd092.png)

Yes, here they are.

**Comment by magicbug** [comment]
I'm going on a guess but I'll go with that it failed to complete the MySQL insert you might get more info looking at the server log files

**Comment by magicbug** [comment]
2 weeks without a reply so closing

**Comment by minorsecond** [comment]
I'm having this issue too. After running the installation wizard (a few times):

```
MariaDB [cloudlog]> show tables;
Empty set (0.000 sec)
```
`Jul 11 19:11:03 log mariadbd[1656]: 2023-07-11 19:11:03 33 [Warning] Aborted connection 33 to db: 'cloudlog' user: '******' host: 'localhost' (Unknown error)`
