### ISSUE TITLE
 CSV export of contest lists contains button labels

### ISSUE THREAD

**Issue by pa8s** [magicbug/Cloudlog#2074]
**Describe the bug**
CSV export of contest lists contains button labels

**To Reproduce**
Steps to reproduce the behaviour:

Admin -> Contests -> CSV
View downloaded CSV file, column D,E and F contains 'Deactivate', 'Edit' and 'Delete' labels respectively. 

**Expected behaviour**
Mentioned columns not present in CSV export

**Logfile**
N/A

**Server**
OS: FreeBSD 13.1
Server: nginx/1.24.0
PHP: 8.1.18
Codeigniter: 3.2.0-dev
Git branch: dev
Git commit: https://github.com/magicbug/Cloudlog/commit/d6139439734f92fbd81cfcb85c3a616fff322832
Git Tag: https://github.com/magicbug/Cloudlog/releases/tag/2.3.1

**Comment by phl0** [comment]
Will be fixed with https://github.com/magicbug/Cloudlog/pull/2077.
