### ISSUE TITLE
Warning --> Undefined array key "manual" 

### ISSUE THREAD

**Issue by pa8s** [magicbug/Cloudlog#2076]
**Describe the bug**
Warning --> Undefined array key "manual" 

**To Reproduce**
Unable to recall performed steps :(

**Expected behaviour**
No error in logfile

**Logfile**
ERROR - 2023-04-24 21:05:34 --> Severity: Warning --> Undefined array key "manual" /mnt/www/application/views/interface_assets/footer.php 2397

**Server**
OS: FreeBSD 13.1
Server: nginx/1.24.0
PHP: 8.1.18
Codeigniter: 3.2.0-dev
Git branch: dev
Git commit: https://github.com/magicbug/Cloudlog/commit/d6139439734f92fbd81cfcb85c3a616fff322832
Git Tag: https://github.com/magicbug/Cloudlog/releases/tag/2.3.1

**Comment by phl0** [comment]
Happens upon editing contests. Fix will be included with https://github.com/magicbug/Cloudlog/pull/2078.
