### ISSUE TITLE
ADIF import is not working after codeignitor3.1.6 update

### ISSUE THREAD

**Issue by wvolz** [magicbug/Cloudlog#211]
ADIF import is failing with a "filetype you are attempting to upload is not allowed." error.

**Comment by magicbug** [comment]
Not had time to check but guessing https://github.com/magicbug/Cloudlog/pull/212 addresses this?

**Comment by paulburton0** [comment]
I just pulled latest from master and still getting the same error when importing adi file:

`The filetype you are attempting to upload is not allowed.`

**Comment by wvolz** [comment]
@magicbug Not sure it was clear, but yes.

**Comment by wvolz** [comment]
@paulburton0 I've run into some issues where my OS sets the wrong MIME type on the upload and that causes CodeIgnitor to reject the file. What OS are you on?

**Comment by paulburton0** [comment]
@wvolz I'm using Ubuntu 16.04.3
