### ISSUE TITLE
eQSL images not downloaded

### ISSUE THREAD

**Issue by m0urs** [magicbug/Cloudlog#2113]
I just saw, by accident, that I have only 116 images "images/eqsl_card_images" and for most of my eQSL confirmations I cannot see the QSL image. I only get the information 

![image](https://user-images.githubusercontent.com/2588362/236670728-1dce7ec0-9f42-4c10-95a7-85cb71cd03cd.png)

My last image is from April 8th and I do have eQSL confirmations after that date which have no image as well.

So I have the following questions:

- Should an image be downloaded for every eQSL confirmation?
- If yes, what could be the reason that no images are downloaded any longer?
- I would have said that I had more images already in that directory in the past (although I am not 100% sure) so maybe something has been lost in the past. Is there any possibility to re-download all eQSL images for all existing, confirmed QSOs?

**Comment by AndreasK79** [comment]
From what I can figure out looking in the code, the image is not automatically downloaded. It is only downloaded when you click on the confirmation.

I read in the code that it is also rate limited, so that using a script for downloading all does not seem like a good idea.

Perhaps someone with more knowledge about eQSL have some more information.

**Comment by m0urs** [comment]
Ah ok, thank you. If it is downloaded if I click on the confirmation, then this would be good enough. However, it seems that this is broken at the moment. So I only get the error above and the image is not displayed.

**Comment by phl0** [comment]
Jepp. eQSL is rate limited. Bulk downloading will not work. And yes the code was designed to only download on demand (maybe due to rate limit). 
On my end eQSL download works at the moment. Maybe temporary issue?

**Comment by magicbug** [comment]
Correct eqsl rate limit and that's why I coded it to do them on demand not in bulk.

This issue will resolve itself after a few minutes

**Comment by m0urs** [comment]
It does not work for me with the current DEV branch. If I switch to the current master then it is working again. @AndreasK79 , could it be that some of your code regarding eQSL sync from command line has broken the eQSL image display?

**Comment by m0urs** [comment]
The following errors are logged while trying to display the eQSL image:

```
ERROR - 2023-05-07 15:41:36 --> Severity: Warning --> Undefined property: eqsl::$user_model /var/www/cloudlog.urspringer.de/html/application/controllers/Eqsl.php 485
ERROR - 2023-05-07 15:41:36 --> Severity: error --> Exception: Call to a member function get_by_id() on null /var/www/cloudlog.urspringer.de/html/application/controllers/Eqsl.php 485
```

**Comment by m0urs** [comment]
@AndreasK79  It seems to work again if I add the following lines to "application/controllers/Eqsl.php":

**// Check logged in
$this->load->model('user_model');**

in line 473 like:

```
        function image($id) {
                $this->load->library('electronicqsl');
                $this->load->model('Eqsl_images');

                // Check logged in
                $this->load->model('user_model');

               if($this->Eqsl_images->get_image($id) == "No Image") {
		
```

**Comment by phl0** [comment]
This fixes it: https://github.com/AndreasK79/Cloudlog/pull/7.

**Comment by AndreasK79** [comment]
Thanks @m0urs and @phl0. The fix is merged.

**Comment by m0urs** [comment]
And it does work for me 👍

**Comment by AndreasK79** [comment]
@m0urs great. I think most of the stuff should be sorted, but you never know.
