### ISSUE TITLE
Table broken on eQSL upload page

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#2115]
On the latest dev release, the table that should show successfully uploaded QSOs to eQSL.net isn't wrapping correctly.

<img width="1372" alt="Screenshot 2023-05-07 at 7 15 26 PM" src="https://user-images.githubusercontent.com/5504940/236709938-51428bf2-40db-451b-b69d-868f44290d08.png">

**Comment by phl0** [comment]
> Pull latest code and test please.

Pulled and tested ok. Fix works.
