### ISSUE TITLE
Feature request: Add "About" or "Version" to Account drop-down (top right corner) when running on a Release branch

### ISSUE THREAD

**Issue by gx1400** [magicbug/Cloudlog#2121]
When running on a Release (https://github.com/magicbug/Cloudlog/releases), e.g. version 2.4.2, it would be nice to have a convenient place in Cloudlog to find which release you're running on.  This may exist and I don't see it quickly.

This version/about page could also include a "Current Version:" and "Newest Release:" verbiage.

It would also be nice if there were a dismiss-able banner that would pop up when there is a newer release than you are currently running.

I am not familiar with the Git Release API, but quick google found this: https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28

**Comment by gx1400** [comment]
https://api.github.com/repos/magicbug/Cloudlog/releases

**Comment by magicbug** [comment]
Already exists in /debug it was only available in developer mode but just fixed that in the dev branch so that its shown to anyone with the Admin role

**Comment by magicbug** [comment]
![image](https://user-images.githubusercontent.com/84308/236841453-4ca1e76f-8dac-42ab-8e2a-1c007579a3c6.png)

**Comment by magicbug** [comment]
Currently have no intentions to change branch names at this point.
