### ISSUE TITLE
mysql_pconnect() depreciated

### ISSUE THREAD

**Issue by m1geo** [magicbug/Cloudlog#214]
Hi Pete. Using the latest commit, I get the following error:

> Severity: 8192
> Message: mysql_pconnect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead
> Filename: mysql/mysql_driver.php
> Line Number: 135

George M1GEO

**Comment by teabreakninja** [comment]
Hi George, if you edit _application/config/database.php_ and change the _dbdriver_ to "mysqli" it should now work. I guess you are using php version >= 7.0 ?

Andy
