### ISSUE TITLE
QSO End Date not updated when uploading new LoTW certificate

### ISSUE THREAD

**Issue by pa8s** [magicbug/Cloudlog#2141]
**Describe the bug**
My previous LoTW certificate was valid until 12 May 2023. A renewed certificate was issued 14 April 2023 and subsequently uploaded to my Cloudlog instance. Up until 12 May the scheduled upload via cron went smoothly. Since then no upload was performed via cron as via manual syncing within Cloudlog. To check if it was certificate releated I uploaded a few logs of QSOs I've made on the 13th via TrustedQSL and this worked as expected. 
So it might be date related? As I have log entries later than 12 May in my logbook I was surprised to see the certificate list in Cloudlog was still showing 'QSO End Date' as 12 May 2023 although the last QSO was made on the 13th. So that date has nothing to do with log entries. To check I manually edited the date in the sql database to a later date, this changed the date in the certificate list and did a manual sync. Now the last QSOs are uploaded to LoTW, checked by logging in at ARRL. 

**To Reproduce**
Try to upload/sync logbook with QSO dated later than the 'QSO End Date' in the certificate list. This should fail.

**Expected behaviour**
When uploading/updating certificate the 'QSO End Date' is updated to what the certificates states. In my case the 'QSO End Date' is set to 'N/A' according to TQSL.
If a 'N/A' date can not be handled by Cloudlog, at least set the 'QSO End Date' to the expiry date of the certificate. 

**Logfile**
N/A

**Server**
OS: FreeBSD 13.1
Server: nginx/1.24.0
PHP: 8.1.18
Codeigniter: 3.2.0-dev
Git branch: dev
Git commit: https://github.com/magicbug/Cloudlog/commit/b52449da3c0bfc87f2f22ce2bef92acba4431023
Git Tag: https://github.com/magicbug/Cloudlog/releases/tag/2.3.1

**Comment by magicbug** [comment]
stumbled into this bug the other day, solution for now is to delete the cert from Cloudlog and reupload it, however, will get it resolved.

@phl0 oh look the issue i had!

**Comment by phl0** [comment]
I will have a look.

**Comment by phl0** [comment]
@ryandzink This is the open issue for this. Did you re-upload the same cert? And has the previous one been uploaded before August 2022?

**Comment by ryandzink** [comment]
@phl0 yes I uploaded the same cert file as was previously imported into my instance. The last time it had been uploaded was August 29 2022

**Comment by phl0** [comment]
> @phl0 yes I uploaded the same cert file as was previously imported into my instance. The last time it had been uploaded was August 29 2022

Ok thats a good hint as about that time I introduced the QSO date stuff. Maybe I made a stupid mistake here. Will check. Does it now show the correct date?

**Comment by ryandzink** [comment]
Yeah, here's a before and after of the same file uploaded:

<img width="1158" alt="Screenshot 2023-05-21 at 6 46 41 AM" src="https://github.com/magicbug/Cloudlog/assets/13768946/7c93137b-4c0d-4a46-911c-f29f349f3ef2">

<img width="1234" alt="Screenshot 2023-05-21 at 6 40 42 AM" src="https://github.com/magicbug/Cloudlog/assets/13768946/44711d6c-a81e-4a26-bd20-610a5a0fa682">

**Comment by phl0** [comment]
> Yeah, here's a before and after of the same file uploaded:

Weird. It shows the same dates ... That is gonna be a tricky one ... :)

**Comment by ryandzink** [comment]
Oh good grief I screwed up my upload... too my screenshots!

Before: 
<img width="700" alt="239720327-fda32bc9-e7ee-44c8-a22d-7c4e0c246f1b" src="https://github.com/magicbug/Cloudlog/assets/13768946/ed1eba16-1e48-41c0-80b6-d32fe97d39c5">

After:
<img width="1148" alt="image" src="https://github.com/magicbug/Cloudlog/assets/13768946/97295e82-535d-4cf3-9c66-99dbc24aad47">

**Comment by phl0** [comment]
> Oh good grief I screwed up my upload... too my screenshots!

Ok. That looks ... different now ... I guess I made a mistake in the migration for existing certificates. I will dig into this. Thank you for the evidences.

**Comment by phl0** [comment]
Note to myself: Corresponding PR is/was https://github.com/magicbug/Cloudlog/pull/1580.

**Comment by pa8s** [comment]
Checked with latest dev and 'QSO End Date' is now set to one day prior to expiry date of certificate. Thanks for the fix.

**Comment by phl0** [comment]
> Checked with latest dev and 'QSO End Date' is now set to one day prior to expiry date of certificate. Thanks for the fix.

It should not be set to one day prior to expiry of the certificate in general. The QSO validity dates are separate properties of the certs which you can set during creation of the cert. But for most use cases it is the same as validity period of the cert itself probably ...

**Comment by phl0** [comment]
Btw could you please close here as the fix obviously works :) tnx
