### ISSUE TITLE
Feature Request: Install Cloudlog with YunoHost

### ISSUE THREAD

**Issue by mattbk** [magicbug/Cloudlog#2185]
**Describe the bug**
Not a bug, but feature request to add installation with YunoHost: https://yunohost.org/.

Intro to packaging is here: https://yunohost.org/en/packaging_apps.

I have opened a PR to add Cloudlog to the YunoHost app wishlist, so this issue is to close the loop. https://github.com/YunoHost/doc/pull/2274.

**Expected behaviour**
Search the YunoHost app directory and install Cloudlog from there.

**Comment by magicbug** [comment]
I understand that some may desire this, but it may not be worth the time that could be dedicated to Cloudlog.

**Comment by mattbk** [comment]
I get that. Mostly I wanted to get an issue out there im case others might be searching for it.

**Comment by magicbug** [comment]
This appears to have been implimented https://github.com/YunoHost-Apps/cloudlog_ynh if you can confirm

**Comment by mattbk** [comment]
Awesome. I was able to install using that package. Thanks for the note!
