### ISSUE TITLE
Make the sender email address configurable via global options

### ISSUE THREAD

**Issue by int2001** [magicbug/Cloudlog#2197]
(Sender-)emailadress is currently hardcoded in application/controllers/User.php and Oqrs.php
Would be great, to make these two values configureable via config.php.

**Comment by magicbug** [comment]
Seems a good request, can be added to /options/email

**Comment by AndreasK79** [comment]
Added pr #2204

**Comment by AndreasK79** [comment]
Merged into dev now.
