### ISSUE TITLE
Stop syncing to qrz.com if Key is expired

### ISSUE THREAD

**Issue by int2001** [magicbug/Cloudlog#2198]
if one enters a qrz.com-api-key, cloudlog syncs to qrz.com (Great Feature!)
But if the qrz-subscription expires, cloudlog will try the sync **for each (unsynced) QSO** every time.

Suggestion: If the first Request failed with the following Errormessage, then stop trying to upload the rest of the QSOs.

`--> QRZ upload failed with the following message: STATUS=AUTH&REASON=user does not have a valid QRZ subscription to use this function`

Saves a lot of traffic.

**Comment by magicbug** [comment]
This seems like a good reason, if that's returned simple solution might be to delete the API key

**Comment by int2001** [comment]
Yes, one can do that. But the "normal User" isn't aware of that. He's confused about "no sync" while the server is establishing more and more connections.
Extreme situation: Fresh Account. User imports everything via ADIF-Import und has a key. But key is invalid.

So CL tries every croncycle to sync (happened here: More than 200 MB every hour)

**Comment by int2001** [comment]
Fix with PR: https://github.com/magicbug/Cloudlog/pull/2252
