### ISSUE TITLE
Set initial focus on username field for login page

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#2221]
This is incredibly nitpicky, but it would be great if user's cursor is set to be active in the username field for Cloudlog upon page load. This would prevent an extra cursor click before typing in credentials!

**Comment by magicbug** [comment]
Think we're at that stage but yeah seems a solid suggestion

**Comment by AndreasK79** [comment]
As far as I can tell, this works now.

**Comment by ofadam** [comment]
It does indeed work! Thanks so much.
