### ISSUE TITLE
Map issue on /application/views/view_log/qso.php

### ISSUE THREAD

**Issue by magicbug** [magicbug/Cloudlog#223]
@teabreakninja there appears to be an issue with the map, when you click on a callsign it brings up /application/views/view_log/qso.php and the map is normally just a pin centered on the lat/long

This doesn't seem to happen any more just zooms in but no pin, however, if I zoom out I can see all the QSOs which it shouldn't.

**Comment by teabreakninja** [comment]
![cloudlog_qso_details](https://user-images.githubusercontent.com/9462722/49069314-e5053880-f220-11e8-8ce3-c42014dd8dd0.png)
Is this what you mean? This works for me.

**Comment by magicbug** [comment]
Yes, should only be the one pin for the contact in question

I either get two pins guess its getting it from the maps list the front page uses
![zoomed in two pins](https://user-images.githubusercontent.com/84308/49085736-a1272900-f24a-11e8-8f63-93dbdc4d59ca.PNG)

Or if its beyond the time cut off for the front page, it zooms into the area but no pin
![zoomed in but no pin](https://user-images.githubusercontent.com/84308/49085738-a1bfbf80-f24a-11e8-89db-6ce2d254e79f.PNG)

This is what it used to do on Google Maps

![gmaps](https://user-images.githubusercontent.com/84308/49085817-d3388b00-f24a-11e8-8ea5-205b73ad5880.PNG)

I tend to use these screens for grabbing screenshots for tweets.

**Comment by magicbug** [comment]
Theres actually an issue on /index.php/logbook/ where the map should only show the QSOs for whats displayed on the screen where as again its showing the information from the home screen map

**Comment by magicbug** [comment]
OK I've updated the map code on the QSO popup can be seen here https://github.com/magicbug/Cloudlog/commit/906a4ce249ba60132fc900e34fa804b37b3cc551

What I haven't done yet is the logbook one

**Comment by magicbug** [comment]
Fixed logbook aswell https://github.com/magicbug/Cloudlog/commit/1690bd1bb8e19296ce14ddad3fd3903138abf573
