### ISSUE TITLE
None of your Logbooks are configured to export data to the QO-100 Dx Club's API.

### ISSUE THREAD

**Issue by do4bmw** [magicbug/Cloudlog#2230]
HY

i want to Upload my Logs die QO100DX Club , and it works in the past
but now i get this Message in Red 

> None of your Logbooks are configured to export data to the QO-100 Dx Club's API.
> To configure this feature, go to your profile page at the [QO-100 Dx Club](https://qo100dx.club/) and Create an API key. Then, navigate to your [Station Locations](http://log.do4bmw.de/index.php/station) and configure you station with the key you have created at the club.

Problem is , i have a Valid API Key allready entered

![Screenshot_75](https://github.com/magicbug/Cloudlog/assets/76187206/b444fa78-0bce-441f-897f-553b1b82e37b)

**Comment by phl0** [comment]
I think the error message is misleading. It also appears if all QSOs are uploaded and no new ones exist. Maybe this is the case here?

**Comment by do4bmw** [comment]
Hy Phl0

you are right ... many thanks

![image](https://github.com/magicbug/Cloudlog/assets/76187206/e6153880-5b81-4856-bd43-609542b5fabb)

**Comment by phl0** [comment]
Proposed a fix in https://github.com/magicbug/Cloudlog/pull/2231.
