### ISSUE TITLE
FEATURE REQUEST: Awards -> DXCC: Add option to show only unconfirmed QSOs

### ISSUE THREAD

**Issue by m0urs** [magicbug/Cloudlog#2261]
I would like to be able to see a list of all DXCC countries which I have worked but which are not yet confirmed. I would like to use this view to check if I have a possibility to get a confirmation e.g. by requesting a direct QSL card etc.

Currently I do not see a possibility to do this with the current filter options in Awards -> DXCC:

![image](https://github.com/magicbug/Cloudlog/assets/2588362/faacb516-62cd-4d38-9e03-6eb5485680b0)

Maybe it would make sense, to add the same logic to the other Awards view likes WAS etc.

**Comment by m0urs** [comment]
> Uh oh! @m0urs, the image you shared is missing helpful alt text. Check your issue body.
> 
> Alt text is an invisible description that helps screen readers describe images to blind or low-vision users. If you are using markdown to display images, add your alt text inside the brackets of the markdown image.
> 
> Learn more about alt text at [Basic writing and formatting syntax: images on GitHub Docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#images).

Is this something which we might be able to switch off? :-)

**Comment by magicbug** [comment]
> Is this something which we might be able to switch off? :-)

Nope its a good idea to add ALT text to images, which helps those with visual impairments.

`![Alt text](image URL)`

**Comment by int2001** [comment]
I cannot reproduce this @m0urs 
if I set the filters exactly as in your screenshot, I get a list (or map) of all those DXCCs for which I never received a QSL or LotW confirmation.
If there is only one LotW/QSL confirmation from that DXCC, the DXCC is not shown, otherwise it is listed.
Isn't that what you wanted?

Maybe I misunderstood your feature-request?

**Comment by m0urs** [comment]
@int2001 You are absolutely right. I have no idea what I have seen and/or thought yesterday :-( It is exactly how it should be ... So sorry for that and we can close it.
