### ISSUE TITLE
Advanced logbook: Filters are reset after editing a QSO

### ISSUE THREAD

**Issue by m0urs** [magicbug/Cloudlog#2265]
If I set a filter to the Advanced Logbook view (e.g. all QSOs with DXCC=K and MODE=SSB) and then click on one of the QSOs and edit them, the Advanced Logbook filters are reset to "No filter".

This is very inkonvenient if I need to edit a bulk of QSOs which have the selected criteria. 

Any chance to fix this?

**Comment by AndreasK79** [comment]
I disabled page reload after QSO edit in the Advanced Logbook. That should solve this.
