### ISSUE TITLE
Maritime Mobile station qsos not showing up in search

### ISSUE THREAD

**Issue by N9EAT** [magicbug/Cloudlog#2267]
My QSOs with various maritime mobile stations (e.g., UT1FG/mm) will not show up using the search bar. I can however find them when searching in the advanced log. 

This issue doesn't seem to apply to other prefixes or suffixes.

**Comment by phl0** [comment]
This has already been fixed in dev with https://github.com/magicbug/Cloudlog/commit/10d7739ea2c20d6d50a535a8b9fd997efa248837. Will be available with the next release.

**Comment by magicbug** [comment]
Yep can confirm this ones fixed
