### ISSUE TITLE
Unable to see git information on Admin -> Debug card when installed per wiki due to git permission issues

### ISSUE THREAD

**Issue by gx1400** [magicbug/Cloudlog#2275]
**Describe the bug**
See discussion in: https://github.com/magicbug/Cloudlog/discussions/2272
Admin -> Debug view does not show git information card

**To Reproduce**
Steps to reproduce the behaviour:
1. Admin -> Debug view does not show git information card

**Expected behaviour**
git information card shown on debug view

**Screenshots**

**Desktop (please complete the following information):**
 - OS: `Linux ubuntu-22 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
 - Browser: Firefox

**Additional context**
When installing per [Linux install on Wiki](https://github.com/magicbug/Cloudlog/wiki/Installation), git install is owned by the user who executes the git clone clone.  PHP executes on 'www-data' apache2 user, which does not have permission to the '.git' folder to execute git information commands.

Unable to see git information card on Admin -> Debug view until I performed a `chown -R www-data:www-data .git`

**Comment by magicbug** [comment]
Yeah this isn't a bug with Cloudlog but a permissions issue with the file system, but I will add a note about the .git file
