### ISSUE TITLE
ADIF - If importing and station_callsign isn't provided check if OPERATOR is

### ISSUE THREAD

**Issue by magicbug** [magicbug/Cloudlog#2295]
If importing an ADIF file and station_callsign isn't provided check if OPERATOR is and use that instead thus suppressing unnecessary erroring.

![photo_2023-07-15_10-58-52](https://github.com/magicbug/Cloudlog/assets/84308/e766b833-1009-40a1-ba79-029e3c8bd91e)

Get rid of those errors! :)

Possibly might want to change the error to say that said tag was missing or incorrect rather than just wrong

Thanks G0ABI for reporting

**Comment by magicbug** [comment]
For now i've commented out the offending IF statement as this is creating plenty support requests https://github.com/magicbug/Cloudlog/pull/2296/files

**Comment by int2001** [comment]
working on that. tnx 4 reporting.

Idea is to set station_callsign to chosen call (profile) when delivered empty.

**Comment by magicbug** [comment]
Ah yeah was causing lots of breaking and an busy email inbox :p

**Comment by int2001** [comment]
made a pr. plz test.
wondering which ADIF-Source produces adif without station_callsign. Do you know?
