### ISSUE TITLE
Columns mismatch after upgrading to 2.4.5

### ISSUE THREAD

**Issue by iu2frl** [magicbug/Cloudlog#2308]
**Describe the bug**
When upgrading from latest release to 2.4.5 some DB structures have been changed, after the upgrade i see:

- Main page:
![image](https://github.com/magicbug/Cloudlog/assets/61653175/6e8b467c-53cf-4fd6-bbff-27fe71510a0c)

- User settings:
![image](https://github.com/magicbug/Cloudlog/assets/61653175/2b4bacdb-58e9-4c4d-8a8a-59e5c6352da6)

- I tried updating my user settings and:
![image](https://github.com/magicbug/Cloudlog/assets/61653175/0b5433b5-6335-403c-af31-5d70b7dfaad3)

**Desktop (please complete the following information):**
 - OS: Ubuntu server
 - Browser: Chrome

**Comment by magicbug** [comment]
Looks like the migration system didn't successfully complete you could try index.php/migration and see if anything errors.

**Comment by iu2frl** [comment]
I think i got it, i had to manually open the DB and create this structure:

![image](https://github.com/magicbug/Cloudlog/assets/61653175/c7e213ac-ed5f-4ee5-9804-f99bdb085c91)

**Comment by iu2frl** [comment]
I just pulled the container and executed that, then i opened the usual URL, it asked me the login details and the main page showed up with that error

**Comment by iu2frl** [comment]
@magicbug i just discovered some other columns are missing somewhere else, i tried the migration URL but no luck, any other suggestion?

![missing migration page](https://github.com/magicbug/Cloudlog/assets/61653175/0096737a-ac61-4004-a51c-48b085a59eeb)
