### ISSUE TITLE
Unable to save location

### ISSUE THREAD

**Issue by dexdeadly** [magicbug/Cloudlog#2316]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
On a fresh install I am having an issue. When I try to create an active station I was unable to. I found that I was able to save only a few top items and get passed. However I noticed if I try to save any location information such as the city, state, country and county. I've tried to reboot the docker to no avail. 

**To Reproduce**
Steps to reproduce the behaviour:
1. New Installation
2. Click on user name up top
3. click on Station Locations
4. Try creating the location

**Expected behaviour**
All data to be saved

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Brave and Chrome
 - Version 1.56.11

**Smartphone (please complete the following information):**
None

**Additional context**

**Comment by int2001** [comment]
did you create a Station Logbook 1st?
Process is:
* create user
* create Station Logbook
* create Station Location
* Link both

**Comment by magicbug** [comment]
Can we first check that in Station Location when your trying to create one that you can see the DXCC dropdown? if not you'll need to fix that first, you can update the tables by going to Admin -> Update Country files

**Comment by dexdeadly** [comment]
AH HA. Ok, so I did the logbook, location, linked them and all of that.  The part I did not do was what magicbug had just mentioned. I updated the country files. Once I did that it was able to save everything.
