### ISSUE TITLE
Uploading .p12 LoTW certificate fails with no visible error

### ISSUE THREAD

**Issue by lu1aax** [magicbug/Cloudlog#2334]
Using latest version updated with git, using it in developer mode now.

I needed to update my LoTW. I uploaded new p12 file. No error, but new cert not shown. I deleted the old cert. Tried again and no error and no available certs listed.

Please help, thanks!

**Comment by phl0** [comment]
This is most probably not a Cloudlog issue but OpenSSL. See https://github.com/magicbug/Cloudlog/issues/2068.

**Comment by lu1aax** [comment]
Hi! Thanks for your prompt reply.

Activated the legacy support in openssl.cnf. Still the same situation.

There's no trace of what went wrong... No information in the logs, it's strange. Even though I am in developer mode there's absolutely no feedback about what went on.

**Comment by lu1aax** [comment]
It seems like there is something else going on here, I cannot upload the old certificate (2020) neither.

**Comment by phl0** [comment]
Did you edit the openssl.cnf file which is in use for the PHP module running inside the webserver? 
It does not matter if yoj are uploading old or new certs since all of them use the same (old) algorithms as to my knowledge. Set the log threshold to 4 and have a look at the logs generated in application/logs.

**Comment by lu1aax** [comment]
Thanks for the guidance!

I'm getting this:

ERROR - 2023-07-28 19:14:41 --> Severity: Notice --> Undefined index: cert /srv/www/lu1aax.taslik.net/Cloudlog/application/controllers/Lotw.php 407
ERROR - 2023-07-28 19:14:41 --> error:0308010C:digital envelope routines::unsupported
