### ISSUE TITLE
ADIF Error

### ISSUE THREAD

**Issue by DL3EL** [magicbug/Cloudlog#2341]
I have just upgraded to the latest version and now I see an error while importing ADIF data. The same files worked without issues before.
Interesting is, that the error is empty (see photo). I will attach the file for import as well. [
![Clipboard01](https://github.com/magicbug/Cloudlog/assets/35669080/52f9f43e-982e-47fa-94b8-af9abf4d407b)
](url)
[cl_error.txt](https://github.com/magicbug/Cloudlog/files/12196826/cl_error.txt)

vy 73 de Thomas, DL3EL

**Comment by DL3EL** [comment]
additional remark: when I export a single qso from the advanced view, change call and time and import it again, the same error occures

**Comment by int2001** [comment]
the main question is: Are all QSOs imported? Do you miss a QSO?

There's bug in the last master, which is fixed here: https://github.com/magicbug/Cloudlog/commit/49dcc9c3d0893032531910c500bbdf109ec724b0
will be available in the next Version.

The bug consists of printing out that Error, but importing everything...

**Comment by phl0** [comment]
Would you be able to supply the ADIF file you were trying for debugging purposes? If so you may send it to me via email pse.

**Comment by DL3EL** [comment]
it looks like everything is imported ok

**Comment by int2001** [comment]
Ok, then this is fixed in the latest dev (and soon in master).

But can be closed?!

**Comment by DL3EL** [comment]
I think so
