### ISSUE TITLE
A locator longer than six characters or faulty info won't save qso

### ISSUE THREAD

**Issue by oh1jw** [magicbug/Cloudlog#2342]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
A locator longer than six characters, usually fetched from QRZ.com or similar, gives warning
when saving qso - but won't save qso details or actually the qso at all. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'QSO (live or post)'
2. Add qso details, with long grid e.g. IN52OF72PK
3. Click on 'Add qso'
4. See error --> 
<img width="642" alt="Näyttökuva 2023-7-28 kello 21 08 56" src="https://github.com/magicbug/Cloudlog/assets/77230101/d5bd86a0-35ca-4ffc-b627-a66e6d722987">

**Expected behaviour**
Shorten locator value automaticly for 6 characters? OR at least save qso without locator, but not losing all the qso details and give some kind of warning about missing locator. But not to any circumstances leave the qso unsaved. 

**Screenshots**
<img width="642" alt="Näyttökuva 2023-7-28 kello 21 08 56" src="https://github.com/magicbug/Cloudlog/assets/77230101/19f4f7fd-ce3a-4ded-80b6-a6d6fa6bb962">

**Comment by magicbug** [comment]
Not so much faulty just not accepted, works in progress to handle them however.

**Comment by magicbug** [comment]
The dev branch can handle up to 8 there for I'm going to propose we trim anything beyond that going forward.

**Comment by oh1jw** [comment]
> Not so much faulty just not accepted, works in progress to handle them however.

Good that in progress... this happened me in the middle of the pileup, so there was already a lot of hassle when I noticed that the entire qso was not saved and the details were cleared.

**Comment by magicbug** [comment]
Now resolved in the dev branch
