### ISSUE TITLE
Advanced Logbook Filter is missing qsos

### ISSUE THREAD

**Issue by DL3EL** [magicbug/Cloudlog#2346]
you can filter qsos, if they are cionfirmed with LOTW or not. I have several qsos, which are not shown, when you select LOTW = NO. 
A closer look at the qso data shows, that these qso do not contain the field "<LOTW_QSL_RCVD:1>N".

Could that be the reason?

**Comment by phl0** [comment]
> A closer look at the qso data shows, that these qso do not contain the field "<LOTW_QSL_RCVD:1>N".

What exactly do you mean by "does not contain the field"? Are you talking about an ADIF im- or export?

**Comment by phl0** [comment]
Oh advanced logbook. My fault for bot reading correctly. @AndreasK79 already has an idea. So this should be fix-able.

**Comment by phl0** [comment]
I proposed a patch with https://github.com/magicbug/Cloudlog/pull/2347. @DL3EL could you please verify this works on your system?

**Comment by AndreasK79** [comment]
It's merged now, so pull latest dev.

**Comment by DL3EL** [comment]
@AndreasK79 with that it works, thanks
