### ISSUE TITLE
table adif_modes contains 9672 rows

### ISSUE THREAD

**Issue by DL2CC** [magicbug/Cloudlog#2416]
**Describe the bug**
Table adif_modes contains lots of duplicate modes

**To Reproduce**
Add QSO, open dropdown for mode, see lots of duplicates

**Expected behaviour**
fewer modes with distinct values should be visibke

**Additional context**

Updated to latest version using git pull today, don't know when or by which update this happened as I have updated last few releases without using the QSO entry window. Definitely not happened by update to 2.4.7 (switched to my backup but didn't help) but used to work fine 6 weeks ago when I was using it.

adif_modes contains 9672 rows, 339 DIGITAL VOICE, out of which just C4FM alone has 112 rows

**Comment by AndreasK79** [comment]
Looking at the code, I can't tell why this happened. Did you manage to clean it up?

**Comment by DL2CC** [comment]
hi there, no not yet. I haven't found the create command for the table yet so I can drop and recreate. Couldn't find it in the setup script. Do you know where it is?

**Comment by AndreasK79** [comment]
Haven't looked, but you could just remove duplicates in the table.

**Comment by AndreasK79** [comment]
I checked myself. I had a few duplicates, which I removed with the attached SQL. Make a backup, just to be on the safe side.

Try the following SQL:

> DELETE from adif_modes where id in
   (SELECT id from
        (SELECT *, ROW_NUMBER() OVER(PARTITION BY mode, submode, qrgmode ORDER BY  id) as rn
    FROM adif_modes) as delmodes
WHERE rn > 1);

**Comment by dg9vh** [comment]
You also could use this query:

`-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Erstellungszeit: 28. Aug 2023 um 20:17
-- Server-Version: 5.7.41-log-cll-lve
-- PHP-Version: 8.1.16

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Datenbank: `huebelon_clprod`
--

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle `adif_modes`
--

DROP TABLE IF EXISTS `adif_modes`;
CREATE TABLE `adif_modes` (
  `id` int(9) NOT NULL,
  `mode` varchar(12) NOT NULL,
  `submode` varchar(25) DEFAULT NULL,
  `qrgmode` varchar(4) NOT NULL,
  `active` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Daten für Tabelle `adif_modes`
--

INSERT INTO `adif_modes` (`id`, `mode`, `submode`, `qrgmode`, `active`) VALUES
(1, 'AM', NULL, 'SSB', 0),
(2, 'ARDOP', NULL, 'DATA', 0),
(3, 'ATV', NULL, 'DATA', 0),
(4, 'C4FM', NULL, 'DATA', 0),
(5, 'CHIP', NULL, 'DATA', 0),
(6, 'CHIP', 'CHIP128', 'DATA', 0),
(7, 'CHIP', 'CHIP64', 'DATA', 0),
(8, 'CLO', NULL, 'DATA', 0),
(9, 'CONTESTI', NULL, 'DATA', 0),
(10, 'CW', NULL, 'CW', 1),
(11, 'CW', 'PCW', 'CW', 0),
(12, 'DIGITALVOICE', NULL, 'DATA', 1),
(13, 'DOMINO', NULL, 'DATA', 0),
(14, 'DOMINO', 'DOMINOEX', 'DATA', 0),
(15, 'DOMINO', 'DOMINOF', 'DATA', 0),
(16, 'DSTAR', NULL, 'DATA', 0),
(17, 'FAX', NULL, 'DATA', 0),
(18, 'FM', NULL, 'SSB', 1),
(19, 'FSK441', NULL, 'DATA', 0),
(20, 'FT8', NULL, 'DATA', 1),
(21, 'HELL', NULL, 'DATA', 0),
(22, 'HELL', 'FMHELL', 'DATA', 0),
(23, 'HELL', 'FSKHELL', 'DATA', 0),
(24, 'HELL', 'HELL80', 'DATA', 0),
(25, 'HELL', 'HFSK', 'DATA', 0),
(26, 'HELL', 'PSKHELL', 'DATA', 0),
(27, 'ISCAT', NULL, 'DATA', 0),
(28, 'ISCAT', 'ISCAT-A', 'DATA', 0),
(29, 'ISCAT', 'ISCAT-B', 'DATA', 0),
(30, 'JT4', NULL, 'DATA', 0),
(31, 'JT4', 'JT4A', 'DATA', 0),
(32, 'JT4', 'JT4B', 'DATA', 0),
(33, 'JT4', 'JT4C', 'DATA', 0),
(34, 'JT4', 'JT4D', 'DATA', 0),
(35, 'JT4', 'JT4E', 'DATA', 0),
(36, 'JT4', 'JT4F', 'DATA', 0),
(37, 'JT4', 'JT4G', 'DATA', 0),
(38, 'JT44', NULL, 'DATA', 0),
(39, 'JT65', NULL, 'DATA', 0),
(40, 'JT65', 'JT65A', 'DATA', 0),
(41, 'JT65', 'JT65B', 'DATA', 0),
(42, 'JT65', 'JT65B2', 'DATA', 0),
(43, 'JT65', 'JT65C', 'DATA', 0),
(44, 'JT65', 'JT65C2', 'DATA', 0),
(45, 'JT6C', NULL, 'DATA', 0),
(46, 'JT6M', NULL, 'DATA', 0),
(47, 'JT9', NULL, 'DATA', 0),
(48, 'JT9', 'JT9-1', 'DATA', 0),
(49, 'JT9', 'JT9-10', 'DATA', 0),
(50, 'JT9', 'JT9-2', 'DATA', 0),
(51, 'JT9', 'JT9-30', 'DATA', 0),
(52, 'JT9', 'JT9-5', 'DATA', 0),
(53, 'JT9', 'JT9A', 'DATA', 0),
(54, 'JT9', 'JT9B', 'DATA', 0),
(55, 'JT9', 'JT9C', 'DATA', 0),
(56, 'JT9', 'JT9D', 'DATA', 0),
(57, 'JT9', 'JT9E', 'DATA', 0),
(58, 'JT9', 'JT9E FAST', 'DATA', 0),
(59, 'JT9', 'JT9F', 'DATA', 0),
(60, 'JT9', 'JT9F FAST', 'DATA', 0),
(61, 'JT9', 'JT9G', 'DATA', 0),
(62, 'JT9', 'JT9G FAST', 'DATA', 0),
(63, 'JT9', 'JT9H', 'DATA', 0),
(64, 'JT9', 'JT9H FAST', 'DATA', 0),
(65, 'JTMS', NULL, 'DATA', 0),
(66, 'JTMSK', NULL, 'DATA', 0),
(67, 'MFSK', NULL, 'DATA', 1),
(68, 'MFSK', 'FSQCALL', 'DATA', 0),
(69, 'MFSK', 'FT4', 'DATA', 1),
(70, 'MFSK', 'JS8', 'DATA', 0),
(71, 'MFSK', 'MFSK11', 'DATA', 0),
(72, 'MFSK', 'MFSK128', 'DATA', 0),
(73, 'MFSK', 'MFSK16', 'DATA', 0),
(74, 'MFSK', 'MFSK22', 'DATA', 0),
(75, 'MFSK', 'MFSK31', 'DATA', 0),
(76, 'MFSK', 'MFSK32', 'DATA', 0),
(77, 'MFSK', 'MFSK4', 'DATA', 0),
(78, 'MFSK', 'MFSK64', 'DATA', 0),
(79, 'MFSK', 'MFSK8', 'DATA', 0),
(80, 'MSK144', NULL, 'DATA', 0),
(81, 'MT63', NULL, 'DATA', 0),
(82, 'OLIVIA', NULL, 'DATA', 0),
(83, 'OLIVIA', 'OLIVIA 16/1000', 'DATA', 0),
(84, 'OLIVIA', 'OLIVIA 16/500', 'DATA', 0),
(85, 'OLIVIA', 'OLIVIA 32/1000', 'DATA', 0),
(86, 'OLIVIA', 'OLIVIA 4/125', 'DATA', 0),
(87, 'OLIVIA', 'OLIVIA 4/250', 'DATA', 0),
(88, 'OLIVIA', 'OLIVIA 8/250', 'DATA', 0),
(89, 'OLIVIA', 'OLIVIA 8/500', 'DATA', 0),
(90, 'OPERA', NULL, 'DATA', 0),
(91, 'OPERA', 'OPERA-BEACON', 'DATA', 0),
(92, 'OPERA', 'OPERA-QSO', 'DATA', 0),
(93, 'PAC', NULL, 'DATA', 0),
(94, 'PAC', 'PAC2', 'DATA', 0),
(95, 'PAC', 'PAC3', 'DATA', 0),
(96, 'PAC', 'PAC4', 'DATA', 0),
(97, 'PAX', NULL, 'DATA', 0),
(98, 'PAX', 'PAX2', 'DATA', 0),
(100, 'PSK', NULL, 'DATA', 0),
(101, 'PSK', 'FSK31', 'DATA', 0),
(102, 'PSK', 'PSK10', 'DATA', 0),
(103, 'PSK', 'PSK1000', 'DATA', 0),
(104, 'PSK', 'PSK125', 'DATA', 0),
(105, 'PSK', 'PSK250', 'DATA', 0),
(106, 'PSK', 'PSK31', 'DATA', 0),
(107, 'PSK', 'PSK500', 'DATA', 0),
(108, 'PSK', 'PSK63', 'DATA', 0),
(109, 'PSK', 'PSK63F', 'DATA', 0),
(110, 'PSK', 'PSKAM10', 'DATA', 0),
(111, 'PSK', 'PSKAM31', 'DATA', 0),
(112, 'PSK', 'PSKAM50', 'DATA', 0),
(113, 'PSK', 'PSKFEC31', 'DATA', 0),
(114, 'PSK', 'QPSK125', 'DATA', 0),
(115, 'PSK', 'QPSK250', 'DATA', 0),
(116, 'PSK', 'QPSK31', 'DATA', 0),
(117, 'PSK', 'QPSK500', 'DATA', 0),
(118, 'PSK', 'QPSK63', 'DATA', 0),
(119, 'PSK', 'SIM31', 'DATA', 0),
(120, 'PSK2K', NULL, 'DATA', 0),
(121, 'Q15', NULL, 'DATA', 0),
(122, 'QRA64', NULL, 'DATA', 0),
(123, 'QRA64', 'QRA64A', 'DATA', 0),
(124, 'QRA64', 'QRA64B', 'DATA', 0),
(125, 'QRA64', 'QRA64C', 'DATA', 0),
(126, 'QRA64', 'QRA64D', 'DATA', 0),
(127, 'QRA64', 'QRA64E', 'DATA', 0),
(128, 'ROS', NULL, 'DATA', 0),
(129, 'ROS', 'ROS-EME', 'DATA', 0),
(130, 'ROS', 'ROS-HF', 'DATA', 0),
(131, 'ROS', 'ROS-MF', 'DATA', 0),
(132, 'RTTY', NULL, 'DATA', 1),
(133, 'RTTY', 'ASCI', 'DATA', 0),
(134, 'RTTYM', NULL, 'DATA', 0),
(135, 'SSB', NULL, 'SSB', 1),
(136, 'SSB', 'LSB', 'SSB', 1),
(137, 'SSB', 'USB', 'SSB', 1),
(138, 'SSTV', NULL, 'DATA', 0),
(139, 'T10', NULL, 'DATA', 0),
(140, 'THOR', NULL, 'DATA', 0),
(141, 'THRB', NULL, 'DATA', 0),
(142, 'THRB', 'THRBX', 'DATA', 0),
(143, 'TOR', NULL, 'DATA', 0),
(144, 'TOR', 'AMTORFEC', 'DATA', 0),
(145, 'TOR', 'GTOR', 'DATA', 0),
(146, 'V4', NULL, 'DATA', 0),
(147, 'VOI', NULL, 'DATA', 0),
(148, 'WINMOR', NULL, 'DATA', 0),
(149, 'WSPR', NULL, 'DATA', 0),
(151, 'DYNAMIC', 'VARA HF', 'DATA', 1),
(152, 'DYNAMIC', 'VARA SATELLITE', 'DATA', 1),
(154, 'DIGITALVOICE', 'C4FM', 'DATA', 1),
(155, 'DIGITALVOICE', 'DMR', 'DATA', 1),
(156, 'DIGITALVOICE', 'DSTAR', 'DATA', 1),
(157, 'DYNAMIC', NULL, 'DATA', 1),
(160, 'DYNAMIC', 'VARA FM 1200', 'DATA', 1),
(161, 'DYNAMIC', 'VARA FM 9600', 'DATA', 1),
(162, 'DOMINO', 'DOM-M', 'DATA', 0),
(163, 'DOMINO', 'DOM4', 'DATA', 0),
(164, 'DOMINO', 'DOM5', 'DATA', 0),
(165, 'DOMINO', 'DOM8', 'DATA', 0),
(166, 'DOMINO', 'DOM11', 'DATA', 0),
(168, 'DOMINO', 'DOM22', 'DATA', 0),
(169, 'DOMINO', 'DOM44', 'DATA', 0),
(170, 'DOMINO', 'DOM88', 'DATA', 0),
(171, 'HELL', 'HELLX5', 'DATA', 0),
(172, 'HELL', 'HELLX9', 'DATA', 0),
(173, 'HELL', 'SLOWHELL', 'DATA', 0),
(174, 'MFSK', 'FST4', 'DATA', 0),
(175, 'MFSK', 'FST4W', 'DATA', 0),
(176, 'MFSK', 'JTMS', 'DATA', 0),
(177, 'MFSK', 'Q65', 'DATA', 0),
(178, 'PSK', '8PSK125', 'DATA', 0),
(179, 'PSK', '8PSK125F', 'DATA', 0),
(180, 'PSK', '8PSK125FL', 'DATA', 0),
(181, 'PSK', '8PSK250', 'DATA', 0),
(182, 'PSK', '8PSK250F', 'DATA', 0),
(183, 'PSK', '8PSK250FL', 'DATA', 0),
(184, 'PSK', '8PSK500', 'DATA', 0),
(185, 'PSK', '8PSK500F', 'DATA', 0),
(186, 'PSK', '8PSK1000', 'DATA', 0),
(187, 'PSK', '8PSK1000F', 'DATA', 0),
(188, 'PSK', '8PSK1200F', 'DATA', 0),
(189, 'PSK', 'PSK63F', 'DATA', 0),
(190, 'PSK', 'PSK63RC4', 'DATA', 0),
(191, 'PSK', 'PSK63RC5', 'DATA', 0),
(192, 'PSK', 'PSK63RC10', 'DATA', 0),
(193, 'PSK', 'PSK63RC20', 'DATA', 0),
(194, 'PSK', 'PSK63RC32', 'DATA', 0),
(195, 'PSK', 'PSK125C12', 'DATA', 0),
(196, 'PSK', 'PSK125R', 'DATA', 0),
(197, 'PSK', 'PSK125RC10', 'DATA', 0),
(198, 'PSK', 'PSK125RC12', 'DATA', 0),
(199, 'PSK', 'PSK125RC16', 'DATA', 0),
(200, 'PSK', 'PSK125RC4', 'DATA', 0),
(201, 'PSK', 'PSK125RC5', 'DATA', 0),
(202, 'PSK', 'PSK250C6', 'DATA', 0),
(203, 'PSK', 'PSK250R', 'DATA', 0),
(204, 'PSK', 'PSK250RC2', 'DATA', 0),
(205, 'PSK', 'PSK250RC3', 'DATA', 0),
(206, 'PSK', 'PSK250RC5', 'DATA', 0),
(207, 'PSK', 'PSK250RC6', 'DATA', 0),
(208, 'PSK', 'PSK250RC7', 'DATA', 0),
(209, 'PSK', 'PSK500C2', 'DATA', 0),
(210, 'PSK', 'PSK500C4', 'DATA', 0),
(211, 'PSK', 'PSK500R', 'DATA', 0),
(212, 'PSK', 'PSK500RC2', 'DATA', 0),
(213, 'PSK', 'PSK500RC3', 'DATA', 0),
(214, 'PSK', 'PSK500RC4', 'DATA', 0),
(215, 'PSK', 'PSK800C2', 'DATA', 0),
(216, 'PSK', 'PSK800RC2', 'DATA', 0),
(217, 'PSK', 'PSK1000C2', 'DATA', 0),
(218, 'PSK', 'PSK1000R', 'DATA', 0),
(219, 'PSK', 'PSK1000RC2', 'DATA', 0),
(220, 'THOR', 'THOR-M', 'DATA', 0),
(221, 'THOR', 'THOR4', 'DATA', 0),
(222, 'THOR', 'THOR5', 'DATA', 0),
(223, 'THOR', 'THOR8', 'DATA', 0),
(224, 'THOR', 'THOR11', 'DATA', 0),
(225, 'THOR', 'THOR16', 'DATA', 0),
(226, 'THOR', 'THOR22', 'DATA', 0),
(227, 'THOR', 'THOR25X4', 'DATA', 0),
(228, 'THOR', 'THOR50X1', 'DATA', 0),
(229, 'THOR', 'THOR50X2', 'DATA', 0),
(230, 'THOR', 'THOR100', 'DATA', 0),
(231, 'THRB', 'THRBX1', 'DATA', 0),
(232, 'THRB', 'THRBX2', 'DATA', 0),
(233, 'THRB', 'THRBX4', 'DATA', 0),
(234, 'THRB', 'THROB1', 'DATA', 0),
(235, 'THRB', 'THROB2', 'DATA', 0),
(236, 'THRB', 'THROB4', 'DATA', 0),
(237, 'TOR', 'NAVTEX', 'DATA', 0),
(238, 'TOR', 'SITORB', 'DATA', 0),
(239, 'DIGITALVOICE', 'FREEDV', 'DATA', 1),
(240, 'DIGITALVOICE', 'M17', 'DATA', 1);

--
-- Indizes der exportierten Tabellen
--

--
-- Indizes für die Tabelle `adif_modes`
--
ALTER TABLE `adif_modes`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT für exportierte Tabellen
--

--
-- AUTO_INCREMENT für Tabelle `adif_modes`
--
ALTER TABLE `adif_modes`
  MODIFY `id` int(9) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=241;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;`

**Comment by DL2CC** [comment]
Thanks a lot dg9vh & AndreasK79! 
dg9vh sql worked like a charm. Now I finally can use live QSO again.

**Comment by dg9vh** [comment]
Nice to hear :-)
