### ISSUE TITLE
New station location QSOs not showing in Logbook overview (or homepage) but does show in Advanced logbook view

### ISSUE THREAD

**Issue by M5JFS** [magicbug/Cloudlog#2435]
User error or a bug?

I created a new station location MU5JFS but QSO for 18.8.23 with TF/DL2GRC does not show in the Logbook overview or the homepage,
If I page pack in time, other station locations (eg. MR5JFS) do show in the overview.
The MU5JFS QSO does show in the advanced logbook view however and it also comes up in search results if I search for TF/DL2GRC

QSO showing in search results
![image](https://github.com/magicbug/Cloudlog/assets/73586719/8db0cd66-5b8d-4b06-9e2c-39ea3a47e0a4)

QSO showing in logbook advanced view
![image](https://github.com/magicbug/Cloudlog/assets/73586719/04bcdca4-89d0-4ba0-ba26-3e72c2da24ad)

QSO not showing in logbook overview
![image](https://github.com/magicbug/Cloudlog/assets/73586719/ae386be6-9e5c-4822-8bd6-8902c73925bf)

QSO not showing in homepage 
![image](https://github.com/magicbug/Cloudlog/assets/73586719/4961f563-7e4d-460e-84c7-61cbc1a01d85)

MR5JFS station location calls showing in logbook overview
![image](https://github.com/magicbug/Cloudlog/assets/73586719/d02596df-b42a-4ceb-8de9-0d84b9b81cc5)

**Comment by magicbug** [comment]
I'm guessing when you created the new location you added it either to a new "Logbook" or an existing one? and that said ones active along with the location

**Comment by M5JFS** [comment]
User error - I'd forgotten to add it to the list of locations for my main logbook 🤦‍♂️.
