### ISSUE TITLE
[Feature Request] DB structure check

### ISSUE THREAD

**Issue by iu2frl** [magicbug/Cloudlog#2450]
**Describe the request**
When updating Cloudlog installations (or trying to implement new fieatures for devs), the DB structure is sometime updated, this means that the DB structure may not be 100% aligned with the requirements.

This has happened to me in the past where some migration scripts have failed and i had to manually add some columns here and there

**Expected behaviour**
Minimum requirement:
- Somewhere in an advanced settings page there may be an option to check the DB structure and warn the user if something is wrong

Ideal:

- User is prompt to fix the missing/wrong columns

**Comment by substa** [comment]
Thank you for this nice release. When will the docker image be updated?
