### ISSUE TITLE
QSL Request CSV contains unicode characters which MS Excel/MS Word doesn't like!

### ISSUE THREAD

**Issue by m1geo** [magicbug/Cloudlog#2453]
The Export to CSV button generates CSV that includes "Ø" characters which aren't correctly handled by Microsoft Excel/Word for using in mail merges. 

![image](https://github.com/magicbug/Cloudlog/assets/758615/e9e01058-0a1e-4d80-89e6-345b4f852108)

I know that Word does support these, but it gets broken when opened. Not sure if you can add some metadata or make this an option during the export.

![image](https://github.com/magicbug/Cloudlog/assets/758615/9f1c6440-cab2-46d7-9a5b-86011a99cce4)

Looking at the same QSOs in the ADIF shows a standard ASCII "0" character:

![image](https://github.com/magicbug/Cloudlog/assets/758615/ee87a673-b013-4876-abb5-736bd7048462)

Just in case there is a way to make this import work better :)

Thanks for the great work,
George, M1GEO. sk sk.

**Comment by phl0** [comment]
Fix proposed in https://github.com/magicbug/Cloudlog/pull/2454.

**Comment by magicbug** [comment]
This code is now in the master branch so @m1geo should be able to use and test it easily.
