### ISSUE TITLE
Advanced Search showing duplicate rows

### ISSUE THREAD

**Issue by magicbug** [magicbug/Cloudlog#2469]
Can't figure this one out, I'm seeing duplicate rows of the same QSO which even has the same primary id

![Image showing advanced search with duplicate rows](https://github.com/magicbug/Cloudlog/assets/84308/8d6a380a-a437-4850-b0bd-2f67c1e7c21c)

I had the same on the standard logbook view and adding a distinct seemed to resolve it but I cant seem todo the same for this.

Thoughts @phl0 @int2001 @AndreasK79 

Happening on both dev and master

**Comment by int2001** [comment]
do you have two certs with the same call, @magicbug ?

**Comment by magicbug** [comment]
Nope

**Comment by magicbug** [comment]
Resolved, seems the lotw_users table had duplicate entries!

**Comment by int2001** [comment]
we are going to create a mig-script, which puts a unique-idx on lotw_users.call.
i think root-cause was a broken cronjob or sth. like that.

**Comment by AndreasK79** [comment]
Happy you figured it out. Table should be emptied when cron is run, so a bit strange. Unique index will fix it though.
