### ISSUE TITLE
[Feature Request] Split ADIF file while exporting

### ISSUE THREAD

**Issue by m0urs** [magicbug/Cloudlog#2477]
My ADIF file is now over 8MB in size and sometimes it is not possible to upload such big files to other services. Therefore it would be great that we could have the possibility to split the file during exporting either by size or by number of records.

Maybe this could be implemented?

**Comment by int2001** [comment]
Search -> Advanced Search:
Add Filter "TIME_OFF > [date]" then Search and then "Export to ADIF" should do the job

**Comment by magicbug** [comment]
Yep advance options should do the trick,

**Comment by m0urs** [comment]
Hm, yes. You can do that as a workaround. However you need to make several tries until you find the correct date so that the file is not greater than e.g. x MB. But ok, as it is not to be done so often, that is ok.

**Comment by int2001** [comment]
Perhaps i don't understand your usecase, @m0urs 

Which service requires *always* to upload your whole log? The services i know are happy with daily/weekly/monthly content (content: what's new in difference to the last upload).

Cloudlog itself is doing that in this way with lotw/hrdlog/clublog/qrz. Even if a QSO is changed afterwards it uploads the changed one to the services.

And if you want to provide your log to another tool, you also do not have to upload the *whole* log everytime. What am i missing here?

**Comment by m0urs** [comment]
@int2001 Is it really the case that it uploads changed QSOs to e.g. Clublog also? It does it for QRZ.com but I think not for the other services? So Clublog e.g. does not get QSL information for past QSOs or am I wrong? 

But yes, as I said, I agree. It is not needed very often so you can do that with exporting logs for smaller time slots.

**Comment by int2001** [comment]
Yes, it is doing that for clublog. I fixed that by myself a few months ago.
Whenever a LoTW-Confirmation is dropped on a QSO, Cloudlog reuploads the QSO to Clublog (and QRZ)

**Comment by m0urs** [comment]
Ok, thanks for the info!
