### ISSUE TITLE
Upload to LoTW does not work

### ISSUE THREAD

**Issue by DL4AN** [magicbug/Cloudlog#2496]
The new QSOs do not get uploaded to the LoTW and keep being "red" in Logbook-Overview.
Neither GUI nor Cronjob with curl .../index.php/lotw/lotw_upload work.

The status of the LoTW certificate is shown as "Valid. Not synced"

Cloudlog has the newest version from github.

**Comment by magicbug** [comment]
Is this a brand new install? what version of PHP

**Comment by DL4AN** [comment]
Not a new install, it is in use since ~2 years. I've tested it with PHP versions 7.4 and 8.2 with the no effect.

**Comment by DL4AN** [comment]
Update - the reason is an unset cert_dxcc_id and therefore "continue" in this statement in application/controllers/Lotw.php
`
                               // If Station Profile has no LoTW Cert continue on.
                               if(!isset($data['lotw_cert_info']->cert_dxcc_id)) {
                                        continue;
                                }
`

**Comment by DL4AN** [comment]
Works now - the DXCC country in the station profile was "Germany DL/D (Deleted)"
After changing it to "Federal Republic of Germany - DL" the LoTW sync works again.
