### ISSUE TITLE
station_profile Table - Missing primary key / AI

### ISSUE THREAD

**Issue by Manawyrm** [magicbug/Cloudlog#250]
Hi,

the station_profile table is missing a primary key and an auto-increment flag. 
https://github.com/magicbug/Cloudlog/blob/master/sql/tables/station_profile.sql

    ALTER TABLE `station_profile`
    MODIFY COLUMN `station_id`  int(11) UNSIGNED NOT NULL AUTO_INCREMENT FIRST ,
    ADD PRIMARY KEY (`station_id`);

I'd recommend adding this to the file...

So long,
Tobias

**Comment by magicbug** [comment]
Whoops not sure why that was missing

**Comment by Manawyrm** [comment]
Thought so. Should I open a PR? 
There's another issue in the new BS4 parts, in the API-keys the Link is incorrect.

Can I send a PR for that, too, or are you currently working on these files?

**Comment by magicbug** [comment]
No feel free to play with those bits not touching API area at the moment
