### ISSUE TITLE
Advanced Logbook - An Error Occurred

### ISSUE THREAD

**Issue by Michael-AUG** [magicbug/Cloudlog#2519]
Hi

A while back now I was importing an ADI file into my CloudLog instance and something went wrong. I don't know exactly what; but now, whenever I click on 'Advanced Log', I get this error message display:

![2023-09-27T18:22:51,928393495+01:00](https://github.com/magicbug/Cloudlog/assets/126279033/de7fc994-c8fb-41de-8994-bdbb89c3e31f)

Is there something I can do at the server end to reset this/fix it? I would go and fiddle around but I don't want to lose all my logs!

Thanks
Michael GM5AUG

**Comment by phl0** [comment]
Can you have a look at the network tab and let us know what the network requests for table content says?

**Comment by Michael-AUG** [comment]
![2023-09-27T20:44:59,533205014+01:00](https://github.com/magicbug/Cloudlog/assets/126279033/1e620873-07c4-40a9-bd82-99eee9e319ef)
Is this what you need to see? Or something else?

**Comment by phl0** [comment]
The details of the packet resulting in the error 500 at the bottom is of interest. Can you show the details and the response here?

**Comment by Michael-AUG** [comment]
![2023-09-27T20:48:48,386304370+01:00](https://github.com/magicbug/Cloudlog/assets/126279033/f4397b98-50dc-42f7-bb27-2703b983067b)
Thanks Florian.

**Comment by phl0** [comment]
Yeah and here the response tab please?

**Comment by Michael-AUG** [comment]
Response tab empty... screenshots:
![2023-09-27T20:51:06,769918358+01:00](https://github.com/magicbug/Cloudlog/assets/126279033/8710ef7a-6c7b-4491-ab2e-4da3d0f027e0)
![2023-09-27T20:51:13,192004168+01:00](https://github.com/magicbug/Cloudlog/assets/126279033/e73bbf55-a56e-4bbd-8633-5340f85f3ce6)
![2023-09-27T20:51:20,524196680+01:00](https://github.com/magicbug/Cloudlog/assets/126279033/9b478079-946e-4b39-a5c3-e1e30b50e4ea)

**Comment by phl0** [comment]
Could you please enable development mode in index.php and re-do that? Looking for the error message which is hidden in prod mode ...

**Comment by Michael-AUG** [comment]
![2023-09-27T20:59:31,966242302+01:00](https://github.com/magicbug/Cloudlog/assets/126279033/c7bf684c-fbce-408e-9f72-815b7c8c4d0c)
![2023-09-27T20:59:42,898499856+01:00](https://github.com/magicbug/Cloudlog/assets/126279033/86aeb5e6-a28a-45b7-94f8-b45b82fe8edd)
![2023-09-27T20:59:51,239566665+01:00](https://github.com/magicbug/Cloudlog/assets/126279033/494218a9-0ebd-4d43-9f86-019d17d82f67)
Is this right?

**Comment by phl0** [comment]
Set 

```
define('ENVIRONMENT', 'development');
```

in index.php. Again open dev tools of your browser, call the advanced search and show the response tab of the packet producing the error 500 pls.

**Comment by Michael-AUG** [comment]
Sorry to be thick Florian... do you mean type `define...`  in the Developer Tools - Console? Or edit the index.php file?

**Comment by magicbug** [comment]
You'll need to edit index.php set the environment to development

**Comment by phl0** [comment]
No worries. Edit index.php. Find the line containing `define('ENVIRONMENT')` and change production to development here.
Then enable developer tools in your browser. Select the Network tab and go to advanced search again. Then show the response tab of the packet causing the error 500 please.

**Comment by Michael-AUG** [comment]
Yup - gotcha. Was just about to delete that message. Thanks Peter. I'm on it, Florian.

**Comment by Michael-AUG** [comment]
![2023-09-27T21:07:42,607444246+01:00](https://github.com/magicbug/Cloudlog/assets/126279033/36656a1e-af90-46ab-a13b-8279cc0ecbe5)
OK... ^

**Comment by phl0** [comment]
Yeah. This helps (I guess at least). Let me check.

**Comment by phl0** [comment]
Can you supply the adif file which produced the error? Would be apprechiated via mail. My mail is ok on QRZ.com :)

**Comment by Michael-AUG** [comment]
No I'm afraid I can't. I stupidly deleted it when it wasn't working :{

**Comment by magicbug** [comment]
Export of your logbook from Cloudlog might be the next best thing

**Comment by phl0** [comment]
Hmmm I set BAND to null for a test QSO. But does not produce an error in logbook advanced ....

**Comment by phl0** [comment]
Maybe you can provide an SQL dump of your DB/table?

**Comment by phl0** [comment]
@Michael-AUG Which version of Cloudlog are you using btw?

**Comment by phl0** [comment]
Ping

**Comment by Michael-AUG** [comment]
Hi guys. Sorry for radio silence on this one.

> Export of your logbook from Cloudlog might be the next best thing

Sorry - being thick. Do you mean an ADIF? Or an export from the server?

> Which version of CloudLog are you using btw?

I'm using v 2.3.3 

> Maybe you can provide an SQL dump of your DB/table?

Could you talk me through how to do this please?

Thanks everyone - really appreciate your help.
Michael

**Comment by magicbug** [comment]
> I'm using v 2.3.3

First I'd suggest updating to see if it resolves itself, but if not yes ADIF export via Cloudlog would be a good start.

**Comment by Michael-AUG** [comment]
OK - I'll get to work on that now.

**Comment by ryandzink** [comment]
I am seeing the same issue, but I don't remember ever having a failed ADIF import. What info can I help provide that might help get to a root cause?

**Comment by phl0** [comment]
> I am seeing the same issue, but I don't remember ever having a failed ADIF import. What info can I help provide that might help get to a root cause?

Which version are you using? And does it show the same error concerning band in the details?

**Comment by ryandzink** [comment]
@phl0 I am using v2.4.10

Here is the response on the HTTP 500 that I am seeing:

```
An uncaught Exception was encountered

Type: ParseError

Message: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

Filename: /opt/bitnami/apache2/htdocs/src/QSLManager/QSO.php

Line Number: 12
```

**Comment by phl0** [comment]
> @phl0 I am using v2.4.10

Thats good so far :) Is that happening on specific filters or on first call directly? Is it maybe one (or more) specific QSOs that cause the error? If so you do an SQL dump showing the stored data for that/those QSOs?

**Comment by phl0** [comment]
> @phl0 I am using v2.4.10
> 
> Here is the response on the HTTP 500 that I am seeing:

Oh and which PHP/SQL versions are you using?

**Comment by ryandzink** [comment]
I'm using MySQL 5.7 and PHP 7.3.15. It happens even on first load of the page, before executing any searches.

I'm happy to query the TABLE_HRD_CONTACTS_V01 table but it's got several thousand QSOs so I might need something specific to look for.

**Comment by AndreasK79** [comment]
You need at least PHP 7.4. The search is executed on page load, so that is why you see it. Try upgrading PHP and see if that fixes the problem.
