### ISSUE TITLE
Add the ability to set Time on and Time Off in /QSO/

### ISSUE THREAD

**Issue by freemo** [magicbug/Cloudlog#2524]
Log entires covers start time but not time off despite this being a requirement for ham radio station logging and supported by ADIF.

**Comment by magicbug** [comment]
Theres no set requirement, however we don't easily allow setting the end time at the moment but this has been mentioned here https://github.com/magicbug/Cloudlog/discussions/2515 and requires some interface changes but its on the roadmap
