### ISSUE TITLE
Feature: Support EDI contest format 

### ISSUE THREAD

**Issue by petrkr** [magicbug/Cloudlog#2543]
Moon contest need EDI format, because it support more fields than cabrillo format (for example QTH name).

Would be nice to have direct export to this format aswell

**Comment by magicbug** [comment]
Do you have any information about this format?

**Comment by HB9HIL** [comment]
> Moon contest need EDI format, because it support more fields than cabrillo format (for example QTH name).
> 
> Would be nice to have direct export to this format aswell

@petrkr This one? [](https://www.ok2kkw.com/ediformat.htm)

**Comment by petrkr** [comment]
Yes, i can send sample, which I exported later

**Comment by abarrau** [comment]
for information, this feature is available on contest plugin

**Comment by petrkr** [comment]
> for information, this feature is available on contest plugin
> 
> ![EDI Format](https://github.com/magicbug/Cloudlog/assets/13674762/12f7dd4b-9ce2-42fc-b8c0-f8842f710edd)

after year I again started VKV contests, but I still not see EDI export and this is closed. You said it is in contest plugin, but my contest page looks different than on screenshot
