### ISSUE TITLE
Unable to setup cloudlog without error

### ISSUE THREAD

**Issue by fattredd** [magicbug/Cloudlog#2549]
Seems as though there and php errors during the initial setup.

**Describe the bug**
Following the [docker stack](https://github.com/magicbug/Cloudlog/wiki/Executing-the-full-standalone-Cloudlog-stack) instructions, upon clicking the "Install" button a php error occurs in `helpers/url_helper.php`

The error is as follows:
```
A PHP Error was encountered
Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /var/www/html/application/migrations/139_modify_eQSL_url.php:1)

Filename: helpers/url_helper.php

Line Number: 564
```

Interestingly, opening the page in a new tab allows me to log in as though everything were fine.

**To Reproduce**
Steps to reproduce the behaviour:
1.  [docker stack](https://github.com/magicbug/Cloudlog/wiki/Executing-the-full-standalone-Cloudlog-stack) instructions
2. Run `docker compose up -d`
3. Fill out the init form
4. Click Install

**Expected behaviour**
The setup completes

**Comment by fattredd** [comment]
I've also been seeing several other `A PHP Error was encountered`. I'm unsure of how related they are:  
  
  
When uploading my `.p12` certificate:
```

A PHP Error was encountered

Severity: Warning

Message: Undefined array key "cert"

Filename: controllers/Lotw.php

Line Number: 407
A PHP Error was encountered

Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /var/www/html/system/core/Exceptions.php:283)

Filename: helpers/url_helper.php

Line Number: 564
```

**Comment by HB9HIL** [comment]
> Seems as though there and php errors during the initial setup.
> 
> **Describe the bug** Following the [docker stack](https://github.com/magicbug/Cloudlog/wiki/Executing-the-full-standalone-Cloudlog-stack) instructions, upon clicking the "Install" button a php error occurs in `helpers/url_helper.php`
> 
> The error is as follows:
> 
> ```
> A PHP Error was encountered
> Severity: Warning
> 
> Message: Cannot modify header information - headers already sent by (output started at /var/www/html/application/migrations/139_modify_eQSL_url.php:1)
> 
> Filename: helpers/url_helper.php
> 
> Line Number: 564
> ```
> 
> Interestingly, opening the page in a new tab allows me to log in as though everything were fine.
> 
> **To Reproduce** Steps to reproduce the behaviour:
> 
>     1. [docker stack](https://github.com/magicbug/Cloudlog/wiki/Executing-the-full-standalone-Cloudlog-stack) instructions
> 
>     2. Run `docker compose up -d`
> 
>     3. Fill out the init form
> 
>     4. Click Install
> 
> 
> **Expected behaviour** The setup completes

I could not replicate this php errors with the basic setup described in the wiki. 
On which system do you run the stack?
Did you made any other changes to the 'docker-compose.yml' then just the Passwords?

**Comment by fattredd** [comment]
Sorry for the delay. I'm running on aarch64 (raspberry pi 4, 64-bit).  
  
For the sake of ensuring I didn't muck something up, I tried again with a freshly copied `docker-compose.yml` and deleted the existing volumes. For testing I didn't bother changing anything in the yaml -- not even the passwords.  
  
I start the stack with `docker compose up` so I could watch the output. After waiting a bit for mysql to initialize, I navigate to `http://localhost:8086/`.  

I fill out the database settings sections with `hostname: cloudlog-mysql`, `username: cloudlog`, `password: cloudlog-pass`, and `database name: cloudlog`. I click the Install button and get a page that says:  
  
```
A PHP Error was encountered
Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /var/www/html/application/migrations/139_modify_eQSL_url.php:1)

Filename: core/Common.php

Line Number: 575

An uncaught Exception was encountered
Type: mysqli_sql_exception

Message: Table 'cloudlog.users' doesn't exist

Filename: /var/www/html/system/database/drivers/mysqli/mysqli_driver.php

Line Number: 301
```

And here's the `docker compose` output. I've thrown it in a gist so it doesn't clutter the page:  
https://gist.github.com/fattredd/7bd83d2aa7eeff658e33cad83cd507f0

**Comment by HB9HIL** [comment]
> Sorry for the delay. I'm running on aarch64 (raspberry pi 4, 64-bit).
> 
> For the sake of ensuring I didn't muck something up, I tried again with a freshly copied `docker-compose.yml` and deleted the existing volumes. For testing I didn't bother changing anything in the yaml -- not even the passwords.
> 
> I start the stack with `docker compose up` so I could watch the output. After waiting a bit for mysql to initialize, I navigate to `http://localhost:8086/`.
> 
> I fill out the database settings sections with `hostname: cloudlog-mysql`, `username: cloudlog`, `password: cloudlog-pass`, and `database name: cloudlog`. I click the Install button and get a page that says:
> 
> ```
> A PHP Error was encountered
> Severity: Warning
> 
> Message: Cannot modify header information - headers already sent by (output started at /var/www/html/application/migrations/139_modify_eQSL_url.php:1)
> 
> Filename: core/Common.php
> 
> Line Number: 575
> 
> An uncaught Exception was encountered
> Type: mysqli_sql_exception
> 
> Message: Table 'cloudlog.users' doesn't exist
> 
> Filename: /var/www/html/system/database/drivers/mysqli/mysqli_driver.php
> 
> Line Number: 301
> ```
> 
> And here's the `docker compose` output. I've thrown it in a gist so it doesn't clutter the page: https://gist.github.com/fattredd/7bd83d2aa7eeff658e33cad83cd507f0

Which Kernel do you use on the rapsi?

You can find out with `uname -r`

**Comment by HB9HIL** [comment]
@fattredd I was able to reproduce your error. Seems like there is a Problem with ArmV8. I would recommend to install cloudlog on the raspi the traditional way like [the wiki says](https://github.com/magicbug/Cloudlog/wiki/Installation). 

@iu2frl Could you check that?

**Comment by iu2frl** [comment]
I don't think is anything on the raspberry itself but rather a missing table on the database, did you run through the "install" procedure?

**Comment by HB9HIL** [comment]
> I don't think is anything on the raspberry itself but rather a missing table on the database, did you run through the "install" procedure?

I did the exact same steps of a basic stack install on a 

**raspberry pi 4 - os light 32 bit --> error**
<img width="415" alt="image" src="https://github.com/magicbug/Cloudlog/assets/80885850/87a6ef8d-1872-4d62-b084-b137d56c50f5">

**raspberry pi 4 - os light 64 bit --> error**
same as @fattredd already mentioned above
```
A PHP Error was encountered
Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /var/www/html/application/migrations/139_modify_eQSL_url.php:1)

Filename: core/Common.php

Line Number: 575

An uncaught Exception was encountered
Type: mysqli_sql_exception

Message: Table 'cloudlog.users' doesn't exist

Filename: /var/www/html/system/database/drivers/mysqli/mysqli_driver.php

Line Number: 301
```

basic debian 12 vm on amd64 --> no errors, installation successfull with problems

**Comment by iu2frl** [comment]
This is your issue: Message: Table 'cloudlog.users' doesn't exist, anything else can be ignored. How are you connecting to the database? Did you create users and permissions to access the database? Can you reach the database itself using any third party client?

**Comment by HB9HIL** [comment]
> This is your issue: Message: Table 'cloudlog.users' doesn't exist, anything else can be ignored. How are you connecting to the database? Did you create users and permissions to access the database? 

I did nothing different as in the debian amd64 machine. And there it worked without any problems. 

> Can you reach the database itself using any third party client?

not from outside of docker because I didn't change the `docker-compose.yml` 
If I could reach it from inside docker I didn't test.

**Comment by f5mzn** [comment]
Hi - Same error message here, runing the install procedure as described on the wiki. This is on OSX, with Docker Desktop. The `cloudlog.users` table is well created, though. 73

**Comment by iu2frl** [comment]
I tried on develop on a completely blank machine and i got a different error:

```
A PHP Error was encountered
Severity: Warning

Message: Cannot modify header information - headers already sent by (output started at /var/www/html/application/migrations/139_modify_eQSL_url.php:1)

Filename: helpers/url_helper.php

Line Number: 564
```

**Comment by HB9HIL** [comment]
> I tried on develop on a completely blank machine and i got a different error:
> 
> ```
> A PHP Error was encountered
> Severity: Warning
> 
> Message: Cannot modify header information - headers already sent by (output started at /var/www/html/application/migrations/139_modify_eQSL_url.php:1)
> 
> Filename: helpers/url_helper.php
> 
> Line Number: 564
> ```

I created a debian 12 machine on amd64 and do not have any issues. Which kind of machine did u use?

**Comment by magicbug** [comment]
Lets be clear as a project I have decided not to provide docker support going forward, as this isn't code related if you need help with setting up server components use discussions
