### ISSUE TITLE
DB migration handling

### ISSUE THREAD

**Issue by Manawyrm** [magicbug/Cloudlog#255]
Cloudlogs database has changed a bit over the years, but the https://github.com/magicbug/Cloudlog/tree/master/application/migrations folder wasn't kept up-to-date. 

The assets/install.sql file contains an (older version) database dump which is executed. It's not up-to-date and doesn't contain the migrations table, so that will directly lead to failures on new installations.

Apart from use as a reference - is the sql/tables folder used anywhere? 

My suggestion/plan for work would be: 
Install a current cloudlog build with the assets/install.sql file, create the migrations table there. 
Then I'd go ahead, build migrations up to the current database version.

Maybe the sql/tables-Folder shouldn't be used at all? 

What do you think about the idea to clean this up? Would such a PR be accepted?

**Comment by magicbug** [comment]
Yes that makes sense, sql/tables can go that's an old from the start relic
