### ISSUE TITLE
Feature: Show progress bar during QSO upload

### ISSUE THREAD

**Issue by petrkr** [magicbug/Cloudlog#2560]
Would be handy (and also it could solve timeouts of PHP) if you upload QSO to sites like eQSL, QRZ.COM etc. to show some "information" it is happening. Now you do not know if you clicked properly or if something happening

My suggestions:
 - disable button after click until request is done
 - make it async (javascript can call some endpoint using jquery/XMLHttpRequest)
 - serverside can long-polling way reply status, which can be hadled by client javascript to show some progress bar (since it already sending content, server will NOT timeout)

**Comment by magicbug** [comment]
Providing a progress bar can be trouble some but we could use HTMX https://htmx.org/examples/ which would allow us to easily had a spinning notification so people feel that somethings happening
