### ISSUE TITLE
Could not find the language line "options_dxcluster_decont_hint"

### ISSUE THREAD

**Issue by pa8s** [magicbug/Cloudlog#2567]
**Describe the bug**
While using the DXCluster Bandmap , the log file reports following error:
```
ERROR - 2023-10-15 19:08:31 --> Could not find the language line "options_dxcluster_decont_hint"
```
The website is only using the English language file in my case. Other language files also doesn't have mentioned line.

**To Reproduce**
Steps to reproduce the behaviour:
1. Select the Bandmap from the menu.
2. Select a radio in the dropdown menu.
3. Check the most recent logfile.

**Expected behaviour**
No error in logfile.

**Server**
OS: FreeBSD 13.1
Server: nginx/1.24.0
PHP: 8.1.24
Git branch: dev
Commit: https://github.com/magicbug/Cloudlog/commit/ab75d5807df87a46b5c34d5dd601c7f3fa90af81
Tag: [2.4.10-120-gab75d580](https://github.com/magicbug/Cloudlog/releases/tag/2.4.10)

**Comment by phl0** [comment]
Fix in https://github.com/magicbug/Cloudlog/pull/2569.
