### ISSUE TITLE
Station Location County not pushed to QRZ

### ISSUE THREAD

**Issue by ae5au** [magicbug/Cloudlog#2646]
QSOs pushed to QRZ don't include the proper US county. They default to the home county on QRZ.

Station City, Station State, and Station Gridsquare are uploaded based on the station location from the QSO, but Station County is ignored.

Steps to reproduce the behaviour:
1. Create a new QSO with a specific station location that has fields set.
2. Push to QRZ (tested with same results using real-time and batched push).
3. Compare record on QRZ to record from station location.

Station location:
![Screenshot showing station location in Cloudlog with county set](https://github.com/magicbug/Cloudlog/assets/5542863/d782c3f1-b707-4024-91a6-ce6709950936)

Record on QRZ:
![Screenshot showing how QSO is transferred to QRZ without setting county...defaulting to QRZ default county](https://github.com/magicbug/Cloudlog/assets/5542863/f38b2787-7d92-4a42-9cca-484ad785f2fc)

**Comment by ae5au** [comment]
I also verified that the same QSO does send the county to LoTW.

![Screenshot of LoTW QSO record showing proper county](https://github.com/magicbug/Cloudlog/assets/5542863/b4f8e82c-edc5-4347-8bb5-dcca802ebcc8)

Also, I know that manually uploading an ADIF file to QRZ with MY_CNTY set will populate the county properly as this is how I've been handing my POTA activations for a while now.

**Comment by magicbug** [comment]
thanks for reporting that does indeed look like a bug!

**Comment by AndreasK79** [comment]
The problem lies in the component that generates our ADIF file. Since the county should be in the format of state, county.

```
<Two-letter state abbr.>
 
COMMA
 
<county name>
```
We only output the station county in my_cnty, so we need an update here.

**Comment by AndreasK79** [comment]
I pushed a fix to the dev branch that should take care of this.
