### ISSUE TITLE
logbookadvanced page table footnote is incorrect

### ISSUE THREAD

**Issue by littlebear0729** [magicbug/Cloudlog#2666]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
I have 637 QSOs.
When the page size is 250, the footnote below the table shows 'Showing 1 to 250 of 250 entries', and it should be 'Showing 1 to 250 of 637 entries'
When the page size is 1000 or more, it shows 'Showing 1 to 637 of 637 entries' which is correct.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to advanced logbook page
2. Click on Search Button
3. Change page size
4. Click on Search Button

**Expected behaviour**
I have 637 QSOs.
When the page size is 250, the footnote below the table shows 'Showing 1 to 250 of 250 entries', and it should be 'Showing 1 to 250 of 637 entries'
When the page size is 1000 or more, it shows 'Showing 1 to 637 of 637 entries' which is correct.

**Screenshots**
![image](https://github.com/magicbug/Cloudlog/assets/8424735/c1069c5c-1739-41aa-8000-76d0919cb50b)
![image](https://github.com/magicbug/Cloudlog/assets/8424735/c9f10c3f-05a0-40f8-a918-e0c902ef9941)

 Cloudlog Version 2.5.0 with Chinese language setting.

**Comment by abarrau** [comment]
Hello, 
in fact, on logbookadvanced page, table return the number defined (and limit result with this number). 
you can see that there is no pagination offered.
To see how the cloudlog team wishes to implement this results table ?

**Comment by HB9HIL** [comment]
@littlebear0729 

I understand your expectation to see `Showing 1 to 250 of 637 entries`
But I think there is a difference between expectation and what this "#Results Dropdown" does. I'll try to explain. 

This is no bug, rather it does exactly how it is designed. 

![dropdown](https://github.com/magicbug/Cloudlog/assets/80885850/628c04a0-b659-4f4e-bf4e-87d7e2a61eb8)

This Dropdown acts like a filter. 
Maybe your expectation was `Show me max. 250 QSO's of all my QSO's in Logbook`

But it acts like `Show me max. 250 QSO's in this list`

So if you need a number of all QSO's you can use for example the Analytics > Statistics Page on Tab "QSO" 

I hope I was able to explain why there is a difference between User Expectation and Design of the Logbook Advanced
