### ISSUE TITLE
Database error - missing table

### ISSUE THREAD

**Issue by g7kse** [magicbug/Cloudlog#268]
**Describe the bug**
On  fresh install and after an intial update. I went to import the old adif and get a database error

**To Reproduce**
1. Go to Admin > Update Tools > Update DXCC
2. Click on Update
3. Downloading file (seems to take an age)
4. Check in tables to see if dxcc table exists (it does, as does a single dxccexceptions)
5. Go to Admin > adif import
6. Browse and upload

**Expected behavior**
Adif to upload as normal, error as screenshot below. Note also the layout of the screen changes too

**Screenshots**
![image](https://user-images.githubusercontent.com/13124178/53893863-ef587f00-4026-11e9-8594-3c87c75a8898.png)

Layout change from 
![image](https://user-images.githubusercontent.com/13124178/53894301-c71d5000-4027-11e9-9a5c-33138cfd0f0b.png)

To
![image](https://user-images.githubusercontent.com/13124178/53894245-b076f900-4027-11e9-9dfc-1b099ad98a21.png)

**Desktop (please complete the following information):**
 - OS: RPi 3 LAMP (Mariadb). DietPi OS (previously ok)
 - Browser Chrome
 - Version 65.0.2 (64-bit)

**Additional context**
Tables are as follows:
![image](https://user-images.githubusercontent.com/13124178/53894522-21b6ac00-4028-11e9-9355-8839c7304b09.png) 

versus previous install
![image](https://user-images.githubusercontent.com/13124178/53895314-af46cb80-4029-11e9-9388-2eef9b43df86.png)

I think I had a previous error and created the table manullay but can't remember what I did and couldn't see a similar error in issues.

**Comment by magicbug** [comment]
This issue is now resolved in the code base.

**Comment by g7kse** [comment]
I think it is still missing the dxcc_prefixes table

**Comment by g7kse** [comment]
Closed after update to code base
