### ISSUE TITLE
[FEATURE REQUEST] Support for WAJA, perhaps other JARL awards. 

### ISSUE THREAD

**Issue by N9EAT** [magicbug/Cloudlog#2702]
Chasing for the WAJA award on greencube seems to be popular so I think this would be a useful feature for Cloudlog. Perhaps other JARL awards would be nice too.

**Comment by HB9HIL** [comment]
@N9EAT We have this on the Todo List :)

**Comment by HB9HIL** [comment]
@N9EAT It's on it's way #2747
