### ISSUE TITLE
Start Date/Time gets deleted when editing existing QSO

### ISSUE THREAD

**Issue by 205er** [magicbug/Cloudlog#2703]
Hi all,

I found a bug, that is very annoying. I logged a QSO and afterwards I need to make some changes to it, so I edit the QSO and save my corrections. Unfortunately, the start date/time will then be set automatically to _0000-00-00 00:00:00_ (while the end date stays untouched)
![Changed start date](https://github.com/magicbug/Cloudlog/assets/14996169/df79b08f-dfad-4811-adad-3fcc770459ca)

![Changed start date](https://github.com/magicbug/Cloudlog/assets/14996169/4c59366f-06f8-4081-b8d8-9b7b6ad33a33)

This issue will only appear when changing an existing QSO from "Live QSO" (at the right side) 

I'm using Cloudlog 2.5.1

**Comment by magicbug** [comment]
Yep seems resolved now in dev branch

**Comment by phl0** [comment]
I can confirm that this fixes/fixed the bug.

**Comment by 205er** [comment]
Thanks HB9HIL for you fix! Hope to meet you on the bands soon! ..und 73 von der anderen Bodenseeseite.
