### ISSUE TITLE
Comments will get (partially) deleted when including quotation marks 

### ISSUE THREAD

**Issue by 205er** [magicbug/Cloudlog#2704]
Hi,

today I discovered that comments will get (partially) deleted after saving when the text including quotation marks. Here is an example:

First I enter the comment...
![edit mode](https://github.com/magicbug/Cloudlog/assets/14996169/c43d3185-8e0b-4b4a-889e-12aaedb3a8e3)
...and save the QSO data set.

The comment is visible in viewing mode
![viewing mode](https://github.com/magicbug/Cloudlog/assets/14996169/0e800b5b-7786-4d34-b94e-d7f558415de8)

But after reopening the QSO, the comment text partially disappeared.
![disappeared comment](https://github.com/magicbug/Cloudlog/assets/14996169/e9e6997e-40bc-40c3-9626-4a9a789b0fd8)

There seems to be a function that interprets quotation marks incorrectly.

I'm using Cloudlog 2.5.1

**Comment by HB9HIL** [comment]
@205er Thx for reporting this bug. :)

**Comment by 205er** [comment]
*wow* that was a quick bug fix! Thanks for your help!

**Comment by HB9HIL** [comment]
have to get proofed by the others but here this works. was able to reproduce that issue :)
