### ISSUE TITLE
VUCC award worked/confirmed gives bogus values

### ISSUE THREAD

**Issue by pa8s** [magicbug/Cloudlog#2714]
**Describe the bug**
On the main page the VUCC stats gives bogus values.

I have no idea where the worked (991) and confirmed (886) values come from. The only VUCC band in my log is 6m with only 12 qsos of which 10 are confirmed. 

**To Reproduce**
n/a

**Expected behaviour**
VUCC values representing logged QSOs

**Server**
OS: FreeBSD 13.1
Server: nginx/1.24.0
PHP: 8.1.25
Git branch: dev
Commit: https://github.com/magicbug/Cloudlog/commit/694f9fbd80cb7ce28286efbc0d280e6f238f5c0a
Tag: https://github.com/magicbug/Cloudlog/releases/tag/2.5.0

**Comment by int2001** [comment]
@pa8s i think we can close this now?!

**Comment by pa8s** [comment]
Issue solved. Thank you
