### ISSUE TITLE
SQL data of the table dxcc_entities

### ISSUE THREAD

**Issue by pa2eon** [magicbug/Cloudlog#274]
Dear Peter,

In the migration to the last source of cloudlog .. I missed the content of the table dxcc_entities.
Where can I generate or download these table.
If this table is empty .. you can not make a correct station profile

vy '73 Eric / PA2EON

**Comment by pa2eon** [comment]
Found the file from github download file: logbook_2m0sql_master.zip -  database is up2date now.

**Comment by magicbug** [comment]
All SQL can be found in https://github.com/magicbug/Cloudlog/blob/master/install/assets/install.sql this is updated when changes have been made
