### ISSUE TITLE
php-fpm module hangs when import adif file doesn't terminate correctly

### ISSUE THREAD

**Issue by raufaser** [magicbug/Cloudlog#2765]
**Describe the bug**
php-fpm module hangs when import adif file doesn't terminate correctly

**To Reproduce**
Steps to reproduce the behaviour:
1. Try to import an adif file with the terminating tag "<e" instead of "<eor>

**Expected behaviour**
Error output and stop processing the file

**Screenshots**
<img width="557" alt="Screenshot 2023-12-02 133449" src="https://github.com/magicbug/Cloudlog/assets/72879802/ad57a3c3-2d6a-46ee-90fa-2b09405d6236">

**Server (please complete the following information):**
 - OS: Ubuntu 22.04
 - PHP 8.2

**Comment by raufaser** [comment]
Sure.
```
WSJT-X ADIF Export<eoh>
<call:6>AB0CDE <gridsquare:0> <mode:3>FT8 <rst_sent:3>-07 <rst_rcvd:3>-09 <qso_date:8>20231201 <time_on:6>162945 <qso_date_off:8>20231201 <time_off:6>162945 <band:3>12m <freq:9>24.917091 <station_callsign:5>ZZ0YXZ <my_gridsquare:6>JO62VM <eor>
<call:6>AC0EDC <gridsquare:4>JO22 <mode:3>FT8 <rst_sent:3>-08 <rst_rcvd:3>-05 <qso_date:8>20231202 <time_on:6>005100 <qso_date_off:8>20231202 <time_off:6>005200 <band:4>160m <freq:8>1.841946 <station_callsign:5>ZZ0YXZ <my_gridsquare:6>JO62VM <e
```

**Comment by phl0** [comment]
Fix proposed with https://github.com/magicbug/Cloudlog/pull/2774. Please close here if this fixed the issue for you as well. Otherwise please comment :) Tnx.
