### ISSUE TITLE
Advanced Logbook is empty

### ISSUE THREAD

**Issue by m0urs** [magicbug/Cloudlog#2778]
**Describe the bug**

In the current Dev build, the Advanced Logbook does no longer show any entries.

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to 'Logbook -> Advanced'
2. You see that there are no QSOs listed

**Expected behaviour**

The last 250 QSOs should be displayed.

**Screenshots**

![image](https://github.com/magicbug/Cloudlog/assets/2588362/7764727f-8df2-41c5-9170-601fef0fb97e)

In the Master build everything still works fine.

**Comment by phl0** [comment]
I cannot confirm. Could you please press CTRL + F5 and if that does not work please show the response/request after pressing the search button.

**Comment by AndreasK79** [comment]
Can't reproduce here either. Could you go to options and save, then try?

**Comment by m0urs** [comment]
Saving the options did repair it...! I only tried "Reset" before which did not change anything. Thanks a lot for your quick help!
