### ISSUE TITLE
Issue logging past QSO when pushing reset button, clock starts running 

### ISSUE THREAD

**Issue by dk5cr** [magicbug/Cloudlog#2784]
**Describe the bug**
When opening QSO -> Log past QSO (in German "zeitversetztes QSO", second entry in the menu) you can click on the clock-icon to adjust the time to the current time. When you with to cancel the entries in the fields and click on the reset-button, then the clock starts running with hh:mm:ss just like in live-logging. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to QSO -> past QSO logging
2. Click on "cancel" (left of submit) 
3. have a look at the running clock in the time box above 

**Expected behaviour**
I expect to see the clock set to the current time in hh:mm without starting running in seconds like in live logging QSO. 

**Desktop (please complete the following information):**
 - OS: Armbian on BananaPi 
 - Browser Firefox 
 - Version 2.5.2

**Comment by phl0** [comment]
Fix proposed in https://github.com/magicbug/Cloudlog/pull/2785. Please test and report.
