### ISSUE TITLE
New API key - error test button - no remove API

### ISSUE THREAD

**Issue by pa2eon** [magicbug/Cloudlog#282]
After the clear update of the cloudlog I want to add the two API key's.
Generating the key is not a problem but two other things they are;

* No delete button to remove the API-key if you want to clean the settings.
* When pushed on the 'Test' button I got the error shown in de picture below:

![image](https://user-images.githubusercontent.com/4719917/59146983-86055500-89f5-11e9-9b71-8dacf885cac5.png)

Will I missed something

vy'73 PA2EON, Eric

**Comment by magicbug** [comment]
Yes, this is a known issue and hasn't worked ever, I'll get around to fixing it, however.

**Comment by magicbug** [comment]
This has been addressed and fixed in the codebase
