### ISSUE TITLE
Always marked as "sent via bureau" when press the button "Mark requested QSLs as sent"

### ISSUE THREAD

**Issue by qiuyuair** [magicbug/Cloudlog#2822]
In "Print Requested QSLs" view, when pressing the button "mark selected QSOs as sent", QSOs will always marked as "sent via bureau"  instead of it's original value.
![image](https://github.com/magicbug/Cloudlog/assets/49612373/c83b54b6-8160-44a1-bba2-f5992a2e27bc)

**Comment by int2001** [comment]
Working on it

**Comment by int2001** [comment]
@qiuyuair should be fixed in the actual fresh 2.6-Release

**Comment by qiuyuair** [comment]
Thx! It works well now.
