### ISSUE TITLE
Datatables reinitialise error loop

### ISSUE THREAD

**Issue by petrkr** [magicbug/Cloudlog#2827]
In gridmap if you click fast enough. There will popup datatable warning, which keeping in loop there.

Tag	[2.5.1]

Server Information
Server Software	Apache/2.4.57 (Debian)
PHP Version	8.2.8
MySQL Version	10.5.21-MariaDB-0+deb11u1

![Screenshot_20231213_135358](https://github.com/magicbug/Cloudlog/assets/6428351/2522ed10-b9b0-4472-b5bd-b8e01ade57d8)

**Comment by int2001** [comment]
This one should fix it: https://github.com/magicbug/Cloudlog/pull/2836
