### ISSUE TITLE
Handle FT-4 as a submode (This actually seems to effect all data modes based on new adif spec)

### ISSUE THREAD

**Issue by magicbug** [magicbug/Cloudlog#283]
It seems now that we have yet more digital modes they are now being split into sub-modes just looked at the updated ADIF spec and FT4 should now be stored as a sub-mode of MFSK.

This means that the interface will need to be updated and also export from Cloudlog.

Importing from WSJT-X should be fine, however.

**Comment by ofadam** [comment]
Should FT4 be importing as MFSK or should it actually show as FT4? I noticed that you can select that mode manually by editing a QSO, but was hopeful I didn't need to do it for all.
