### ISSUE TITLE
Top nav dropdowns are not expanding

### ISSUE THREAD

**Issue by patrickrb** [magicbug/Cloudlog#2835]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
Dropdowns in the top nav bar do not expand/open in Edge

- just updated to version 2.6.0

**To Reproduce**
Steps to reproduce the behaviour:
1. log in
2. try to hover over any dropdown in the top nav
3. unable to open a dropdown

**Expected behaviour**
Dropdown menus should expand

**Screenshots**
![2023-12-14 16 29 04](https://github.com/magicbug/Cloudlog/assets/6586559/e9c3090f-41e5-4a09-baf5-069791a1cfc1)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser edge
 - Version  120.0.2210.61 (Official build) (arm64)

**Additional context**
I'm not seeing any warning or errors in the console.log

**Comment by HB9HIL** [comment]
Press 


on Windows: "Ctrl + F5"

or

on Mac: "Cmd + Shift + R"

as it was described in the Version Info Popup.

Alternative would be to clear the Browser Cache.

We had a libary upgrade in this release which could cause this issue.

**Comment by patrickrb** [comment]
that fixed it, thank you!
