### ISSUE TITLE
API-Key revocation

### ISSUE THREAD

**Issue by dg9vh** [magicbug/Cloudlog#286]
Adding a function at the API-Key tab to revoke a single API-Key. Actually there is no possibility to revoke/delete a key instead of deleting it via SQL in the database itself.

**Comment by magicbug** [comment]
It actually had a delete... not sure what i did :p codes there will add it back

**Comment by magicbug** [comment]
This is now implemented

**Comment by dg9vh** [comment]
Nice, tnx!
