### ISSUE TITLE
LoTW import does not update QSO records if the time does not match precisely

### ISSUE THREAD

**Issue by jstrahle** [magicbug/Cloudlog#2877]
**Describe the bug**
I noticed that some of the QSO records are not being updated even when doing manual import from LoTW (tested with both pull data and adif-import options). While doing the update, it states that a matching record was found and it is being updated:
<img width="972" alt="image" src="https://github.com/magicbug/Cloudlog/assets/15327065/91e3b933-19ca-4710-a44d-109332a260d2">

When I go and check theQSO log  record, it is not updated:
<img width="992" alt="image" src="https://github.com/magicbug/Cloudlog/assets/15327065/54bd9d7d-0392-4c06-a8b4-0ee2cce62cac">

This is the QSO information from LoTW website:
<img width="274" alt="image" src="https://github.com/magicbug/Cloudlog/assets/15327065/2050477c-1a4c-406f-b8af-7c9bf6840124">

I noticed that QSO time in my log and LoTW are having 1min difference. I tought that it might be causing the issue. I changed the entry in my log to be exactly the same as it is in LoTW. After doing this, the log entry updated when I re-run the LoTW import.

**Expected behaviour**
There should be some kind of tolerance with the QSO record time. LoTW import recognizes records to be updated, but the record is not being updated.

**Comment by phl0** [comment]
Have the QSOs been uploaded from this Cloudlog instance to LoTW?

**Comment by jstrahle** [comment]
@phl0 No, those log entries have been uploaded from different log software before I started using the Cloudlog

**Comment by phl0** [comment]
> @phl0 No, those log entries have been uploaded from different log software before I started using the Cloudlog

Could you pls show an extract of the mentioned QSO in the other logging software that was used to upload to LoTW? What times does it show?

**Comment by jstrahle** [comment]
> Could you pls show an extract of the mentioned QSO in the other logging software that was used to upload to LoTW? What times does it show?

Sure. There are actually two timestamps in Amateur Contact Log that I used before Cloudlog: Start and End. Looks like LoTW is using Start timestamp in their logs and after ADIF import, Cloudlog is only showing the End time.

<img width="1137" alt="image" src="https://github.com/magicbug/Cloudlog/assets/15327065/7249ce92-8e32-4906-ac71-885a21c28885">

**Comment by jstrahle** [comment]
I made an ADIF export from Cloudlog and manually uploaded that via LoTW website, and after that did LoTW import in Cloudlog. Now it looks better. Will close the bug report because I believe that this behavior is related to chaning from log software to another.

**Comment by phl0** [comment]
Maybe. Would you be able and willing to provide the ADIF file sonthat I can have a look on what and how its imported?
