### ISSUE TITLE
Feature-Request: QSL-Received Button beneath "Edit"-Button in Logbook-View

### ISSUE THREAD

**Issue by dg9vh** [magicbug/Cloudlog#291]
For faster paper-QSL-card recording, a button called "QSL received" with the functionality described below would be of effort:

Functionality:
When the button is clicked, set COL_QSL_RCVD = 'Y' and COL_QSLRDATE = now().

This speeds up mass-registration of received QSL-cards after a club meeting. If you want to register actually, you need to do 3 clicks after searching the callsign and identifying the qso in the list. The new button speeds up by 1/3 of time at least.

If you agree, I could try to realize it in a separate branch on a fork of your code and you can take a look at it before merging it into the master-branch.

73
Kim
DG9VH

**Comment by dg9vh** [comment]
Just made a PR for this. here on my side it's working.

**Comment by magicbug** [comment]
Thanks all, always nice when i can just merge a PR :)

**Comment by dg9vh** [comment]
I know - and with my few skills, I could bring some ideas into your vy gd project :-) So a classical win-win-situation :-)

**Comment by magicbug** [comment]
OK just had a morning with the new button, it's annoying me a bit, but not sure the best way to address it, I do wonder whether the button could be removed and the arrow for incoming QSL could be the link instead making it a bit more subtle, the same could be added for sent too

**Comment by magicbug** [comment]
Thinking further I'm wondering whether this could be a Cog icon on the logbook display than a drop down which could support more options.

**Comment by magicbug** [comment]
Made some adjustments as the PR was missing a couple of files and it didn't work, Edit/QSL Received Marking is now a dropdown cog which will allow for more features.

I need to add similar to the search

**Comment by dg9vh** [comment]
This is a much better way to do it :-) and also a speeding up at qsl-receiving :-)
