### ISSUE TITLE
Error Message in "view QSL Cards"

### ISSUE THREAD

**Issue by vbueschken** [magicbug/Cloudlog#2915]
Today I have installed Cloudlog on my hosted environment ( v2.6.2 )
PHP 8.2 

When I click on "view QSL Cards" I get following error message:

An uncaught Exception was encountered
Type: InvalidArgumentException
Message: where_in() expects $values to be a non-empty array
Filename: /www/htdocs/buesccom/cloudlog.bueschken.com/system/database/DB_query_builder.php
Line Number: 884

**Comment by magicbug** [comment]
Was this a fresh install with no Qsos present?

Message: where_in() expects $values to be a non-empty array

Suggests that no Logbook has been created with an attached Station Location

**Comment by vbueschken** [comment]
Yes..  this is a fresh install... no data.Gesendet von Outlook für Android

**Comment by magicbug** [comment]
Perfect, thanks that needs cleaned up :)

**Comment by magicbug** [comment]
Not a bug per say but visually not very nice!

**Comment by vbueschken** [comment]
I also get this Message, when I try to save a Live QSO:

A PHP Error was encountered
Severity: 8192
Message: trim(): Passing null to parameter #1 ($string) of type string is deprecated
Filename: models/Logbook_model.php
Line Number: 297

May be the same cause..?
The Record is saved - I can see it in Logbook Advanced

**Comment by magicbug** [comment]
> I also get this Message, when I try to save a Live QSO:
> 
> A PHP Error was encountered Severity: 8192 Message: trim(): Passing null to parameter #1 ($string) of type string is deprecated Filename: models/Logbook_model.php Line Number: 297
> 
> May be the same cause..? The Record is saved - I can see it in Logbook Advanced

This is unrelated i'd suggest creating a new  issue but perhaps you haven't created a station location and linked it to a Station Logbook?
