### ISSUE TITLE
FR: Clublog-Upload/Export

### ISSUE THREAD

**Issue by dg9vh** [magicbug/Cloudlog#294]
I don't know, if Clublog is providing an API for this but you also can deliver log-entries via E-mail, so it could be done with an additional field in the logbook-table that marks a log-line as "delivered to clublog" after exporting it and sending it to Clublog.

This is a "nice to have"-feature - actually the ADIF-export is working for this but one has to upload it by hand (or by email) to Clublog.

73 de Kim
DG9VH

**Comment by magicbug** [comment]
Its been on my radar for a while, Clublog is already used for the dxcc / exception information within Cloudlog. I need to look at the best way to integrate some real time qso posting, really its probably better to mark it as a task and its handled by another script

**Comment by dg9vh** [comment]
Yes, I agree - doing it automatically by logging a QSO could cause some problems when logging "by accident"... so triggering the export by the user would be the best way.

**Comment by magicbug** [comment]
Okay, think the best way to do this create a controller called **clublog** then  process

- sync - which sends qsos to Clublog and also downloads from clublog which marks the COL_CLUBLOG_QSO_UPLOAD_DATE and COL_CLUBLOG_QSO_UPLOAD_STATUS fields

then use the config file to store the information Cloudlog needs to talk with Clublog.

Thoughts? @dg9vh @Manawyrm

**Comment by dg9vh** [comment]
What exactly you would fetch from clublog? Syncing up to clublog ok in this way, but what to sync downwards? Syncing-results like changes of DXCC or similar?

**Comment by magicbug** [comment]
Okay so I have added a new controller with a function `clublog/upload/<username>` if you have added your Clublog details to your user profile and provide the username with your username you can then upload to Clublog it will then mark the QSOs as sent.

**Comment by dg9vh** [comment]
When calling the URL with my callsign as registered as callsign at clublog, I get following message without nothing else:

Nothing awaiting upload to clublog

**Comment by magicbug** [comment]
Yes seems issue with anything beyond my local machine!

**Comment by dg9vh** [comment]
ok, seems correct:
waiting a few minutes and calling again:
Club Log has already processed this exact file in the past (checksum duplicate)
A PHP Error was encountered
Severity: Warning

Message: strpos() expects parameter 1 to be string, resource given

Filename: controllers/Clublog.php

Line Number: 72

QSOs uploaded and Logbook QSOs marked as sent to Clublog

Only thing now: Warning :-)

**Comment by magicbug** [comment]
Okay, just committed code thats working locally for me, however its not working on production not even getting a warning

**Comment by magicbug** [comment]
Think i found it oops

**Comment by dg9vh** [comment]
ok, waiting for new code :-)

**Comment by dg9vh** [comment]
With actual code getting following:
2.2 Cloudlog Version 1.7 
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /home/huebelon/public_html/dg9vh.de/cloudlog/system/database/drivers/mysqli/mysqli_result.php on line 237

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 32768 bytes) in /home/huebelon/public_html/dg9vh.de/cloudlog/system/core/Exceptions.php on line 1

**Comment by magicbug** [comment]
OK, stupid me error, forgot to add the directory array from the config.php to the clublog stuff so it was looking for files in the wrong place ... I know idiot.

**Comment by magicbug** [comment]
Only thing not fixed now is marking QSOs as sent to clublog

**Comment by dg9vh** [comment]
![Clublog](https://user-images.githubusercontent.com/13950650/59786733-39106100-92c8-11e9-990c-32a79de74956.png)

Seems to work now :-)

**Comment by magicbug** [comment]
Just need to fix marking QSOs as sent to Clublog then I'll be happy.
Hopefully have some time tomorrow evening!

**Comment by magicbug** [comment]
Should be resolved now with any luck, mine are going up ok

**Comment by dg9vh** [comment]
It's working after "clear log" at clublog.org... otherwise we simply get an "Error"-Message...

Maybe something, that should be documented later in the wiki?

**Comment by magicbug** [comment]
Error message will now display what clublog returns.
