### ISSUE TITLE
selected mode disapears in ui if trx data is set by using the radio api 

### ISSUE THREAD

**Issue by peacekiller** [magicbug/Cloudlog#2942]
Hi there, first let me thank you for this wonderful logbook software. I love it!

I have a small problem and I'm not sure if there is a bug or a failure on my side. I use a simple self written python script to read the TRX informations like frequency, mode, name,power etc. from a flrig xmlrpc server and send them to cloudlog  using the radio api.

This works very well but there is a problem with the modes field. The value I get from the tranceiver (flrig) when I'm doing digi modes is something returned like 'DATA-U' or 'RTTY-U'. This is fine because my trx down't know things like FT-8, PSK, FT4 etc.

But when I send the value to cloudlog, the mode checkbox in the ui is empty. This is also ok for me, but when I manually choose the mode in the ui, the selection disappears after some seconds.

This happens indifferent which value I give to the API. I tried something like "DATA", "", None. 

Should I have to use a 'magic value' for mode to prevent this behaviour?

This is my script:
```python
import xmlrpc.client
import datetime
import requests

flrigServerUrl = "http://localhost:12345/"
cloudlogUrl = "https://my-cloudlog-instance.com"

flrigClient = xmlrpc.client.ServerProxy(flrigServerUrl)
trxname = flrigClient.rig.get_xcvr()
powerWatts = flrigClient.rig.get_power()
vfoHz = flrigClient.rig.get_vfo()
mode = flrigClient.rig.get_mode()
timestamp = datetime.datetime.now().strftime("%Y/%m/%d %H:%M")

r = requests.post(cloudlogUrl + '/api/radio', json={
    "key": "my-api-key",
    "radio": trxname,
    "frequency": str(vfoHz),
    "power": str(powerWatts),
    "mode": mode, # 'DATA', '', None
    "timestamp": timestamp
})
print(r.status_code)
```

**Comment by magicbug** [comment]
Correct DATA-U isn't a mode you'd need to send it USB/LSB
