### ISSUE TITLE
Gridsquare Map default view shows all QSLs as confirmed

### ISSUE THREAD

**Issue by stevendodd** [magicbug/Cloudlog#2948]
Need to manually select confirmation checkboxes and click plot

<img width="885" alt="Screenshot 2024-01-31 at 09 43 30" src="https://github.com/magicbug/Cloudlog/assets/8025323/0b05bc7b-8099-4c44-a69d-4450f6a9a812">

<img width="885" alt="Screenshot 2024-01-31 at 09 43 15" src="https://github.com/magicbug/Cloudlog/assets/8025323/02bdbac9-ffbe-4f96-a37d-4e0530094228">

**Comment by phl0** [comment]
Also check settings in your profile for default QSL methods:

![image](https://github.com/magicbug/Cloudlog/assets/7112907/49e58e0f-763b-4f5a-af7d-a9eff676e63c)

**Comment by stevendodd** [comment]
@phl0 works great thanks

**Comment by magicbug** [comment]
Merged into dev so marking as resolved unless someone shouts at me
