### ISSUE TITLE
Public view gridsquares link shows empty map

### ISSUE THREAD

**Issue by stevendodd** [magicbug/Cloudlog#2949]
Clicking the link goes to the following URL which shows an empty map: https://stevendodd.ddns.net/cloudlog/index.php/visitor/satellites/M0SNZ

<img width="885" alt="Screenshot 2024-01-31 at 09 48 25" src="https://github.com/magicbug/Cloudlog/assets/8025323/8cf39394-28d0-4b92-86c4-4557f446272f">

**Comment by phl0** [comment]
Fix proposed in https://github.com/magicbug/Cloudlog/pull/2950.

**Comment by stevendodd** [comment]
@phl0 I've manually tested this fix and it doesn't work

**Comment by stevendodd** [comment]
@phl0 sorry my mistake it does work, should it be showing only satellites though?

**Comment by stevendodd** [comment]
It also shows all as unconfirmed; perhaps a similar problem as https://github.com/magicbug/Cloudlog/issues/2948#issue-2109687414

**Comment by phl0** [comment]
> @phl0 sorry my mistake it does work, should it be showing only satellites though?

Yepp as it says in the menu header.

**Comment by stevendodd** [comment]
What I meant is why only satellites - the link on the public page says grid squares not satellite grid squares? Is there any configuration that allows you to show all work to get squares regardless of type.

The map is not empty but now it shows all as unconfirmed.

<img width="885" alt="Screenshot 2024-01-31 at 11 47 14" src="https://github.com/magicbug/Cloudlog/assets/8025323/f5cc8633-32f2-461e-b2f8-9c2b4d764989">

**Comment by magicbug** [comment]
Its satellite grids as thats what i wanted at the time, ideally needs the interface from the login side so it can be filtered but hasn't got that far but its not a bug.
