### ISSUE TITLE
A PHP Error was encountered, Awards - CQ Magazine WAZ

### ISSUE THREAD

**Issue by n5hc** [magicbug/Cloudlog#2970]
PHP Error was encountered**
Severity: Notice
Message: Undefined offset: 45
Filename: models/Cq.php
Line Number: 56

**A PHP Error was encountered**
Severity: Notice
Message: Undefined index: count
Filename: models/Cq.php
Line Number: 56

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on 'Awards'
2. Click on 'CQ'

**Screenshots**
![Normal](https://github.com/magicbug/Cloudlog/assets/8440347/a1cd6276-7b21-467a-a416-7530a16f3417)
![Normal](https://github.com/magicbug/Cloudlog/assets/8440347/e3d25775-522b-4619-add9-a3a1e021b3dc)
![Error](https://github.com/magicbug/Cloudlog/assets/8440347/60474a3e-fa26-49c7-868a-b10239772a99)

**Desktop (please complete the following information):**
 - OS: [macOS 14.3.1 (23D60)]
 - Browser [safari ]
 - Version [17.3.1 (19617.2.4.11.12)]

**Comment by n5hc** [comment]
Basically the ITU and CQ is swapped for JH5FTY (and a few other JA's) in QRZ.COM.

ITU should be 45
CQ should be 25

Perhaps some more validation?

**Comment by phl0** [comment]
Fix proposed in https://github.com/magicbug/Cloudlog/pull/2971.
