### ISSUE TITLE
In search results, gear icon menus aren't working anymore after editing a qso

### ISSUE THREAD

**Issue by raufaser** [magicbug/Cloudlog#2973]
After editing one qso via search results screen, editing another qso is not possible, because the gear icon menus aren't opening anymore.

Steps to reproduce the behaviour:
1. Perform a search which results in multiple qsos
2. Click on the gear icon of one qso and on 'edit qso'
3. do the edit and 'save changes'
4. back to the results screen the gear icon menus aren't working anymore

**Expected behaviour**
When returning to the result screen the page refreshes and the gear icon menus work.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Thorium (Chrome fork) in Incognito mode
 - Version: 111.0.5563.111

**Comment by magicbug** [comment]
Thanks for reporting this is now resolved
