### ISSUE TITLE
Cloudlog Cat no frequency

### ISSUE THREAD

**Issue by Duffischer** [magicbug/Cloudlog#2974]
**Describe the bug**
I tried using Cloudlog Cat with my Icom IC7300. Cloudlog Cat shows the rig as online and also has the right mode. When I change the mode the mode is also changed in Cloudlog Cat. But no frequency is shown in Cloudlog Cat.

**To Reproduce**
1. Connect IC7300
2. Start Cloudlog Cat

**Expected behaviour**
I would expect the frequency to be updated as well as the mode.

**Screenshots**
![Screenshot of Cloudlog Cat settings](https://github.com/magicbug/Cloudlog/assets/109034446/95a542af-97b2-4b7e-9d0d-e6ed7ade09a7)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Chrome
 - Version Cloudlog Cat 1.3.0.0

**Additional context**
Due to the fact that the mode is working I'm assuming that the missing frequency is an issue with the Cloudlog Cat and not the settings but please correct me if I'm wrong and just missed some setting.

**Comment by magicbug** [comment]
Reinstall with https://github.com/magicbug/CloudlogCAT/releases/download/1.8/CloudlogCAT.Test.Release.ICOM.zip and it should resolve it

**Comment by Duffischer** [comment]
> Reinstall with https://github.com/magicbug/CloudlogCAT/releases/download/1.8/CloudlogCAT.Test.Release.ICOM.zip and it should resolve it

Yep, frequency is now showing in the Cloudlog Cat but now the sync to my Cloudlog isn't working anymore. I added the URL and the API key, but it doesn't sync.

**Comment by Duffischer** [comment]
@magicbug Do you have any update for me on this issue?

**Comment by Reset4350** [comment]
Hi -- I just installed v1.8 today and having the same issue. I now have the frequency from my 7300, but getting, "Cloudlog Synced: Failed". I see packets flowing between the client and the server, but the client does not seem to be happy. :)

![image](https://github.com/user-attachments/assets/2b91d755-39cc-4a08-a56d-be3bb966f696)

![image](https://github.com/user-attachments/assets/ab394d89-00f7-4d39-ab2e-4ae29b5ad666)

**Comment by Reset4350** [comment]
Just to follow up on my experience, I dug around the interwebs and found if I use the following URL/ API for CloudLog things start working. The URL/API used is not what shows up in Cloudlog to copy and paste into the app using the API key: 

![image](https://github.com/user-attachments/assets/f02e2442-bc8b-48b6-9cbc-12a9406c2eef)

**Comment by Duffischer** [comment]
@Reset4350 
I in fact found out that a new version was released at some point which did work with my Icom and the sync was working as well. 

Just tried to look up the exact version but sadly the info page in the cloudlog cat shows just 1.0.0.0.
I did also clear my downloads folder recently so I was not able to retrieve the version number from there. 

Did you download the newest version from the Cat project?

**Comment by Reset4350** [comment]
I downloaded this version of CloudLog Cat and it cured the frequency issue with the 7300. It shows as version 1.8. I don't think that the changes in 1.8 have been incorporated in the latest stable release of CloudLog Cat: https://github.com/magicbug/CloudlogCAT/releases/download/1.8/CloudlogCAT.Test.Release.ICOM.zip
