### ISSUE TITLE
Error in RX_PWR value in ADIF does not throw error in ADIF import

### ISSUE THREAD

**Issue by Reid-n0rc** [magicbug/Cloudlog#2983]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
I had an ADIF file with several invalid values for the RX_PWR field in the ADIF file. I had entered the cut number in the ARRL DX CW contest so the field ended up with values like `KW` and `1TT` instead of `1000` and `100`. This resulted in an error and the QSOs not being added to Cloudlog. When the import was complete, the `Yay, its imported!` message was shown with no errors. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'ADIF Import/Export'
2. click on 'Choose File.' Select a ADIF file with invalid values in the `RX_PWR` field.
3. Click on 'Upload'
4. See no error message after `Yay, its imported!`
5. Check the log for imported QSOs
6. See imported QSOs are not in the log.

**Expected behaviour**
When the ADIF file has an error that prevents the qso from being imported, there should be an error shown in the upload result.

**Comment by magicbug** [comment]
Oh, yes definitely need to put a filter on those as RX_PWR fields in ADIF are number only.. what apps putting that into those fields as that's incorrect

**Comment by Reid-n0rc** [comment]
@magicbug I exported from N1MM

**Comment by magicbug** [comment]
@Reid-n0rc could you drop me the file via email or on here be good to test against

**Comment by Reid-n0rc** [comment]
Here ya go @magicbug 

[N0RC.adi.txt](https://github.com/magicbug/Cloudlog/files/14364408/N0RC.adi.txt)

**Comment by magicbug** [comment]
Now throws an error with the reason and sets the field to null so it can import regardless

![RX_PWR Error](https://github.com/magicbug/Cloudlog/assets/84308/f44c78be-bcec-4995-9689-970aed6671ca)

Hopefuly @Reid-n0rc this fixes your problem

**Comment by Reid-n0rc** [comment]
Thank you @magicbug , you're the best!
