### ISSUE TITLE
Logbook overview - edit QSO menu is cutoff

### ISSUE THREAD

**Issue by LarsThunberg** [magicbug/Cloudlog#2996]
When edit a QSO in "Logbook" -> "Overview", the menu is cutoff. Best shown in the image below (in the red marked area):
Note! If you click the menu one more time, the full menu text is shown.

**Expected behaviour**
Would it be possible to show the complete menu in this case, after the first click?

**Screenshots**
![image](https://github.com/magicbug/Cloudlog/assets/35871385/6884ecc3-9bf2-4fcd-a677-a1f6774eb45a)

**Desktop (please complete the following information):**
 - Windows 11
 - Chrome latest version

**Comment by magicbug** [comment]
Can you confirm which theme you have selected in your account settings

**Comment by LarsThunberg** [comment]
It is the default team and the version of Cloudlog is 2.6.6

**Comment by LarsThunberg** [comment]
Hmmmm.  I updated to 2.6.6 yesterday and now I can not see the original problem anymore:

![image](https://github.com/magicbug/Cloudlog/assets/35871385/5b9c7ce2-31f9-4a8e-b0b5-0d6645d62087)

**Comment by magicbug** [comment]
Quite possible that it was a caching issue don't think I've touched any code in that area
