### ISSUE TITLE
DXPeditions Cut off calls with `/`

### ISSUE THREAD

**Issue by Reid-n0rc** [magicbug/Cloudlog#2999]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
In Cloudlog ver 2.6.6, the links in the DXPeditions table are cutting off calls wtih `/` in them. For example `J3/DB4BJ` is just showing `J3`. Also the link to DXHeat just goes to the callsign `J3` and not `J3/DB4BJ`

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the main log page
2. Look at `DXPeditions (This Week)`

**Expected behaviour**
Should be a link showing the text of the full callsign and the link should lead to the DXHeat page for the full callsign.

**Screenshots**
![Screenshot showing the error in the DXPeditions table](https://github.com/magicbug/Cloudlog/assets/468300/7ab647b0-043d-4f8b-9fa0-28afda66b376)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome 
 - Version 122.0.6261.111
 -

**Comment by magicbug** [comment]
Its not being cut off, its due to the fact where the data is collected from they didn't provide the callsign in the relevant field, only the comment section. Hence why its displayed as it is.
