### ISSUE TITLE
Missing POTA-Field for own POTA-Reference in Cloudlog (COL_MY_POTA_REF)

### ISSUE THREAD

**Issue by dk5cr** [magicbug/Cloudlog#3007]
For POTA Park2Park-activities it's necessary to have to own POTA-Ref and the POTA-Ref of my QSO-partner. 

**Describe the bug**
In the database there are the columns COL_POTA_REF and COL_MY_POTA_REF. Unfortunately there's no field to type in my own MY_POTA_REF. With CloudLogOffline-app - currently not available! - the field is enabled and visible.

**To Reproduce**
See Add QSO in Stylesheet "default" and try to find the field to enter your own POTA Ref. 
There's only the POTA-field for my QSO-partner

**Desktop (please complete the following information):**
 - OS: LINUX on raspberry 
 - Browser: FireFox 
 - Version 123.0.1

**Comment by dk5cr** [comment]
Thanks for reply. I actually found the POTA field, but NOT the MY_POTA-Field. 
When doing POTA out of a park and having a QSO with another POTA-activator, then you have to fill in two reference numbers for making clear to have a park-to-park-activation. 
In the database there is the field already (COL_MY_POTA_REF) but not in the qso/index-file when adding a new QSO.

**Comment by magicbug** [comment]
MY fields in the hrd_ table are completely ignored.. although the fields are there its a legacy item.

**Comment by dk5cr** [comment]
Okay, thanks for information. 
But please: 
Where can i put in MY POTA-Reference-number when i do POTA with another POTA-park?

**Comment by phl0** [comment]
> Okay, thanks for information. But please: Where can i put in MY POTA-Reference-number when i do POTA with another POTA-park?

See my post above. Your reference as activator goes into the POTA field in the station location you are using.

**Comment by dk5cr** [comment]
so this means that i have to create a station location for every park, i'd like to activate?! 
Hmmm.... Not a very lucky situation. 

Btw: Please tell me, where the code for storing the formfields in the database is located?! tnx

**Comment by phl0** [comment]
It is stored in the station_profile table.

**Comment by dk5cr** [comment]
i meant: in which file is the code with the specific SQL-Commands or so, to communicate with the database and so on... ?
