### ISSUE TITLE
Feature Request: Add support for saving SSTV images in a QSO

### ISSUE THREAD

**Issue by patrickrb** [magicbug/Cloudlog#3016]
### Problem / Feature
- We should have the ability to save SSTV images that were part of a QSO
- I'd love to dive into working on this feature.  Wanted to post it here publicly since I'm new to the project and any feedback or guidance on best practices for this project would be appreciated.

### User Stories 
- Users should have an easy way to upload images from the live/post QSO pages
- Users should be able to view the associated images when viewing a logged SSTV QSO

I'll start a branch associated with this feature request/issue and keep this issue open to track progress.

**Comment by patrickrb** [comment]
I'm going to start by looking at how EQSL cards are saved/loaded in this project and probably use that as s start for how I store the SSTV images.

**Comment by phl0** [comment]
> I'm going to start by looking at how EQSL cards are saved/loaded in this project and probably use that as s start for how I store the SSTV images.

Better look at the QSL managements for (scans) of paper cards. eQSL images cannot be uploaded manually.

**Comment by magicbug** [comment]
Yep seems best place, I'm wondering if it makes sense to have an "Additional Material" so that you can upload any file against a QSO so whether that's audio or an image that might better suit this overall task

**Comment by patrickrb** [comment]
was able to get quite a bit of work done on this feature today.  all the writes are working, both the image data to a new directory `assets/sstvimages` and a new table `sstv_images`

![image](https://github.com/magicbug/Cloudlog/assets/6586559/0a229326-114f-4b12-9a1f-05e2c64f66ec)

I just need to work on showing the images that have been uploaded/saved, hoping to have it wrapped up for PR in the next week or so!

**Comment by patrickrb** [comment]
> Yep seems best place, I'm wondering if it makes sense to have an "Additional Material" so that you can upload any file against a QSO so whether that's audio or an image that might better suit this overall task

I went ahead and started adding this specifically for SSTV, my plan is to only show the SSTV Management tab if the QSO mode is `SSTV` 

That said, I'd be happy to adjust my current PR for 'additional material', or even make another feature PR for audioQSL/additional material.

@magicbug let me know how youd like me to proceed.
