### ISSUE TITLE
Lotw synchronization issue

### ISSUE THREAD

**Issue by vitalijsl** [magicbug/Cloudlog#3029]
I have set up Lotw connection in Cloudlog and no errors are shown either in "Logbook of the Worl" page or in Cloudlog's "Debug information" page:
![Screenshot of "Logbook of the World" section in Cloudlog](https://github.com/magicbug/Cloudlog/assets/52464180/5f9bd882-a47d-4e84-b4b9-0dfaccf44d55)

When pressing "Manual Sync", nothing happens. Even no error or info message.

After enabling logging, I see the following output whenever manual sync is initialized:
ERROR - 2024-03-25 17:49:20 --> Severity: Error --> Maximum execution time of 30 seconds exceeded /var/www/html/application/controllers/Lotw.php 965

I must mention that I have uploaded into Cloudlog quite a big ADIF file of >6000 entries. May it be the reason why the process times out?
If so, how to resolve?

**Comment by magicbug** [comment]
You will need to increase the maximum execution time so that its more than 30seconds

This is the max_execution_time in the php.ini settings on the server.

**Comment by f4cib** [comment]
Same issue there after recovering whole LoTW QSO from ADIF. Most QSO are not flag as LoTW sent so I assume the script needs a looong time to execute. (>40k QSO)
After modifying php.ini execution to 300, and even larger looks like it still takes into account the 30s.
Was able to get a verbose by typing whole adress on my explorer
i.e. : https://my_cloudlog_adress.com/index.php/lotw/lotw_upload
Fatal error/var/www/html/my_cloudlog_adress.com/public_html/application/controllers/Lotw.php960
A PHP Error was encountered
Severity: Error

Message: Maximum execution time of 30 seconds exceeded
Filename: controllers/Lotw.php
Line Number: 960
