### ISSUE TITLE
Message: Undefined array key "qso_date" 

### ISSUE THREAD

**Issue by PartTimeLegend** [magicbug/Cloudlog#3036]
**Describe the bug**
When importing my ADIF log file via the web interface I get this error.

```
A PHP Error was encountered
Severity: Warning

Message: Undefined array key "qso_date"

Filename: models/Logbook_model.php

Line Number: 3192

A PHP Error was encountered
Severity: Warning

Message: Undefined array key "qso_date"

Filename: models/Logbook_model.php

Line Number: 3203

A PHP Error was encountered
Severity: Warning

Message: Undefined array key "qso_date"

Filename: models/Logbook_model.php

Line Number: 3192

A PHP Error was encountered
Severity: Warning

Message: Undefined array key "qso_date"

Filename: models/Logbook_model.php

Line Number: 3203

A PHP Error was encountered
Severity: Warning

Message: Undefined array key "qso_date"

Filename: models/Logbook_model.php

Line Number: 3192

A PHP Error was encountered
Severity: Warning

Message: Undefined array key "qso_date"

Filename: models/Logbook_model.php

Line Number: 3203
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to index.php/adif and select to import log file (attached). Don't select any of the checkboxes on the screen.
2. Click on Upload.
3. Scroll up to the top of the screen where you will see the above errors.

**Expected behaviour**
Not throw exceptions.

**Screenshots**
![image](https://github.com/magicbug/Cloudlog/assets/791578/0b37ec30-d80c-479f-88b8-95dc7d31154b)

**Desktop (please complete the following information):**
 - OS: MacOS 14.4 Sonoma
 - Browser: Google Chrome
 - Version 123.0.6312.59 (arm64)

**Additional context**
*Webserver*
- OS: CentOS
- Webserver: Apache
- PHP Version: 8.0

[m7fgz.381236.20240328131509.adi.txt](https://github.com/magicbug/Cloudlog/files/14790301/m7fgz.381236.20240328131509.adi.txt)

**Comment by magicbug** [comment]
I'm a bit short of time to find the perminant fix as its CQ WPX Contest coming up this weekend but it looks like its todo with the following QSOS

Error QSO: IZ5WSR QSO_Date is Missing?

Error QSO: PD2GCM QSO_Date is Missing?

Error QSO: UX0FY QSO_Date is Missing?

I've had a quick glance and the qso_date is present so will need to dig into this a bit more after the weekend to see what the problem actually is.

**Comment by magicbug** [comment]
I believe the issue for each of these QSOS is the qsl_via field in each record seem to be incorrect but might be wrong

**Comment by magicbug** [comment]
I can confirm the issue is with the qsl_via  tags for those 3 QSOs the output from QRZ Logbook is incorrect saying the strings are longer than they are and thus giving malformed ADIF records it looks like QRZ Logbook isn't handling unicode properly.

See below for the ADIF with the offending issues removed.

[fixed_adif.txt](https://github.com/magicbug/Cloudlog/files/14790685/fixed_adif.txt)

I'll add some code into Cloudlog to hopefully catch this
