### ISSUE TITLE
[Wiki] [Looking For Help] Wiki needs content

### ISSUE THREAD

**Issue by magicbug** [magicbug/Cloudlog#305]
Hi All,

You all probably are aware of Cloudlog Wiki and some parts of it are better than others, I've been doing my best to add content as I've been making changes but it needs some work.

You can see it here [https://github.com/magicbug/Cloudlog/wiki](https://github.com/magicbug/Cloudlog/wiki)

That said if anyone fancies adding some content feel free, also if there's anything in the structure that you think needs changed.

Peter.

**Comment by pa2eon** [comment]
Hi Peter,

To add items in the Wiki I will help.
Nice to do =;)

vy'73 PA2EON
