### ISSUE TITLE
Feature request - Backup to cloud

### ISSUE THREAD

**Issue by patrickrb** [magicbug/Cloudlog#3051]
# Feature Request: Database Backup to Cloud Storage
Objective: To develop an easy-to-use backup solution that enables server admins to securely save their entire database to a choice of cloud storage services.

### Cloud Storage Options:

- Enable backup to various cloud platforms to offer flexibility. Initial support should include:
  - Azure Blob Storage
  - Amazon Web Services (AWS) S3
  - Dropbox
  - Google Drive
  - Google Cloud Storage

- Add options in the admin section for server admins to:
  - Choose their cloud storage service.
  - Set up access and permissions.
  - Schedule automatic backups.
  - Make sure these settings are straightforward to find and adjust.
- Automated Backup Process:
  - Use a cron job to handle the backup at scheduled times automatically, creating and uploading the backup files to the chosen cloud service.

## Backup Contents and Format:

- The backup should include:
  - SQL database dumps.
  - All related images, including EQSL, QSL, and SSTV.
  - Pack everything into a .tar.gz file to save space while keeping the data safe.
Security Measures:

- Ensure the backup process is secure, encrypting files and safely transferring them to the cloud service.

## Additional Considerations:

- Think about whether to use full or incremental backups, based on database size and update frequency, to be more efficient.
- Look into setting up notifications for the admin about the backup status.
- Explore adding an option in the admin section for manual backup operations and restorations.

**Comment by pd5wl** [comment]
My be Add (S)FTP as well for those lucky enough to run there own systems (Sorry, comes with the job. Hi)

**Comment by magicbug** [comment]
This really is a server function and not something Cloudlog needs to handle, there is plenty scripts available for backing up files to the cloud
