### ISSUE TITLE
Post QSO not working correctly

### ISSUE THREAD

**Issue by ok1cdj** [magicbug/Cloudlog#3052]
Post QSO not working correctly when you not worked station before.
When you have callsing in log from previous time all is working.
When you trying to log a new station, the icon of QRZ is not shown and the data like DXCC continent are not populated.
You are not able to save QSO.  You need manualy select DXCC and then you able to save.
![Screenshot (11)](https://github.com/magicbug/Cloudlog/assets/672504/a7b67456-4355-4dfc-b8e3-23483056f432)

**Comment by magicbug** [comment]
Weird, not seeing such a problem, have you tried recently to update the country files and its failed? if not i'd try that first

**Comment by ok1cdj** [comment]
Yes, tried update country files with success.
It is happened only when SAT is selected.

INFO - 2024-04-04 10:47:16 --> Model "Logbook_model" initialized
INFO - 2024-04-04 10:47:16 --> Model "Logbooks_model" initialized
ERROR - 2024-04-04 10:47:16 --> Query error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 - Invalid query: select name, cqz, lat, 'long' from dxcc_entities where adif = 
ERROR - 2024-04-04 10:47:16 --> Severity: error --> Exception: Call to a member function result() on bool /var/www/hosts/log.sv0syh.eu/application/models/Logbook_model.php 4270
INFO - 2024-04-04 10:47:16 --> Session: Class initialized using 'files' driver.

**Comment by magicbug** [comment]
I'm hopeful this has now been fixed
