### ISSUE TITLE
PHP errors if SSTV dir does not exist

### ISSUE THREAD

**Issue by phl0** [magicbug/Cloudlog#3062]
PHP throws errors if the SSTV images directory does not exist and the user calls the view SSTV images menu item:

![Screenshot from 2024-04-07 08-51-43](https://github.com/magicbug/Cloudlog/assets/7112907/285356ec-38cf-40b5-af0b-912e8bb1f561)

![Screenshot from 2024-04-07 08-53-43](https://github.com/magicbug/Cloudlog/assets/7112907/a52e9ebd-b630-4e41-9f3b-345cb011d2cc)

Maybe the dir should be created automagically on the first call.

**Comment by patrickrb** [comment]
got a fix for this locally, trying to track down the issue with sstvimages directory not being added to the repo

**Comment by phl0** [comment]
Fixed by https://github.com/magicbug/Cloudlog/pull/3063.
