### ISSUE TITLE
Advanced Search result in 500 internal error

### ISSUE THREAD

**Issue by wafer-li** [magicbug/Cloudlog#3070]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
/search/run_query return 500 internal error, but other search approach results good.

It does not seem to a DB issue, much like the php logic code error.

Because when run the query, it does provide at least one result in the response, but the HTTP Code is 500 and no result output to the page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://<your.domain.com>/search/filter'
2. Click on 'Run query or Search' with any rules that will provide non-empty result

**Expected behaviour**
It should show the result correctly.

**Screenshots**
<img width="1698" alt="image" src="https://github.com/magicbug/Cloudlog/assets/12459199/fc84b0d8-2f32-4970-8497-e44e4ff4c85c">
<img width="670" alt="image" src="https://github.com/magicbug/Cloudlog/assets/12459199/9edccbbe-c036-45fe-abb2-e67c88f26e71">
<img width="881" alt="image" src="https://github.com/magicbug/Cloudlog/assets/12459199/fc71fd21-4728-457c-abdd-629439f6246d">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome 
 - Version 123.0.6312.107

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wafer-li** [comment]
<img width="1403" alt="image" src="https://github.com/magicbug/Cloudlog/assets/12459199/a0844c4b-8b54-4579-8b3b-b9191d6e4eae">

**Comment by wafer-li** [comment]
@magicbug 

Do you need more precise info about it?

I currently enable error threshold in 1.

I could increase this number if you need more information.

**Comment by magicbug** [comment]
Nope! I've added a commit to the dev branch https://github.com/magicbug/Cloudlog/commit/dc5dd227665bc52910a82bed794b6457b48b830c that should hopefully solve it

If your able to download the dev branch and use that

**Comment by wafer-li** [comment]
<img width="1601" alt="image" src="https://github.com/magicbug/Cloudlog/assets/12459199/388d7ce4-86d8-4182-a321-895980eabbe9">
Still same error

**Comment by magicbug** [comment]
Ok that suggests the library isn't being called made another change but I'm not certain it will resolve it

**Comment by wafer-li** [comment]
> Ok that suggests the library isn't being called made another change but I'm not certain it will resolve it

Nevertheless, I will try it to provide more info for you.

**Comment by wafer-li** [comment]
<img width="1617" alt="image" src="https://github.com/magicbug/Cloudlog/assets/12459199/0599b64f-f3d4-48ad-9149-9e40376f211c">
Still same error

I feels like, it might be related to the `$ci` not defined?

Cause an undefined variable's member will be null, like the `frequency`

**Comment by magicbug** [comment]
lower case ci instead of upper commit made

**Comment by wafer-li** [comment]
<img width="1617" alt="image" src="https://github.com/magicbug/Cloudlog/assets/12459199/0599b64f-f3d4-48ad-9149-9e40376f211c">
Still same error

I feels like, it might be related to the `$ci` not defined?

Cause a undefined variable's member will be null

> <img alt="image" width="1617" src="https://private-user-images.githubusercontent.com/12459199/321314956-0599b64f-f3d4-48ad-9149-9e40376f211c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NjYyMTksIm5iZiI6MTcxMjc2NTkxOSwicGF0aCI6Ii8xMjQ1OTE5OS8zMjEzMTQ5NTYtMDU5OWI2NGYtZjNkNC00OGFkLTkxNDktOWU0MDM3NmYyMTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE2MTgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyOTY1NTFmNDhiZmVhZTMwZGY5YWI1NDZhNzcyOTA4YjM4ZDU0ZDExOWViNTlhNjhiZTExODUzNjQ1NDA2YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FknEwMSW2tCEERg1LWJooJv82lTXabKBQnykrbLh7M8"> Still same error
> I feels like, it might be related to the `$ci` not defined?
> 
> Cause an undefined variable's member will be null, like the `frequency`

@magicbug 

The log shows that the exception accur at L134.

Therefore, the approach f46b550 of the `$CI` **works** and actually fix this issue, but partially.

**Comment by magicbug** [comment]
I've changed it to $CI so hopefully this might actually resolve it..

**Comment by wafer-li** [comment]
> I've changed it to $CI so hopefully this might actually resolve it.

Yes!

I confirmed that the commit 04ba3e7 actually fixed the issue, entirely.

I did a query which will provide all my QSOs, and it turns out good.

**Comment by magicbug** [comment]
Woohoo!
