### ISSUE TITLE
Feature Request: WAB Processing

### ISSUE THREAD

**Issue by aaggiiss** [magicbug/Cloudlog#3079]
Hi,

Just getting back on again after many years off and I have not found a good way to keep track of WAB workings etc.  Would it be possible to add something in like you have done for other squares and counties ?

Thanks

Stuart
G7JYF

**Comment by magicbug** [comment]
Hi Stuart,

The answer is yes it would just need the code written to draw the wab squares which I don't have handy at the moment but once we have that it would be fairly straightforward.

Peter

**Comment by magicbug** [comment]
@aaggiiss looked into this a little more and found a kml file with WAB squares I need to check how it functions before over committing but this feature does seem viable at least on first glance.

**Comment by aaggiiss** [comment]
Great thank you :-)

**Comment by magicbug** [comment]
![example map showing wab squares](https://github.com/magicbug/Cloudlog/assets/84308/feba8abd-dea0-4839-8a7a-dcf41f9f851f)

Its starting to come together each square is clickable to have the table appear and it can highlight grids

Best way to handle the data will be using the SIG field so SIG name will be WAB and the sig info will be the square eg SP50

![image](https://github.com/magicbug/Cloudlog/assets/84308/b8201146-36ee-498e-b63f-0c3cbf782c1d)

**Comment by magicbug** [comment]
Now implimented fully in the dev branch under Awards -> Worked All Britain
