### ISSUE TITLE
Show warning if selected radio CAT data is X minutes old

### ISSUE THREAD

**Issue by magicbug** [magicbug/Cloudlog#310]
I'm proposing we add a warning on the QSO page if the selected radios data is older than X minutes to catch any potential issues.

**Comment by dg9vh** [comment]
Good idea but what interval are you thinking about? Consider someone's calling CQ or you're having a CW-QSO on 40m, then I would see 30 minutes as a value we can use... or - yeah, new option in cloudlog.php - we make it configurable in the custom-config :-) So everyone using CAT can decide, what interval would be best for his use-cases... good idea?

**Comment by magicbug** [comment]
I've started this by adding the option to config/cloudlog.php to default to 5minutes (https://github.com/magicbug/Cloudlog/commit/66455193a8f03e5efc03487ad480454786a898a2) I'll be adding the code to display the message tomorrow.

**Comment by dg9vh** [comment]
@magicbug how far is this going on? Is it transported to master or still in development?

**Comment by magicbug** [comment]
Barely started if I'm honest keeps getting knocked down my list

**Comment by dg9vh** [comment]
Hihi, no problem...

**Comment by magicbug** [comment]
![2m0sql](https://user-images.githubusercontent.com/84308/81747194-8d539f00-949f-11ea-897d-df7fd978027e.PNG)

Started working on this today :)

**Comment by magicbug** [comment]
This is now implemented and functioning
