### ISSUE TITLE
When LoTW is Down no message when manual sync is used

### ISSUE THREAD

**Issue by Reid-n0rc** [magicbug/Cloudlog#3103]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
When lotw.arrl.org is down (as it is right now) and manual LoTW sync is used, nothing is displayed after the manual button is pressed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Username -> Logbook of the world
2. Click on 'Manual Sync'
3. Nothing happens

**Expected behaviour**
There should be an indication that the process failed because lotw.arrl.org is not reachable.

**Comment by stevendodd** [comment]
This is also happening for me, although I've not confirmed if logbook of the world is down or not

**Comment by Reid-n0rc** [comment]
LoTW has been down all day.

**Comment by Reid-n0rc** [comment]
LoTW has been down all day 
![image](https://github.com/magicbug/Cloudlog/assets/468300/9b817fd4-ea0b-400e-800c-a4dec7a9548c)

**Comment by magicbug** [comment]
If the Cloudlog is unable to upload to LoTW it will fail silently if its down, any QSOs it tried to upload will be marked as not sent and it will just try it again.

You can see in /logbook that its the case by looking at the arrows for example from my logbook today

![Cloudlog Logbook showing LoTW failed uploads](https://github.com/magicbug/Cloudlog/assets/84308/93f6470a-a9fc-4a16-8902-14eac0fe19bc)

Like everyone else I wait for it to return :)

**Comment by magicbug** [comment]
Worth noting added some extra code to say upload fails, however this info will only turn up on the screen when the PHP request times out, depending on how you setup your server this could take a while, you can check by running the URL used for the cronjob in the browser.
