### ISSUE TITLE
When an ADIF file is chosen, "You did not select a file to upload." is still displayed

### ISSUE THREAD

**Issue by m1bxf** [magicbug/Cloudlog#311]
**Describe the bug**
I use the "ADIF import" feature on a regular basis.  I've noticed since the recent Cloudlog update, in the "ADIF Import" box there is a red/pink box which says "You did not select a file to upload".  If I select an ADIF log file to upload by using 'Choose file', then although the ADIF file 'wsjtx_log.adi' is shown to the right of the 'Choose file' box but the red/pink box still says "You did not select a file to upload",

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Admin'
2. Go to 'ADIF Import/Export'
3. Click on the 'Choose file' button,  
4. Navigate to the folder which contains the WSJT-X ADIF log file 'wsjtx_log.adi', select the file and click 'Open'.
5. Even though 'wsjtx_log.adi' is shown to the right of the 'Choose file' box but the red/pink box still says "You did not select a file to upload"

**Expected behaviour**
I would expect the box with "You did not select a file to upload" to vanish or change colour to green and state a new message like "ADIF file selected complete, now click on upload".

**Screenshots**
![Cloudlog_ADIF_Display_Issue](https://user-images.githubusercontent.com/906380/60383282-da38ad80-9a66-11e9-8b99-e58ddaad0fdd.JPG)

**Comment by magicbug** [comment]
Yep this is a bug, it actually shouldn't be shown at all on first load its for when you submit the form.. will look into it
