### ISSUE TITLE
eQSL error: eQSL Nicknames in Station Profiles aren't defined

### ISSUE THREAD

**Issue by zcrowman** [magicbug/Cloudlog#3111]
I've been stuck trying to get a connection to eQSL. I've tried it with a nickname in eQSL and without a nickname. I reached out to eQSL about nicknames and he confirmed that indeed that I do have a nickname defined. But still no luck making a connection.

**Comment by magicbug** [comment]
You have set username and password in the account page?

**Comment by magicbug** [comment]
Other thing to try is enable logging in /application/config/config.php  and see what is in the application/logs

**Comment by zcrowman** [comment]
> You have set username and password in the account page?

Are you referring to the eQSL username/password externally?

**Comment by zcrowman** [comment]
I have added the user/pass to Cloudlog for eqsl.

**Comment by zcrowman** [comment]
> Other thing to try is enable logging in /application/config/config.php and see what is in the application/logs

Okay. I've activated the log and don't see anything in the log to indicate an issue

**Comment by zcrowman** [comment]
Issue resolved. I didn't realize that there was a place under station settings for this.
