### ISSUE TITLE
Map of QSO's shows paths and locations in different spots

### ISSUE THREAD

**Issue by zcrowman** [magicbug/Cloudlog#3112]
![Advanced_logbook_-_Cloudlog](https://github.com/magicbug/Cloudlog/assets/132226113/ec9f0cc9-570f-4613-8ecd-b7d47915cf69)
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
The map plot showing QSO's has some of the paths not meeting up with the actual plotted points of each QSO

**To Reproduce**
Steps to reproduce the behaviour:
Go to Logbook > Advanced
Click on MAP

**Expected behaviour**
Each path should end in its destination but instead, some appear in different spots

**Screenshots**
I've attached the screenshot

**Desktop (please complete the following information):**
 - OS: MacOS
 - Firefox
 - 126
 - viewing on a 27" screen at a resolution of 2560 x 1440px

**Additional context**

**Comment by magicbug** [comment]
Known issue, this is a leafletjs issue and haven't found the solution yet.

**Comment by zcrowman** [comment]
Thanks!
