### ISSUE TITLE
Edit possible options 'change Station Profile'

### ISSUE THREAD

**Issue by pa2eon** [magicbug/Cloudlog#312]
1. When edit a QSO, need the possibility to edit the Station Profile name.
No you can not see after from what 'station profile' you had made the QSO.

2. The active edit screen may be bigger in size or change size by yourself.

vy '73 PA2EON

**Comment by magicbug** [comment]
Station Profile is set a set of variables that held then put with the QSO record, I will make these text boxes within the edit, quite a few more need to be made available.

**Comment by magicbug** [comment]
Made my station profile information available for editing.

**Comment by pa2eon** [comment]
Many thanks, seen the update.
In which source file I can change the viewport settings .. to make the edit active window bigger ?

Eric

**Comment by magicbug** [comment]
I'd recommend exploring the /application/views folder there's a lot of code with the potential to break things

**Comment by pa2eon** [comment]
Yep I seen .. the best I need is in general.css .. change the parm: .fancybox-content { .. make 200 more ) 
that will do the job .. =;)
