### ISSUE TITLE
No check QRZ / HamQTH after git update

### ISSUE THREAD

**Issue by pa2eon** [magicbug/Cloudlog#313]
Dear Peter,

The latest changes will kill the QRZ/HamQTH update requests.
My previous version (see picture)
![image](https://user-images.githubusercontent.com/4719917/60395062-0f5c0300-9b2e-11e9-84be-54ea5d09fa4d.png)
Then after the github update of today:
![image](https://user-images.githubusercontent.com/4719917/60395265-39fb8b00-9b31-11e9-872d-0d51f0790f44.png)

So now a great function is lost =;) 

vy '73 Eric / PA2EON

**Comment by magicbug** [comment]
Hmm not sure that anything has changed to break it, will look

**Comment by magicbug** [comment]
I can confirm that QRZ is certainly working

**Comment by magicbug** [comment]
Eric,

Can you confirm that you are seeing this issue both with the QRZ and the HamQTH? as I'm using QRZ and can't see any issue with fields being populated, I'll check HamQTH later.

**Comment by pa2eon** [comment]
A requests to HamQTH their will be no information about the station.
A reguest to QRZ.COM the information is collected and shown.

So something for the HamQTH routine is bugged.

vy '73, Eric

**Comment by magicbug** [comment]
OK strange, guessing nothing changed within the /application/config/config.php file? 

If you go to `<url-to-cloudlog>/index.php/logbook/json/mm3php` does it return any results or does it error? you might need to edit index.php and set the debug mode to development

**Comment by magicbug** [comment]
I've made one code adjustment that if QSL_Manager isn't returned its skipped, not sure whether this might have caused an issue.

However, just tried it again after defining the below items in cloudlog.php and it worked flawlessly 

`
$config['hamqth_username'] = "";
$config['hamqth_password'] = "";
`
