### ISSUE TITLE
Gridmap - When zoomed in to 6 char colouring isn't shown

### ISSUE THREAD

**Issue by magicbug** [magicbug/Cloudlog#3136]
### Discussed in https://github.com/magicbug/Cloudlog/discussions/3130

<div type='discussions-op-text'>

<sup>Originally posted by **emics** June  7, 2024</sup>
With v2.6.14 in Gridmap i can see all grid worked and confirmed (red and green square).
If I zoom in a 4 chars square i can see detailed grid (6 chars) but i don't have the square coloured green and red although my QSO are correct with 6 chars grid.

have you the same ?
thanks</div>

**Comment by emics** [comment]
I Have investigated ,
the first thing is to enable: `$config['map_6digit_grids'] = TRUE;` in application/config/cloudlog.php
the second thing is wrong parameters in d3 variable (located in line 37 -  assets/js/leaflet/L.MaidenheadColouredGridMap.js)
```
redraw: function () {
		var d3 = new Array(20, 10, 10, 1, 1, 1, 1, 1, 1, 1, 1 / 24, 1 / 24, 1 / 24, 1 / 24, 1 / 24, 1 / 240, 1 / 240, 1 / 240, 1 / 240, 1 / 240 / 24, 1 / 240 / 24);
```
zomming the map some 6digit square are green and red but in the wrong position.
the bounds variable in line 67 contains the corners of confirmed square and the coordinates are wrong.

i hope to help someone to fix the bug!!!

**Comment by magicbug** [comment]
Fixed

**Comment by emics** [comment]
Hi Peter,
in the new [realease](https://github.com/magicbug/Cloudlog/releases/tag/2.6.15) there is always the problem in 4 digit gridsqare.
I show you some screen in GridSquare Map:

This is the grid of Rome (Italy)
![zoom1](https://github.com/magicbug/Cloudlog/assets/1004363/c4c22202-4995-4a42-b078-5ff87fe1df6c)

if I zoom in the squares changes
![zoom2](https://github.com/magicbug/Cloudlog/assets/1004363/0c81e7d1-87eb-4d25-ac13-64be6d727e8e)

another level of zoom and change again
![zoom3](https://github.com/magicbug/Cloudlog/assets/1004363/82539489-dcb4-4da6-8d48-1ded470cddd2)

the only QSO I have in JN61 grid are in
- JN61is
- JN61iu
- JN61gu [confirmed]
- JN61hv
- JN61fv

there is somthing wrong in d3 variable (located in line 37 - assets/js/leaflet/L.MaidenheadColouredGridMap.js)
read my comment [here](https://github.com/magicbug/Cloudlog/issues/3136#issuecomment-2161006216)
