### ISSUE TITLE
After 2nd update error from /migrations/016_lotwusers.php

### ISSUE THREAD

**Issue by pa2eon** [magicbug/Cloudlog#314]
When I update the software twice from github ( git pull ) I get the error that the record is stil their from the file 016_lotwusers.php

![image](https://user-images.githubusercontent.com/4719917/60397452-be5c0700-9b4d-11e9-8d00-eb730f337441.png)

Also from the file 018_clubloguserfields.php I have to clear all the line's.
To make a work-arround you can add a '#' sign in front of the line.

![image](https://user-images.githubusercontent.com/4719917/60397457-db90d580-9b4d-11e9-978d-0d481511e307.png)

Need to update the source code when check if the database fields are their or not !

vy '73 PA2EON

**Comment by magicbug** [comment]
Migrations run when Codeigniter hasn't run them, I've done 6 new installs with the current code and update 15 nightly and its worked flawlessly so I don't really plan on changing them. 

If your having to code change then something has changed within your install and i'm not sure what.

**Comment by pa2eon** [comment]
I think that is correct .. the error was in the second 'run' with the git update.
So when the code checks if the tables are their it have to do nothing .. but it will .. so it says something like 'already have the table name .. ed. '

**Comment by pa2eon** [comment]
After new github update .. no error anymore ! 
Seems to be fixed ..
