### ISSUE TITLE
Result of direct search in QRZ database after git update

### ISSUE THREAD

**Issue by pa2eon** [magicbug/Cloudlog#315]
>>
OK strange, guessing nothing changed within the /application/config/config.php file?

If you go to <url-to-cloudlog>/index.php/logbook/json/mm3php does it return any results or does it error? you might need to edit index.php and set the debug mode to development

It will give no error but also no search result !

![image](https://user-images.githubusercontent.com/4719917/60398500-34b23680-9b59-11e9-8823-1d5f7017e010.png)

The info reguest is made to QRZ.com

vy '73 Eric

**Comment by pa2eon** [comment]
Update the screen to .. no find call information .. and no filled data in fields screen:

![image](https://user-images.githubusercontent.com/4719917/60398564-10a32500-9b5a-11e9-9b7a-eabc77bb7aaa.png)

**Comment by pa2eon** [comment]
Test the checkup via Hamqth !!!  => The data filled in correct !
Changed to QRZ.com .. the data was NOT filled in (see screendump ) .. weird !!

**Comment by magicbug** [comment]
Please make sure you have QRZ information set I'm using an active subscription and it works perfectly.

**Comment by pa2eon** [comment]
FOUND THE SOLUTION !!!!  =;)
In QRZ.com you may NOT be use an '#' sign in your password !
Remove it .. and the search result is working !!

**Comment by magicbug** [comment]
Odd that # causes an issue but pleased it's resolved
