### ISSUE TITLE
No Map if logged in

### ISSUE THREAD

**Issue by dg9vh** [magicbug/Cloudlog#316]
**Describe the bug**
After login in, no map is shown on dashboard or logbook-tab.

**To Reproduce**
1. Log in
2. Click on Logbook
3. See error

**Expected behavior**
The Map should be shown.

**Error-messages from Code Inspector (Chrome)**

logbook:1219 Uncaught SyntaxError: Unexpected token ;

Corresponding lines in Code:
                var q_lat = ;
        var q_lng = ; 

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Chrome
 - Version: 75.0.3770.100

**Comment by magicbug** [comment]
I'm not seeing that here at all? going to need some more informatoin

**Comment by magicbug** [comment]
I'd suggest looking at `/index.php/logbook/qso_map/25/` to see if anything is displayed espescially errors, but I don't believe i broke anything

**Comment by dg9vh** [comment]
Hi, 
problem solved. I replaced my QRA-Locator yesterday from JN39KF to JN39KF05 - that was not resolved to longitude and latitude. Removing the last 2 digits, it is solved.

73 de Kim
DG9VH
