### ISSUE TITLE
Band-slot grid

### ISSUE THREAD

**Issue by M0LTE** [magicbug/Cloudlog#318]
**Is your feature request related to a problem? Please describe.**
It would be really nice to be able to see a summary of number of QSOs per country per hand.

**Describe the solution you'd like**
A grid. Along the top, bands. Along the left side, countries. In each cell, count of QSOs in that slot.
Only show band columns with QSOs.
Check a checkbox to show countries with zero contacts in any band - needed slots

**Describe alternatives you've considered**
Queried the DB:
`
SELECT COL_COUNTRY Country, COL_BAND Band, COUNT(1) QSOs FROM TABLE_HRD_CONTACTS_V01 WHERE COL_COUNTRY <> '' GROUP BY COL_COUNTRY, COL_BAND;
`

**Additional context**
none

**Comment by M0LTE** [comment]
Could link to this page from Countries Breakdown... Worked and Needed on the homepage

**Comment by M0LTE** [comment]
It would probably live under the Analytics tab

**Comment by magicbug** [comment]
Is this not covered by Awards - DXCC?

**Comment by M0LTE** [comment]
Oops, totally missed this page. Pretty much, yes.

Would be nice to be able to show missing countries, and hide bands with no QSOs.

John says modes would be nice too.

Might be nice to link to this from the countries section of the homepage too.

Just some thoughts.

**Comment by magicbug** [comment]
Think it only hides bands with QSOs, but agree needs further functions for filtering by mode, band etc

**Comment by AndreasK79** [comment]
I have made something like this in my own project:
![image](https://user-images.githubusercontent.com/6977712/75017413-3dab9b80-548d-11ea-97de-e485ae6077e5.png)
I might be able to incorporate something similar. Let me know, and I'll see what I can do.

**Comment by dg9vh** [comment]
I would like to see it 😁

**Comment by magicbug** [comment]
@AndreasK79 I think that would be a nice step up improvement to the index.php/awards/dxcc page like @dg9vh would love to see it.

**Comment by AndreasK79** [comment]
I have a working version now:
![image](https://user-images.githubusercontent.com/6977712/75672448-128d2d00-5c81-11ea-87d9-cc2d4893be12.png)
I still have a few bugs to fix, and some more testing to do.
One but I haven't figured out yet, is the setting of start and end in dxcc_entities. In my table start and end are all set to NULL. I tried to look at the code, and it's supposed to set them, but that does not work at my local copy. Any ideas @magicbug ?

**Comment by magicbug** [comment]
Yes entitles has nothing, but prefixes does, think I just copied the table schemas for all three types and just populated what was available

**Comment by AndreasK79** [comment]
@magicbug I found the problem. The wrong variable name was used when fetching start and end in update.php. I'll submit the fix with the PR for this. Just need to fix a few more things.

**Comment by AndreasK79** [comment]
PR has been submitted. An update for country files needs to be done to set start/end in dxcc_entitites. If this is not done, entitites will not be marked as deleted.
