### ISSUE TITLE
Allow "Search Callsign" box to use MySQL wildcard syntax

### ISSUE THREAD

**Issue by M0LTE** [magicbug/Cloudlog#319]
**Is your feature request related to a problem? Please describe.**
I would like to be able to search for, e.g. all YV stations in my log.

**Describe the solution you'd like**
I would like to be able to type "YV%" into the search window and get all QSOs with calls starting with "YV". Passing the [MySQL LIKE syntax](http://www.mysqltutorial.org/mysql-like/) through might be an easy way to do this.

**Describe alternatives you've considered**
Querying the database directly

**Additional context**
n/a

**Comment by magicbug** [comment]
Hi Tom,

I'll see about adding this feature, don't think theres any reason not to add it, the search is reasonably flexible on what you can chuck in at the moment but this would allow more features with syntax.
