### ISSUE TITLE
Multiple QSO's starting to be missing from the log

### ISSUE THREAD

**Issue by zcrowman** [magicbug/Cloudlog#3198]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to log and search for a known QSO (based on information from QRZ)
2. Says that there are no matches. 
3. This has happened for about 6 different QSO's over the last couple weeks

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser [Firefox] 
 - Version 130.0.1

**Additional context**
This is a self-hosted install of Cloudlog on a webserver

**Comment by magicbug** [comment]
Information would be returned from QRZ so if its not populated it could either be it took to long to respond or QRZ had another problem. I'd suggest enable logging and check server logs to see whats going on with the system
