### ISSUE TITLE
Query QSO count for a given slot via API

### ISSUE THREAD

**Issue by M0LTE** [magicbug/Cloudlog#320]
**Is your feature request related to a problem? Please describe.**
I'm writing a program which I would like to be able to check against my logbook for needed slots.

**Describe the solution you'd like**
An API equivalent to:
`SELECT COUNT(1) FROM TABLE_HRD_CONTACTS_V01 WHERE COL_DXCC=@dxcc AND COL_BAND = @band;`
I guess something like: `/api/slotqsos?dxcc=230&band=20` returning a bare number. This example would be Germany, 20m.
Mode could be an optional parameter.

**Describe alternatives you've considered**
I am currently querying the database directly but this requires direct access to the DB

**Additional context**
none

**Comment by magicbug** [comment]
I'll try to get this added tomorrow afternoon when I've some time between work stuff, so you can carry on with making the lookup Tom.

Do you need this with mode filtering, as I'm guessing you want band= but also mode= ?

If you want a similar thing for grid let me know.

**Comment by M0LTE** [comment]
It would be nice to have all of band and mode and grid and for them all to
be optional :-)

Cheers
Tom

**Comment by magicbug** [comment]
Hi Tom,

It's now implemented you can call it as 

`/api/country_worked/230/40m/ssb` or `/api/country_worked/230/40m`

It just returns the number not json encoded

**Comment by magicbug** [comment]
Same function should work for gridsquare_worked

**Comment by M0LTE** [comment]
For "New country on any band" I'm having to do this:

`int qsosWithThatCountryOnAnyBand = 0;
foreach (string metres in new[] { "160", "80", "60", "40", "30", "20", "17", "15", "12", "10", "6", "2", "70c" })
{
    qsosWithThatCountryOnAnyBand += int.Parse(HttpGet($"country_worked/{dxcc}/{metres}m"));
}`

and the database/API is beginning to creak!

Any chance of supporting just `country_worked/dxcc`? :-)

**Comment by magicbug** [comment]
@M0LTE How would being able to define band as "all" work?

**Comment by magicbug** [comment]
Then you could just use current APIs just tell it you want all the bands rather than a set one

**Comment by magicbug** [comment]
@M0LTE You can now do `/api/country_worked/230/all/ssb` and it will check the whole database.

**Comment by M0LTE** [comment]
Working, thanks!
