### ISSUE TITLE
QRZ INTEGRATION DOES NOT WORK

### ISSUE THREAD

**Issue by dalekhog** [magicbug/Cloudlog#3207]
### Discussed in https://github.com/magicbug/Cloudlog/discussions/3206

<div type='discussions-op-text'>

<sup>Originally posted by **dalekhog** October 16, 2024</sup>
Hi, thanx for this excellent logging app.
SInce this version, 2.6.16, (full new install in another pc, Windows), when adding a QSO, fields are not populated.
Added qrz with credentials in Third Party Services, and also in the config.php file and still doesnt work.
If I select NONE in Third Party Services, fileds are populated with callsigns I have already worked.

Does anybody have this working?

Should I reinstall everything?

Thank you again,

Pablo
CX4RL</div>

**Comment by magicbug** [comment]
Seem to have posted this twice, but after adding QRZ login details log out and in again to clear session data and see if that clears it any problems.

**Comment by dalekhog** [comment]
Yes sorry, posted it twice. Will follow in the discussions section.
Thank you.-

**Comment by magicbug** [comment]
I've now committed a new code update to master which should address Callbooks, if you're having issues suggest updating and reentering the information
