### ISSUE TITLE
Charset problems

### ISSUE THREAD

**Issue by DL3RTL** [magicbug/Cloudlog#321]
**Describe the bug**
I imported an ADIF with the argument `<name:4>Jörg`

**Expected behavior in Frontend**
Name: Jörg

**real behavior in Frontend**
Name: Jör   (with the missing g to Jörg)

**ADIF export next problem*
`<name:4>JÃ¶r`

**Comment by DL3RTL** [comment]
My ADIF import was originalle <name:4>Jörg

**Comment by magicbug** [comment]
Can you try with the latest commit, made sure UTF-8 headers were set correctly.

**Comment by DL3RTL** [comment]
I downloaded the version of yesterday.
If I have to install everything again it would take hours :-((
Is there a sprcific file I could exchange?

**Comment by magicbug** [comment]
See git commit history, not sure why it would take hours and sadly there's no other way of delivery everything but application/config is safe to overnight, else use Git to do version control.

**Comment by DL3RTL** [comment]
Many thanks for your fast reply.
This morning I downloaded the lastest code and tried again.
Unfortunatley the result is the same.

**Comment by DL3RTL** [comment]
How could we open this issue in order to get is debugged? Don't find a button... :-/

**Comment by DL3RTL** [comment]
How can we solf this problem ?
Has anyone in idea ?
