### ISSUE TITLE
Spots in public station logbook map

### ISSUE THREAD

**Issue by dg3feh** [magicbug/Cloudlog#3215]
**Describe the bug**
Not all spots are shown as in the logbook overview map

Steps to reproduce the behaviour:
Compare LOGBOOK -> OVERVIEW vs. <LOGIN-NAME> -> STATION LOGBOOKS -> LINK TO PUBLIC LOGBOOK

**Expected behaviour**
All spots are shown, atleast the spots of the certain page

**Desktop (please complete the following information):**
 - Win10
 - Firefox
 - 131.0.3
 - Cloudlog v2.6.16 on ubuntu linux with apache

**Comment by magicbug** [comment]
I cant seem to replicate this the map loads as expected here
