### ISSUE TITLE
Contest RST (S) and RST (R) values displayed in logbook but not in index.php/logbookadvanced window

### ISSUE THREAD

**Issue by ei8fdb** [magicbug/Cloudlog#3216]
**Describe the bug**
When logging QSOs in a contest window (`/index.php/contesting`) the recorded RST (S) and (R) is recorded in the `/index.php/logbook` window but not in the `index.php/logbookadvanced` window.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to either `Live` or `Post` Contesting Logging 
2. Choose CQ WW SSB contest
3. Start contest log
4. Record log a QSO
5. Log entry for RST (R) and (S)
6. Go to `index.php/logbook` - see recorded RST values displayed
7. Go to `index.php/logbookadvanced` - values RST values are not displayed

**Expected behaviour**
Since RST values are displayed in `index.php/logbook` it's expected they are displayed also in `index.php/logbookadvanced`.

It seems odd it'd be populated in one but not in the other.

**Screenshots**
RST is shown in `logbook`

<img width="1311" alt="Screenshot of Cloudlog logbook window showing RST Received and Sent values populated." src="https://github.com/user-attachments/assets/ea75846f-d07b-43ea-9f7e-84066d6e366b">

but not shown in `advancedlogbook`

<img width="1311" alt="Screenshot of Cloudlog advanced logbook window showing RST Received and Sent fields are not populated." src="https://github.com/user-attachments/assets/47b3e85e-106d-429a-9857-114e4661bd65">

**Desktop (please complete the following information):**
 - OS: any OS (in this case Ubuntu 22.05)
 - Browser [Firefox 131.03]

**Additional context**
Have not checked if this happens in any other contests.

**Comment by magicbug** [comment]
Looks like you spotted a bug, need to investigate to see why its not rendered in Advanced Logbook
