### ISSUE TITLE
<qsl_sent:1>Y with no effect

### ISSUE THREAD

**Issue by DL3RTL** [magicbug/Cloudlog#322]
I was uploading an aidf file with the argument
`<qsl_sent:1>Y`

But in the frontend of this specific QSO entry this outgoing QSL card still has a red arrow. And if I open the entry to edit it the outgoing QSL is 
Sent: No

If i do an ADIF backup of my logs from cloudlog there again the
`<qsl_sent:1>Y`

It seems not to be shown to the Frontend.

This seems to be a bug.

**Comment by magicbug** [comment]
That is strange, theres no fancy checking going on `<qsl_sent:<?php echo strlen($qso->COL_QSL_SENT); ?>><?php echo $qso->COL_QSL_SENT; ?>` should just grab whats in the database and dump it out.

**Comment by DL3RTL** [comment]
As I described: There is a Y. Also in the ADIF export. Just in the frontend there's nothing, so Sent: No.

**Comment by DL3RTL** [comment]
ADIF export from Cloudlog:
<call:6>DL6AAO<band:4>160m<mode:3>FT8<freq:4>1.84<qso_date:8>20190709<time_on:6>200200<time_off:6>200200<rst_rcvd:2>59<rst_sent:2>59<qsl_rcvd:0><qsl_sent:1>y<country:27>Federal Republic Of Germany<eor>

Result in Frontend:
![qsl](https://user-images.githubusercontent.com/43474018/61743886-61dbb880-ad96-11e9-8dad-70269a928348.PNG)

I imported more than 1000 QSOs. Only the very forst QSOs have the right status of QSL shown. All the others don't work.

**Comment by DL3RTL** [comment]
I dropped the database and uploaded the same ADIF file once more. Now the status of the QSL is correct.
