### ISSUE TITLE
No Frequency displayed

### ISSUE THREAD

**Issue by Jackdog44ron** [magicbug/Cloudlog#3221]
Every thing connects but unable to get frequency to show . So I log get random frequencies.

**Comment by magicbug** [comment]
You're going to need to explain this a bit more, are you using Cloudlog CAT or just using the band selection?

**Comment by Jackdog44ron** [comment]
Hi. I am using cloud cat and omnirig both ic7610 and ic7300 say connected as omnirig 1 and 2  it also says url is sync but I can add entries but get no band or frequency showing have to add it  manually RobSent from my Galaxy
-------- Original message --------From: Peter Goodhall ***@***.***> Date: 31/10/2024  22:05  (GMT+00:00) To: magicbug/Cloudlog ***@***.***> Cc: Jackdog44ron ***@***.***>, Author ***@***.***> Subject: Re: [magicbug/Cloudlog] No Frequency displayed (Issue #3221) 
You're going to need to explain this a bit more, are you using Cloudlog CAT or just using the band selection?

**Comment by magicbug** [comment]
- Is CloudlogCAT showing the rig data?
- In Cloudlog if you go to the your callsign dropdown top right and go to Hardware Interfaces do you see the radio data?
- Are you selecting the radio in the QSO panel under station radio
