### ISSUE TITLE
Not all modes displayed in filter in advanced logbook

### ISSUE THREAD

**Issue by sebket** [magicbug/Cloudlog#3227]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
When using the "advanced logbook" and trying to filter after mode, not all modes are shown, in my case USB

**To Reproduce**
Go to Logbook, then Advanced
Click on Filters
Expand the dropdown list for Modes

**Expected behaviour**
I have QSOs in many different modes in my log, mostly various digimodes.
But there are also some QSOs in the Mode USB.
The mode USB is not shown and therefore not selectable.

**Screenshots**
![Screenshot 2024-11-15 083944](https://github.com/user-attachments/assets/40a686ef-1acc-4b2c-80cc-a0b921b27be8)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 132.0.1

 - Version of Cloudlog: 2.6.16

73 Sebastian DL2KSE

**Comment by magicbug** [comment]
This is functioning correctly it gets ALL the qsos from the locations in the logbook and it shows all the unique modes.

Unless you can provide an example of this not being the case

**Comment by magicbug** [comment]
now resolved in the dev branch
