### ISSUE TITLE
error while "Pull LoTW data for me"

### ISSUE THREAD

**Issue by DL3RTL** [magicbug/Cloudlog#324]
I just tried the function "Pull LoTW data for me".

There are the same logs in LOTW and in Cloudlod database.

Afterwads I got the attached error messages.

The problem was a misconfiguration with a wrong password.

If poosible please be so kind and have an error message with the correct hint to the login problem. If you are not familiar with code someone could think that there's an error with cloudlog.

Message: Trying to get property 'COL_LOTW_QSLRDATE' of non-object

Filename: models/Logbook_model.php

Line Number: 789

Error: Adif_Parser Already Initialized or No in ADIF File
Cloudlog
Logbook
QSO
Notes
Analytics
Awards
Admin
Search Callsign
Logged in as DL3RTL
LoTW ADIF Information
A PHP Error was encountered
Severity: Notice

Message: Undefined variable: lotw_table_headers

Filename: lotw/analysis.php

Line Number: 4

A PHP Error was encountered
Severity: Notice

Message: Undefined variable: lotw_table

Filename: lotw/analysis.php

Line Number: 5

**Comment by magicbug** [comment]
Its already on the todo list
