### ISSUE TITLE
Error message with Clublog upload

### ISSUE THREAD

**Issue by DL3RTL** [magicbug/Cloudlog#327]
I followed the steps of
https://github.com/magicbug/Cloudlog/wiki/Clublog-Upload

so I opened the url https://www.xxxxx.de/logbuch/index.php/clublog/upload/daniel

In the upload folder I found the file
clublog5d3819d1c341a.adi

But the frontend shows the following error:
couldn't open file "/www/htdocs/xxxxx/xxxxxl.de//uploads/clublog5d3819d1c341a.adi"Error

**Comment by magicbug** [comment]
This isn't a cloudlog issue rather a server permissions, make sure /uploads is writeable and readbale.

**Comment by dg9vh** [comment]
What source is the adif file from?

**Comment by dg9vh** [comment]
Had this issue with ucxlog, solved by removing first line.

**Comment by DL3RTL** [comment]
The ADIF is handmade and there in no additional row in the header.

**Comment by DL3RTL** [comment]
Writable and readable? Is it like 777 ?
