### ISSUE TITLE
Error when trying to login

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#329]
I get a 404 error when trying to login after a successful installation – any idea what could be causing this?

**Comment by magicbug** [comment]
Hard to know without further information
Are you using the latest master from GitHub? Screenshots might be useful

**Comment by dg9vh** [comment]
Hi,

what is the content of $config['base_url'] in /application/config/config.php ?

**Comment by ofadam** [comment]
https://ofadam.com/dx/

The initial screen will load, but logging in results in a 404 that WordPress then serves.

**Comment by dg9vh** [comment]
I'm getting connection refused...

**Comment by ofadam** [comment]
Give it a shot now.

**Comment by dg9vh** [comment]
So once again my question above:
what is the content of $config['base_url'] in /application/config/config.php ?

AND:

Do you have any .htaccess-file containing some url-rewriting-rules? I see a difference between the URL on my side and on your side:

https://ofadam.com/dx/user/login
versus
https://cloudlog.dg9vh.de/index.php/user/login

I got that index.php in my url (working ufb) but when adding this to your url at the position, it would be removed by the webserver, so there must be some url rewriting active...

**Comment by dg9vh** [comment]
Problem could be caused by Wordpress-rewriting-rules because you are hosting cloudlog as subdirectory within your wordpress-installation?

**Comment by ofadam** [comment]
That's what I'm thinking – I will try to reposition as a subdomain and see
if it works.

**Comment by dg9vh** [comment]
Give it a try and reply :-)
