### ISSUE TITLE
Award page : QSO number

### ISSUE THREAD

**Issue by F4MZI** [magicbug/Cloudlog#334]
I do not really know if it's a bug, on the page "Awards" appears the countries with which QSOs were made. The number of QSOs does not correspond to the QSOs displayed when this number is clicked.
For example, in my log, I have 81 QSOs with England. But when I want to display these QSOs, only 20 QSOs appear.
I'm using this page to update my QSOs because the database I've imported does not keep Grid Squares and I have to fix the QSOs one by one.
But maybe it's not a bug but a feature ...
Pierre-Philippe Brocard
F4MZI
  - OS: Debian 10
  - Browser: Any
  - Version: Git

**Comment by magicbug** [comment]
I'd recommend going to Admin -> Update Country Files then asking it to recheck all your log, this might fix things not lining up, it certainly has in the past
