### ISSUE TITLE
Suggest satellite name and populate satellite mode

### ISSUE THREAD

**Issue by magicbug** [magicbug/Cloudlog#335]
**Is your feature request related to a problem? Please describe.**

If you don't use SatPC32 intergration you have to manually enter satellite name and mode, be nice if it suggested it

**Describe the solution you'd like**

json file that could store satellite names and modes available, so you type AO- it would suggest AO-91 for example then populate the sat mode with U/V and set the mode to FM and band to 70cm

**Comment by ea5wa** [comment]
Why not a combobox with satellite names, selecting one of them automatic population of sat mode, Mode, Frequencies.
It would be perfect solution for Satellite Portable operation

**Comment by ok1cdj** [comment]
Please use this ARRL list to have it correct for LOTW upload.

**Comment by magicbug** [comment]
> Please use this ARRL list to have it correct for LOTW upload.
> https://lotw.arrl.org/lotw-help/frequently-asked-questions/#sats

I'd recommend using the actual satellite names, it can then be adjusted for LOTW because satellite applications don't use LOTW names.
