### ISSUE TITLE
Export to eQSL does not respect "ignore"-flag in EQSL_QSL_SENT

### ISSUE THREAD

**Issue by dg9vh** [magicbug/Cloudlog#338]
**Describe the bug**
Export to eQSL does not respect "ignore"-flag in EQSL_QSL_SENT

**To Reproduce**
1. Edit QSO
2. Set eQSL-Sent state to Invalid (Ignore)
3. Export eQSL

**Expected behavior**
We should add the Invalid (Ignore) state into the list that is not exported to eQSL. I think, it would be done in the Logbook_model.php at line 929:
      $this->db->where('COL_EQSL_QSL_SENT  !=', 'Y');
This line has to be changed to an "not in" (where COL_EQSL_SQL_SENT not in ('Y', 'I')).

**Comment by magicbug** [comment]
This seems a reasonable request and I agree should be set to ignored if thats the option selected.

**Comment by dg9vh** [comment]
Fixed with https://github.com/magicbug/Cloudlog/pull/340
