### ISSUE TITLE
Allow Date Selection on ADIF Export

### ISSUE THREAD

**Issue by magicbug** [magicbug/Cloudlog#342]
**Is your feature request related to a problem? Please describe.**

Allow users to export ADIF records by defining a date period

**Describe the solution you'd like**

Input fields for start and end date that have a calendar popup that allows you to define the two data points followed by an export button.

**Comment by ea5wa** [comment]
It could be very convenient at the end of a field day

**Comment by AndreasK79** [comment]
I have a working concept with minor adjustments to 2 files. It works, and most new browsers have a datepicker built in. A bit more work is needed to add a javascript bootstrap datepicker. Any suggestions, or am I free to pick one?

![image](https://user-images.githubusercontent.com/6977712/74008053-31e5b280-4980-11ea-95c5-778f006badfc.png)
![image](https://user-images.githubusercontent.com/6977712/74008494-4b3b2e80-4981-11ea-93bb-c8774db3caa3.png)

**Comment by magicbug** [comment]
As long as it works with bootstrap looks ok on desktop and mobile no real constraints.

**Comment by AndreasK79** [comment]
I guess this can be closed now with the commit I made two days ago?
