### ISSUE TITLE
Synchronization with (new) Mac/iOS Logbook

### ISSUE THREAD

**Issue by myzinsky** [magicbug/Cloudlog#345]
Synchronization with e.g. http://pignology.net/hamlog.html would be very interesting. Or, creating a individual CloudLog app for MacOS and iOS. I would also volunteer and code these apps.

**Comment by magicbug** [comment]
As this isn't an application by myself mentioned above and i don't use Mac/iOS products it would be up to someone else to integrate this however the felt it should via a Pull Request.

**Comment by magicbug** [comment]
I currently have no plans to build desktop logging applications, that said Cloudlog has APIs that anyone can use.
