### ISSUE TITLE
enlarge COL_MODE from varchar(10) to varchar(12)

### ISSUE THREAD

**Issue by dg9vh** [magicbug/Cloudlog#359]
If you take a look at http://www.adif.org/304/ADIF_304.htm#Mode_Enumeration you'll see, that "DIGITALVOICE" is a valid mode in ADIF-Specification with length of 12 chars, COL_MODE only allows varchar(10), so we need 2 additional characters there to produce valid logs in ADIF.

**Comment by magicbug** [comment]
Oddly I hit that issue today I just made a change request on the PR sir once change is done i'll add it.

You might need to add similar for sub_mode

**Comment by magicbug** [comment]
@dg9vh Kim Thanks its now merged :) do you think COL_SUB_MODE needs similar?

**Comment by magicbug** [comment]
Submodes 25 so should be fine! closing this issue
