### ISSUE TITLE
QSOs Pushed To eQSL #bug

### ISSUE THREAD

**Issue by DJUnreal** [magicbug/Cloudlog#361]
QSOs which have been imported from ADIF files created by other programs are not being pushed to eQSL when I navigate to the export to eQSL page. A QSO should only have two eQSL states - uploaded to eQSL and not uploaded to eQSL. If Cloudlog hasn't pushed it, the safe assumption would be that it hasn't been pushed, and so should be marked as awaiting pushing. Currently it seems ADIF uploaded QSOs go into some kind of third state of not having been pushed but also not being marked as ready to push.

My hosted instance currently has 30+ brand new QSOs which haven't been pushed, if you wish to view that. It also has a large number of old ones, some of which I've pushed manually, but that haven't been identified by Cloudlog during previous syncs. Cloudlog should be able to see which QSOs don't have sent records from eQSL and upload those.

**Comment by magicbug** [comment]
Made a tweak and resolved this see the commit history
