### ISSUE TITLE
LOTW QSO Import #feature

### ISSUE THREAD

**Issue by DJUnreal** [magicbug/Cloudlog#362]
I'd really like it if, when Cloudlog connects to my LOTW account, it checks for QSOs listed on LOTW and imports them, rather than ignoring them as is its current behaviour. Being able to populate based on historic QSOs listed on LOTW would be really handy!

**Comment by magicbug** [comment]
If the logbook is empty then it will import from LOTW, I'm not too sure about grabbing QSOs, not within the log and merging them in personally.
