### ISSUE TITLE
ADIF Header Handling #bug

### ISSUE THREAD

**Issue by DJUnreal** [magicbug/Cloudlog#363]
At the moment, ADIF imports don't seem to be able to handle header data. If an ADIF file with a header is uploaded, the upload page states the file type is invalid.

I would suggest having the ADIF parser begin by looking for an <EOH> tag (seems to be a standard header tag in ADIF), and ignore everything above that tag. This should then allow it to parse files correctly even with headers in there.

**Comment by magicbug** [comment]
It actually handles header data fine, what it doesn't handle is free flow text thats become popular in ADIF files of late (no idea why)

**Comment by DJUnreal** [comment]
Thanks Pete!

**Comment by AndreasK79** [comment]
I had this problem when testing out the log as well. I traced it to the mime-check done by Codeigniter. Modifying mimes.php solved the problem for me.

'adi'   =>  array('application/octet-stream','text/plain', 'audio/x-hx-aac-adif'),
'adif'  =>  array('application/octet-stream','text/plain', 'audio/x-hx-aac-adif'),
'ADI'   =>  array('application/octet-stream','text/plain', 'audio/x-hx-aac-adif'),
'ADIF'  =>  array('application/octet-stream','text/plain', 'audio/x-hx-aac-adif'),

**Comment by dg9vh** [comment]
How about a pull-request? @AndreasK79

**Comment by AndreasK79** [comment]
Sure. I'll look into it later. I just need to get things set up.

**Comment by magicbug** [comment]
Thanks, PR definitely would appreciated.
