### ISSUE TITLE
Change Country Names on Dashboard/Logbook Display to Flags

### ISSUE THREAD

**Issue by magicbug** [magicbug/Cloudlog#380]
I'm proposing that on the Dashboard/Logbook page where countries are referenced that they are replaced with suitable flags to improve space and layout available.

The country name would still be shown when hovering over said flag.

**Comment by tonyc** [comment]
I think the issue with this would be that you instantly lose readability, and at least in the US, I'd suspect that most people don't know what other country's flags look like, outside of a handful. This is probably less of a problem in EU, perhaps?

I'm scanning down the flags on https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes and I would be terribly confused, so I'm wondering if there's a better way besides a flag.

Could you attach a screenshot of what it looks like currently?

**Comment by magicbug** [comment]
Interesting, on this page, I don't think it would make a huge difference unless most don't know where a callsign references? You'd still get full dxcc name when making the QSO.

I could make it an option, you can have full name or the flags? half way keep everyone happy. maybe EU is more aware of callsign and country.

![screencapture-logbooks-2m0sql-2m0sql-index-php-logbook-2019-10-22-22_15_25](https://user-images.githubusercontent.com/84308/67334100-8ec87480-f519-11e9-9436-d7cfe9e1214c.png)

**Comment by tonyc** [comment]
Honestly, on that screenshot, I think it looks fine the way it is.

**Comment by tonyc** [comment]
Ah yes. Hmmm...... what about collapsing it to a flag on mobile devices, and use the full country name if there's enough width?

**Comment by magicbug** [comment]
I think that seems like a reasonable halfway medium, as always easy to think theres an issue when there isn't!
