### ISSUE TITLE
password not accepted - is all lost ???

### ISSUE THREAD

**Issue by DL3RTL** [magicbug/Cloudlog#385]
I use couldlog since 3 months and changes nothing. all of a sudden I can not log in to logbook from any device. how can I reset the password? how can I get all my data??? need HELP !!!

**Comment by magicbug** [comment]
Fear not, go to /application/config/config.php then find  $config['use_auth'] = true; change to false reset password & set it back to true.

**Comment by DL3RTL** [comment]
Many thank for your fast reply Peter. I did change it to false and stored the file. Then i changed it again to true and stored the file once again on the server.
What do I have to do next  to log in or to reset/change the password ?

**Comment by dg9vh** [comment]
Hi,
I think the process would be:
- set it to false
- login to cloudlog and go to "edit user" to change your password
- set it to true again

73 de Kim
DG9VH

**Comment by DL3RTL** [comment]
But I can not log in without the password.

**Comment by DL3RTL** [comment]
In the URL https://www.   ........   /index.php/user/login

I type my Username and leave the password field blank.

Then I get the error message "The Password field is required.

Oh my god.....

**Comment by dg9vh** [comment]
Are you able to access to the database directly via phpmyadmin or something like that?

**Comment by DL3RTL** [comment]
yes

**Comment by dg9vh** [comment]
So you can use https://php-password-hash-online-tool.herokuapp.com/password_hash for example to generate a initial password like test01 and paste the password-hash into the users-table-row concerning your user. After this, you could try to log in with test01 as password.

**Comment by dg9vh** [comment]
you could use following parameters for generating - I tested it on my dev-system, it's working fine:
![image](https://user-images.githubusercontent.com/13950650/68536286-b3fa1700-0350-11ea-889e-2ee6f1b48c4e.png)

**Comment by magicbug** [comment]
@dg9vh's method works, however setting Auth to false should make huge admin drop down available then just edit

**Comment by DL3RTL** [comment]
I tried it with test01 but I can not log in :-(

**Comment by DL3RTL** [comment]
And what is a huge admin drop down ?

**Comment by DL3RTL** [comment]
Now it worked with the new password. I forgot to set to true again in the config file. I sucessfully changed my password again and I have full access to the logbook.

Still I don't know what went wrong. I was just storing a qso when I was logged out and had no chance to get in again.

Never the less many thanks for your fast help that late evening Peter and Kim.

Daniel...

**Comment by dg9vh** [comment]
Ok, then I can go to bed in a good mood :-)

Have a good night :-) Best 73
Kim
