### ISSUE TITLE
QSO Time Incorrect

### ISSUE THREAD

**Issue by tspowell01** [magicbug/Cloudlog#387]
I just installed Cloudlog on my Linux box.  I clicked on the QSO and clicked on Live QSO.  When the screen came up, I noticed that the time was off by 5 hours; I'm on eastern time in the USA.  I edited the profile for the account I was using, but changing the time zone didn't change the time on the Live QSO screen. My Linux box time is set to local time.  Any suggestions? Thank you.

**Comment by magicbug** [comment]
From memory Cloudlog should default to UTC, this is the first instance that that not happening that I'm aware of.

Just to confirm that the date/time on the servers correct? Could you screenshot the QSO panel too.

The QSO info in the browser is automatically figured out based on local clock of the browsers device it doesn't actually use the time zone selection.

Info on timezone used also be useful & browser.

**Comment by magicbug** [comment]
Quick further comment, I'm going to guess you haven't changed the time zone info in application/config/config.php

**Comment by tspowell01** [comment]
Okay, it's a misunderstanding on my part.  I was expecting the time in the QSO to be the same as my local time, but you convert it to UTC.  

![TimeReference](https://user-images.githubusercontent.com/55894166/68726365-32dc9300-058f-11ea-99bb-540a8c620f1f.png)
![QSOlive](https://user-images.githubusercontent.com/55894166/68726370-36701a00-058f-11ea-9c61-16f00f45e852.png)
