### ISSUE TITLE
Installation issue with Nginx

### ISSUE THREAD

**Issue by TriBallscom** [magicbug/Cloudlog#389]
**Unable to logon after installation**
The installation process work fine, no errors reported. The database looks fine, the user m0abc is in there but when I try to logon with the m0abc/demo account it redirects to: http://<website>/index.php/user/login
and responds with a 404 error.

**server configuration**
ubuntu 18.04
Nginx 1.14 
php-fpm 7.2.24
mySQL 5.7

**Comment by magicbug** [comment]
This is due to $config['base_url'] within /application/config/config.php not being setup correctly or a nginx configration issue
