### ISSUE TITLE
Save eQSL Image locally against a QSO

### ISSUE THREAD

**Issue by TriBallscom** [magicbug/Cloudlog#390]
When an eQSL arrives it would be nice if it could be uploaded/added to the log.
Now you have to go to another website to see the card (or print it) but it would be nice if you could download the card and add it to the log as a reference.

**Comment by magicbug** [comment]
a user did start creating a similar idea at https://github.com/magicbug/Cloudlog/pull/348 however the PR seemed to stall.

**Comment by magicbug** [comment]
I'm closing this issue as its a duplicate and already being discussed in https://github.com/magicbug/Cloudlog/issues/343
