### ISSUE TITLE
update issue

### ISSUE THREAD

**Issue by g7kse** [magicbug/Cloudlog#392]
I'll start this by saying it was probably an error on my part. Updated on self hosted cloudlog and get most of the menu's like this

![image](https://user-images.githubusercontent.com/13124178/69906929-3fe8e700-13c3-11ea-8f99-aec62d5cbbfb.png)

with the exception of when I go to admin and it looks all swizy, new and lovely, a la....

![image](https://user-images.githubusercontent.com/13124178/69906942-6c9cfe80-13c3-11ea-9a6b-2c416bbd94f2.png)

Any chance of putting me right? It seems perfectly functional though.

I also noticed that you've got a link to when I poped it onto a Pi Zero W. I'm going to update this as I'm in the process of moving everything onto my own server so the link will not work for now. I've moved everything onto a DietPi distro which includes a web server and it is a much nicer option, just don't expect a brilliant Boostrap based site. it is me after all ;-)

**Comment by magicbug** [comment]
Top versions old and the new ones how it looks now. If you'd like to add anything to the wiki feel free.

**Comment by g7kse** [comment]
Sorted the wiki. Now killed my install.....A little knowledge is dangerous ;-)
