### ISSUE TITLE
Incorrect integer value: '' for column 'station_dxcc' at row 1

### ISSUE THREAD

**Issue by M0LTE** [magicbug/Cloudlog#395]
**Describe the bug**
When creating a station profile, I get the following:

```
A Database Error Occurred
Error Number: 1366

Incorrect integer value: '' for column 'station_dxcc' at row 1

INSERT INTO \`station_profile\` (\`station_profile_name\`, \`station_gridsquare\`, \`station_city\`, \`station_iota\`, \`station_sota\`, \`station_callsign\`, \`station_dxcc\`, \`station_country\`, \`station_cnty\`, \`station_cq\`, \`station_itu\`) VALUES ('Home IO91lk', 'IO91LK', 'Reading', '', '', 'M0LTE', '', '', '223', '14', '27')

Filename: models/Stations.php

Line Number: 49
```

**To Reproduce**
1. Upgrade cloudlog to a version that prompts you to create a station profile
2. Create a station profile with the above data

**Expected behavior**
A station profile to be created

I worked around it by manually creating a row in the database.
I also had to execute `update TABLE_HRD_CONTACTS_V01 set station_id=1` to get my QSOs to show up.

Cheers Peter.

**Comment by magicbug** [comment]
That must have been a fairly old version as station profiles have been available since September, it looks like Country Name is whats missing, this is populated using the info from Club log via the country files, when you were creating the station profile did country name populate the dropdown?

**Comment by M0LTE** [comment]
No, from memory it didn’t render an input field at all.

I just did a git pull to get up to date- it’s been a while since I’ve done
that.

**Comment by dg9vh** [comment]
Sometimes it would help to clean cache in browser...

**Comment by magicbug** [comment]
This is what the station profile (Add) page looks like, if it doesn't then make sure "Update Country Files" is carried out.

![screencapture-cloudlog-mg-index-php-station-create-2019-12-08-21_44_28](https://user-images.githubusercontent.com/84308/70396792-025c0d80-1a04-11ea-9fa2-4dfa3016dddd.png)

**Comment by M0LTE** [comment]
It now looks like that after updating country files.
