### ISSUE TITLE
Adding JS8 for the QSO modes for using with JS8Call 

### ISSUE THREAD

**Issue by motoionic** [magicbug/Cloudlog#396]
Can't find a way through the UI to add new modes, but I do a few contacts using JS8Call. Which on Log4OM and QRZ get logged as JS8.

Can this be added easily?

**Comment by magicbug** [comment]
Hi @motoionic 

Isn't too hard this is now done in https://github.com/magicbug/Cloudlog/commit/5bfab7dec5a9dee5de405d9762adc1e68c4af40e so you should be good to go
