### ISSUE TITLE
Question: Semantic of LOTW Symbols

### ISSUE THREAD

**Issue by myzinsky** [magicbug/Cloudlog#401]
I have a question on the semantic of the LOTW symbols, mainly why sometimes the symbols are missing? does that mean that this station does not use LOTW? 

<img width="1111" alt="Bildschirmfoto 2020-01-02 um 20 00 11" src="https://user-images.githubusercontent.com/1970554/71686190-b437f100-2d9a-11ea-9fc6-36012e01dfbd.png">

Also for this screenshot I have signed and uploaded the downloaded log file to LOTW. Why are the outgoing symbols red then? Because this was issued to LOTW?

**Comment by magicbug** [comment]
No, its something that needs fixed when saving a QSO the LOTW Sent & Recv flags aren't being set to No so you get the blank spaces where as if you "update" a qso it is..
