### ISSUE TITLE
API Add - Request for info

### ISSUE THREAD

**Issue by motoionic** [magicbug/Cloudlog#402]
I'm putting together a small Android app that will allow me (and eventually others) to quickly log a QSO to my Cloudlog, or in offline mode build up a queue of contacts to push to cloudlog.  

Im after information for the API Add request, looking in the Wiki it is still be to be documented.

As and when you get 5 spare minutes can you throw some info on the page please.

Many Thanks!!

**Comment by motoionic** [comment]
Scrap this I've just realised you have a newer api than the XML one to make this easier.

**Comment by magicbug** [comment]
Fab pleased you found it, yes the XML interface will be depreciated in V2.
