### ISSUE TITLE
Uploading lotw report; no qso found

### ISSUE THREAD

**Issue by m0pcb** [magicbug/Cloudlog#407]
**Describe the bug**
When uploading a lotw.adi report from a file, if the QSO record doesn't match it appears that a new QSO is added in the active station profile with the QSO details from the lotw.adi file. 

**Expected behavior**
If the QSO in the lotw report.adi doesn't match anything in the log then there should be a warning and the data not inserted into the active profile.

**Desktop (please complete the following information):**
Hosted instance on cloudlog.co.uk

**Comment by m0pcb** [comment]
Hmm, it actually seems to have reassigned the QSOs to the active profile. This happened to 17 QSOs in a large upload, where the QSOs were logged as M0PCB/P but lotw had them as M0PCB. The result was that the QSOs were then attributed to AD5XI profile.

**Comment by magicbug** [comment]
Not sure why you'd upload the report as it would treat the QSO as new.

Best way to match is via the built in system.

**Comment by magicbug** [comment]
Hmm looks that that might be broken in that case, I know the internal system for downloading with user & pass works will need to explore

**Comment by AndreasK79** [comment]
What about adding an option to not import QSOs not found? That way people can decide when pulling data from LoTW.

**Comment by magicbug** [comment]
Yes I much prefer that solution

**Comment by magicbug** [comment]
My biggest concern is when adding a missing QSO on import is that it gets correctly assigned to the right station profile in Cloudlog

**Comment by AndreasK79** [comment]
@magicbug Ok. What about an option, and then check if current station_id matches the callsign from LoTW? If not, another check could be done to check to find a station_id with that call. If not, skip the whole import thing.

**Comment by magicbug** [comment]
That feels like a reasonable compromise.

**Comment by magicbug** [comment]
While thinking about it, can we match based on the callsign and the gridsquare from LoTW that should give a perfect match every time
