### ISSUE TITLE
clublog_scp.txt still tracked

### ISSUE THREAD

**Issue by abrain** [magicbug/Cloudlog#415]
With 1462e4fc5efd3b0b261461f271460ef193f13487 `/updates/clublog_scp.txt` was added to `.gitignore`. At the time, the file was already tracked, so the repository still contains this file. As it is outdated, I suggest to remove it. And I believe, that was the intention of the commit back then.

Possible issue: Upon the next `git pull` the file will be removed, even if installations have updated the file since `git clone`. Users will have to execute `/index.php/update/update_clublog_scp` again, or wait until the cronjob does. Is there a way in Cloulog to do this automatically during/after the update?

**Comment by magicbug** [comment]
`update/update_clublog_scp ` will update / download the file its not automaticly run currently
