### ISSUE TITLE
can no longer log in

### ISSUE THREAD

**Issue by nr0q** [magicbug/Cloudlog#417]
After the nightly "auto-update", my install of Cloudlog no longer allows me to log into the program. I go to the page and can see my log but the user/password field and login button are all missing

Installed on my webserver running CentOS 7 and Apache with MariaDB

**Comment by nr0q** [comment]
one thing to note is that GridTracker is still able to push data into my log through the API

**Comment by dg9vh** [comment]
Can you show us some screenshots of the situation?

**Comment by magicbug** [comment]
Nothings changed in the code to effect login, so something else has gone a miss.

You can disable the auth in the application/config/config.php set $config['use_auth'] = true; to false then reset the password and set it back to true.. however I'm interested to know what caused a lock out.

**Comment by nr0q** [comment]
sure, here's screen shots of the web browser tab, database and a 'ls -l' of the main directory

![CloudLog_database](https://user-images.githubusercontent.com/10331370/74610038-3f541880-50b5-11ea-8541-f073f59d0796.png)
![Cloudlog_files](https://user-images.githubusercontent.com/10331370/74610039-3f541880-50b5-11ea-924a-ee6ffa5d818f.png)
![CloudLog_lockedout](https://user-images.githubusercontent.com/10331370/74610040-3fecaf00-50b5-11ea-893c-3be5feeaffca.png)

**Comment by nr0q** [comment]
I tried to change $config['use_auth'] = true; to false and restarted the httpd service just in case and still wouldn't let me in.

**Comment by magicbug** [comment]
Sure your using the master branch of Cloudlog? That looks like v2 if that's the case it's not ready for use

**Comment by nr0q** [comment]
should be the master, might have to re-clone it back and see if that fixes it

**Comment by magicbug** [comment]
Quick give away would be doing /login and /register URLs and if it returns something that looks different then that will give it away

**Comment by nr0q** [comment]
those urls returned 404 errors, I accidently blew away the Cloudlog folder, so no cloning it back but am getting a bunch of error messages, i think i'm going to have to wipe the database and start over from scratch :(

**Comment by magicbug** [comment]
The hrs table is safe plus the profiles but definitely sounds like you switched branch no idea how if you was automating it

**Comment by nr0q** [comment]
i followed the directions on the wiki, so I'm not sure, but i probably will omit that step once I get it working again

**Comment by nr0q** [comment]
I can longer get it running, i've wiped the database and started a new one, wiped the directory and did a new git clone and can't get anything to work, it once worked on this system and now nothing

**Comment by nr0q** [comment]
so the only way I could find to repair an install that accidently got upgraded to V2 is to wipe everything and reinstall, for the record. 

issue closed
