### ISSUE TITLE
resizable map on dashboard

### ISSUE THREAD

**Issue by nr0q** [magicbug/Cloudlog#422]
**Is your feature request related to a problem? Please describe.**
the QSO map on the dashboard (home) page is wide enough but not tall enough to show the whole CONUS unless you zoom out a bit, then it shows a lot of oceans on the sides and all the pins are on top of each other. 

**Describe the solution you'd like**
I went to Inspect Element in my browser and resized the map to be 400px tall and it looks a lot better, but some users may not like the map that big, I suggest making the map height a user settable option somewhere. 

1st screen shot is the default map size setting
![Logbook_20200227_125723](https://user-images.githubusercontent.com/10331370/75476761-c67c7880-5960-11ea-807e-331c62732778.png)

2nd screen shot is after I changed the map size
![Logbook_20200227_123854](https://user-images.githubusercontent.com/10331370/75476808-dd22cf80-5960-11ea-8a9f-ae6e4196f8bb.png)

**Comment by magicbug** [comment]
Currently, no plan to add this perhaps further down the road but users are free to change code on their local copies.
