### ISSUE TITLE
selected General -> Propagation mode setting doesn't stay for next QSO

### ISSUE THREAD

**Issue by AD7Djoe** [magicbug/Cloudlog#424]
**Describe the bug**
For every  QSO I make, I still have to go to General -> Propagation mode -> Satellite.

I have QO-100 and SSB selected and these are sticky for each QSO.

If I do not set the propagation mode, then export, uploading to LOTW flags the entries as not having SAT mode selected.

**To Reproduce**
1.  Start a QSO.
2.  Select General -> Propagation mode -> Satellite
3.  Select QO-100 and SSB.
4.  Fill in the usual items and Save QSO.
5.  Start another QSO.
6.   General -> Propagation mode -> is blank.

**Expected behavior**
The value for General -> Propagation mode -> Satellite is sticky and is applied to each QSO.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by magicbug** [comment]
Is this in Live QSO mode or Post?

**Comment by AD7Djoe** [comment]
Live QSO mode.

**Comment by magicbug** [comment]
Interesting, I know for me when I populate Sat Name/Mode Cloudlog in the background will add Prop Mode, but i dont think it populates the frontend select but its certainly saved against the QSO as thats how I do it for QO-100

**Comment by AD7Djoe** [comment]
OK… yea, thought it was all fine, but then LOTW flag me on some QSOs and sure enough, SAT wasn’t in those QSO so I went and edited the QSO, download, and upload to LOTW then they made it in.

**Comment by magicbug** [comment]
While I couldn't see a bug with SAT_NAME not making prop_mode set, I have added code so that a session is set and Prop_mode is shown to track the previous QSO till cleared unless radio "satpc32" is selected then when you unselect the radio the prop mode is reset.
