### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by oe3ide** [magicbug/Cloudlog#428]
Hi,
I tried to run cloudlog on my hosting-package (webspace, mysql databae). Install was successful, but I get some errors:

Severity: Warning
Message:  mysqli::real_connect(): Persistent connections are disabled. Downgrading to normal
Filename: mysqli/mysqli_driver.php
Line Number: 201

Severity: Warning
Message:  ini_set(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s): (/home/.sites/805/site1069704/web:/home/.sites/805/site1069704/tmp:/usr/share/pear:/usr/bin/php_safemode)
Filename: drivers/Session_files_driver.php
Line Number: 108

Any ideas?
73 de Ernst, OE3IDE

**Comment by oe3ide** [comment]
Ok, first error (persistent connections) solved, I changed pconnect from true to false.

**Comment by magicbug** [comment]
Session info can be changed in /application/config/config.php but this is normally fine. Sadly it's not a Cloudlog issue but a web host problem so you'll need to speak to them.
