### ISSUE TITLE
Failed to boot 'VFS unable to mount root fs..' on Pi image version

### ISSUE THREAD

**Issue by g0cer** [magicbug/Cloudlog#433]
**Describe the bug**
I downloaded the Pi distro which includes Cloudlog pre-installed from this site. 
On booting DMEG gets as far as :
[   1.54273 ---[ end Kernel panic - not syncing: VFS unable to mount root fs on unknown-block(179,2) ]---

Note I've transcribed that from the pi boot screen not pasted it but its accurate.
I have downloaded it twice and tried two seperate writer programs to write to the card in the Pi
Same error each time & multiple attempts at booting.

The Pi is Pi 3 Model  v1.2

**To Reproduce**

**Expected behavior**
full boot

**Screenshots**
See attached photo of screen
![IMG_1621](https://user-images.githubusercontent.com/1623041/76554238-6ec82c00-648d-11ea-9671-f3f1d05b37f6.JPG)
.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
The Pi only has a wifi card in to connect to a keyboard - I have tried booting it without any
The Pi connects directly into a monitor via a HDMI >DVI interface which works normally this and other version.
The pi works normally with other OS cards in place.

**Comment by magicbug** [comment]
Pi image is broken hence removed it from the wiki front-page, will work on improving it in the coming days.

**Comment by g0cer** [comment]
Hi Peter 
I see the page is still on the wiki linked to the february version that won't boot as per above  
https://github.com/magicbug/Cloudlog/wiki/Raspberry-Pi-Image-Information
I must be the only one trying this or having this issue, I'd be interested to see if others have booted it.
Dave G0CER
