### ISSUE TITLE
Country not found

### ISSUE THREAD

**Issue by ClaudeMa** [magicbug/Cloudlog#438]
**Describe the bug**
some days cloudlog stoped setting country name in new QSO 

updating DXCC retrun this

> Updating...
> Dxcc Entities: 402
> Dxcc Exceptions: 1050
> Dxcc Prefixes: 0

And check missin return

> 0 updated

update directory contains these files
![Capture1](https://user-images.githubusercontent.com/2773730/76708881-aa1b6280-66fa-11ea-821c-b9a8714495a8.PNG)

Any idea?
Thank

![Capture](https://user-images.githubusercontent.com/2773730/76708751-9fac9900-66f9-11ea-9278-5ab2a7917a5a.PNG)

**Comment by dg9vh** [comment]
![image](https://user-images.githubusercontent.com/13950650/76709080-177bc300-66fc-11ea-9f97-6fd0e7aa8f78.png)
You should try with waiting till the update process is done... as I can see, you changed to another side while updating.

The process could take a minute depending on your internet-connection.

73 de Kim
DG9VH

**Comment by magicbug** [comment]
Beat me too it, just leave it to run, speed will depend on hosting environment how quick it completes.

**Comment by ClaudeMa** [comment]
Two days that i try, screenshot is take after 20mn waiting.

 "Done " is never show


retrying and retrying finished working maybe an  issue with clublog

Many thanks for help
