### ISSUE TITLE
Imported adif logs don't get flagged for LoTW

### ISSUE THREAD

**Issue by m0pcb** [magicbug/Cloudlog#445]
When live logging a QSO both teh QSL and LoTW columns are filled with red arrows to show that QSLs haven't been exchanged.

When importing an ADIF file these arrows are not present in the LoTW column, but they do get populated for QSL card.

**Comment by magicbug** [comment]
While its not a "bug" just the data isn't available if the arrows didnt show the default if data isn't present should just be show the red arrow.

**Comment by AndreasK79** [comment]
I added a PR #457 with a few options to the ADIF import, and among them, option to mark all QSOs as exported to LoTW.

**Comment by magicbug** [comment]
Looks sorted to me, thanks
