### ISSUE TITLE
Add Satellites to the Band Selection of Analytics / Gridsquares 

### ISSUE THREAD

**Issue by dl6kbg** [magicbug/Cloudlog#450]
First of all i like to say thank you for the nice piece off software.

I stumbled upon working lienar satellites for the last weeks. It would be cool to be able to add the satellites to the band selection list.  The Arrl Lotw Satellite name apears in the Logbook as Band.

While adding this it might be useful to add the satellites list like it is in TQSL available as dropdown list.

Many thanks and 73 Oliver DL6KBG

**Comment by magicbug** [comment]
Satellites appear in the band column purely because of limited UI space so that's only reason, within time I might allow further dropdowns got the gridmap but not within the current system.

Other issue has already been tasked with its own todo.
