### ISSUE TITLE
Renamed: Cannot download country files from Clublog (Cannot create station profile)

### ISSUE THREAD

**Issue by janipewter** [magicbug/Cloudlog#453]
Cannot create station profile because DXCC field is required but is not available.

Update Dxcc button in Admin -> Update country files also doesn't work. Nothing happens when clicking it.

Ubuntu 18.04.4
nginx 1.16.1
PHP 7.4.4

**Comment by magicbug** [comment]
If the Update Country Files isn't working then you have an issue with your configuration, best bets check you have folder permissions correct, all the modules installed (see https://github.com/magicbug/Cloudlog/wiki/Installation) and check your local log files for errors.

The Update Country Files can take a while to run if you have a slow system.

**Comment by janipewter** [comment]
OK thanks, it was a permissions issued. I changed ownership on the entire Clublog directory and that seems to have solved it.
