### ISSUE TITLE
documentation: how to install on a Mac with packages from Homebrew (brew)

### ISSUE THREAD

**Issue by vielmetti** [magicbug/Cloudlog#456]
I'm looking to install this on a Mac, running locally, with packages installed via Homebrew (brew).

I'll take some notes here, with a goal of writing them up for others to use, with details for a PR or a wiki entry.

If anyone has done this I'd appreciate any notes to share, I didn't see any instructions on the issue list.

So far this is what I have:

```
brew install nginx
brew services start nginx
brew install php
brew install mysql
brew services start mysql
```

**Comment by magicbug** [comment]
@vielmetti I'm not aware of any Homebrew guides but if you want to put something together happy to add it to the wiki.

**Comment by magicbug** [comment]
As theres been no interest in this and its not a issue with the codebase I'm closing the issue.
