### ISSUE TITLE
Power level via ADIF (Add Power Level input to station tab and QSO popup)

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#458]
Is there a way to import and surface power levels via ADIF? These show in the QRZ log after import, but not Cloudlog.

**Comment by magicbug** [comment]
If they we're included in the ADIF file on import they will be in the database I just never exposed the data.

**Comment by m0pcb** [comment]
I like the idea of logging and seeing power level too.

Iain AD5XI/M0PCB

**Comment by magicbug** [comment]
I'll add an input to the "station" tab for now and show on the details of QSOs when clicked will get that done later this evening / tomorrow

**Comment by magicbug** [comment]
Started addressing this request in commit https://github.com/magicbug/Cloudlog/commit/625f828bd5b8e015f4129d0af68ebd29b12fb189 just need to add the input box next

**Comment by magicbug** [comment]
This is now fully addressed

**Comment by ofadam** [comment]
Is this retroactive for any ASIF imports, or do I need to reimport? Does the field only support raw numbers or "W" for watt on the end?

**Comment by magicbug** [comment]
ADIF spec is power level in watts (number only), if adifs with this data has been imported & was valid then the data will be there.
