### ISSUE TITLE
Allow Custom Fetch Date for LOTW Data Pull

### ISSUE THREAD

**Issue by pa3ang** [magicbug/Cloudlog#465]
Peter,

how can i download all LOTW confirmations starting from 2001-01-06 . When doing the ADIF upload out of HRD, i'm missing all the LOTW verified QSO and when downloading in Cloudlog it's fetching only some last QSOs.

Regards,
Johan, PA3ANG

**Comment by magicbug** [comment]
Hi @pa3ang,

At the moment it's done by checking the log to see when the last confirmation was guess better option might be adding an option to download all via a checkbox?

in Controller lotw.php
``
$lotw_last_qsl_date = date('Y-m-d', strtotime($this->logbook_model->lotw_last_qsl_date()));
``

**Comment by pa3ang** [comment]
Hi Peter, 

Yes could be a good candidate to be added as more people would like to
migrate to cloudlog with their current logbook solouting. 

I downloaded all qso in the mean time by tweaking this line 'hard coded'
as a one off. 

//$lotw_last_qsl_date = date('Y-m-d',
strtotime($this->logbook_model->lotw_last_qsl_date()));
$lotw_last_qsl_date = "2000-01-01";

73 Johan 

Peter Goodhall schreef op 2020-04-20 12:44:

> Hi @pa3ang [1], 
> 
> At the moment it's done by checking the log to see when the last confirmation was guess better option might be adding an option to download all via a checkbox? 
> 
> in Controller lotw.php
> $lotw_last_qsl_date = date('Y-m-d', strtotime($this->logbook_model->lotw_last_qsl_date())); 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1] https://github.com/pa3ang
[2]
https://github.com/magicbug/Cloudlog/issues/465#issuecomment-616466598
[3]

**Comment by magicbug** [comment]
Changed title so its more obvious and added feature tag :)
