### ISSUE TITLE
WFF field in QSO entry

### ISSUE THREAD

**Issue by ok1cdj** [magicbug/Cloudlog#468]
Please add field for WFF like is for SOTA, DOK...

**Comment by magicbug** [comment]
Only reason they are three is the fact that it's defined in the adif spec my suggestion would be if you need something to track it tag in comment "WFF:#ref#" but it would need it's own awards page good example is the WAB one which works in a similar way.

**Comment by magicbug** [comment]
I mean I don't mind adding another field for WFF and having an exposable field if its really required open to ideas and suggestions.

**Comment by ok1cdj** [comment]
Ok, i will use comment field.
