### ISSUE TITLE
Pull LoTW data not working

### ISSUE THREAD

**Issue by ok1cdj** [magicbug/Cloudlog#469]
See screenshot. Any idea where is problem ?
![screencapture-log-ok1cdj-index-php-lotw-import-2020-04-20-07_51_25](https://user-images.githubusercontent.com/672504/79718404-43323000-82dc-11ea-8cf8-8d553d9fa224.png)

**Comment by magicbug** [comment]
Most likely to be incorrect login details

**Comment by ok1cdj** [comment]
It was bad login, now it will end on timeout. I have on LOTW over 20 000 qsos, but to cloudlog i imported only year 2020. Will it works or not ?

**Comment by ok1cdj** [comment]
Solved..
