### ISSUE TITLE
"Any band" support for gridsquare map

### ISSUE THREAD

**Issue by M0LTE** [magicbug/Cloudlog#470]
**Is your feature request related to a problem? Please describe.**
I can't see a map of all the grids I've worked.

**Describe the solution you'd like**

The following works: 
https://cloudlog.m0lte.uk/index.php/gridsquares/band/20m

It would be nice if the following (or similar) worked the same as above:
https://cloudlog.m0lte.uk/index.php/gridsquares/band/all

**Comment by magicbug** [comment]
So ALL would be everything in the log? or you thinking narrowing it down 

- HF
- VHF
- UHF

etc?

**Comment by M0LTE** [comment]
All is what I had in mind.

Could also accept HF/VHF/UHF as well I guess?

Would be nice to have a checkbox to be able to show or hide numbered grids irrespective of zoom level too.

**Comment by M0LTE** [comment]
Legend :)

It's ace. Thanks.

**Comment by hairlesshobo** [comment]
> Would be nice to have a checkbox to be able to show or hide numbered grids irrespective of zoom level too.

Was this also added when you added the "all" drop down selection, or would I need to create a new feature request for it. Currently, I have to zoom in much more than I would prefer in order to be able to see numbered grids. 

Thanks!

**Comment by AndreasK79** [comment]
This was not added. I am also interested in this, but I'm not sure how to control the zoom and the displaying of the gridsquares.

**Comment by AndreasK79** [comment]
@hairlesshobo please create a new issue for this feature.

**Comment by hairlesshobo** [comment]
@AndreasK79  will do!
