### ISSUE TITLE
Edit / delete QSO : Trying to get property of non-object

### ISSUE THREAD

**Issue by m0boy** [magicbug/Cloudlog#493]
Multiple PHP notices when trying to edit/delete QSO, 
A PHP Error was encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: qso/edit.php

Line Number: 49
">
End Date/Time.. same for multiple actions, Line numbers: 49,54, 60,63, 121,126,137,146,158,163,168,195,225,331,497

Add dummy QSO, then click the QSO, Edit QSO then Delete QSO.

![Screenshot from 2020-05-10 11-08-04](https://user-images.githubusercontent.com/65112878/81496489-e230c300-92af-11ea-95f5-b40b6a8a1678.png)
![Screenshot from 2020-05-10 11-07-54](https://user-images.githubusercontent.com/65112878/81496490-e2c95980-92af-11ea-9856-9fcf083ec378.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [Firefox,]
 - Version [latest]

**Smartphone (please complete the following information):**
 - Device: [iPhoneXSMax]
 - OS: [Latest IOS]
 - Browser [Safari]
 - Version [built in]

**Additional context**

**Comment by magicbug** [comment]
Something not right there, what was the contents of the dummy QSO?

**Comment by magicbug** [comment]
Also worth asking is this the latest version from git or older

**Comment by m0boy** [comment]
Hi, Was having this issue since first time installed cloudlog about 6mo ago. Content of QSO is irrelevant, is doing it with any qso. Did not pay attention to it as I was able to delete the QSO if needed so. However good habbits to report issues. 
Updated cloudlog 2 weeks ago.

**Comment by magicbug** [comment]
Yeah that's not right, I'm guessing country files updated.

I'll go through the errors see if I can figure out what's up but that's not normal behaviour

**Comment by m0boy** [comment]
![Screenshot from 2020-05-10 12-58-21](https://user-images.githubusercontent.com/65112878/81498626-f11e7200-92bd-11ea-9504-b46e9720518b.png)
Might be useful :)

**Comment by magicbug** [comment]
That is rather a bazaar issue looking at the code errors report to fields being echoed so if this was a widespread issue I'd have seen it, or I'd hope so.

Can you do a more recent code update, not convinced it will make any difference but the rare chance it might? thats basically saying nothings coming back from the server which feels unlikely.

**Comment by magicbug** [comment]
Going to tag @dg9vh and @AndreasK79 just on the off chance they have an idea.

**Comment by m0boy** [comment]
Update didn't help. Something really stuck there, created a fresh install in a new folder with new database: 
![Screenshot from 2020-05-10 17-00-39](https://user-images.githubusercontent.com/65112878/81504220-e5dc3e00-92df-11ea-96b7-b2cc8e053aeb.png)

Please note that I had this problem very first day on my first install.

**Comment by dg9vh** [comment]
Hi,
as I can see, this is only(!) a notice-error-message, so it could be ignored and the webserver itself should be configured to suppress this messages...

The cause of this notice could be, that echo $qso->COL_PRIMARY_KEY; is operating on a null-value in $qso, so getting the attribute COL_PRIMARY_KEY of this would end in such an errormessage.

Question is, why $qso would be null?

**Comment by AndreasK79** [comment]
Can't say I understand what's going on here, but since a new install works, something must have happened with the old install. @m0boy do you get the same error if you switch to the old databasen in the new folder?

**Comment by m0boy** [comment]
The only occurence I managed to make it work is the one above. Did 3 reinstalls since and all coming up with the error. 3 different databases. files uploaded through FTP.
https://logbook.m0boy.uk/index.php please feel free to log in with defaults (m0abc) and test

**Comment by buhalo1** [comment]
Just installed cloudbook and having the same issue. 
$config['directory'] = "/logbook";
$config['base_url']	= 'https://callsign.radio1234.org/logbook/';

**Comment by dg9vh** [comment]
I think you doubled the information... try to let config[directory] empty...

**Comment by buhalo1** [comment]
Tried to make clean install. Got the following screen on first run.

![cloudlog](https://user-images.githubusercontent.com/54483056/82751590-eb965100-9dc0-11ea-8f79-3143daeb5873.jpg)

**Comment by dg9vh** [comment]
What happend after login and creating an own user and setting station profile?

**Comment by dg9vh** [comment]
By the way: this is just a notice-message that could be ignored... you should configure your php.ini to suppress such notices on production-services.

**Comment by buhalo1** [comment]
Those notices dissapeared on page refresh. 
QSO delete errors are still there.

**Comment by magicbug** [comment]
This is definitely relating to a configuration with a server as if it was the code it would have been reported by everyone using it., hiding those errors doesn't fix the problem they shouldn't exist in the first place, 

My first suggestion would be to use a newer PHP version, development-wise I'm testing on PHP 7.3 & 7.4.. 7.3 is certainly stable. 7.0.33 is end of life since the start of 2019

**Comment by buhalo1** [comment]
After successful QSO removal it tries to get back to previous page which is the QSO edit page, then it tries to populate fields on this page by quering the content of QSO fields from database. The error is that it tries to load data for QSO that just been removed.
