### ISSUE TITLE
Can't create country entry (station DXCC)

### ISSUE THREAD

**Issue by K6TD** [magicbug/Cloudlog#495]
When creating station profile, station DXCC label exists, but, no entry box, nor pull down is present.  When profile is created, country is blank.

73, K6TD

**Comment by magicbug** [comment]
As per the wiki install make sure you have updated the country files via the Admin dropdown (https://github.com/magicbug/Cloudlog/wiki/Installation)

**Comment by K6TD** [comment]
Perhaps change the order of tasks in the wiki, under Linux, to show update DXCC files before creating a station profile.

Updating DXCC solved the issue of can't add station DXCC to station profile.

**Comment by magicbug** [comment]
Fixed 👍
