### ISSUE TITLE
Hint on CloudLogCatQt

### ISSUE THREAD

**Issue by myzinsky** [magicbug/Cloudlog#501]
Hi, 

Since I'm a Mac user. I created a cross plattform tool for the remote CAT control that works together with FlRig: https://github.com/myzinsky/CloudLogCatQt

It would be nice if you could also link it in the right places in the readme and the wiki. 

vy 73 de DL9MJ, Matthias

**Comment by magicbug** [comment]
Fantastic, I'm happy to get it added to the wiki, I've cleaned up the readme making it a little less chaotic.

**Comment by magicbug** [comment]
@myzinsky Thanks for building this tool, I've added it to the wiki and given it a mention on the @cloudloghq twitter account! 👍

**Comment by myzinsky** [comment]
Thx! Next project is a cross plattform app for pc, mac, android, linux as offline logbook for SOTA and outdoor activities with no LTE that pushes automatically the QSOs to cloudlog when back to Wifi or LTE ;-)

**Comment by magicbug** [comment]
Shout if you need anything from the API, sounds like local app with database that kicks the API when connections back so that should all be available

**Comment by myzinsky** [comment]
Yes I will do certainly. Is the documentation in the wiki complete? Or should I look in the source code?

**Comment by magicbug** [comment]
90% complete always check source in case i added something
