### ISSUE TITLE
Gateway Timeout

### ISSUE THREAD

**Issue by SA7BNT** [magicbug/Cloudlog#504]
Hallo, im always getting "Gateway Timeout" after i save a Live QSO.
![2020-05-20 20 25 31](https://user-images.githubusercontent.com/35367117/82483069-12f6d080-9ad8-11ea-8c9f-514de859c4ee.jpg)

When im looking in the apache2 error log im getting this 
`[Wed May 20 20:19:04.715789 2020] [proxy_fcgi:error] [pid 16383:tid 140115656767232] (70007)The timeout specified has expired: [client 46.230.209.71:22989] AH01075: Error dispatching request to : (polling), referer: https://sa7bnt.funkerportal.de/Cloudlog/index.php/qso?manual=0`

Can someone help me figure out my issue?

73 
Tim de SA7BNT

**Comment by magicbug** [comment]
As this is not a code issue and misconfigured web server I'd suggest asking for help on the forum rather than on the bugs tracker for Cloudlog

However I'd suggest Googling the error as its todo with FPM timeouts increasing that will likely fix the problem

See https://forum.cloudlog.co.uk/
