### ISSUE TITLE
QSO detail window oversized after search

### ISSUE THREAD

**Issue by Ciemon** [magicbug/Cloudlog#511]
Whilst testing the new QRB feature I searched for a recent QSO and noticed that the QSO detail window, accessed by clicking a link from the search results is expanded to a large percentage of screen width rather than the usual size.

![searched qso](https://user-images.githubusercontent.com/570513/82747791-9ba19500-9d94-11ea-82fc-6bd741b7ef91.png)

**Comment by magicbug** [comment]
Yep looks like i didnt do sizing on that bug needs addressed

**Comment by Ciemon** [comment]
If it's a matter of copying the code from the main qso window to this one, I could do that if I knew which files it was.

**Comment by magicbug** [comment]
Changed the code but it made zero difference so there's something else going on, will need to look when more brain cells are firing

**Comment by AndreasK79** [comment]
This will no longer be an issue when PR #629 is merged. Bootstrapdialog has now been implemented.
