### ISSUE TITLE
Database error on parameter station_dxcc when trying to create new station

### ISSUE THREAD

**Issue by sc0tfree** [magicbug/Cloudlog#532]
When trying to create a station on a brand new installation, I am greeted with the following error message:

```
A Database Error Occurred
Error Number: 1366

Incorrect integer value: '' for column 'station_dxcc' at row 1

INSERT INTO `station_profile` (`station_profile_name`, `station_gridsquare`, `station_city`, `station_iota`, `station_sota`, `station_callsign`, `station_dxcc`, `station_country`, `station_cnty`, `station_cq`, `station_itu`, `state`, `eqslqthnickname`, `qrzapikey`) VALUES ('Long Island', 'FN00AA', 'City Name Here', '', '', 'KXXXXX/P', '', '', '', '5', '8', 'NY', '', 'XXXX-XXXX-XXXX-XXXX')

Filename: models/Stations.php

Line Number: 52
```

The application is hosted on a default LAMP stack on Vultr (via their one-click applications). All wiki instructions have been followed precisely, except for the fact that I installed into the webroot, rather than the cloudlog directory.

Please see the following screenshot:

![image](https://user-images.githubusercontent.com/25855134/83901158-4e280f00-a728-11ea-97fc-c601ecac6520.png)

**Comment by magicbug** [comment]
Please follow the wiki guide fully https://github.com/magicbug/Cloudlog/wiki/Installation and Update Country Files before creating station profiles.
