### ISSUE TITLE
Post QSO, date time spaces

### ISSUE THREAD

**Issue by git1k2** [magicbug/Cloudlog#533]
**Describe the bug**
Just started using Cloudlog on a self hosted container (Debian 10). Entered about 40 QSO's yesterday, without problem. Today when i wanted to add another Post QSO, the date and time had extra spaces around them. 

Here is a copy/paste from the Date and Time input fields, i added square brackets for visualization:
```
[                  05-06-2020                       ]
[                  19:39                    ]
```

When i saved the QSO, i got the error:
```

A Database Error Occurred

Error Number: 1292

Incorrect datetime value: '2020-06-05 19:39 ' for column `cloudlog`.`TABLE_HRD_CONTACTS_V01`.`COL_TIME_ON` at row 1

INSERT INTO <redacted>

Filename: models/Logbook_model.php

Line Number: 338
```

When i manually removed the spaces around the date and time i was able to save to QSO correctly.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on Post QSO.
2. Enter a call sign.
3. Click on Save QSO.

**Expected behaviour**
To be able to log a QSO without error.

**Screenshots**
![cloudlog_spaces](https://user-images.githubusercontent.com/48857344/83917209-c1f10880-a776-11ea-98e4-69dbf7eb2671.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox 77.0.1 / Chrome 83.0.4103.97

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by magicbug** [comment]
Thanks confirmed this is a bug will be resolved tomorrow.

Apologies!

**Comment by git1k2** [comment]
Thanks!
