### ISSUE TITLE
Hawaii showing as worked status in dxcc list, but no Hawaii contacts.

### ISSUE THREAD

**Issue by mbridak** [magicbug/Cloudlog#535]
Hawaii is showing as worked in the DXCC awards page, but I have no Hawaii contacts.

**To Reproduce**
Click Awards -> DXCC -> Show button

**Expected behaviour**
Not to show entities as worked/confirmed when no log exists for the entity.

**Screenshots**
Here's the shot showing worked.
![Screenshot from 2020-06-09 06-40-08](https://user-images.githubusercontent.com/49108421/84156484-6779d580-aa1e-11ea-8a97-c38e8c726b4a.png)

Here's a shot after clicking the 'W' to show filtered log.
![Screenshot from 2020-06-09 06-43-58](https://user-images.githubusercontent.com/49108421/84156524-7496c480-aa1e-11ea-8d0d-cbf84095e55d.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Chrome
 - Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by dg9vh** [comment]
Hi,

Please update DXCC-List und Re-Check ALL after this...

![image](https://user-images.githubusercontent.com/13950650/84157795-6f139b80-aa6b-11ea-884d-80516111d098.png)

Then retry again your DXCC-Awards list.

**Comment by mbridak** [comment]
Did those.
![Screenshot from 2020-06-09 07-11-49](https://user-images.githubusercontent.com/49108421/84158533-d48e6a80-aa20-11ea-817e-70a02a2583b5.png)

![Screenshot from 2020-06-09 07-12-12](https://user-images.githubusercontent.com/49108421/84158565-deb06900-aa20-11ea-9124-c2fc8eb9de5a.png)
![Screenshot from 2020-06-09 07-12-37](https://user-images.githubusercontent.com/49108421/84158580-e40db380-aa20-11ea-9558-1c06542f7d69.png)
![Screenshot from 2020-06-09 07-13-09](https://user-images.githubusercontent.com/49108421/84158618-ecfe8500-aa20-11ea-9f65-f55c4538f89c.png)

But looks the same...

**Comment by dg9vh** [comment]
vy strange... would be interessting, what your system doing there... @magicbug who did this? Maybe you could put him into this ticket as well?

**Comment by mbridak** [comment]
This guy now shows as Hawaii in the log, but he's in Oregon....

![Screenshot from 2020-06-09 07-22-06](https://user-images.githubusercontent.com/49108421/84159637-24216600-aa22-11ea-9fab-06510bbac3dd.png)

And the WAS award shows no Hawaii

**Comment by magicbug** [comment]
@AndreasK79

**Comment by AndreasK79** [comment]
The only reason I can see that a mismatch between the award display and the qso display is happening, is that in the logbook-table, col_dxcc and col_country exists. If col_country is not set to the correct name according to col_dxcc, you will get this problem.

The award is based on col_dxcc, but the lookup is using col_country. The reason behind this, was that this was how the lookup was built before, and I re-used that.

**Comment by mbridak** [comment]
I preface this with the statement that I have Zero codeigniter/query builder experience.

But in Logbook_model.php public function check_missing_dxcc_id($all). It calls check_dxcc_table($row['COL_CALL'], $qso_date).
And in check_dxcc_table() it just queries dxcc_prefixes with out first checking if there is anything matching in the dxcc_exceptions table.

I believe that's where the problem lies.

**Comment by mbridak** [comment]
I submitted a pull request.

**Comment by magicbug** [comment]
Thanks for the PR 👍
