### ISSUE TITLE
QRZ Upload Fails

### ISSUE THREAD

**Issue by myzinsky** [magicbug/Cloudlog#539]
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/1970554/84957969-a2ee6100-b0fc-11ea-8a77-dca6123437fb.png">

**Describe the bug**
QSOs of one Station Profile are not uploaded. 
**Additional context**
I'm using the current master branch.

**Comment by AndreasK79** [comment]
I'm not sure what is going on here, but my guess would be that QRZ returns an error. There is no easy way to see that error right now. I have it on my TODO-list to present the errors for the user.

If you are comfortable in editing the code and run var_dump on a variable, the error can be seen in devtools in the browser.

**Comment by AndreasK79** [comment]
#571  added now. Errors are logged in logfile.
