### ISSUE TITLE
Period in TX_PWR ADIF field taken as comma during import

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#541]
Is it intentional that the TX_PWR ADIF field is imported with a period acting as a comma?

25.000 watts comes over as 25,000W

**Comment by magicbug** [comment]
Shouldn't be, whats the ADIF record look like?

**Comment by ofadam** [comment]
<TX_PWR:6>25.000

**Comment by ofadam** [comment]
Is that what you need? Let me know if you need more of my log.

FILTER_SANITIZE_NUMBER_INT wouldn't allow a period, right?

**Comment by magicbug** [comment]
Guess it needs sanitised, I thought I'd caught most things but seems not!
