### ISSUE TITLE
Show submode instead of mode in logbook

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#542]
With FT8 and FT4 treated very differently by the ADIF specificiations, would there be a way to have the logbook frontend show the "COL_SUBMODE" field if populated? That would help differentiate these submodes when looking at a long list of QSOs.

**Comment by dg9vh** [comment]
This is part of https://github.com/magicbug/Cloudlog/pull/499 that @magicbug is actually investigating to merge.

**Comment by ofadam** [comment]
Closing issue due to being duplicate.
