### ISSUE TITLE
How to backup adif via cron?

### ISSUE THREAD

**Issue by dg9vh** [magicbug/Cloudlog#544]
I have no idea how to call the backup-routine via cron-job. Does anybody has this feature running?

**Comment by AndreasK79** [comment]
I guess creating a cron-job with like this would work: curl --silent https://<URL-To-Cloudlog>/index.php/backup/adif/> &>/dev/null

If you visit that url your browser, it creates an adif from your log and places it in the backup folder.

**Comment by dg9vh** [comment]
huebelon@s074 [~/cloudlog/backup]# curl  https://cloudlog.dg9vh.de/index.php/backup/adif/
huebelon@s074 [~/cloudlog/backup]# ls
./  ../  notes.xml

So nothing happens...

in browser it also does not work if not logged in... it only works in logged-in-state.

**Comment by AndreasK79** [comment]
@dg9vh Ah yes, you are right, i didn't try that. @magicbug Are we missing something here Peter?

**Comment by magicbug** [comment]
Fixed issue where it was wanting you logged in,

However if you run /index.php/backup/adif it will create an ADIF and store it
