### ISSUE TITLE
Need an option to export only QSOs not marked as sent to LoTW

### ISSUE THREAD

**Issue by nr0q** [magicbug/Cloudlog#545]
When exporting now I can select a day or group of days to export. But uploading those produces duplicate QSOs in LoTW when trying to upload only those that haven't been already uploaded. I have some several hundred QSOs that get automatically uploaded to LoTW and eQSl by Gridtracker at the same that GridTracker sends the QSO to CloudLog. I later that day make a dozen SSB QSOs and log them directly into CloudLog. I'd like to export only those and mark them as QSO Requested thinking there might be a mechanism to export only those. Instead I had to export 400 QSOs and reupload all of the FT8 QSOs along with the handful of SSB ones.

**Comment by AndreasK79** [comment]
Added #546

**Comment by magicbug** [comment]
Merged and fixed
