### ISSUE TITLE
Error LOTW Import

### ISSUE THREAD

**Issue by myzinsky** [magicbug/Cloudlog#556]
When pulling LOTW Data I get recently this error:

<img width="1131" alt="Bildschirmfoto 2020-07-05 um 23 26 41" src="https://user-images.githubusercontent.com/1970554/86542585-170b7000-bf17-11ea-9a4c-e9d36d25d9f1.png">

**Comment by dg9vh** [comment]
This sometimes happens also to me on days selected for starting and having absoultely no confirmations on lotw-side on it...

Please check date starting your import... maybe you selected a date in future?

**Comment by tekk** [comment]
Same issue here.

**Comment by kd8skz** [comment]
Go ahead and add me to this list as well, I thought it was a issue with my database, but I guess not.

**Comment by magicbug** [comment]
I've only see this happen when LOTW services are not working, the feature certainly seems to be working.

I've added some further error checking to make this more graceful
