### ISSUE TITLE
Distance calculation problem in 'views/view_log/qso.php' when 'measurement_base' is changed to km

### ISSUE THREAD

**Issue by jtmnt** [magicbug/Cloudlog#559]
QSO Details popup calculates distance in miles even after changing 'measurement_base' to 'K' in config/cloudlog.php

It seems the problem is in application/views/view_log/qso.php file, [line 78](https://github.com/magicbug/Cloudlog/blob/36621b1e23174d93055e59fccf36847a4b48f4ef/application/views/view_log/qso.php#L78)

The 'measurement_base' changes the display label, but not the calculation itself:

```
echo $CI->qra->distance($row->station_gridsquare, $row->COL_GRIDSQUARE, 'M');
switch ($this->config->item('measurement_base')) {
    case 'M':
        echo "mi";
        break;
    case 'K':
        echo "km";
        break;
    case 'N':
        echo "nmi";
        break;
}
```

**Comment by magicbug** [comment]
This seems resolved in the current codebase
