### ISSUE TITLE
Lotw import for all calls not just main account

### ISSUE THREAD

**Issue by m0pcb** [magicbug/Cloudlog#560]
On using the Cloudlog lotw import it only imports lotw confirmations for the main callsign on lotw and not all lotw confirmations.

When I download the report from lotw webpage I can get a file with all my confirmations in (M0PCB and AD5XI), which cloudlog uploads fine. From the lotw update pull from the cloudlog UI I only get confirmations for M0PCB. Better to use the option for all available calls in lotw and then insert them into the correct profile like the lotw adif uploader does.

**Comment by magicbug** [comment]
Now fixed
