### ISSUE TITLE
$config['measurement_base'] = 'K' not calculating correct

### ISSUE THREAD

**Issue by dg9vh** [magicbug/Cloudlog#567]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**
If you set $config['measurement_base'] = 'K'; in cloudlog.php measurement would be in km-units but value is still calculated by miles.

**To Reproduce**
Steps to reproduce the behaviour:
1. set $config['measurement_base'] = 'K';
2. show QSO Details

**Expected behaviour**
Distance should be calculated correctly.

**Comment by jtmnt** [comment]
I think this is the same: #559

**Comment by magicbug** [comment]
This has been resolved in a recent code commit
