### ISSUE TITLE
Databasename with dots not working

### ISSUE THREAD

**Issue by do5cth** [magicbug/Cloudlog#573]
Hi,

i have my Databasa-Name with dots "cloudlog.do5cth.de".
Cloudlog cant run with these after Install.

Following Error on site:

A Database Error Occurred
Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`do5cth`.`de`' at line 1

SHOW TABLES FROM `cloudlog`.`do5cth`.`de`

Filename: libraries/Migration.php

Line Number: 167

**Comment by AndreasK79** [comment]
They are aware of the issue, but it seems not a priority to fix: https://github.com/bcit-ci/CodeIgniter/issues/3719

**Comment by magicbug** [comment]
Sadly this is a limitation of the framework and isn't likely to get resolved. 

Thus closing
