### ISSUE TITLE
modes table / submodes has to be expanded

### ISSUE THREAD

**Issue by dg9vh** [magicbug/Cloudlog#590]
concerning to the adif-specs we have to enlarge the submodes-field-length... 

I will take a look at the maximum actual length and submit a change on the database-structure this week.

**Comment by magicbug** [comment]
Okay, I'll keep eye out for PR

**Comment by dg9vh** [comment]
Fixed with https://github.com/magicbug/Cloudlog/pull/591

**Comment by magicbug** [comment]
Merged and seems ok
