### ISSUE TITLE
Error when clicking on LOTW export

### ISSUE THREAD

**Issue by myzinsky** [magicbug/Cloudlog#600]
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/1970554/92155020-04ce8500-ee27-11ea-8819-ea15449cbc20.png">

I assume that is something because you did some commits for LOTW?

**Comment by myzinsky** [comment]
Negative, the table and fields are there. Seems to be something with the servers settings...

**Comment by myzinsky** [comment]
Adding this to mysql config solves the problem:
```
sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
```

**Comment by magicbug** [comment]
Made a commit that will mean you no longer need todo that change as it seems quite a few are running MySQL in strict mode
