### ISSUE TITLE
User Profile - Create area to select measurement preference

### ISSUE THREAD

**Issue by magicbug** [magicbug/Cloudlog#611]
Move the measurement preference from cloudlog.php config file to the user table making it definable per profile.

**Comment by AndreasK79** [comment]
@magicbug You can assign this to me.

**Comment by magicbug** [comment]
Thanks, makes more sense to put it per user rather than hidden in the configs.

Then the fun job will be making all the dates across Cloudlog stick to it

**Comment by AndreasK79** [comment]
Yeah, that's the other one. Not sure if I'll tackle that. I might take a look after this one is done.

**Comment by AndreasK79** [comment]
PR #615 created for this.

**Comment by magicbug** [comment]
Thanks! merged
