### ISSUE TITLE
Add Station Profile to the API

### ISSUE THREAD

**Issue by ea1jay** [magicbug/Cloudlog#621]
It would be very useful to be able to indicate to the API the Station Profile where you want to upload the QSOs. Having 2 options: active, which would upload the QSOs to the active station profile in that moment and other option to be the name of the station profile or its number.

**Comment by magicbug** [comment]
Seems reasonable I'm going to suggest we do

` "station_name":"the station profile name"`

Then this can be cross checked to make sure its OK

**Comment by magicbug** [comment]
I've added this as "station_profile_id" this is the number you see when editing a station profile in the url string
