### ISSUE TITLE
Wrong frequency from SatPC-32 Interface (Only QO-100)

### ISSUE THREAD

**Issue by HB9WDF** [magicbug/Cloudlog#631]
**Describe the bug**
It's only with the SatPC-32 Interface
It's only with the QO-100 Satellite
The live shown frequency in the log is correct.
After the saving of the qso, there is a wrong value in the log

**To Reproduce**
I use SatPC32 Version 12.8d with the current version of Cloudlog and the SatPC-32 Interface
For QO-100, I use the following definition in the Doppler.sqf: QO-100,10489740,2400240,USB,USB,NOR,0,0,CW/SSB

1. Choose QO-100 for the QSO
2. Start with "Live QSO" in Cloudlog
3. The Satellite and the Frequencys are correct (TX: 2400240000 / RX: 10489739998)
4. After saving the qso, open the qso in the Log in edit mode
5. The Showing value is: -1894727296 

**Expected behaviour**
Save the right frequency

**Screenshots**
![image](https://user-images.githubusercontent.com/53918535/94527741-bcdd2b00-0237-11eb-87a0-0c5bcca78192.png)

![image](https://user-images.githubusercontent.com/53918535/94430332-fcead200-0193-11eb-8c90-69b751e360f8.png)

![image](https://user-images.githubusercontent.com/53918535/94430167-c2813500-0193-11eb-9e11-012808fc64af.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser All Browsers (Chrome, Firefox, Edge)
 - Current Versions

**Smartphone (please complete the following information):**
- Not tested yet

**Additional context**
There is no problem with other satellites in VHF UHF

**Comment by magicbug** [comment]
Interesting, can i see a screenshot of the desktop satpc<>cloudlog app too please

**Comment by magicbug** [comment]
I've just tried this my end, and can't replicate this using the latest codebase and your doppler line

**Comment by magicbug** [comment]
Are you running the latest codebase or one from a while ago?

**Comment by HB9WDF** [comment]
Hi Peter

 

I updated the issue with the screenshot of SatPC-32 and the Cloudlog interface.

I (hope) hat I running the latest codebase. Last one was a few days ago (via git pull)

 

Cloudlog is installed on a raspi.

 

Maybe it’s not the codebase…

What can I do wrong during installation on a raspi, that I got the wrong data?

 

I have an indication for my proposition: I have still the old blue “pins” on the map. Not the new red dot’s. And I can’t find a line in the config, where I can change that.

Maybe, I did a mistake during the installation process? 



 

Thank you for your support Peter.

 

73s Michael

Hb9wdf

 

 

 

Von: Peter Goodhall <notifications@github.com> 
Gesendet: Montag, 28. September 2020 16:57
An: magicbug/Cloudlog <Cloudlog@noreply.github.com>
Cc: HB9WDF <hb9wdf@bluewin.ch>; Author <author@noreply.github.com>
Betreff: Re: [magicbug/Cloudlog] Wrong frequency from SatPC-32 Interface (Only QO-100) (#631)

 

Are you running the latest codebase or one from a while ago?

**Comment by magicbug** [comment]
Very weird, blue pins indicate update isn't working via git pull that is changed by default.

on the command line when you "type git pull" what do you get if there's errors, can you type "git stash" then do "git pull"

I have a feeling old version!

**Comment by HB9WDF** [comment]
Hi Peter
That I got with git pull today
And with "git stash" and git stash show the following:
73s Michael 
----Ursprüngliche Nachricht----
Von : notifications@github.com
Datum : 29/09/2020 - 12:36 (MS)
An : Cloudlog@noreply.github.com
Cc : hb9wdf@bluewin.ch, author@noreply.github.com
Betreff : Re: [magicbug/Cloudlog] Wrong frequency from SatPC-32 Interface (Only QO-100) (#631)
Very weird, blue pins indicate update isn't working via git pull that is changed by default.
on the command line when you "type git pull" what do you get if there's errors, can you type "git stash" then do "git pull"
I have a feeling old version!

**Comment by magicbug** [comment]
Missed the content however did it update Cloudlog?

**Comment by DG7YEO** [comment]
Have the same issue on my QO 100 QSOs, but I don't use SatPC-32 Interface.

If I edit a QSO I did via QO-100 I see a negative value in the Frequency.
When I added the Frequency in live QSO I add ie 2400000000 when added all other and save the QSO and later would like to edit the QSO Data I get a negative value in the Frequency, see picture below.

![cloudlog_QSO-edit](https://user-images.githubusercontent.com/72309397/94994347-52a9ea80-0597-11eb-81a3-6ede0fbda200.jpg)

73
DG7YEO

**Comment by magicbug** [comment]
@DG7YEO Sorry for delay been unwell, can you confirm if this is on the last version of the codebase on github, I'm guessing its latest, but i genuinely cant replicate the issue so be good to know which version of the codebase is dragging this up.

**Comment by DG7YEO** [comment]
Just made a git pull to be sure, is there anything else need to be done to make sure I'm up to date? 
After that I entered a test QSO and still the same problem. I enter 2400000000 into Frequency but when I got with Edit into the log entry Frequency show -1894792296. 

73
DG7YEO

**Comment by HB9WDF** [comment]
Hi Peter
I made a new install of Cloudlog on my Raspi. Now the update function works fine. It was a wrong installation, that was my mistake. I'm still learning with Linux ;-)
But unfortunately I have still the Issue with wrong value in the Frequency. The Issue is in "Live QSO" and also in "Post QSO". I tryed with the SatPC32 Interface and also with "none" in the Radio selection.
73s Michael
----Ursprüngliche Nachricht----
Von : notifications@github.com
Datum : 29/09/2020 - 23:18 (MS)
An : Cloudlog@noreply.github.com
Cc : hb9wdf@bluewin.ch, author@noreply.github.com
Betreff : Re: [magicbug/Cloudlog] Wrong frequency from SatPC-32 Interface (Only QO-100) (#631)
Missed the content however did it update Cloudlog?

**Comment by HB9WDF** [comment]
I played a little bit around. I figured out, that the highest value is 2147483647. After that, it goes negativ.
So I asked google. It's look like, that is a common issue in MySQL. Maybe the following can help.
https://stackoverflow.com/questions/10255724/incorrect-integer-2147483647-is-inserted-into-mysql.

**Comment by HB9WDF** [comment]
Now I think I have found the main Issue:
2147483647 is the highest number in a 32 Bit system. My Raspi has an ARMv7 Proccessor and I think, it's running only with 32 Bit.
In your online demo, the higher frequencies wirks fine.

**Comment by HB9WDF** [comment]
So, today I installed Ubuntu 64 Bit on a spare barebone pc. byebye win10 ;-)
After that, I installed a LAMP server and Cloudlog. 
Now, it works perfect with the frequency higher than 2147483647.
If somebody have the same issue, then it must be a 32 Bit system. (Older Raspi work with 32 Bit...)
