### ISSUE TITLE
Days QSO Feature (AndreasK79)

### ISSUE THREAD

**Issue by M0TZO** [magicbug/Cloudlog#635]
Sorry to be a pain, as was closed, but the start dates for me don't match on QSO Streak feature.

Current streak shows 80 days _2020-04-25 to 2020-09-30_, but should be _2020-07-13 to 2020-09-30_

Thanks in Advance, sorry for delay in reporting.

**Comment by AndreasK79** [comment]
Nothing to be sorry about. I will take another look at the code.

**Comment by AndreasK79** [comment]
#636 added. This should fix the date issue.

**Comment by M0TZO** [comment]
Yep, looks good now. Thanks.

**Comment by M0TZO** [comment]
Odd, was correct July date yesterday, now reverted. Hopefully will show up in the updates soon. :)

**Comment by magicbug** [comment]
Just merged, should be available to grab

**Comment by M0TZO** [comment]
One last issue. I think it includes the first date which should be day zero. Today should be day 82 when I've worked someone, but already shows 82 and will be 83 when I have a QSO, if that makes any sense.

**Comment by AndreasK79** [comment]
I'm not sure I follow. Day 1 is day 1. It is the consecutive days with QSOs. If you have 5 following days with at least 1 QSO, that is a streak of 5.

**Comment by M0TZO** [comment]
Some would count as day Zero, I'm happy it's working so ignore me, Up to 95 days now :)
