### ISSUE TITLE
QRZ Callsign Lookup

### ISSUE THREAD

**Issue by myzinsky** [magicbug/Cloudlog#637]
I observed that the QRZ callsign lookup does not work anymore, even its configured correctly and it was working before. Has something changed in this code part?

**Comment by dg9vh** [comment]
Can't confirm, on my side it's working as ever... maybe on your side something changed? XML-account expired?

**Comment by myzinsky** [comment]
Hi Kim, negative, with the CloudLogOffline app qrz.com still works. Just checked again the configuration in php, it also looks fine. Therefore, I'm asking :)

**Comment by magicbug** [comment]
Working ok here, I'd suggest logging out and in just in case of something is wonky with the session key from qrz

**Comment by myzinsky** [comment]
@magicbug The QSO upload in the log still works. But the call lookup is not triggered for live and post QSOs. Strange... after a logout and login it works again... seams that you had the right idea :-)
