### ISSUE TITLE
Suggestion - Normalise heading styles

### ISSUE THREAD

**Issue by poll-busily** [magicbug/Cloudlog#652]
**Is your feature request related to a problem? Please describe.**
There are three or four styles used on the admin pages when it comes to headings and sub-text. These are the main ones:

1. One card with small header text and then small description text. E.g Radio Interfaces page
2. As above but the first line of the description text is a large font. E.g. API page
3. Multiple cards, each with bold header text and small description text. A big page title above all cards. E.g ADIF page

**Describe the solution you'd like**
I'd like to clean these up a bit but wanted to check the preferred style before starting any work. We could pick one of the three main styles already in use or define something new. 

I think I like a variation of the third style, maybe with a slightly smaller page title font and non-bold headers for each card. The page title could be set from the $page_title property, just like the browser tab title, and any card titles can be set by hand (if there are several) or can use the same $page_title content again.

**Comment by magicbug** [comment]
@poll-busily Hi Paul sorry for taking a while to get back to you, Yes there needs to be some unification of the page titles, ideally coming off $page_title so page titles and <title> tags match.

I'd suggest we match everything to /index.php/lotw then any titles within the cards are relevant to the data in the box if that makes sense.

Oh and thanks for correcting my spelling it is appreciated and cleans up the interface

**Comment by poll-busily** [comment]
That makes sense to me, yeah. I'll make a first pass and see how it looks.
