### ISSUE TITLE
Feature: Always show Frequency Fields

### ISSUE THREAD

**Issue by myzinsky** [magicbug/Cloudlog#664]
**Describe the bug**
When uploading via the API sometimes the frequency is not shown and the band is not correct:
![image](https://user-images.githubusercontent.com/1970554/96374203-81b48480-1171-11eb-900f-fa49ba100418.png)

**Comment by magicbug** [comment]
Not enough information to debug, if the data is coming via the API, what data was sent?

**Comment by magicbug** [comment]
Also useful to see an SQL export of the QSO

**Comment by myzinsky** [comment]
okay the bug is twofold. As mentioned above it would be nice to show the frequency field also when it is empty. I can create a PR for this. For the Synchronisation Problem I assume its a problem of my app.

**Comment by magicbug** [comment]
Happy for frequency fields to be shown on edit think it would be a useful addition
