### ISSUE TITLE
Uninitialized string offset error in Adif_parser.php on esql import

### ISSUE THREAD

**Issue by M0LTE** [magicbug/Cloudlog#680]
**Describe the bug**
When I run eqsl import, I get the following errors:

A PHP Error was encountered
Severity: Notice
Message: Uninitialized string offset: 158
Filename: libraries/Adif_parser.php
Line Number: 159

A PHP Error was encountered
Severity: Notice
Message: Uninitialized string offset: 158
Filename: libraries/Adif_parser.php
Line Number: 165

Each one appears twice.

The rest of the page renders fine below the errors.

**To Reproduce**
Steps to reproduce the behaviour:
1. Admin -> eQSL import
2. Pull eQSL data for me
3. Import eQSL QSO matches

I pulled from master the other day so I'm pretty up to date.

**Expected behaviour**
Error to not occur

**Comment by magicbug** [comment]
I'm actually not sure what caused it, I'd suggest grabbing the ADIF file from eQSL so we can look at it, but without that cant do too much about it.

**Comment by lu1aax** [comment]
Very same issue here...

**Comment by magicbug** [comment]
Stupid question, but does sending to eQSL work?

**Comment by M0LTE** [comment]
> Stupid question, but does sending to eQSL work?

yes, no errors

**Comment by M0LTE** [comment]
Sent you a (twitter!) DM with a link to my eQSL ADIF export @magicbug

**Comment by M0LTE** [comment]
Still persisting, so I guess not a transient eQSL issue

**Comment by AndreasK79** [comment]
@M0LTE did Peter find anything wrong in the ADIF export from eQSL?

**Comment by M0LTE** [comment]
Not heard back.

**Comment by AndreasK79** [comment]
Ok. I could take a look if you send me a link to your export.
