### ISSUE TITLE
certain systems displaying Wrong frequency for QO-100 QSOs

### ISSUE THREAD

**Issue by DG7YEO** [magicbug/Cloudlog#684]
There was already a report on this together with SatPC-32 Interface which is closed but still can't get this fixed in my setup. Even with the latest update I did today still get negative value in the Frequency field.

If I edit a QSO I did via QO-100 I see a negative value in the Frequency.
When I added the Frequency in live QSO I add ie 2400000000 when added all other and save the QSO and later would like to edit the QSO Data I get a negative value in the Frequency, see picture below.

![cloudlog_QSO-edit](https://user-images.githubusercontent.com/72309397/98103197-f0dde880-1e94-11eb-8880-c27bed3ba9f7.jpg)

As in the other thread shown it seems to be an issue with 32 vs 64 bit, but my systems seems to be 64bit, as far as I can check. My cloudlog setup runs on my virtual webservice at my hoster domain factory.
I checked the system the  system the webserver is runnning on and it is a 64bit system, I can check the DB Server as I don't have access to it. 

I tried to change the frequency values in the database for one QSO using phpmyadmin webgui and when I view this QSO in cloudlog afterwards I shows correct values but as soon as I save the QSO again it change back to the wrong negative value.

![qo100-after-db-change](https://user-images.githubusercontent.com/72309397/98104322-93e33200-1e96-11eb-8257-cce50ef23d7c.jpg)
Above you see correct values after I changed them directly in the DB, now select the RX band and click on save canges in cloudlog and open the QSO again and Frequency is wrong again, see below:
![qo100-after-save-again-in-cloudlog](https://user-images.githubusercontent.com/72309397/98104552-ddcc1800-1e96-11eb-9d46-58cd60fd7247.jpg)

As I can set the correct Frequency directly in the DB I expect it is on a 64bit system and the uname -a on the Webserver sa it is a x86_64 GNU/Linux system this is as well a 64bit. 

Any idea what else I could check? 
73
ELmar
DG7YEO

**Comment by DG7YEO** [comment]
I had a ticket with my webhoster, seems the old webhosting product is not 100% 64bit capable, I now requested an update to a new product which should be 100% 64Bit capable. When this is done I hope that issue is fixed.

**Comment by magicbug** [comment]
I'm closing this issue as its not a Cloudlog issue but rather a user environmental one due to 32bit OS limitations
