### ISSUE TITLE
Please don't load pooper.min.js from Cloudflare.com

### ISSUE THREAD

**Issue by schnitzelbert** [magicbug/Cloudlog#686]
I just found out that Cloudlog is loading its popper.min.js from Cloudflare.

IMHO this should be locally hosted to avoid privacy issues.

Thank you!

**Comment by magicbug** [comment]
PRs accepted, however as you would have seen most things are there's just a few bits lurking that need changed locally.

It's on the to do.

**Comment by AndreasK79** [comment]
PR #689 added.
