### ISSUE TITLE
Add 'My Sig' and 'My Sig Info' to station profile in order to support WWFF or similar

### ISSUE THREAD

**Issue by daccle** [magicbug/Cloudlog#688]
I operate regulary portable in the WWFF (https://wwff.co/) contest/award, so I would like to add a WWFF reference (e.g. DLFF-0029) to my station profile. In the ADIF Export, this should be something like:

`<MY_SIG:4>WWFF <MY_SIG_INFO:8>DLFF-0029`

I am willing to implement this for myself, but I would love to have some help in planning the needed steps and I need somebody to review my code.

**Comment by daccle** [comment]
I've started my work here: https://github.com/daccle/Cloudlog/tree/add_sig_to_station

So far I've edited the model and the view. W

**Comment by magicbug** [comment]
You'd need to create a migration file to add the fields to station profile table then adjust the station profile model and frontend to add these with validation for whatever is expected.

I'll admit wasn't on my roadmap to add but no objection to it.

**Comment by daccle** [comment]
Hi Peter!
I've added the changes to the model, the edit/create view. I've made a migration to the respektive fields into the station_profile table. Now I am struggeling to make sure, that 'sig' and 'sig_info' are added to the QSO.

The TABLE_HRD_CONTACTS_V01 already has the fields COL_MY_SIG and COL_MY_SIG_INFO but I don't know how to populate them. Any advise is kindly appreciated.
