### ISSUE TITLE
Edit QSO: Station "Transmit Power (W)" is not viewable or editable

### ISSUE THREAD

**Issue by TrystanDavies** [magicbug/Cloudlog#695]
Description:
Once a QSO is entered, the Station "Transmit Power (W)" is not viewable or editable if the Edit QSO option is selected. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to gear icon next to a QSO
2. Select Edit QSO from the dropdown
3. Look for Transmit Power (W)

**Expected behaviour**
It should be possible to edit a QSO and enter the transmit power. 

**Desktop**
 - OS: Fedora 33
 - Browser Chrome
 - Version 85.0.4183.102 (Official Build) (64-bit)

Best regards,
Trystan G0KAY

**Comment by daccle** [comment]
I've opened a pull request to fix this.

**Comment by TrystanDavies** [comment]
Thanks Daccle

**Comment by daccle** [comment]
You're welcome.
73, DC2ZP
