### ISSUE TITLE
Date preference not reflected on Live QSO or Post QSO pages

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#697]
The date preference specified in the user profile isn't reflected correctly on the Live QSO or Post QSO pages.

**Comment by magicbug** [comment]
Correct aware it's been on my to-do list but keeps nudging down the list.

**Comment by dgdavid** [comment]
> The date preference specified in the user profile isn't reflected correctly on the Live QSO or Post QSO pages.

Neither in the [QSO widget](https://github.com/magicbug/Cloudlog/blob/fba3a16ecc2796e3fbfadea663381cafcdb2dd06/application/views/widgets/qsos.php#L29), as said in  https://github.com/magicbug/Cloudlog/discussions/767#discussioncomment-269505

**Comment by magicbug** [comment]
> > The date preference specified in the user profile isn't reflected correctly on the Live QSO or Post QSO pages.
> 
> Neither in the [QSO widget](https://github.com/magicbug/Cloudlog/blob/fba3a16ecc2796e3fbfadea663381cafcdb2dd06/application/views/widgets/qsos.php#L29), as said in [#767 (comment)](https://github.com/magicbug/Cloudlog/discussions/767#discussioncomment-269505)

QSO Widget should be addressed

**Comment by T012m3n7oR** [comment]
Live QSO - I believe this is in footer.php around [line 506](https://github.com/magicbug/Cloudlog/blob/50cd201573743cbb075c559eda51a7696175e678/application/views/interface_assets/footer.php#L506).  With this being the js, I'm not entirely sure how to convert the date format that is stored on the user profile to the js format string without writing a conversion function, or some kind of dictionary/array lookup.

Post QSO - Appears to be in index.php around [line 45](https://github.com/magicbug/Cloudlog/blob/4cfc4451e6c2d019eefabe07a0abb700b84d6ade/application/views/qso/index.php#L45).  The math that it is completing on 45/47 I don't completely understand.  When will server time ever be 24+ hours (86,400 seconds) off of UTC time?  I don't understand the use of the hidden fields between lines 53-57 either, but they appear to only be used on Live QSO and not related to this issue directly as far as I can tell.

**Comment by AndreasK79** [comment]
@T012m3n7oR Yeah, that is correct. I don't know how to do this in JS, that's why I haven't fixed it. I don't know if @magicbug knows either.

If I remember correctly, the calculation that is done, is to check if the stored date is less than 24 hours old. if it is, use it, if not use current.

**Comment by T012m3n7oR** [comment]
@AndreasK79 I actually just fixed this locally.  You can call PHP in the middle of the JS... so it's definitely dirty, but you can use that to look up the user's setting, and then I'm doing str_replace to replace the values to the jclock equivalents.

I've since tested a few different time formats with the saving QSO post and Live pages and they still seem to work without issue.

I'll PR probably within the next hour or two.

**Comment by AndreasK79** [comment]
@T012m3n7oR guess we solved that PR problem. Great that you found a solution, even though it's a dirty fix.

**Comment by T012m3n7oR** [comment]
@magicbug wasnt this reverted?
