### ISSUE TITLE
Allow users to turn on or off QRZ Real time when saving a QSO in real time

### ISSUE THREAD

**Issue by magicbug** [magicbug/Cloudlog#709]
While I don't use the QRZ feature, I've had a number of people request being able to return off real-time sending to QRZ when saving a QSO and I fully support this, as it's far better suited to a background task.

However I can appreciate some might like to keep this feature, thus I suggest we make this selectable by the user, this might be better under Station Profile or might spur on #630 on a table for global configuration options

**Comment by AndreasK79** [comment]
I'll fix this. I'll put a dropdown to the right of the API Key in the Station Profile. I feel it belongs there, as the API Key is station profile based.

**Comment by AndreasK79** [comment]
#712 added.

**Comment by magicbug** [comment]
Thanks @AndreasK79 merged
