### ISSUE TITLE
Improvement to QRZ Logbook Upload Cron

### ISSUE THREAD

**Issue by magicbug** [magicbug/Cloudlog#721]
Query regarding how the cron works, in theory with this being background work, is it uploading one QSO at a time, or is it bulk uploading, packing up one upload that's then submitted, and if it isn't is there a reason its not? as this would heavily reduce script runtime and database loads.

@AndreasK79 perhaps one for you.

**Comment by AndreasK79** [comment]
@magicbug it is uploading one QSO at a time. When I wrote this, I tried several times to feed the API with more than one QSO. I never got it to work. I can recheck the API to see if anything has changed.

**Comment by magicbug** [comment]
https://www.qrz.com/docs/logbook/QRZLogbookAPI.html

unless this doc has changed it looks like one at a time still

**Comment by magicbug** [comment]
As it's a no go shall close it
