### ISSUE TITLE
[LoTW][Sync] Satellite RX Band Not setting

### ISSUE THREAD

**Issue by magicbug** [magicbug/Cloudlog#740]
Looks like somethings changed in TQSL/LoTW so that satellite rx band isn't being set properly although its being sent and freq is correct.

![lotwsat](https://user-images.githubusercontent.com/84308/101622893-8c6ff500-3a0f-11eb-9b1f-5580ef5f0058.png)
![lotwsat2](https://user-images.githubusercontent.com/84308/101622898-8d088b80-3a0f-11eb-9dad-1516a3dedbe7.png)

![lotwsat2](https://user-images.githubusercontent.com/84308/101622910-8f6ae580-3a0f-11eb-97d0-497b391d9699.png)

**Comment by do4bmw** [comment]
same counts for QO-100

![Download (1)](https://user-images.githubusercontent.com/76187206/102554666-85a74900-40c5-11eb-8dba-d778e23e8f0b.png)


https://prnt.sc/w4znmn

**Comment by magicbug** [comment]
Worth remembering QO-100 is just a satellite and is handled the same as every other satellite, while this doesn't effect uploaded QSOs matching isn't done on band this has now been fixed, you don't need to reupload anything but going forward should be sorted.
