### ISSUE TITLE
Editing from eQSL QSO Upload page results in full-screen edit screen with broken tabs

### ISSUE THREAD

**Issue by philpem** [magicbug/Cloudlog#745]
**Describe the bug**
If I click on a callsign/QSO link from the eQSL QSO Upload screen (Upload tab), the edit window appears full-screen and the tabs along the top don't work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to  eQSL Export
2. Click on a callsign link (for a QSO to be uploaded)
3. Click on one of the tabs in the edit screen, e.g. eQSO
4. Note that the screen does not update like the other QSO Edit screens.

**Expected behaviour**
QSO edit screen either appears as a popup on the eQSL Upload screen (like other editscreens) -- and tabs work correctly (like other edit screens).

**Screenshots**
![image](https://user-images.githubusercontent.com/845744/101778170-69b30e80-3aeb-11eb-9b64-75ed50f412d9.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 83.0 64bit

**Comment by magicbug** [comment]
Thanks in theory they should just show the edit but the info page.. bug will get sorted!

**Comment by AndreasK79** [comment]
The dialog popup should spawn here. It seems that one was missed when changes were done a while back.
