### ISSUE TITLE
Feature Request: DX Cluster to Add QSO

### ISSUE THREAD

**Issue by m1bxf** [magicbug/Cloudlog#77]
It would be neat if you could click on a DX cluster entry, either the callsign or some other link on the line,  and it would goto the Add QSO tab and pre-fill all the data such as band, freq and callsign.

**Comment by magicbug** [comment]
Think for the next release of Cloudlog or coming releases DX Cluster will be removed, its better to keep CL forlogging and use external tools for displaying spots, I might however make a bandmap which has spots on it, but it won't be a tab on the header menu.
