### ISSUE TITLE
[LoTW] imported QSOs not marked as 'sent'

### ISSUE THREAD

**Issue by k7tab** [magicbug/Cloudlog#772]
After importing confirmed QSOs from LOTW, using the 'import missing QSOs' option, imported QSOs were not marked as sent to LOTW. This resulted in several thousand QSOs being  re-uploaded to LOTW.

It was so much fun, I did it twice trying to track down a couple of other lotw import issues ;)

**Comment by magicbug** [comment]
Couple of questions

Did you use "Mark imported QSOs as uploaded to LoTW" or if you was using an adif did the ADIF have the relevent fields sample would be useful.

**Comment by k7tab** [comment]
There is no such option on the LOTW Import page.

In the branch I pulled, the code in LoTW doesn't pass anything to the parameter #4 $markLotw
From Lotw.php line 491/2:
                    if ($station_id != NULL) {
                        $result = $this->logbook_model->import($record, $station_id, NULL, NULL, NULL, NULL);  // Create the Entry


![image](https://user-images.githubusercontent.com/76535253/103040608-2ae07800-4531-11eb-9804-2cd704785b4f.png)

**Comment by magicbug** [comment]
That makes more sense, shall check with mine, can't actually remember the code behind it 😜
