### ISSUE TITLE
How use WSJT-X with cloudlog together

### ISSUE THREAD

**Issue by pa2eon** [magicbug/Cloudlog#787]
Is their any (small) ' readme'  file with instructions how to activate (connect) WSJT-X with cloudlog on Linux and/or Windows.
Regards, Eric

**Comment by magicbug** [comment]
The WSJT apps aren't developed by myself 

however, Gridtracker supports sending QSOs to Cloudlog and M0LTE you might get more help by posting in discussions https://github.com/magicbug/Cloudlog/discussions as I'm sure a few users will be more familiar than me

**Comment by magicbug** [comment]
Please not that theres now a wiki page https://github.com/magicbug/Cloudlog/wiki/WSJT-X-Integration
