### ISSUE TITLE
Update from 1 year old database to last cloudlog - not show any QSO

### ISSUE THREAD

**Issue by pa2eon** [magicbug/Cloudlog#793]
Just made a new update of the cloudlog software.
First make a copy of all the data AND MySQL database.
Then copy the latest software in the folder .. and copied the config and database.php to the new config folder.

I can login again .. and after that I have to activated the station profile.
When I go to the main page .. I see no old QSO's anymore .. only when I go to the page 'Live QSO' or 'Post QSO' I see the latest QSO in the left screen.
When I click on one of the older QSO's I get a black page with on top a blue line with 'QSO Data' in it .. and no old info of the older QSO.

What do I wrong in this update ?

![Schermafdruk van 2021-01-03 15-28-54](https://user-images.githubusercontent.com/4719917/103481043-8552c180-4dd8-11eb-969f-4e297b15fac7.png)

![Schermafdruk van 2021-01-03 15-30-13](https://user-images.githubusercontent.com/4719917/103481058-9d2a4580-4dd8-11eb-9a8c-8c43afe5752e.png)

**Comment by pa2eon** [comment]
Found the solution !

You have to update the field 'station id' in the database (TABLE_HRD_CONTACTS_V01)  with choice number ( in my case number 1 ) !

May be good to make SQL command to do this in one SQL query.

**Comment by pa2eon** [comment]
When you use webmin or other the SQL parm is in one line:
UPDATE TABLE_HRD_CONTACTS_V01 SET station_id = 1

**Comment by magicbug** [comment]
Pleased you figured it out.
