### ISSUE TITLE
ADIF Import 

### ISSUE THREAD

**Issue by do4bmw** [magicbug/Cloudlog#794]
Hy

if i try to import a ADIF Fiel from WSJT-X i get this error message

`Error: Adif_Parser Already Initialized or No in ADIF File
A PHP Error was encountered
Severity: Warning

Message: count(): Parameter must be an array or an object that implements Countable

Filename: libraries/Adif_parser.php

Line Number: 188`

that is the content from the ADIF File

```
WSJT-X ADIF Export<eh>
<call:6>EA7KJE <gridsquare:4>IM66 <mode:3>FT8 <rst_sent:3>+18 <rst_rcvd:3>-03 <qso_date:8>20210102 <time_on:6>105230 <qso_date_off:8>20210102 <time_off:6>105330 <band:3>15m <freq:9>21.075001 <station_callsign:6>DO4BMW <my_gridsquare:4>JO40 <comment:25>FT8  Sent: +18  Rcvd: -03 <eor>
<call:5>OD5ZZ <gridsquare:4>KM74 <mode:3>FT8 <rst_sent:3>+10 <rst_rcvd:3>-06 <qso_date:8>20210104 <time_on:6>091845 <qso_date_off:8>20210104 <time_off:6>092015 <band:3>15m <freq:9>21.076448 <station_callsign:6>DO4BMW <my_gridsquare:4>JO40 <comment:25>FT8  Sent: +10  Rcvd: -06 <eor>
```

**Comment by AndreasK79** [comment]
Hi.

The problem is that WSJT-X had a bug in it when generating the adif-file. The header should be <eoh>, not <eh>.
Change that, and you can import the file.

**Comment by do4bmw** [comment]
ah , many thanks !
