### ISSUE TITLE
ADIF import from a TQSL generated ADIF File does not work

### ISSUE THREAD

**Issue by dl6kbg** [magicbug/Cloudlog#803]
![Screenshot 2021-01-09 012949](https://user-images.githubusercontent.com/34808184/104078032-5e532000-521c-11eb-979d-1f13bfdf8732.jpg)

73 Oliver DL6KBG

**Comment by AndreasK79** [comment]
Can you show the header and the first qso here? Without that, it is impossible to know what is going on.

**Comment by dl6kbg** [comment]
Good morning! Sorry missed that. 

It is only one qso:

----snip----

<CALL:6>CT1BQH
   <BAND:4>13CM
   <MODE:2>CW
   <QSO_DATE:8>20210109
   <TIME_ON:6>000500
   <FREQ:8>2400.019
   <BAND_RX:3>3CM
   <FREQ_RX:9>10489.519
   <PROP_MODE:3>SAT
   <SAT_NAME:6>QO-100
<EOR>

73 Oliver DL6KBG

**Comment by dl6kbg** [comment]
Good morning! Here it is:

![Screenshot 2021-01-09 013322](https://user-images.githubusercontent.com/34808184/104088065-6a62d000-5264-11eb-9d8e-0a79eda02ac1.jpg)

**Comment by AndreasK79** [comment]
Good morning Oliver!

The problem is that there is no header in the file. The adif-parser does look for a header. It does seem to me that TQSL does not add this,

If you add a `<EOH>` at the top, the file will import.

Andreas.

**Comment by dl6kbg** [comment]
Many thanks Andreas! 73 Oliver DL6KBG

Andreas Kristiansen <notifications@github.com> schrieb am Sa. 9. Jan. 2021
um 11:01:
