### ISSUE TITLE
No response when installing on RaspberryPi

### ISSUE THREAD

**Issue by W-Linus** [magicbug/Cloudlog#815]
Dear magicbug,
       When I try to install cloudlog on my raspberrypi, I found there are not any response when I clicked the install button in 192.168.31.191/install. I have no idea what happend. Could you please tell me what should I do next? By the way , Could you please  
tell me what should be filled into Directory blank? 

VY 73!

**Comment by magicbug** [comment]
Sounds like a miss configuration of the web server, I'd suggest posting in the Discussion section has this isn't a code issue but there's lots of users who might be able to help.

I'd suggest checking the web server perhaps Apache to see if there's any errors.
