### ISSUE TITLE
Lightbox not showing map

### ISSUE THREAD

**Issue by PD0RZH** [magicbug/Cloudlog#866]
In [my setup](http://pd0rzh.beukie.com/cloudlog) the lightbox (after clicking a callsign from homescreen)  is not showing a map. I'm not sure whether it has worked before but if it did then I have a bug... ;-)

Any ideas?

**Comment by magicbug** [comment]
If your using a modern desktop browsers hit f12 then go to console in the developer tools then refresh the page and click again to see what errors come up.

I'm going to guess your using the latest codebase at this stage

**Comment by PD0RZH** [comment]
![image](https://user-images.githubusercontent.com/60810525/107042454-15ae6880-67c2-11eb-998b-63893907de49.png)
This is what it comes up with

Regards Rob

**Comment by magicbug** [comment]
I'm guessing in that case you aren't running things using Git in which case latest code base can be had via https://github.com/magicbug/Cloudlog/archive/master.zip

**Comment by magicbug** [comment]
I've a feeling if you update your code this will go away

**Comment by PD0RZH** [comment]
Your feeling did not let you down. Thanks Peter
