### ISSUE TITLE
[PHP-8] Non-fatal PHP warnings

### ISSUE THREAD

**Issue by ofadam** [magicbug/Cloudlog#873]
Since upgrading to PHP 8 on my self-hosted Cloudlog instance, I occasionally get the following deprecated warnings. Everything seems to function as usual, but just thought I'd mention in case you haven't jumped to 8.

Deprecated: Required parameter $skipDuplicate follows optional parameter $station_id in application/models/Logbook_model.php on line 1494

Deprecated: Required parameter $markLotw follows optional parameter $station_id in application/models/Logbook_model.php on line 1494

Deprecated: Required parameter $dxccAdif follows optional parameter $station_id in application/models/Logbook_model.php on line 1494

Deprecated: Required parameter $markQrz follows optional parameter $station_id in application/models/Logbook_model.php on line 1494

**Comment by magicbug** [comment]
I'm actually surprised it works, I wasn't expecting this version of Codeigniter to actually work with php8, I'm sure the warnings can be addressed

**Comment by ofadam** [comment]
It was an ill-advised upgrade, no doubt!
