### ISSUE TITLE
Unable to create station profile due to missing field dxcc

### ISSUE THREAD

**Issue by hb9gix** [magicbug/Cloudlog#893]
**Describe the bug**
It's currently not possible to create a station profile (or edit one), due to the field dxcc (or station_country) being missing from the form

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Admin > Station Profiles > + Create Station Profile
2. Fill out all the required fields
3. Klick 'Create Station Pofile' button on the bottom of the page
4. See error "A Database Error Occurred Error Number: 1366" See second Screenshot

**Expected behaviour**
Station Profile is created

**Screenshots**
![image](https://user-images.githubusercontent.com/79454905/108711891-48709480-7516-11eb-9041-cc050886a983.png)
![image](https://user-images.githubusercontent.com/79454905/108712036-7f46aa80-7516-11eb-9d5b-79d27bef1d86.png)

**Desktop (please complete the following information):**
 - OS: Linux (Kubuntu 20.04)
 - Browser: Firefox 
 - Version 85.0.1 (64-bit)

**Additional context**
The issue can be remedied by inspecting the html code and inserting the form field "dxcc" with the appropriate value and setting the value of the form field "station_country" manually

**Comment by magicbug** [comment]
Missed the step to update country files "admin" - "Update Country files"

**Comment by hb9gix** [comment]
Point taken.
But shouldn't it be handled nontheless?

**Comment by magicbug** [comment]
New install procedure is in the works which will force all the relevant steps to be carried out, we don't package the country files as the data changes on a regular basis with exceptions lists for DX trips (not such an issue with covid!)
