### ISSUE TITLE
eqsl import hangs

### ISSUE THREAD

**Issue by geekmoto13** [magicbug/Cloudlog#894]
when i goto admin -> eqsl import/export and i click on import from eqsl it just hangs and doesnt seem to do anything, i have eqsl credentials in my account profile and then while its processing i try to click to another area and the page does nothing

**Comment by geekmoto13** [comment]
> 
> 
> Weird, when you say hangs does the page time out loading?

it basically just sits there and does nothing, it acts like it does something, even firefox tries to load something, but nothing happened. and but i found out that i had to create a new location in eqsl for it to work,

**Comment by magicbug** [comment]
I'll make sure this gets addressed in the documentation
