### ISSUE TITLE
dxcc tables have the wrong charset

### ISSUE THREAD

**Issue by wvolz** [magicbug/Cloudlog#924]
**Describe the bug**
The 'dxcc_entities' and 'dxcc_exceptions' tables have a default charset of 'utf8'. I think this should be 'utf8mb4'. It looks like migration 014 was supposed to fix this but it has the wrong table names. Also, I think 'dxcc_prefixes' should be utf8mb4?

**To Reproduce**
Steps to reproduce the behaviour:
1. Confirm db tables above have the charset configured as 'utf8' instead of 'utf8mb4'.

**Comment by magicbug** [comment]
Your correct should be utf8mb4 shall get this fixed soon as I can
