### ISSUE TITLE
Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by Taubin** [magicbug/Cloudlog#934]
**This is for reporting bugs with the code, if this issue is regarding setting up on your local server please use the forum see readme for details**

**Describe the bug**

When attempting to log a new QSO, I enter my gridsquare under locator. If I use the 6 digit gridsquare, the box goes red and will not save. If I use an 8 digit square, I get the following error:

```

A PHP Error was encountered

Severity: Notice

Message: Trying to access array offset on value of type bool

Filename: libraries/Qra.php

Line Number: 29
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to log location on server (I can send this privately with a username created if requested)
2. Click on QSO - Post QSO
3. Scroll down to Locator. Enter RF73ig (or any other text for ig) (you will get the red box and inability to save) enter RF73ig38 (or any other number) and the error will show up. 

**Expected behaviour**

I expect to be able to submit a log with my grid locator either the 6 or 8 digit locator. 

**Screenshots**

![Cloudlog](https://user-images.githubusercontent.com/8891792/110719780-4dea1080-8272-11eb-8072-8b4e2989e0dd.jpg)

**Desktop (please complete the following information):**
 - OS:  Win10
 - Browser Firefox and Chrome both exhibit the same behaviour
 - Version FF86

**Smartphone (please complete the following information):**
 - Device: Galaxy S10 - Firefox
 - OS: Android 11
 - Browser Stock and Firefox

**Additional context**

**Comment by magicbug** [comment]
Aware I need to check if it's above six, at the moment my PHP script doesn't support more than that
