### ISSUE TITLE
Can't create any log, neither live nor post

### ISSUE THREAD

**Issue by agamez** [magicbug/Cloudlog#950]
I just can't seem to be able to add any entry at all. Clicking on 'Save QSO' doesn't do anything. Maybe it is because DXCC appears empty and with a red border? But I don't have any list of DXCC entities there, nor can I type anything.

**Comment by AndreasK79** [comment]
My guess is that you need to go to Admin and Update Country Files.

**Comment by agamez** [comment]
That was it, thank you.

I'll try to make a patch to document this requirement next Monday.
