### ISSUE TITLE
Some API Methods are exposed anonymously

### ISSUE THREAD

**Issue by tarantir** [magicbug/Cloudlog#965]
Standard LAMP install

Some API Methods are exposed anonymously without authentication or an API Key
e.g. http://cloudlog.url/cloudlog/index.php/api/search_callsign or e.g. http://cloudlog.url/cloudlog/index.php/api/lookup

Here is a snip from the configured authentication parameters.
$config['use_auth'] = true;
$config['auth_table'] = "users";
$config['auth_mode'] = "1";

**Comment by magicbug** [comment]
/API calls aren't being exposed, they are handled completely separate, in hindsight I need to add API key to them, but they certainly aren't exposing any method for attack

**Comment by tarantir** [comment]
Thanks for checking!
