### ISSUE TITLE
[Callsign Lookup][DXCC] DXCC mapping wrong for Gitmo KG4xx

### ISSUE THREAD

**Issue by magicbug** [magicbug/Cloudlog#979]
Cloudlog maps KG4 to Gitmo. In fact only KG4xx calls are gitmor, any KG4x and KG4xxx are USA

Reported by @m0pcb

**Comment by AndreasK79** [comment]
I guess we need a special handling for calls beginning with KG4 and a length of 5 then.

**Comment by magicbug** [comment]
Yep that would take care of it I think
