### ISSUE TITLE
Error on manual synch to LoTW

### ISSUE THREAD

**Issue by Vic152** [magicbug/Cloudlog#980]
I love the bug template but this is fairly straightforward ;-)

This happens when I do manual synch to LoTW.

I am not sure which version of the Cloudlog we run at https://cloudlog.oarc.uk/

![image](https://user-images.githubusercontent.com/6089679/113445288-83a39480-93ed-11eb-9c62-1bd42a7d986d.png)

**Comment by magicbug** [comment]
Is /uploads/lotw folder writable? First error brings that into question

**Comment by Vic152** [comment]
> Is /uploads/lotw folder writable? First error brings that into question

Will check.

**Comment by magicbug** [comment]
PHP needs read/write access as per the install doc on the wiki on certain folders

**Comment by Vic152** [comment]
Permissions updated all fine! Thanks for the tip! Well done on the software. I really like it. It's my main logbook.
