### ISSUE TITLE
[ADIF export] Problems with lin endings and PROGRAMVERSION

### ISSUE THREAD

**Issue by donfraggle** [magicbug/Cloudlog#997]
The exported adif files cannot be processed with other tools, like the [cabrillo log converter](http://sp7dqr.pl/en/converters.php).
The problem are the unix line endings in the adif file. Unix uses only `\n`. Better is to use windows line endings `\r\n`.
Also the length of PROGRAMVERSION is set to wrong value 3 instead of 11.

![cloudlog_adifExport](https://user-images.githubusercontent.com/53894881/115532913-85e36b00-a296-11eb-8d1a-3dd79742f204.png)

Please read my email to hello@magicbug.co.uk.

**Comment by AndreasK79** [comment]
Thanks for reporting. Added a PR with fixes.
